import type { ChapterFormulaSheet } from "./types";

export const alternatingCurrentFormulaSheet: ChapterFormulaSheet = {
  chapterSlug: "alternating-current",
  chapterName: "Alternating Current",
  className: "12",
  version: "1.0.0",
  lastUpdated: "2026-07-09",
  examCoverage: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
  quickRevisionIds: [
    "ac-rms-value",
    "ac-inductor-reactance",
    "ac-capacitor-reactance",
    "ac-lcr-impedance",
    "ac-resonance-frequency",
    "ac-power-average",
    "ac-quality-factor",
  ],
  topicGroups: [
    {
      id: "ac-basics",
      title: "Instantaneous, Average & RMS Values",
      intro:
        "An alternating quantity averages to zero over a cycle, so 'average current' as commonly meant is really the RMS value — the DC equivalent that would dissipate the same power.",
      formulas: [
        {
          id: "ac-instantaneous-value",
          expression: "I = I₀ sin(ωt + φ)",
          expressionLatex: "I = I_0\\sin(\\omega t+\\varphi)",
          label: "Instantaneous value of an alternating current",
          variables: [
            { symbol: "I₀", name: "peak (maximum) value of current", unit: "A", dimension: "[A]" },
            { symbol: "ω", name: "angular frequency of the AC supply", unit: "rad/s", dimension: "[T⁻¹]" },
            { symbol: "φ", name: "phase constant / initial phase", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
          ],
          conceptLink: {
            chapterSlug: "alternating-current",
            sectionHeading: "1. What Is Alternating Current?",
            concept: "instantaneous AC value",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 7, neet: 9, mhtCet: 6 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["instantaneous ac current", "I0 sin omega t phi"],
        },
        {
          id: "ac-rms-value",
          expression: "I(rms) = I₀/√2 ,  V(rms) = V₀/√2",
          expressionLatex: "I_{rms} = \\dfrac{I_0}{\\sqrt{2}}",
          label: "RMS (root mean square) value of AC",
          derivedFrom: "√(mean of I² over one full cycle) — the DC current that dissipates the same average power in a resistor",
          variables: [
            { symbol: "I(rms)", name: "RMS current — what AC ammeters/voltmeters actually read", unit: "A", dimension: "[A]" },
          ],
          conditions: ["Applies only to a pure sinusoidal waveform — the factor 1/√2 changes for other waveshapes (square, triangular)"],
          commonMistakes: [
            "Household '230 V AC' refers to the RMS voltage — the actual PEAK voltage is 230×√2 ≈ 325 V, a fact often missed in numerical problems",
          ],
          conceptLink: {
            chapterSlug: "alternating-current",
            sectionHeading: "2. Average and RMS Values",
            concept: "RMS value of AC",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 4, neet: 12, mhtCet: 8 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["rms value ac", "I0 by root 2"],
        },
        {
          id: "ac-average-value",
          expression: "I(avg) = 2I₀/π   (over a half cycle)",
          expressionLatex: "I_{avg} = \\dfrac{2I_0}{\\pi}",
          label: "Average value of AC over a half cycle",
          conditions: ["Average over a FULL cycle is exactly zero for a symmetric sine wave — only the half-cycle average is meaningful and non-zero"],
          variables: [],
          conceptLink: {
            chapterSlug: "alternating-current",
            sectionHeading: "2. Average and RMS Values",
            concept: "average value of AC",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 6, neet: 8, mhtCet: 5 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["average value ac half cycle", "2I0 by pi"],
        },
      ],
    },
    {
      id: "ac-pure-elements",
      title: "AC Through Pure R, L and C",
      intro:
        "Each pure circuit element shifts the phase between current and voltage differently — a resistor keeps them in step, an inductor makes current lag, a capacitor makes it lead.",
      formulas: [
        {
          id: "ac-inductor-reactance",
          expression: "X(L) = ωL = 2πfL",
          expressionLatex: "X_L = \\omega L",
          label: "Inductive reactance",
          variables: [
            { symbol: "X(L)", name: "inductive reactance — an inductor's opposition to AC", unit: "Ω", dimension: "[ML²T⁻³A⁻²]" },
          ],
          conditions: ["Current LAGS voltage by 90° (π/2) across a pure inductor", "X(L) = 0 for DC (f=0) — an ideal inductor is a short circuit to steady current"],
          commonMistakes: [
            "'ELI' mnemonic: in an inductor (L), EMF (E) leads current (I) — helps recall the lag direction under exam pressure",
          ],
          conceptLink: {
            chapterSlug: "alternating-current",
            sectionHeading: "5. AC Through a Pure Inductor",
            concept: "inductive reactance",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 10, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["inductive reactance formula", "XL equals omega L"],
        },
        {
          id: "ac-capacitor-reactance",
          expression: "X(C) = 1/(ωC) = 1/(2πfC)",
          expressionLatex: "X_C = \\dfrac{1}{\\omega C}",
          label: "Capacitive reactance",
          variables: [
            { symbol: "X(C)", name: "capacitive reactance — a capacitor's opposition to AC", unit: "Ω", dimension: "[ML²T⁻³A⁻²]" },
          ],
          conditions: ["Current LEADS voltage by 90° across a pure capacitor", "X(C) → ∞ for DC (f=0) — an ideal capacitor blocks steady current completely"],
          commonMistakes: [
            "'ICE' mnemonic: in a capacitor (C), current (I) leads EMF (E) — the opposite lag direction to an inductor",
          ],
          conceptLink: {
            chapterSlug: "alternating-current",
            sectionHeading: "6. AC Through a Pure Capacitor",
            concept: "capacitive reactance",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 10, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["capacitive reactance formula", "XC equals 1 by omega C"],
        },
      ],
      importantObservations: [
        "A pure resistor has zero phase difference between V and I — reactance concepts (which always involve a 90° phase shift) simply don't apply to R",
      ],
    },
    {
      id: "ac-series-circuits",
      title: "Series LR, RC, LCR Circuits & Resonance",
      intro:
        "Combining R with L and/or C mixes in-phase and out-of-phase behaviour — impedance (not simple resistance) governs the circuit, and at resonance the reactive parts cancel entirely.",
      formulas: [
        {
          id: "ac-lr-impedance",
          expression: "Z = √(R² + X(L)²) ,  tanφ = X(L)/R",
          expressionLatex: "Z = \\sqrt{R^2+X_L^2}",
          label: "Impedance of a series LR circuit",
          variables: [
            { symbol: "Z", name: "impedance — total AC opposition of the circuit", unit: "Ω", dimension: "[ML²T⁻³A⁻²]" },
            { symbol: "φ", name: "phase angle by which current lags voltage", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
          ],
          conceptLink: {
            chapterSlug: "alternating-current",
            sectionHeading: "8. Series LR Circuit",
            concept: "impedance of an LR circuit",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 6, neet: 8, mhtCet: 5 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["LR circuit impedance", "root R squared XL squared"],
        },
        {
          id: "ac-rc-impedance",
          expression: "Z = √(R² + X(C)²) ,  tanφ = X(C)/R",
          expressionLatex: "Z = \\sqrt{R^2+X_C^2}",
          label: "Impedance of a series RC circuit",
          variables: [],
          conceptLink: {
            chapterSlug: "alternating-current",
            sectionHeading: "9. Series RC Circuit",
            concept: "impedance of an RC circuit",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 6, neet: 8, mhtCet: 5 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["RC circuit impedance", "root R squared XC squared"],
        },
        {
          id: "ac-lcr-impedance",
          expression: "Z = √(R² + (X(L) − X(C))²) ,  tanφ = (X(L) − X(C))/R",
          expressionLatex: "Z = \\sqrt{R^2+(X_L-X_C)^2}",
          label: "Impedance of a series LCR circuit",
          derivedFrom: "Phasor sum: V(L) and V(C) are exactly antiparallel (180° apart), so their net reactive voltage is (X(L)−X(C))I, combined with V(R) at 90° to that",
          variables: [],
          conditions: ["Circuit is inductive overall if X(L) > X(C) (current lags), capacitive if X(C) > X(L) (current leads)"],
          commonMistakes: [
            "X(L) and X(C) SUBTRACT (not add) because inductive and capacitive voltage phasors point in opposite directions — a very common algebra mistake",
          ],
          usedIn: ["current-electricity"],
          conceptLink: {
            chapterSlug: "alternating-current",
            sectionHeading: "10. Series LCR Circuit",
            concept: "impedance of an LCR circuit",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 5, neet: 12, mhtCet: 8 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["LCR circuit impedance", "root R squared XL minus XC squared"],
        },
        {
          id: "ac-resonance-frequency",
          expression: "ω₀ = 1/√(LC) ,  f₀ = 1/(2π√(LC))",
          expressionLatex: "\\omega_0 = \\dfrac{1}{\\sqrt{LC}}",
          label: "Resonant frequency of a series LCR circuit",
          derivedFrom: "Resonance occurs when X(L) = X(C): ωL = 1/(ωC), solved for ω",
          variables: [
            { symbol: "ω₀", name: "angular resonant frequency", unit: "rad/s", dimension: "[T⁻¹]" },
          ],
          conditions: ["At resonance, Z = R (minimum possible impedance), so current is MAXIMUM and the circuit behaves as purely resistive"],
          conceptLink: {
            chapterSlug: "alternating-current",
            sectionHeading: "11. Series Resonance",
            concept: "resonant frequency",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 4, neet: 11, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["resonant frequency LCR", "omega0 1 by root LC"],
        },
        {
          id: "ac-quality-factor",
          expression: "Q = ω₀L/R = (1/R)√(L/C) = ω₀/Δω",
          expressionLatex: "Q = \\dfrac{\\omega_0 L}{R} = \\dfrac{1}{R}\\sqrt{\\dfrac{L}{C}}",
          label: "Quality factor of a resonant LCR circuit",
          derivedFrom: "Ratio of the voltage across L (or C) at resonance to the applied voltage — measures how 'sharp' the resonance peak is",
          variables: [
            { symbol: "Q", name: "quality factor, dimensionless", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
            { symbol: "Δω", name: "bandwidth — width of the resonance curve between half-power points", unit: "rad/s", dimension: "[T⁻¹]" },
          ],
          conditions: ["Higher Q means a sharper, more selective resonance peak and a smaller bandwidth — the basis of radio tuning circuits"],
          conceptLink: {
            chapterSlug: "alternating-current",
            sectionHeading: "12. Quality Factor and Bandwidth",
            concept: "quality factor",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 4, neet: 7, mhtCet: 5 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["quality factor LCR", "Q omega0 L by R"],
        },
        {
          id: "ac-bandwidth",
          expression: "Δω = R/L",
          expressionLatex: "\\Delta\\omega = \\dfrac{R}{L}",
          label: "Bandwidth of a resonant LCR circuit",
          derivedFrom: "Width of the current-vs-frequency curve between the two half-power points",
          variables: [],
          conditions: ["Combined with Q = ω₀/Δω, larger R broadens the resonance curve (lower Q, worse selectivity)"],
          conceptLink: {
            chapterSlug: "alternating-current",
            sectionHeading: "12. Quality Factor and Bandwidth",
            concept: "bandwidth of resonance",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "medium",
          examStats: { jeeMain: 5, jeeAdvanced: 3, neet: 4 },
          difficulty: "hard",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["bandwidth LCR resonance", "delta omega R by L"],
        },
      ],
      examNotes:
        "JEE Advanced frequently gives Z, R, and one reactance and asks for the other, or gives resonance data and asks to reconstruct L or C — practise algebraic manipulation of these three impedance formulas, not just memorisation.",
    },
    {
      id: "ac-power",
      title: "Power in AC Circuits",
      intro:
        "Unlike DC, power in an AC circuit depends on the phase angle between current and voltage — only the in-phase component of current does any net work over a cycle.",
      formulas: [
        {
          id: "ac-power-average",
          expression: "P(avg) = V(rms) I(rms) cosφ",
          expressionLatex: "P_{avg} = V_{rms}I_{rms}\\cos\\varphi",
          label: "Average power in an AC circuit",
          derivedFrom: "Time-average of instantaneous power P = VI over one complete cycle, using V and I both sinusoidal with phase difference φ",
          variables: [
            { symbol: "cosφ", name: "power factor", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["P(avg) = 0 for a purely reactive circuit (pure L or pure C, φ = 90°) — no net energy is dissipated, only exchanged"],
          conceptLink: {
            chapterSlug: "alternating-current",
            sectionHeading: "13. Power in AC Circuits",
            concept: "average power in AC",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 4, neet: 11, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["average power ac circuit", "Vrms Irms cos phi"],
        },
        {
          id: "ac-power-factor",
          expression: "cosφ = R/Z",
          expressionLatex: "\\cos\\varphi = \\dfrac{R}{Z}",
          label: "Power factor",
          variables: [],
          conditions: ["cosφ = 1 for a pure resistor (Z=R); cosφ = 0 for a pure L or C (no resistance at all)"],
          conceptLink: {
            chapterSlug: "alternating-current",
            sectionHeading: "13. Power in AC Circuits",
            concept: "power factor",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 6, neet: 8, mhtCet: 5 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["power factor formula", "cos phi R by Z"],
        },
        {
          id: "ac-wattless-current",
          expression: "I(wattless) = I(rms) sinφ",
          expressionLatex: "I_{wattless} = I_{rms}\\sin\\varphi",
          label: "Wattless current component",
          derivedFrom: "The component of current 90° out of phase with voltage — contributes to current flow but zero to average power",
          variables: [],
          conditions: ["Present in circuits with L or C; a choke coil deliberately uses this idea to limit current with minimal power loss (compared to a resistor doing the same job)"],
          commonMistakes: [
            "'Wattless' doesn't mean zero current — it means this current component does zero average WORK, even though real current flows and heats up wires via I²R in any real (non-ideal) coil",
          ],
          conceptLink: {
            chapterSlug: "alternating-current",
            sectionHeading: "14. Wattless Current and the Choke Coil",
            concept: "wattless current",
          },
          examTags: ["jee-main", "neet", "mht-cet"],
          frequency: "medium",
          examStats: { jeeMain: 5, neet: 6, mhtCet: 4 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["wattless current", "Irms sin phi"],
        },
      ],
    },
  ],
};
