import type { ChapterFormulaSheet } from "./types";

export const atomsFormulaSheet: ChapterFormulaSheet = {
  chapterSlug: "atoms",
  chapterName: "Atoms",
  className: "12",
  version: "1.0.0",
  lastUpdated: "2026-07-09",
  examCoverage: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
  quickRevisionIds: [
    "atom-bohr-radius-formula",
    "atom-bohr-energy",
    "atom-energy-level-transition",
    "atom-rydberg-formula",
  ],
  topicGroups: [
    {
      id: "atom-rutherford-scattering",
      title: "Rutherford Scattering & the Nuclear Model",
      intro:
        "Rutherford's gold-foil experiment revealed that almost all of an atom's mass and all of its positive charge is concentrated in a tiny central nucleus — the scattering data itself is what pins down the nucleus's size.",
      formulas: [
        {
          id: "atom-distance-closest-approach",
          expression: "r₀ = 2kZe² / (mv²)",
          expressionLatex: "r_0 = \\dfrac{2kZe^2}{mv^2}",
          label: "Distance of closest approach",
          derivedFrom: "Energy conservation: the alpha particle's initial kinetic energy converts entirely into electrostatic potential energy at the point of closest approach",
          variables: [
            { symbol: "r₀", name: "distance of closest approach", unit: "m", dimension: "[L]" },
            { symbol: "Z", name: "atomic number of the target nucleus", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
            { symbol: "m, v", name: "mass and initial speed of the incoming alpha particle", unit: "kg, m/s", dimension: "[M], [LT⁻¹]" },
          ],
          conditions: ["Occurs only for a head-on (zero impact parameter) collision — this gives the SMALLEST possible r₀, an upper bound on the nucleus's size"],
          conceptLink: {
            chapterSlug: "atoms",
            sectionHeading: "4. Distance of Closest Approach and Impact Parameter",
            concept: "distance of closest approach",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 4, neet: 7, mhtCet: 5 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["distance closest approach formula", "2kZe2 by mv squared"],
        },
      ],
      importantObservations: [
        "Most alpha particles passed straight through the foil undeflected (proving atoms are mostly empty space), while a small fraction bounced back at large angles (proving a small, dense, positively charged nucleus)",
      ],
    },
    {
      id: "atom-bohr-model",
      title: "Bohr's Model of the Hydrogen Atom",
      intro:
        "Bohr rescued the nuclear model from classical collapse by simply postulating that angular momentum is quantised — everything else (orbit radius, energy, spectral lines) follows from that single assumption.",
      formulas: [
        {
          id: "atom-bohr-angular-momentum-quantisation",
          expression: "mvr = nh/2π",
          expressionLatex: "mvr = \\dfrac{nh}{2\\pi}",
          label: "Bohr's angular momentum quantisation postulate",
          variables: [
            { symbol: "n", name: "principal quantum number (n = 1, 2, 3, ...)", unit: "dimensionless (integer)", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["The foundational postulate of the entire Bohr model — later justified by de Broglie's matter-wave picture (2πr = nλ)"],
          usedIn: ["dual-nature-of-radiation-and-matter"],
          conceptLink: {
            chapterSlug: "atoms",
            sectionHeading: "6. Bohr's Postulates",
            concept: "angular momentum quantisation",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 11, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["bohr angular momentum quantisation", "mvr equals nh by 2 pi"],
        },
        {
          id: "atom-bohr-radius-formula",
          expression: "r(n) = n² r₁ / Z ,  r₁ = 0.529 Å  (n=1, Z=1)",
          expressionLatex: "r_n = \\dfrac{n^2}{Z}(0.529\\,\\text{Å})",
          label: "Radius of the nth Bohr orbit",
          derivedFrom: "Combining the angular momentum quantisation condition with the Coulomb force providing centripetal force",
          derivation: {
            startsFrom: "Coulomb force provides centripetal force: kZe²/r² = mv²/r, combined with mvr = nh/2π",
            steps: [
              { statement: "Solve the two equations simultaneously for r", expression: "r(n) = n²h²ε₀ / (πmZe²)" },
              { statement: "Evaluate the constants for hydrogen's ground state (n=1, Z=1)", expression: "r₁ = 0.529 Å = 0.529 × 10⁻¹⁰ m" },
              { statement: "General result scales simply with n² and 1/Z", expression: "r(n) = (n²/Z) × 0.529 Å" },
            ],
            askedInBoards: true,
          },
          variables: [
            { symbol: "r(n)", name: "radius of the nth orbit", unit: "m (or Å)", dimension: "[L]" },
          ],
          conditions: ["Orbit radius grows as n², so higher orbits are dramatically larger — the atom's size is set almost entirely by its outermost electron's n"],
          conceptLink: {
            chapterSlug: "atoms",
            sectionHeading: "7. Radius of the Bohr Orbit",
            concept: "radius of the Bohr orbit",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 4, neet: 12, mhtCet: 8 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["bohr radius formula", "rn equals n squared by Z times 0.529 angstrom"],
        },
        {
          id: "atom-bohr-velocity",
          expression: "v(n) = Ze² / (2ε₀nh) = (Z/n) v₁ ,  v₁ ≈ 2.18 × 10⁶ m/s",
          expressionLatex: "v_n = \\dfrac{Z}{n}v_1",
          label: "Velocity of the electron in the nth Bohr orbit",
          variables: [
            { symbol: "v(n)", name: "orbital speed in the nth orbit", unit: "m/s", dimension: "[LT⁻¹]" },
          ],
          conditions: ["Velocity DECREASES with increasing n (unlike radius, which increases) — outer electrons move more slowly"],
          commonMistakes: [
            "Radius scales as n² while velocity scales as 1/n — opposite trends that are easy to mix up under exam pressure",
          ],
          conceptLink: {
            chapterSlug: "atoms",
            sectionHeading: "8. Velocity of the Electron in an Orbit",
            concept: "velocity of the electron in a Bohr orbit",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 4, neet: 7, mhtCet: 5 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["bohr orbit velocity formula", "vn equals Z by n v1"],
        },
        {
          id: "atom-bohr-energy",
          expression: "E(n) = −13.6 Z²/n²  eV",
          expressionLatex: "E_n = -\\dfrac{13.6\\,Z^2}{n^2}\\,\\text{eV}",
          label: "Total energy of the electron in the nth Bohr orbit",
          derivedFrom: "Sum of kinetic energy (½mv²) and Coulomb potential energy (−kZe²/r), evaluated using the quantised radius formula",
          variables: [
            { symbol: "E(n)", name: "total energy of the electron in orbit n", unit: "eV", dimension: "[ML²T⁻²]" },
          ],
          conditions: ["Negative sign indicates a BOUND state — the electron needs +13.6 Z²/n² eV of energy supplied to escape entirely (n → ∞)"],
          commonMistakes: [
            "Ground state energy of hydrogen is exactly −13.6 eV — one of the most memorised numbers in the syllabus; don't forget the negative sign when computing transition energies",
          ],
          usedIn: ["dual-nature-of-radiation-and-matter"],
          conceptLink: {
            chapterSlug: "atoms",
            sectionHeading: "9. Energy of the Electron in an Orbit",
            concept: "energy of the electron in a Bohr orbit",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 10, jeeAdvanced: 5, neet: 13, mhtCet: 8 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["bohr energy formula", "En minus 13.6 Z squared by n squared eV"],
        },
        {
          id: "atom-energy-level-transition",
          expression: "hν = E(n2) − E(n1) = 13.6 Z² (1/n1² − 1/n2²)  eV",
          expressionLatex: "h\\nu = 13.6\\,Z^2\\left(\\dfrac{1}{n_1^2}-\\dfrac{1}{n_2^2}\\right)",
          label: "Energy of a photon emitted/absorbed in an electron transition",
          derivedFrom: "Conservation of energy: the photon carries away exactly the energy difference between the two orbits",
          variables: [
            { symbol: "n1, n2", name: "principal quantum numbers of the lower and higher orbit (n2 > n1)", unit: "dimensionless (integer)", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["Emission when the electron falls from n2 to n1 (higher to lower); absorption for the reverse transition"],
          conceptLink: {
            chapterSlug: "atoms",
            sectionHeading: "10. Energy Level Diagram of Hydrogen",
            concept: "energy level transitions",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 5, neet: 12, mhtCet: 8 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["energy transition formula hydrogen", "13.6 Z squared 1 by n1 squared minus 1 by n2 squared"],
        },
      ],
      examNotes:
        "The number of distinct spectral lines emitted when an electron de-excites from level n to level 1 is n(n−1)/2 — a very common counting question that pairs with the energy transition formula.",
    },
    {
      id: "atom-spectral-series",
      title: "Spectral Series of Hydrogen",
      intro:
        "Every possible electron transition in hydrogen falls into one of a few named series, depending only on which orbit the electron lands in — the Rydberg formula generates every observed spectral line from one equation.",
      formulas: [
        {
          id: "atom-rydberg-formula",
          expression: "1/λ = RZ² (1/n1² − 1/n2²)",
          expressionLatex: "\\dfrac{1}{\\lambda} = RZ^2\\left(\\dfrac{1}{n_1^2}-\\dfrac{1}{n_2^2}\\right)",
          label: "Rydberg formula for spectral lines",
          variables: [
            { symbol: "R", name: "Rydberg constant", unit: "m⁻¹", dimension: "[L⁻¹]", notes: "R ≈ 1.097 × 10⁷ m⁻¹" },
          ],
          conditions: ["Lyman series: n1=1 (UV); Balmer series: n1=2 (visible); Paschen series: n1=3 (IR) — n2 > n1 in every case"],
          commonMistakes: [
            "Only the Balmer series has lines in the visible range — Lyman is entirely UV and Paschen (and beyond) is entirely infrared, a frequently tested fact",
          ],
          conceptLink: {
            chapterSlug: "atoms",
            sectionHeading: "13. Spectral Series of Hydrogen",
            concept: "Rydberg formula",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 4, neet: 12, mhtCet: 8 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["rydberg formula", "1 by lambda R Z squared", "spectral series hydrogen"],
        },
        {
          id: "atom-series-limit",
          expression: "Series limit (shortest λ, n2 → ∞): 1/λ = RZ²/n1²",
          expressionLatex: "\\dfrac{1}{\\lambda_{limit}} = \\dfrac{RZ^2}{n_1^2}",
          label: "Series limit of a spectral series",
          derivedFrom: "Setting n2 → ∞ in the Rydberg formula — the electron transitions from just barely bound (ionisation threshold) down to n1",
          variables: [],
          conditions: ["Gives the shortest wavelength (highest energy) line possible in that series — the point where lines converge and stop"],
          conceptLink: {
            chapterSlug: "atoms",
            sectionHeading: "13. Spectral Series of Hydrogen",
            concept: "series limit",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "medium",
          examStats: { jeeMain: 5, jeeAdvanced: 3, neet: 5 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["series limit formula", "shortest wavelength spectral series"],
        },
      ],
    },
  ],
};
