import type { ChapterFormulaSheet } from "./types";

export const basicMathematicsAndVectorsFormulaSheet: ChapterFormulaSheet = {
  chapterSlug: "basic-mathematics-and-vectors",
  chapterName: "Basic Mathematics & Vectors",
  className: "11",
  version: "1.0.0",
  lastUpdated: "2026-07-08",
  examCoverage: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
  quickRevisionIds: [
    "bmv-small-angle-approx",
    "bmv-binomial-approximation",
    "bmv-vector-addition-magnitude",
    "bmv-resultant-direction",
    "bmv-dot-product",
    "bmv-cross-product",
  ],
  topicGroups: [
    {
      id: "bmv-approximations",
      title: "Trigonometric & Binomial Approximations",
      intro:
        "Physics constantly linearises small quantities. These two approximations turn a hard trigonometric or algebraic expression into a manageable linear one — and JEE/NEET reward recognising when they apply.",
      formulas: [
        {
          id: "bmv-small-angle-approx",
          expression: "sinθ ≈ θ,  tanθ ≈ θ,  cosθ ≈ 1 − θ²/2   (θ in radians, θ → 0)",
          expressionLatex: "\\sin\\theta \\approx \\theta,\\quad \\cos\\theta \\approx 1-\\dfrac{\\theta^2}{2}",
          label: "Small-angle approximation",
          derivedFrom: "Taylor series of sin, cos, tan truncated to leading order",
          variables: [
            { symbol: "θ", name: "angle, must be in RADIANS", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["Only valid for θ in radians, and only for small θ (roughly θ < 0.2 rad, or ~10-15°)"],
          commonMistakes: [
            "Using θ in degrees directly in sinθ ≈ θ — the approximation ONLY holds with θ measured in radians",
          ],
          usedIn: ["oscillations", "waves"],
          conceptLink: {
            chapterSlug: "basic-mathematics-and-vectors",
            sectionHeading: "6. Small-Angle Approximation",
            concept: "small-angle approximation",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 7, jeeAdvanced: 4, neet: 8, mhtCet: 6 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["small angle approximation", "sin theta approx theta", "simple pendulum approximation"],
        },
        {
          id: "bmv-binomial-approximation",
          expression: "(1 + x)ⁿ ≈ 1 + nx   (for |x| ≪ 1)",
          expressionLatex: "(1+x)^n \\approx 1+nx",
          label: "Binomial approximation",
          derivedFrom: "Binomial expansion (1+x)ⁿ = 1 + nx + n(n-1)x²/2! + ⋯, truncated after the linear term",
          variables: [
            { symbol: "n", name: "any real exponent (need not be a positive integer)", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
            { symbol: "x", name: "small quantity", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["Requires |x| ≪ 1 — the smaller x, the better the approximation", "Works for negative and fractional n too, e.g. (1+x)⁻¹ ≈ 1−x, (1+x)^(1/2) ≈ 1 + x/2"],
          commonMistakes: [
            "Applying it when x is not actually small gives a badly wrong answer — always check the smallness condition before using it",
          ],
          usedIn: ["gravitation", "electric-charges-and-fields", "mechanical-properties-of-fluids"],
          conceptLink: {
            chapterSlug: "basic-mathematics-and-vectors",
            sectionHeading: "15. Binomial Approximation",
            concept: "binomial approximation",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 5, neet: 9, mhtCet: 6 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["binomial approximation", "1 plus x to the n", "binomial expansion physics"],
        },
        {
          id: "bmv-quadratic-formula",
          expression: "x = [−b ± √(b² − 4ac)] / 2a   for ax² + bx + c = 0",
          expressionLatex: "x = \\dfrac{-b \\pm \\sqrt{b^2-4ac}}{2a}",
          label: "Quadratic formula",
          variables: [
            { symbol: "a, b, c", name: "coefficients of the quadratic equation", unit: "context-dependent", dimension: "[context-dependent]" },
          ],
          conditions: ["Discard the root that gives a physically impossible answer (e.g. negative time, negative distance)"],
          commonMistakes: [
            "Forgetting to reject the unphysical root — both roots are mathematically valid but only one may make physical sense",
          ],
          conceptLink: {
            chapterSlug: "basic-mathematics-and-vectors",
            sectionHeading: "14. Quadratic Equations",
            concept: "solving quadratic equations",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 5, neet: 6, mhtCet: 4 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["quadratic formula", "minus b plus minus root b squared minus 4ac"],
        },
      ],
      importantObservations: [
        "Both approximations are 'zoom in and it looks like a straight line' tools — recognising a small parameter in a problem is a hint to reach for one of these",
      ],
    },
    {
      id: "bmv-calculus-essentials",
      title: "Differentiation & Integration Essentials",
      intro:
        "Physics defines velocity, acceleration, and countless other quantities as rates of change or accumulated sums — calculus is the language, not an optional extra.",
      formulas: [
        {
          id: "bmv-derivative-power-rule",
          expression: "d/dx(xⁿ) = n xⁿ⁻¹",
          expressionLatex: "\\dfrac{d}{dx}(x^n) = nx^{n-1}",
          label: "Power rule of differentiation",
          variables: [
            { symbol: "n", name: "any real exponent", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["The single most-used calculus rule in mechanics — used to get v = dx/dt and a = dv/dt from a position function"],
          usedIn: ["kinematics", "work-energy-and-power"],
          conceptLink: {
            chapterSlug: "basic-mathematics-and-vectors",
            sectionHeading: "9. Rules of Differentiation",
            concept: "power rule of differentiation",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 9, mhtCet: 6 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["power rule differentiation", "d dx x to n"],
        },
        {
          id: "bmv-derivative-standard",
          expression: "d/dx(sinx) = cosx ;  d/dx(cosx) = −sinx ;  d/dx(eˣ) = eˣ",
          expressionLatex: "\\dfrac{d}{dx}\\sin x = \\cos x,\\quad \\dfrac{d}{dx}\\cos x = -\\sin x",
          label: "Standard derivatives used in physics",
          variables: [],
          conditions: ["x must be in radians for the trigonometric derivatives to hold in this simple form"],
          usedIn: ["oscillations", "waves", "alternating-current"],
          conceptLink: {
            chapterSlug: "basic-mathematics-and-vectors",
            sectionHeading: "9. Rules of Differentiation",
            concept: "standard derivatives",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 4, neet: 6 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["derivative of sin cos", "standard derivatives physics"],
        },
        {
          id: "bmv-maxima-minima-condition",
          expression: "Maximum: dy/dx = 0 and d²y/dx² < 0 ;  Minimum: dy/dx = 0 and d²y/dx² > 0",
          expressionLatex: "\\dfrac{dy}{dx}=0,\\quad \\dfrac{d^2y}{dx^2} \\lessgtr 0",
          label: "Condition for maxima and minima",
          derivedFrom: "First derivative gives the stationary point; the sign of the second derivative classifies it",
          variables: [],
          conditions: ["A stationary point (dy/dx = 0) with d²y/dx² = 0 needs further checking — it may be a point of inflection, not an extremum"],
          usedIn: ["work-energy-and-power", "electrostatic-potential-and-capacitance"],
          conceptLink: {
            chapterSlug: "basic-mathematics-and-vectors",
            sectionHeading: "10. Maxima and Minima",
            concept: "maxima and minima",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 4, neet: 5 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["maxima minima condition", "second derivative test"],
        },
        {
          id: "bmv-integral-power-rule",
          expression: "∫xⁿ dx = xⁿ⁺¹/(n+1) + C   (n ≠ −1)",
          expressionLatex: "\\int x^n\\,dx = \\dfrac{x^{n+1}}{n+1}+C",
          label: "Power rule of integration",
          variables: [
            { symbol: "C", name: "constant of integration", unit: "context-dependent", dimension: "[context-dependent]" },
          ],
          conditions: ["Used constantly to reconstruct v from a(t), or x from v(t), given initial conditions to fix C"],
          usedIn: ["kinematics", "work-energy-and-power"],
          conceptLink: {
            chapterSlug: "basic-mathematics-and-vectors",
            sectionHeading: "11. Integration: Reversing Differentiation",
            concept: "power rule of integration",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 4, neet: 6 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["integral power rule", "integration x to n"],
        },
        {
          id: "bmv-definite-integral-area",
          expression: "Area under y(x) from a to b = ∫[a to b] y dx",
          expressionLatex: "A = \\int_a^b y\\,dx",
          label: "Definite integral as area under a curve",
          derivedFrom: "Limit of a Riemann sum of infinitesimally thin strips",
          variables: [],
          conditions: ["The classic physics use: area under a v–t graph gives displacement; area under F–x graph gives work done"],
          commonMistakes: [
            "Signed area: regions below the x-axis subtract from the total, they don't automatically add as positive area",
          ],
          usedIn: ["kinematics", "work-energy-and-power"],
          conceptLink: {
            chapterSlug: "basic-mathematics-and-vectors",
            sectionHeading: "12. Definite Integrals, Area Under a Curve, and Average Value",
            concept: "definite integral as area",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 7, neet: 8, mhtCet: 6 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["area under curve integral", "v t graph area displacement"],
        },
      ],
    },
    {
      id: "bmv-vector-basics",
      title: "Vector Representation & Addition",
      intro:
        "A vector needs both magnitude and direction to be fully specified. Addition of vectors is never simple arithmetic — it always accounts for the angle between them.",
      formulas: [
        {
          id: "bmv-vector-magnitude-components",
          expression: "|A| = √(Ax² + Ay² + Az²)",
          expressionLatex: "|\\vec{A}| = \\sqrt{A_x^2+A_y^2+A_z^2}",
          label: "Magnitude of a vector from its rectangular components",
          variables: [
            { symbol: "Ax, Ay, Az", name: "components of A along the x, y, z axes", unit: "same as A", dimension: "same as A" },
          ],
          conditions: ["Components must be along MUTUALLY PERPENDICULAR axes"],
          conceptLink: {
            chapterSlug: "basic-mathematics-and-vectors",
            sectionHeading: "22. Resolving a Vector into Rectangular Components",
            concept: "vector magnitude from components",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 10, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["vector magnitude components", "root Ax squared Ay squared"],
        },
        {
          id: "bmv-unit-vector",
          expression: "Â = A / |A|",
          expressionLatex: "\\hat{A} = \\dfrac{\\vec{A}}{|\\vec{A}|}",
          label: "Unit vector along a given vector",
          variables: [
            { symbol: "Â", name: "unit vector, magnitude exactly 1, dimensionless", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["A unit vector carries direction information only — never carries the physical dimensions of A itself"],
          conceptLink: {
            chapterSlug: "basic-mathematics-and-vectors",
            sectionHeading: "19. Types of Vectors",
            concept: "unit vector",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 6, neet: 8, mhtCet: 5 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["unit vector formula", "A hat equals A by magnitude A"],
        },
        {
          id: "bmv-vector-addition-magnitude",
          expression: "R = √(A² + B² + 2AB cosθ)",
          expressionLatex: "R = \\sqrt{A^2+B^2+2AB\\cos\\theta}",
          label: "Magnitude of the resultant of two vectors (parallelogram law)",
          derivedFrom: "Law of cosines applied to the triangle formed by A, B, and their resultant",
          variables: [
            { symbol: "A, B", name: "magnitudes of the two vectors being added", unit: "context-dependent", dimension: "context-dependent" },
            { symbol: "θ", name: "angle between the two vectors", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["R is maximum (= A+B) when θ = 0°, minimum (= |A−B|) when θ = 180°"],
          commonMistakes: [
            "The angle θ is the angle BETWEEN the vectors as drawn tail-to-tail, not the angle in the parallelogram diagram's corner in every orientation — draw it carefully",
          ],
          usedIn: ["laws-of-motion", "electric-charges-and-fields"],
          conceptLink: {
            chapterSlug: "basic-mathematics-and-vectors",
            sectionHeading: "20. Adding Two Vectors: Triangle and Parallelogram Laws",
            concept: "vector addition — parallelogram law",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 4, neet: 11, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["resultant of two vectors", "parallelogram law magnitude", "root A squared B squared 2AB cos theta"],
        },
        {
          id: "bmv-resultant-direction",
          expression: "tanβ = B sinθ / (A + B cosθ)",
          expressionLatex: "\\tan\\beta = \\dfrac{B\\sin\\theta}{A+B\\cos\\theta}",
          label: "Direction of the resultant of two vectors",
          variables: [
            { symbol: "β", name: "angle the resultant makes with vector A", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["β leans toward whichever of A or B has the larger magnitude"],
          conceptLink: {
            chapterSlug: "basic-mathematics-and-vectors",
            sectionHeading: "20. Adding Two Vectors: Triangle and Parallelogram Laws",
            concept: "direction of the resultant vector",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 3, neet: 7, mhtCet: 5 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["direction of resultant vector", "tan beta B sin theta"],
        },
        {
          id: "bmv-vector-subtraction",
          expression: "|A − B| = √(A² + B² − 2AB cosθ)",
          expressionLatex: "|\\vec{A}-\\vec{B}| = \\sqrt{A^2+B^2-2AB\\cos\\theta}",
          label: "Magnitude of the difference of two vectors",
          derivedFrom: "A − B = A + (−B); apply the addition formula with the angle between A and −B, which is (180° − θ)",
          variables: [],
          conditions: ["Maximum |A−B| = A+B when θ = 180° (vectors antiparallel); minimum = |A−B| when θ = 0°"],
          commonMistakes: [
            "Subtraction is NOT commutative in direction: A−B and B−A have the same magnitude but point in opposite directions",
          ],
          conceptLink: {
            chapterSlug: "basic-mathematics-and-vectors",
            sectionHeading: "21. Subtracting Two Vectors",
            concept: "vector subtraction",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 6, neet: 8, mhtCet: 5 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["vector subtraction magnitude", "A minus B root A squared B squared minus 2AB cos theta"],
        },
      ],
      importantObservations: [
        "Relative velocity problems are vector subtraction in disguise: v(A relative to B) = v(A) − v(B)",
      ],
      examNotes:
        "NEET frequently tests the special cases θ = 0°, 90°, 180° for both addition and subtraction as one-line MCQs — memorise the three magnitudes (A+B, √(A²+B²), |A−B|) directly.",
    },
    {
      id: "bmv-vector-products",
      title: "Scalar and Vector Products",
      intro:
        "Multiplying two vectors gives either a scalar (dot product) or another vector (cross product) — physics uses both constantly, and picking the right one is half the battle in a problem.",
      formulas: [
        {
          id: "bmv-dot-product",
          expression: "A·B = AB cosθ = AxBx + AyBy + AzBz",
          expressionLatex: "\\vec{A}\\cdot\\vec{B} = AB\\cos\\theta",
          label: "Scalar (dot) product of two vectors",
          variables: [
            { symbol: "A·B", name: "dot product, a pure scalar", unit: "product of A and B's units", dimension: "product of A and B's dimensions" },
          ],
          conditions: ["A·B = 0 when the vectors are perpendicular (θ = 90°) — the basis of the 'no work done' rule when force ⊥ displacement"],
          commonMistakes: [
            "Dot product is commutative (A·B = B·A), unlike the cross product — a frequent point of confusion",
          ],
          usedIn: ["work-energy-and-power", "electric-charges-and-fields", "moving-charges-and-magnetism"],
          conceptLink: {
            chapterSlug: "basic-mathematics-and-vectors",
            sectionHeading: "24. Scalar (Dot) Product",
            concept: "dot product",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 4, neet: 10, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["dot product formula", "A dot B AB cos theta", "scalar product"],
        },
        {
          id: "bmv-cross-product",
          expression: "A × B = AB sinθ n̂  ;  |A × B| = AB sinθ",
          expressionLatex: "\\vec{A}\\times\\vec{B} = AB\\sin\\theta\\,\\hat{n}",
          label: "Vector (cross) product of two vectors",
          derivedFrom: "Right-hand rule gives n̂'s direction, perpendicular to the plane containing A and B",
          variables: [
            { symbol: "n̂", name: "unit vector perpendicular to both A and B, direction from the right-hand rule", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["|A × B| = 0 when the vectors are parallel/antiparallel (θ = 0° or 180°)"],
          commonMistakes: [
            "Cross product is ANTI-commutative: A × B = −(B × A) — swapping the order flips the direction, unlike the dot product",
          ],
          usedIn: ["system-of-particles-and-rotational-motion", "moving-charges-and-magnetism"],
          conceptLink: {
            chapterSlug: "basic-mathematics-and-vectors",
            sectionHeading: "25. Vector (Cross) Product",
            concept: "cross product",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 5, neet: 9, mhtCet: 6 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["cross product formula", "A cross B AB sin theta", "vector product right hand rule"],
        },
        {
          id: "bmv-area-parallelogram-triangle",
          expression: "Area of parallelogram = |A × B| ;  Area of triangle = ½|A × B|",
          expressionLatex: "\\text{Area}_{\\triangle} = \\dfrac{1}{2}|\\vec{A}\\times\\vec{B}|",
          label: "Area of a parallelogram/triangle from two adjacent sides",
          derivedFrom: "Geometric meaning of the cross product's magnitude (base × height = AB sinθ)",
          variables: [],
          conditions: ["A and B must be the two vectors representing adjacent sides emanating from the same vertex"],
          conceptLink: {
            chapterSlug: "basic-mathematics-and-vectors",
            sectionHeading: "25. Vector (Cross) Product",
            concept: "area via cross product",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "medium",
          examStats: { jeeMain: 5, jeeAdvanced: 3, neet: 4 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["area parallelogram cross product", "area triangle vectors"],
        },
      ],
      examNotes:
        "A recurring JEE Advanced trick: express torque (r × F), angular momentum (r × p), and magnetic force (qv × B) all use the identical cross-product mechanics — practise the determinant method once and reuse it everywhere.",
    },
  ],
};
