import type { ChapterFormulaSheet } from "./types";

export const centreOfMassAndCollisionsFormulaSheet: ChapterFormulaSheet = {
  chapterSlug: "centre-of-mass-and-collisions",
  chapterName: "Centre of Mass & Collisions",
  className: "11",
  version: "1.0.0",
  lastUpdated: "2026-07-03",
  examCoverage: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
  quickRevisionIds: [
    "com-position",
    "com-momentum-conservation",
    "com-coefficient-restitution",
    "com-elastic-1d-final-velocities",
    "com-perfectly-inelastic-velocity",
    "com-ke-loss-inelastic",
  ],
  topicGroups: [
    {
      id: "com-centre-of-mass",
      title: "Centre of Mass",
      intro:
        "The centre of mass is the mass-weighted average position — the single point where the whole system's translational story can be told.",
      formulas: [
        {
          id: "com-position",
          expression: "x(cm) = (m₁x₁ + m₂x₂ + ...) / (m₁ + m₂ + ...)",
          expressionLatex: "x_{cm} = \\dfrac{\\sum m_i x_i}{\\sum m_i}",
          label: "Position of centre of mass (particles)",
          variables: [
            { symbol: "x(cm)", name: "centre of mass coordinate", unit: "m", dimension: "[L]" },
            { symbol: "mᵢ", name: "mass of the ith particle", unit: "kg", dimension: "[M]" },
            { symbol: "xᵢ", name: "position of the ith particle", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Apply separately for each axis (x, y, z)"],
          commonMistakes: [
            "The centre of mass needs NO mass at its own location — for a ring it is at the empty centre",
            "For two particles, the COM divides the line joining them in the INVERSE ratio of masses (closer to the heavier one)",
          ],
          conceptLink: {
            chapterSlug: "centre-of-mass-and-collisions",
            sectionHeading: "1. Centre of Mass",
            concept: "centre of mass of a system of particles",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, neet: 11, mhtCet: 8 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["centre of mass", "com position", "mass weighted average"],
        },
        {
          id: "com-remaining-part",
          expression: "x(remaining) = (M x(M) − m x(m)) / (M − m)",
          label: "COM after removing a piece (cavity problems)",
          derivedFrom: "Treat the removed piece as negative mass at its own COM",
          variables: [
            { symbol: "M", name: "mass of the original full body", unit: "kg", dimension: "[M]" },
            { symbol: "m", name: "mass of the removed piece", unit: "kg", dimension: "[M]" },
          ],
          conditions: ["x(M), x(m) are the COMs of the full body and the removed piece"],
          commonMistakes: [
            "Using areas or volumes directly as masses is fine ONLY for uniform density",
          ],
          conceptLink: {
            chapterSlug: "centre-of-mass-and-collisions",
            sectionHeading: "1. Centre of Mass",
            concept: "centre of mass with cavity",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 3, neet: 7 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["cavity", "removed mass", "negative mass method"],
        },
        {
          id: "com-velocity",
          expression: "v(cm) = (m₁v₁ + m₂v₂) / (m₁ + m₂) = p(total)/M",
          expressionLatex: "\\vec{v}_{cm} = \\dfrac{\\sum m_i \\vec{v}_i}{\\sum m_i}",
          label: "Velocity of the centre of mass",
          variables: [
            { symbol: "v(cm)", name: "velocity of centre of mass", unit: "m/s", dimension: "[LT⁻¹]" },
            { symbol: "p(total)", name: "total momentum of the system", unit: "kg·m/s", dimension: "[MLT⁻¹]" },
            { symbol: "M", name: "total mass", unit: "kg", dimension: "[M]" },
          ],
          conditions: ["With zero external force, v(cm) stays constant no matter what happens internally"],
          commonMistakes: [
            "In explosion problems the COM keeps moving on the ORIGINAL trajectory — fragments rearrange around it",
          ],
          usedIn: ["system-of-particles-and-rotational-motion"],
          conceptLink: {
            chapterSlug: "centre-of-mass-and-collisions",
            sectionHeading: "2. Motion of the Centre of Mass",
            concept: "velocity of centre of mass",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 5, neet: 9 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["velocity of com", "total momentum by total mass"],
        },
      ],
      importantObservations: [
        "Standard COM results: uniform semicircular ring → 2R/π from centre; semicircular disc → 4R/3π; solid hemisphere → 3R/8; hollow hemisphere → R/2 (all along the symmetry axis)",
        "Internal forces can never move the centre of mass of an isolated system",
      ],
      examNotes:
        "JEE loves the man-walking-on-boat setup — the COM of (man + boat) stays fixed when water friction is neglected.",
    },
    {
      id: "com-momentum",
      title: "Conservation of Linear Momentum",
      intro:
        "When the net external force is zero, total momentum cannot change. This survives even when kinetic energy is destroyed — which is why it rules every collision.",
      formulas: [
        {
          id: "com-momentum-conservation",
          expression: "m₁u₁ + m₂u₂ = m₁v₁ + m₂v₂",
          expressionLatex: "m_1\\vec{u}_1 + m_2\\vec{u}_2 = m_1\\vec{v}_1 + m_2\\vec{v}_2",
          label: "Conservation of linear momentum",
          derivedFrom: "Newton's third law: internal impulses cancel in pairs",
          variables: [
            { symbol: "u₁, u₂", name: "velocities before the event", unit: "m/s", dimension: "[LT⁻¹]" },
            { symbol: "v₁, v₂", name: "velocities after the event", unit: "m/s", dimension: "[LT⁻¹]" },
          ],
          conditions: [
            "Net EXTERNAL force zero (or the event is so brief that external impulse is negligible)",
            "It is a VECTOR equation — conserve each component separately in 2-D",
          ],
          commonMistakes: [
            "Momentum is conserved in every collision — elastic or not; it is kinetic energy that may be lost",
          ],
          usedIn: ["laws-of-motion", "nuclei"],
          conceptLink: {
            chapterSlug: "centre-of-mass-and-collisions",
            sectionHeading: "3. Conservation of Momentum",
            concept: "conservation of linear momentum",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 13, jeeAdvanced: 7, neet: 16, mhtCet: 11 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["momentum conservation", "collision", "recoil"],
        },
        {
          id: "com-recoil",
          expression: "v(gun) = − (m(bullet) / M(gun)) v(bullet)",
          label: "Recoil velocity of a gun",
          derivedFrom: "Total momentum zero before and after firing",
          variables: [
            { symbol: "v(gun)", name: "recoil velocity", unit: "m/s", dimension: "[LT⁻¹]" },
            { symbol: "m(bullet), M(gun)", name: "bullet and gun masses", unit: "kg", dimension: "[M]" },
          ],
          commonMistakes: [
            "KE is NOT shared equally — the lighter bullet carries almost all the kinetic energy (K = p²/2m, same p, smaller m)",
          ],
          conceptLink: {
            chapterSlug: "centre-of-mass-and-collisions",
            sectionHeading: "3. Conservation of Momentum",
            concept: "recoil",
          },
          examTags: ["neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { neet: 8, mhtCet: 6 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["recoil", "gun bullet", "explosion momentum"],
        },
      ],
      importantObservations: [
        "In 2-D explosion/collision problems, draw the momentum vector triangle — if total momentum is zero, the three momenta close a triangle",
      ],
    },
    {
      id: "com-collisions",
      title: "Collisions",
      intro:
        "Every collision conserves momentum. What distinguishes them is the coefficient of restitution — how much of the approach speed survives as separation speed.",
      formulas: [
        {
          id: "com-coefficient-restitution",
          expression: "e = (v₂ − v₁) / (u₁ − u₂)",
          expressionLatex: "e = \\dfrac{v_2 - v_1}{u_1 - u_2}",
          label: "Coefficient of restitution",
          variables: [
            { symbol: "e", name: "coefficient of restitution", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]", notes: "e = 1 elastic, e = 0 perfectly inelastic, 0 < e < 1 real collisions" },
            { symbol: "u₁ − u₂", name: "velocity of approach", unit: "m/s", dimension: "[LT⁻¹]" },
            { symbol: "v₂ − v₁", name: "velocity of separation", unit: "m/s", dimension: "[LT⁻¹]" },
          ],
          conditions: ["Velocities along the line of impact"],
          commonMistakes: [
            "Getting the order wrong: e = separation speed / approach speed — both taken along the impact line",
          ],
          conceptLink: {
            chapterSlug: "centre-of-mass-and-collisions",
            sectionHeading: "4. Collisions",
            concept: "coefficient of restitution",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet"],
          frequency: "very-high",
          examStats: { jeeMain: 10, jeeAdvanced: 6, neet: 9 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["coefficient of restitution", "e separation approach"],
        },
        {
          id: "com-elastic-1d-final-velocities",
          expression: "v₁ = ((m₁−m₂)u₁ + 2m₂u₂)/(m₁+m₂),  v₂ = ((m₂−m₁)u₂ + 2m₁u₁)/(m₁+m₂)",
          expressionLatex: "v_1 = \\dfrac{(m_1-m_2)u_1 + 2m_2u_2}{m_1+m_2}",
          label: "Final velocities — 1-D elastic collision",
          derivedFrom: "Solving momentum conservation together with e = 1",
          derivation: {
            startsFrom: "Momentum conservation plus the elastic condition (separation speed = approach speed)",
            steps: [
              { statement: "Momentum", expression: "m₁u₁ + m₂u₂ = m₁v₁ + m₂v₂" },
              { statement: "Elastic (e = 1)", expression: "v₂ − v₁ = u₁ − u₂" },
              { statement: "Solve the two linear equations for v₁ and v₂" },
            ],
          },
          variables: [
            { symbol: "u₁, u₂", name: "initial velocities", unit: "m/s", dimension: "[LT⁻¹]" },
            { symbol: "v₁, v₂", name: "final velocities", unit: "m/s", dimension: "[LT⁻¹]" },
          ],
          conditions: [
            "Equal masses → velocities EXCHANGE",
            "Heavy hits light at rest → light leaves at ≈ 2u₁, heavy barely slows",
            "Light hits heavy at rest → light bounces back with ≈ same speed",
          ],
          commonMistakes: [
            "Memorise the three limiting cases above — most exam questions are one of them in disguise",
          ],
          conceptLink: {
            chapterSlug: "centre-of-mass-and-collisions",
            sectionHeading: "4. Collisions",
            concept: "elastic collision in one dimension",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 5, neet: 12, mhtCet: 8 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["elastic collision", "velocity exchange", "final velocities"],
        },
        {
          id: "com-perfectly-inelastic-velocity",
          expression: "v = (m₁u₁ + m₂u₂) / (m₁ + m₂)",
          expressionLatex: "v = \\dfrac{m_1u_1 + m_2u_2}{m_1 + m_2}",
          label: "Common velocity — perfectly inelastic collision",
          derivedFrom: "Momentum conservation with both bodies moving together after impact",
          variables: [
            { symbol: "v", name: "common final velocity", unit: "m/s", dimension: "[LT⁻¹]" },
          ],
          conditions: ["Bodies stick together (e = 0)"],
          usedIn: ["system-of-particles-and-rotational-motion"],
          conceptLink: {
            chapterSlug: "centre-of-mass-and-collisions",
            sectionHeading: "4. Collisions",
            concept: "perfectly inelastic collision",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 13, mhtCet: 9 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["perfectly inelastic", "stick together", "common velocity"],
        },
        {
          id: "com-ke-loss-inelastic",
          expression: "ΔK = ½ (m₁m₂/(m₁+m₂)) (u₁ − u₂)²",
          expressionLatex: "\\Delta K = \\dfrac{1}{2}\\dfrac{m_1m_2}{m_1+m_2}(u_1-u_2)^2",
          label: "KE lost in a perfectly inelastic collision",
          derivedFrom: "K(initial) − K(final) using the common-velocity result; μ = m₁m₂/(m₁+m₂) is the reduced mass",
          variables: [
            { symbol: "ΔK", name: "kinetic energy converted to heat/deformation", unit: "J", dimension: "[ML²T⁻²]" },
            { symbol: "u₁ − u₂", name: "relative velocity of approach", unit: "m/s", dimension: "[LT⁻¹]" },
          ],
          conditions: ["Perfectly inelastic (e = 0); for general e, multiply by (1 − e²)"],
          commonMistakes: [
            "The ballistic pendulum needs BOTH tools: momentum conservation for the impact, energy conservation for the swing after — never energy across the impact itself",
          ],
          usedIn: ["work-energy-and-power"],
          conceptLink: {
            chapterSlug: "centre-of-mass-and-collisions",
            sectionHeading: "4. Collisions",
            concept: "energy loss in inelastic collision",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "high",
          examStats: { jeeMain: 7, jeeAdvanced: 4, neet: 8 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["energy loss collision", "reduced mass", "ballistic pendulum"],
        },
        {
          id: "com-bounce-height",
          expression: "h(n) = e²ⁿ h₀,  v(after) = e v(before)",
          expressionLatex: "h_n = e^{2n}h_0",
          label: "Ball bouncing on the floor (nth bounce)",
          derivedFrom: "Each impact scales speed by e; height goes as speed squared",
          variables: [
            { symbol: "h₀", name: "initial drop height", unit: "m", dimension: "[L]" },
            { symbol: "h(n)", name: "height after the nth bounce", unit: "m", dimension: "[L]" },
            { symbol: "n", name: "bounce number", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
          ],
          commonMistakes: [
            "Height scales as e²ⁿ (not eⁿ) because h ∝ v²",
          ],
          conceptLink: {
            chapterSlug: "centre-of-mass-and-collisions",
            sectionHeading: "4. Collisions",
            concept: "bouncing ball and restitution",
          },
          examTags: ["jee-main", "neet"],
          frequency: "medium",
          examStats: { jeeMain: 4, neet: 6 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["bouncing ball", "e squared n", "rebound height"],
        },
      ],
      importantObservations: [
        "In a 2-D elastic collision between EQUAL masses (one initially at rest), the two final velocities are perpendicular — a JEE classic",
        "Oblique collisions: the velocity component PERPENDICULAR to the line of impact never changes for smooth spheres",
      ],
      examNotes:
        "NEET stays with 1-D collisions and the limiting cases; JEE Advanced moves to oblique impacts and collision-with-spring problems where maximum compression occurs at common velocity.",
    },
  ],
};
