import type { ChapterFormulaSheet } from "./types";

export const circularMotionFormulaSheet: ChapterFormulaSheet = {
  chapterSlug: "circular-motion",
  chapterName: "Circular Motion",
  className: "11",
  version: "1.0.0",
  lastUpdated: "2026-07-08",
  examCoverage: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
  quickRevisionIds: [
    "circ-relation-linear-angular",
    "circ-centripetal-acceleration",
    "circ-centripetal-force",
    "circ-unbanked-road-max-speed",
    "circ-banking-angle-no-friction",
    "circ-vertical-circle-min-speed-top",
    "circ-vertical-circle-min-speed-bottom",
  ],
  topicGroups: [
    {
      id: "circ-angular-kinematics",
      title: "Angular Kinematics",
      intro:
        "Angular kinematics mirrors linear kinematics exactly — every SUVAT-style equation has a direct rotational twin, with θ, ω, α replacing x, v, a.",
      formulas: [
        {
          id: "circ-angular-velocity",
          expression: "ω = dθ/dt   (instantaneous);  ω(avg) = Δθ/Δt",
          expressionLatex: "\\omega = \\dfrac{d\\theta}{dt}",
          label: "Angular velocity",
          variables: [
            { symbol: "ω", name: "angular velocity", unit: "rad/s", dimension: "[T⁻¹]" },
            { symbol: "θ", name: "angular position", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["A vector quantity; direction along the rotation axis via the right-hand rule"],
          conceptLink: {
            chapterSlug: "circular-motion",
            sectionHeading: "2. Angular Velocity",
            concept: "angular velocity",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 7, neet: 9, mhtCet: 6 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["angular velocity formula", "omega d theta dt"],
        },
        {
          id: "circ-angular-acceleration",
          expression: "α = dω/dt",
          expressionLatex: "\\alpha = \\dfrac{d\\omega}{dt}",
          label: "Angular acceleration",
          variables: [
            { symbol: "α", name: "angular acceleration", unit: "rad/s²", dimension: "[T⁻²]" },
          ],
          conditions: ["Zero for uniform circular motion (ω constant) — non-zero only when speed along the circle changes"],
          conceptLink: {
            chapterSlug: "circular-motion",
            sectionHeading: "3. Angular Acceleration",
            concept: "angular acceleration",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 6, neet: 8, mhtCet: 5 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["angular acceleration formula", "alpha d omega dt"],
        },
        {
          id: "circ-angular-equations-motion",
          expression: "ω = ω₀ + αt ;  θ = ω₀t + ½αt² ;  ω² = ω₀² + 2αθ",
          expressionLatex: "\\omega = \\omega_0+\\alpha t,\\quad \\theta = \\omega_0 t + \\tfrac{1}{2}\\alpha t^2",
          label: "Equations of motion for constant angular acceleration",
          derivedFrom: "Direct rotational analogues of the linear SUVAT equations, ω↔v, θ↔x, α↔a",
          variables: [
            { symbol: "ω₀", name: "initial angular velocity", unit: "rad/s", dimension: "[T⁻¹]" },
          ],
          conditions: ["Valid only for CONSTANT angular acceleration — same restriction as the linear SUVAT set"],
          usedIn: ["kinematics"],
          conceptLink: {
            chapterSlug: "circular-motion",
            sectionHeading: "4. Equations of Motion with Constant Angular Acceleration",
            concept: "rotational equations of motion",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 6, neet: 8, mhtCet: 5 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["rotational SUVAT equations", "omega omega0 plus alpha t"],
        },
        {
          id: "circ-relation-linear-angular",
          expression: "v = rω ;  a(tangential) = rα",
          expressionLatex: "v = r\\omega,\\quad a_t = r\\alpha",
          label: "Relation between linear and angular quantities",
          derivedFrom: "Arc length s = rθ, differentiated once for v = rω and again for aₜ = rα",
          variables: [
            { symbol: "r", name: "radius of the circular path", unit: "m", dimension: "[L]" },
            { symbol: "v", name: "linear (tangential) speed", unit: "m/s", dimension: "[LT⁻¹]" },
          ],
          conditions: ["r is measured from the axis of rotation, not from some arbitrary point"],
          commonMistakes: [
            "For points at different radii on the same rigid rotating body, ω is the SAME for all of them, but v = rω differs — a very common source of error in rigid-body problems",
          ],
          usedIn: ["system-of-particles-and-rotational-motion", "moving-charges-and-magnetism"],
          conceptLink: {
            chapterSlug: "circular-motion",
            sectionHeading: "5. Relation Between Linear and Angular Quantities",
            concept: "relation between linear and angular quantities",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 4, neet: 11, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["v equals r omega", "linear angular velocity relation", "tangential acceleration r alpha"],
        },
        {
          id: "circ-time-period-frequency",
          expression: "T = 2π/ω = 1/f ;  ω = 2πf",
          expressionLatex: "T = \\dfrac{2\\pi}{\\omega},\\quad \\omega = 2\\pi f",
          label: "Time period and frequency of circular motion",
          variables: [
            { symbol: "T", name: "time for one complete revolution", unit: "s", dimension: "[T]" },
            { symbol: "f", name: "frequency (revolutions per second)", unit: "Hz", dimension: "[T⁻¹]" },
          ],
          conceptLink: {
            chapterSlug: "circular-motion",
            sectionHeading: "2. Angular Velocity",
            concept: "time period and frequency",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 7, neet: 9, mhtCet: 6 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["time period angular velocity", "T equals 2 pi by omega"],
        },
      ],
    },
    {
      id: "circ-dynamics",
      title: "Centripetal Acceleration & Force",
      intro:
        "Moving in a circle at constant speed still means accelerating — the velocity's DIRECTION is constantly changing, and that requires a net inward force at every instant.",
      formulas: [
        {
          id: "circ-centripetal-acceleration",
          expression: "a(c) = v²/r = ω²r",
          expressionLatex: "a_c = \\dfrac{v^2}{r} = \\omega^2 r",
          label: "Centripetal (radial) acceleration",
          derivedFrom: "Rate of change of the velocity vector's DIRECTION (not magnitude) for motion along a circle",
          variables: [
            { symbol: "a(c)", name: "centripetal acceleration, directed toward the centre", unit: "m/s²", dimension: "[LT⁻²]" },
          ],
          conditions: ["Present even in UNIFORM circular motion (constant speed) — direction alone changing is enough to require this acceleration"],
          commonMistakes: [
            "Centripetal acceleration is NOT a separate force by itself — it's the acceleration that some real force (tension, gravity, friction, normal force) must supply",
          ],
          usedIn: ["gravitation", "moving-charges-and-magnetism"],
          conceptLink: {
            chapterSlug: "circular-motion",
            sectionHeading: "6. Centripetal (Radial) Acceleration",
            concept: "centripetal acceleration",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 4, neet: 12, mhtCet: 8 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["centripetal acceleration formula", "v squared by r", "omega squared r"],
        },
        {
          id: "circ-tangential-total-acceleration",
          expression: "a(net) = √(a(c)² + a(t)²)",
          expressionLatex: "a_{net} = \\sqrt{a_c^2+a_t^2}",
          label: "Net acceleration in non-uniform circular motion",
          derivedFrom: "Radial (centripetal) and tangential acceleration components are always perpendicular, so they combine via Pythagoras",
          variables: [
            { symbol: "a(t)", name: "tangential acceleration, from the changing SPEED", unit: "m/s²", dimension: "[LT⁻²]" },
          ],
          conditions: ["a(t) = 0 for uniform circular motion, leaving only a(c) — total acceleration then points purely radially inward"],
          conceptLink: {
            chapterSlug: "circular-motion",
            sectionHeading: "7. Tangential Acceleration and Total Acceleration",
            concept: "net acceleration in non-uniform circular motion",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 4, neet: 7, mhtCet: 5 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["net acceleration circular motion", "tangential radial acceleration combine"],
        },
        {
          id: "circ-centripetal-force",
          expression: "F(c) = mv²/r = mω²r",
          expressionLatex: "F_c = \\dfrac{mv^2}{r} = m\\omega^2 r",
          label: "Centripetal force",
          derivedFrom: "Newton's second law applied along the radial direction: F = ma(c)",
          variables: [
            { symbol: "m", name: "mass of the object moving in the circle", unit: "kg", dimension: "[M]" },
          ],
          conditions: ["Not a NEW type of force — it's whichever real force (or component of it) happens to point toward the centre"],
          commonMistakes: [
            "Never add 'centripetal force' as an extra arrow on a free-body diagram alongside gravity/tension/normal — it IS the net inward component of those real forces",
          ],
          usedIn: ["gravitation", "laws-of-motion"],
          conceptLink: {
            chapterSlug: "circular-motion",
            sectionHeading: "8. Centripetal Force",
            concept: "centripetal force",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 4, neet: 12, mhtCet: 8 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["centripetal force formula", "mv squared by r"],
        },
        {
          id: "circ-centrifugal-force",
          expression: "F(cf) = −mω²r   (pseudo force, rotating frame only)",
          expressionLatex: "F_{cf} = -m\\omega^2 r",
          label: "Centrifugal force (pseudo force)",
          variables: [],
          conditions: ["Only appears when analysing motion from within the ROTATING (non-inertial) frame — has no place in an inertial-frame free-body diagram"],
          commonMistakes: [
            "Mixing centrifugal force into an inertial-frame analysis alongside real forces is a direct contradiction — pick ONE frame and stay consistent",
          ],
          conceptLink: {
            chapterSlug: "circular-motion",
            sectionHeading: "12. Centrifugal Force",
            concept: "centrifugal force as a pseudo force",
          },
          examTags: ["jee-main", "neet", "mht-cet"],
          frequency: "medium",
          examStats: { jeeMain: 5, neet: 6, mhtCet: 4 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["centrifugal force pseudo force", "rotating frame fictitious force"],
        },
      ],
      importantObservations: [
        "Every circular-motion problem starts the same way: identify which real force(s) — or components of them — supply the required centripetal force, then apply F(net, radial) = mv²/r",
      ],
    },
    {
      id: "circ-applications",
      title: "Banking of Roads, Conical Pendulum & Vertical Circle",
      intro:
        "These three classic setups are the same centripetal-force idea applied to increasingly clever geometries — each one is a guaranteed numerical question in JEE/NEET.",
      formulas: [
        {
          id: "circ-unbanked-road-max-speed",
          expression: "v(max) = √(μrg)",
          expressionLatex: "v_{max} = \\sqrt{\\mu r g}",
          label: "Maximum speed on a flat (unbanked) circular road",
          derivedFrom: "Friction alone supplies the centripetal force: μmg = mv²/r",
          variables: [
            { symbol: "μ", name: "coefficient of friction between tyres and road", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
            { symbol: "g", name: "acceleration due to gravity", unit: "m/s²", dimension: "[LT⁻²]" },
          ],
          conditions: ["Beyond this speed, the car skids outward — friction alone cannot provide enough centripetal force"],
          conceptLink: {
            chapterSlug: "circular-motion",
            sectionHeading: "9. Motion of a Vehicle on a Flat (Unbanked) Circular Road",
            concept: "maximum speed on an unbanked road",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 10, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["unbanked road max speed", "root mu r g"],
        },
        {
          id: "circ-banking-angle-no-friction",
          expression: "tanθ = v²/rg",
          expressionLatex: "\\tan\\theta = \\dfrac{v^2}{rg}",
          label: "Banking angle for a frictionless banked road",
          derivedFrom: "Only normal force provides centripetal force: N sinθ = mv²/r, with N cosθ = mg vertically",
          derivation: {
            startsFrom: "Resolve the normal force N into horizontal and vertical components on a banked (frictionless) road",
            steps: [
              { statement: "Vertical equilibrium", expression: "N cosθ = mg" },
              { statement: "Horizontal: net force supplies centripetal force", expression: "N sinθ = mv²/r" },
              { statement: "Divide the two equations", expression: "tanθ = v²/rg" },
            ],
            askedInBoards: true,
          },
          variables: [
            { symbol: "θ", name: "angle of banking of the road", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["This is THE ONE ideal safe speed for a given banking angle when friction is completely absent"],
          usedIn: ["laws-of-motion"],
          conceptLink: {
            chapterSlug: "circular-motion",
            sectionHeading: "10. Banking of Roads",
            concept: "banking angle without friction",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 4, neet: 12, mhtCet: 8 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["banking angle formula", "tan theta v squared by rg"],
        },
        {
          id: "circ-banking-with-friction-max-speed",
          expression: "v(max) = √[rg(tanθ + μ) / (1 − μtanθ)]",
          expressionLatex: "v_{max} = \\sqrt{\\dfrac{rg(\\tan\\theta+\\mu)}{1-\\mu\\tan\\theta}}",
          label: "Maximum safe speed on a banked road WITH friction",
          derivedFrom: "Both normal force and friction (acting down the incline, at the verge of outward skidding) contribute to the centripetal force",
          variables: [],
          conditions: ["Minimum safe speed (verge of sliding DOWN and inward) replaces + with − in both places: v(min) = √[rg(tanθ − μ)/(1+μtanθ)]"],
          commonMistakes: [
            "This formula reduces correctly to both simpler cases: set μ = 0 to recover tanθ = v²/rg, or θ = 0 to recover the unbanked-road result",
          ],
          conceptLink: {
            chapterSlug: "circular-motion",
            sectionHeading: "10. Banking of Roads",
            concept: "banking with friction",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 4, neet: 6 },
          difficulty: "hard",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["banked road friction max speed", "safe speed range banked curve"],
        },
        {
          id: "circ-conical-pendulum",
          expression: "tanθ = v²/rg   ;   T(period) = 2π√(l cosθ / g)",
          expressionLatex: "T = 2\\pi\\sqrt{\\dfrac{l\\cos\\theta}{g}}",
          label: "Conical pendulum — angle and time period",
          derivedFrom: "Tension's horizontal component supplies centripetal force; vertical component balances gravity — identical structure to frictionless banking",
          variables: [
            { symbol: "l", name: "length of the string", unit: "m", dimension: "[L]" },
            { symbol: "θ", name: "angle the string makes with the vertical", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["r = l sinθ relates the circle's radius to the string length and angle"],
          usedIn: ["oscillations"],
          conceptLink: {
            chapterSlug: "circular-motion",
            sectionHeading: "11. Conical Pendulum",
            concept: "conical pendulum",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 7, jeeAdvanced: 3, neet: 8, mhtCet: 6 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["conical pendulum formula", "conical pendulum time period"],
        },
        {
          id: "circ-vertical-circle-min-speed-top",
          expression: "v(top, min) = √(gr)",
          expressionLatex: "v_{top} = \\sqrt{gr}",
          label: "Minimum speed at the top of a vertical circle",
          derivedFrom: "At the critical (minimum) speed, gravity alone supplies the entire centripetal force — tension/normal force just touches zero",
          derivation: {
            startsFrom: "At the top: T + mg = mv²/r, with the critical condition T = 0",
            steps: [
              { statement: "Set tension to zero at the minimum condition", expression: "mg = mv(top)²/r" },
              { statement: "Solve for v", expression: "v(top, min) = √(gr)" },
            ],
            askedInBoards: true,
          },
          variables: [],
          conditions: ["Applies to a string/track providing tension/normal force only inward — below this speed, the object cannot maintain contact at the top and falls out of the circular path"],
          commonMistakes: [
            "Below v(top,min), the object does NOT slow down and reverse — it leaves the circular path entirely and becomes a projectile",
          ],
          usedIn: ["gravitation"],
          conceptLink: {
            chapterSlug: "circular-motion",
            sectionHeading: "14. Condition for Completing the Vertical Circle",
            concept: "minimum speed at the top of a vertical circle",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 11, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["minimum speed top vertical circle", "root gr"],
        },
        {
          id: "circ-vertical-circle-min-speed-bottom",
          expression: "v(bottom, min) = √(5gr)",
          expressionLatex: "v_{bottom} = \\sqrt{5gr}",
          label: "Minimum speed at the bottom to complete a full vertical circle",
          derivedFrom: "Energy conservation from bottom to top (height gained = 2r) combined with v(top,min) = √(gr)",
          derivation: {
            startsFrom: "Conservation of energy: ½mv(bottom)² = ½mv(top)² + mg(2r)",
            steps: [
              { statement: "Substitute v(top)² = gr", expression: "½v(bottom)² = ½(gr) + 2gr" },
              { statement: "Solve for v(bottom)²", expression: "v(bottom)² = 5gr  ⟹  v(bottom, min) = √(5gr)" },
            ],
            askedInBoards: true,
          },
          variables: [],
          conditions: ["This is THE single most tested numerical result in vertical circular motion — memorise both the value and its energy-conservation derivation"],
          conceptLink: {
            chapterSlug: "circular-motion",
            sectionHeading: "14. Condition for Completing the Vertical Circle",
            concept: "minimum speed at the bottom of a vertical circle",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 5, neet: 13, mhtCet: 8 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["minimum speed bottom vertical circle", "root 5gr", "vertical circle numerical"],
        },
        {
          id: "circ-vertical-circle-tension-general",
          expression: "T = mv²/r − mg cosφ   (φ measured from the TOP of the circle)",
          expressionLatex: "T = \\dfrac{mv^2}{r} - mg\\cos\\varphi",
          label: "Tension at a general point on a vertical circle",
          derivedFrom: "Newton's second law along the radial direction, with gravity's component toward/away from the centre depending on position",
          variables: [
            { symbol: "φ", name: "angle of the current position measured from the top of the circle", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["At the top (φ=0): T = mv²/r − mg; at the bottom (φ=180°): T = mv²/r + mg — sign of the gravity term flips"],
          commonMistakes: [
            "The gravity term's sign depends on position — always re-derive it from a free-body diagram at that specific point rather than memorising one fixed sign",
          ],
          conceptLink: {
            chapterSlug: "circular-motion",
            sectionHeading: "13. Motion in a Vertical Circle — Setting Up the Problem",
            concept: "tension at a general point in a vertical circle",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 4, neet: 6 },
          difficulty: "hard",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["tension vertical circle general point", "T mv2/r minus mg cos phi"],
        },
      ],
      examNotes:
        "JEE Advanced frequently combines vertical-circle problems with energy conservation across multiple points, not just top/bottom — always set up energy conservation between the two points actually asked about, not just the standard top-bottom pair.",
    },
  ],
};
