import type { ChapterFormulaSheet } from "./types";

export const currentElectricityFormulaSheet: ChapterFormulaSheet = {
  chapterSlug: "current-electricity",
  chapterName: "Current Electricity",
  className: "12",
  version: "1.0.0",
  lastUpdated: "2026-07-08",
  examCoverage: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
  quickRevisionIds: [
    "ce-drift-velocity-current",
    "ce-ohms-law",
    "ce-resistivity-formula",
    "ce-series-resistors",
    "ce-parallel-resistors",
    "ce-wheatstone-bridge",
    "ce-power-electrical",
  ],
  topicGroups: [
    {
      id: "ce-current-drift",
      title: "Current, Drift Velocity & Mobility",
      intro:
        "Current is charge flow, but at the microscopic level it's driven by a slow drift of electrons superimposed on their fast, random thermal motion.",
      formulas: [
        {
          id: "ce-current-def",
          expression: "I = q/t  (steady); I = dq/dt (general)",
          expressionLatex: "I = \\dfrac{dq}{dt}",
          label: "Electric current",
          variables: [
            { symbol: "I", name: "electric current", unit: "A", dimension: "[A]" },
            { symbol: "q", name: "charge transferred", unit: "C", dimension: "[AT]" },
            { symbol: "t", name: "time", unit: "s", dimension: "[T]" },
          ],
          conditions: ["Conventional current direction is opposite to electron flow in a metal"],
          conceptLink: {
            chapterSlug: "current-electricity",
            sectionHeading: "1. Electric Current — Definition and Direction",
            concept: "definition of electric current",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 7, neet: 9, mhtCet: 6 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["current definition", "I equals q by t"],
        },
        {
          id: "ce-current-density",
          expression: "J = I/A",
          expressionLatex: "J = \\dfrac{I}{A}",
          label: "Current density",
          variables: [
            { symbol: "J", name: "current density", unit: "A/m²", dimension: "[AL⁻²]" },
            { symbol: "A", name: "cross-sectional area", unit: "m²", dimension: "[L²]" },
          ],
          conditions: ["J is a vector along the direction of current flow (conventional)"],
          conceptLink: {
            chapterSlug: "current-electricity",
            sectionHeading: "2. Current Density",
            concept: "current density",
          },
          examTags: ["jee-main", "neet", "mht-cet"],
          frequency: "medium",
          examStats: { jeeMain: 5, neet: 6, mhtCet: 4 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["current density", "J equals I by A"],
        },
        {
          id: "ce-drift-velocity-current",
          expression: "I = n A e v(d)",
          expressionLatex: "I = nAev_d",
          label: "Current in terms of drift velocity",
          derivedFrom: "Charge crossing area A in time t: q = n(A·v(d)·t)e, then I = q/t",
          variables: [
            { symbol: "n", name: "free electron density (number per unit volume)", unit: "m⁻³", dimension: "[L⁻³]" },
            { symbol: "e", name: "electronic charge", unit: "C", dimension: "[AT]", notes: "e = 1.6 × 10⁻¹⁹ C" },
            { symbol: "v(d)", name: "drift velocity of electrons", unit: "m/s", dimension: "[LT⁻¹]" },
          ],
          conditions: ["v(d) is typically ~10⁻⁴ m/s — far slower than the electrons' random thermal speed (~10⁵ m/s)"],
          commonMistakes: [
            "Signal/current propagates near the speed of light through the field, even though individual electrons drift extremely slowly — don't confuse drift speed with signal speed",
          ],
          conceptLink: {
            chapterSlug: "current-electricity",
            sectionHeading: "5. Relating Current to Drift Velocity",
            concept: "current and drift velocity",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 4, neet: 12, mhtCet: 8 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["drift velocity current", "I equals nAev", "current microscopic"],
        },
        {
          id: "ce-drift-velocity-formula",
          expression: "v(d) = eEτ / m = eV τ /(mL)",
          expressionLatex: "v_d = \\dfrac{eE\\tau}{m}",
          label: "Drift velocity in terms of relaxation time",
          derivedFrom: "Average velocity gained between collisions: v(d) = a·τ with a = eE/m",
          variables: [
            { symbol: "τ", name: "average relaxation time between electron collisions", unit: "s", dimension: "[T]" },
            { symbol: "m", name: "electron mass", unit: "kg", dimension: "[M]" },
          ],
          conditions: ["Assumes electrons start with zero average velocity after each collision (randomised by scattering)"],
          conceptLink: {
            chapterSlug: "current-electricity",
            sectionHeading: "4. Drift Velocity",
            concept: "drift velocity mechanism",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 4, neet: 7 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["drift velocity relaxation time", "eE tau by m"],
        },
        {
          id: "ce-mobility",
          expression: "μ = v(d) / E = eτ/m",
          expressionLatex: "\\mu = \\dfrac{v_d}{E}",
          label: "Mobility of charge carriers",
          variables: [
            { symbol: "μ", name: "mobility", unit: "m²/(V·s)", dimension: "[M⁻¹T²A]" },
          ],
          conditions: ["Mobility connects the microscopic drift picture to macroscopic conductivity: σ = neμ"],
          conceptLink: {
            chapterSlug: "current-electricity",
            sectionHeading: "6. Mobility",
            concept: "mobility of charge carriers",
          },
          examTags: ["jee-main", "neet", "mht-cet"],
          frequency: "high",
          examStats: { jeeMain: 6, neet: 8, mhtCet: 5 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["mobility formula", "mu equals vd by E"],
        },
      ],
    },
    {
      id: "ce-ohms-law-resistance",
      title: "Ohm's Law, Resistance & Resistivity",
      intro:
        "Ohm's law is not a fundamental law — it holds only for materials (ohmic conductors) where resistivity stays constant regardless of the field applied.",
      formulas: [
        {
          id: "ce-ohms-law",
          expression: "V = IR",
          expressionLatex: "V = IR",
          label: "Ohm's law (macroscopic form)",
          variables: [
            { symbol: "V", name: "potential difference across the conductor", unit: "V", dimension: "[ML²T⁻³A⁻¹]" },
            { symbol: "R", name: "resistance", unit: "Ω", dimension: "[ML²T⁻³A⁻²]" },
          ],
          conditions: ["Holds only for ohmic conductors at constant physical conditions (temperature, etc.)"],
          commonMistakes: [
            "Not universal — diodes, transistors, and electrolytes are common non-ohmic examples where V–I is non-linear",
          ],
          conceptLink: {
            chapterSlug: "current-electricity",
            sectionHeading: "7. Microscopic and Macroscopic Forms of Ohm's Law",
            concept: "Ohm's law",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, neet: 12, mhtCet: 8 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["ohms law", "V equals IR"],
        },
        {
          id: "ce-ohms-law-microscopic",
          expression: "J = σE  (equivalently E = ρJ)",
          expressionLatex: "\\vec{J} = \\sigma\\vec{E}",
          label: "Ohm's law (microscopic form)",
          variables: [
            { symbol: "σ", name: "conductivity of the material", unit: "S/m", dimension: "[M⁻¹L⁻³T³A²]" },
          ],
          conditions: ["Valid pointwise inside the conductor, more fundamental than V = IR"],
          conceptLink: {
            chapterSlug: "current-electricity",
            sectionHeading: "7. Microscopic and Macroscopic Forms of Ohm's Law",
            concept: "microscopic Ohm's law",
          },
          examTags: ["jee-advanced", "neet"],
          frequency: "medium",
          examStats: { jeeAdvanced: 3, neet: 4 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["microscopic ohms law", "J equals sigma E"],
        },
        {
          id: "ce-resistivity-formula",
          expression: "R = ρL / A",
          expressionLatex: "R = \\dfrac{\\rho L}{A}",
          label: "Resistance in terms of resistivity",
          variables: [
            { symbol: "ρ", name: "resistivity of the material", unit: "Ω·m", dimension: "[ML³T⁻³A⁻²]" },
            { symbol: "L", name: "length of the conductor", unit: "m", dimension: "[L]" },
            { symbol: "A", name: "cross-sectional area", unit: "m²", dimension: "[L²]" },
          ],
          conditions: ["ρ depends only on the material and temperature — never on geometry"],
          conceptLink: {
            chapterSlug: "current-electricity",
            sectionHeading: "8. Resistance, Resistivity and Conductivity",
            concept: "resistivity and resistance",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 11, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["resistance resistivity", "R equals rho L by A"],
        },
        {
          id: "ce-resistivity-microscopic",
          expression: "ρ = m / (n e² τ)",
          expressionLatex: "\\rho = \\dfrac{m}{ne^2\\tau}",
          label: "Resistivity in terms of microscopic quantities",
          derivedFrom: "Combining v(d) = eEτ/m with I = nAev(d) and Ohm's law",
          variables: [
            { symbol: "n", name: "free electron density", unit: "m⁻³", dimension: "[L⁻³]" },
            { symbol: "τ", name: "average relaxation time between collisions", unit: "s", dimension: "[T]" },
          ],
          conditions: ["Explains why ρ increases with temperature for metals — τ decreases as thermal collisions increase"],
          conceptLink: {
            chapterSlug: "current-electricity",
            sectionHeading: "8. Resistance, Resistivity and Conductivity",
            concept: "microscopic origin of resistivity",
          },
          examTags: ["jee-advanced", "neet"],
          frequency: "medium",
          examStats: { jeeAdvanced: 3, neet: 4 },
          difficulty: "hard",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["resistivity microscopic formula", "m by ne squared tau"],
        },
        {
          id: "ce-stretching-wire",
          expression: "R' = R (L'/L)² = R × (stretch factor)²",
          expressionLatex: "R' = R\\left(\\dfrac{L'}{L}\\right)^2",
          label: "Effect of stretching a wire on its resistance (volume constant)",
          derivedFrom: "Volume conserved: A'L' = AL; R = ρL/A so R ∝ L² at constant volume",
          variables: [
            { symbol: "L'", name: "new length after stretching", unit: "m", dimension: "[L]" },
          ],
          conditions: ["If length increases n times, resistance increases n² times (volume of the wire stays fixed)"],
          commonMistakes: [
            "Only valid when volume is conserved during stretching (typical assumption) — not valid if material is added/removed",
          ],
          conceptLink: {
            chapterSlug: "current-electricity",
            sectionHeading: "9. Effect of Stretching a Wire on its Resistance",
            concept: "resistance change on stretching",
          },
          examTags: ["jee-main", "neet", "mht-cet"],
          frequency: "high",
          examStats: { jeeMain: 6, neet: 8, mhtCet: 5 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["stretching wire resistance", "R proportional L squared"],
        },
        {
          id: "ce-temperature-dependence",
          expression: "R(T) = R₀(1 + αΔT)",
          expressionLatex: "R_T = R_0(1+\\alpha\\Delta T)",
          label: "Temperature dependence of resistance",
          variables: [
            { symbol: "α", name: "temperature coefficient of resistance", unit: "per °C or per K", dimension: "[Θ⁻¹]" },
            { symbol: "R₀", name: "resistance at the reference temperature", unit: "Ω", dimension: "[ML²T⁻³A⁻²]" },
          ],
          conditions: ["α is positive for metals (R increases with T), negative for semiconductors (R decreases with T)"],
          commonMistakes: [
            "Semiconductor resistivity DECREASES with temperature (more charge carriers freed) — opposite trend to metals",
          ],
          conceptLink: {
            chapterSlug: "current-electricity",
            sectionHeading: "11. Temperature Dependence of Resistivity and Resistance",
            concept: "temperature dependence of resistance",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 10, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["temperature coefficient resistance", "R0 1 plus alpha delta T"],
        },
      ],
    },
    {
      id: "ce-combinations-cells",
      title: "Combinations of Resistors, EMF & Internal Resistance",
      intro:
        "Resistors in series share current; in parallel they share voltage. A real cell always has internal resistance, which is why terminal voltage falls under load.",
      formulas: [
        {
          id: "ce-series-resistors",
          expression: "R(eq) = R₁ + R₂ + ⋯",
          expressionLatex: "R_{eq} = R_1+R_2+\\cdots",
          label: "Equivalent resistance in series",
          variables: [],
          conditions: ["Same current flows through every resistor in series", "R(eq) always LARGER than the largest individual resistance"],
          conceptLink: {
            chapterSlug: "current-electricity",
            sectionHeading: "13. Series and Parallel Combination of Resistors",
            concept: "series resistors",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 7, neet: 9, mhtCet: 6 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["series resistors", "R equivalent sum"],
        },
        {
          id: "ce-parallel-resistors",
          expression: "1/R(eq) = 1/R₁ + 1/R₂ + ⋯",
          expressionLatex: "\\dfrac{1}{R_{eq}} = \\dfrac{1}{R_1}+\\dfrac{1}{R_2}+\\cdots",
          label: "Equivalent resistance in parallel",
          conditions: ["Same voltage across every resistor in parallel", "R(eq) always SMALLER than the smallest individual resistance"],
          variables: [],
          conceptLink: {
            chapterSlug: "current-electricity",
            sectionHeading: "13. Series and Parallel Combination of Resistors",
            concept: "parallel resistors",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 7, neet: 9, mhtCet: 6 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["parallel resistors", "1 by R equivalent"],
        },
        {
          id: "ce-terminal-voltage",
          expression: "V = ε − Ir  (discharging);  V = ε + Ir  (charging)",
          expressionLatex: "V = \\varepsilon - Ir",
          label: "Terminal voltage of a cell with internal resistance",
          derivedFrom: "Applying Kirchhoff's voltage law around a loop with the cell and external resistance",
          variables: [
            { symbol: "ε", name: "EMF of the cell", unit: "V", dimension: "[ML²T⁻³A⁻¹]" },
            { symbol: "r", name: "internal resistance of the cell", unit: "Ω", dimension: "[ML²T⁻³A⁻²]" },
            { symbol: "I", name: "current drawn from the cell", unit: "A", dimension: "[A]" },
          ],
          conditions: ["V = ε only when I = 0 (open circuit) — the true EMF is only measurable with no current flowing"],
          commonMistakes: [
            "While CHARGING (external source driving current backward through the cell), terminal voltage EXCEEDS EMF: V = ε + Ir",
          ],
          conceptLink: {
            chapterSlug: "current-electricity",
            sectionHeading: "15. EMF, Internal Resistance and Terminal Voltage of a Cell",
            concept: "terminal voltage and internal resistance",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 11, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["terminal voltage cell", "epsilon minus Ir"],
        },
        {
          id: "ce-cells-series",
          expression: "ε(eq) = nε;  r(eq) = nr  (n identical cells in series)",
          expressionLatex: "\\varepsilon_{eq} = n\\varepsilon,\\quad r_{eq} = nr",
          label: "n identical cells connected in series",
          conditions: ["Useful for high-voltage requirements; internal resistance adds up too, which limits current"],
          variables: [
            { symbol: "n", name: "number of identical cells", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
          ],
          conceptLink: {
            chapterSlug: "current-electricity",
            sectionHeading: "16. Combination of Cells",
            concept: "cells in series",
          },
          examTags: ["jee-main", "neet", "mht-cet"],
          frequency: "high",
          examStats: { jeeMain: 6, neet: 8, mhtCet: 5 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["cells in series", "n cells emf internal resistance"],
        },
        {
          id: "ce-cells-parallel",
          expression: "ε(eq) = ε;  r(eq) = r/n  (n identical cells in parallel)",
          expressionLatex: "r_{eq} = \\dfrac{r}{n}",
          label: "n identical cells connected in parallel",
          conditions: ["Useful for high-current requirements; EMF stays the same as a single cell but internal resistance drops"],
          variables: [],
          conceptLink: {
            chapterSlug: "current-electricity",
            sectionHeading: "16. Combination of Cells",
            concept: "cells in parallel",
          },
          examTags: ["jee-main", "neet", "mht-cet"],
          frequency: "high",
          examStats: { jeeMain: 5, neet: 7, mhtCet: 4 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["cells in parallel", "internal resistance parallel cells"],
        },
      ],
    },
    {
      id: "ce-kirchhoff-bridges",
      title: "Kirchhoff's Laws, Bridges & Potentiometer",
      intro:
        "Kirchhoff's laws are conservation of charge (junction rule) and energy (loop rule) applied to circuits — the Wheatstone bridge and potentiometer are their most exam-favoured applications.",
      formulas: [
        {
          id: "ce-kirchhoff-current-law",
          expression: "ΣI(in) = ΣI(out)  at any junction",
          expressionLatex: "\\sum I_{in} = \\sum I_{out}",
          label: "Kirchhoff's current law (junction rule)",
          variables: [],
          conditions: ["Statement of conservation of charge — charge cannot accumulate at a junction in steady state"],
          conceptLink: {
            chapterSlug: "current-electricity",
            sectionHeading: "14. Kirchhoff's Laws",
            concept: "Kirchhoff's current law",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 7, neet: 9, mhtCet: 6 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["kirchhoffs current law", "junction rule"],
        },
        {
          id: "ce-kirchhoff-voltage-law",
          expression: "Σ(around a closed loop) IR = Σ EMF",
          expressionLatex: "\\sum IR = \\sum \\varepsilon",
          label: "Kirchhoff's voltage law (loop rule)",
          variables: [],
          conditions: ["Statement of conservation of energy around any closed loop in a circuit"],
          commonMistakes: [
            "Sign convention matters: traverse a resistor in the direction of assumed current for a −IR drop; traverse a cell from − to + terminal for a +ε gain",
          ],
          conceptLink: {
            chapterSlug: "current-electricity",
            sectionHeading: "14. Kirchhoff's Laws",
            concept: "Kirchhoff's voltage law",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 10, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["kirchhoffs voltage law", "loop rule circuits"],
        },
        {
          id: "ce-wheatstone-bridge",
          expression: "P/Q = R/S  (balanced condition)",
          expressionLatex: "\\dfrac{P}{Q} = \\dfrac{R}{S}",
          label: "Wheatstone bridge balance condition",
          derivedFrom: "Zero galvanometer deflection means no potential difference across the bridge arm, giving equal potential drops across P–Q and R–S branches",
          variables: [
            { symbol: "P, Q, R, S", name: "the four resistances forming the bridge arms", unit: "Ω", dimension: "[ML²T⁻³A⁻²]" },
          ],
          conditions: ["At balance, the galvanometer carries zero current regardless of its own resistance"],
          conceptLink: {
            chapterSlug: "current-electricity",
            sectionHeading: "20. Wheatstone Bridge and Metre Bridge",
            concept: "Wheatstone bridge",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 11, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["wheatstone bridge balance", "P by Q equals R by S"],
        },
        {
          id: "ce-metre-bridge",
          expression: "R/S = l / (100 − l)",
          expressionLatex: "\\dfrac{R}{S} = \\dfrac{l}{100-l}",
          label: "Metre bridge (a practical Wheatstone bridge)",
          variables: [
            { symbol: "l", name: "balance length from one end (in cm, on a 100 cm wire)", unit: "cm", dimension: "[L]" },
          ],
          conditions: ["End corrections and jockey resistance are ignored in the ideal formula"],
          conceptLink: {
            chapterSlug: "current-electricity",
            sectionHeading: "20. Wheatstone Bridge and Metre Bridge",
            concept: "metre bridge",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 6, neet: 8, mhtCet: 6 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["metre bridge formula", "l by 100 minus l"],
        },
        {
          id: "ce-potentiometer-principle",
          expression: "V ∝ l  (potential drop is proportional to balancing length)",
          expressionLatex: "V = k\\,l,\\quad k = \\dfrac{\\varepsilon}{L}",
          label: "Potentiometer principle",
          derivedFrom: "Uniform potential gradient k = ε/L along a wire of length L carrying a steady current",
          variables: [
            { symbol: "l", name: "balancing length where the galvanometer shows null deflection", unit: "m", dimension: "[L]" },
            { symbol: "k", name: "potential gradient along the wire", unit: "V/m", dimension: "[MLT⁻³A⁻¹]" },
          ],
          conditions: ["Potentiometer draws NO current from the cell/EMF being measured at balance — this is its key advantage over a voltmeter"],
          commonMistakes: [
            "A voltmeter always draws some current and hence measures terminal voltage, not true EMF — only a potentiometer at null gives exact EMF",
          ],
          conceptLink: {
            chapterSlug: "current-electricity",
            sectionHeading: "21. Potentiometer — Principle and Applications",
            concept: "potentiometer principle",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 3, neet: 10, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["potentiometer principle", "V proportional to l", "potential gradient"],
        },
      ],
      examNotes:
        "Boards frequently ask to derive the Wheatstone bridge balance condition using Kirchhoff's laws directly — know the loop-rule derivation, not just the final ratio.",
    },
    {
      id: "ce-power-heating",
      title: "Electrical Power & Joule Heating",
      intro:
        "Electrical energy dissipated in a resistor converts entirely to heat — the basis of every heating appliance and a starting point for circuit power-transfer problems.",
      formulas: [
        {
          id: "ce-power-electrical",
          expression: "P = VI = I²R = V²/R",
          expressionLatex: "P = I^2R = \\dfrac{V^2}{R}",
          label: "Electrical power dissipated in a resistor",
          variables: [
            { symbol: "P", name: "power dissipated", unit: "W", dimension: "[ML²T⁻³]" },
          ],
          conditions: ["All three forms are equivalent via V = IR; choose whichever quantities are known"],
          conceptLink: {
            chapterSlug: "current-electricity",
            sectionHeading: "17. Electrical Power, Energy and Joule's Law of Heating",
            concept: "electrical power",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, neet: 12, mhtCet: 8 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["electrical power formula", "P equals VI I squared R"],
        },
        {
          id: "ce-joule-heating",
          expression: "H = I²Rt  (heat generated in time t)",
          expressionLatex: "H = I^2Rt",
          label: "Joule's law of heating",
          variables: [
            { symbol: "H", name: "heat energy generated", unit: "J", dimension: "[ML²T⁻²]" },
            { symbol: "t", name: "time for which current flows", unit: "s", dimension: "[T]" },
          ],
          conditions: ["This is exactly the electrical energy dissipated: H = Pt"],
          conceptLink: {
            chapterSlug: "current-electricity",
            sectionHeading: "17. Electrical Power, Energy and Joule's Law of Heating",
            concept: "Joule heating",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 6, neet: 8, mhtCet: 5 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["joules law heating", "H equals I squared R t"],
        },
        {
          id: "ce-max-power-transfer",
          expression: "P(max) at R(external) = r  (internal resistance)",
          expressionLatex: "P_{max} \\text{ when } R = r",
          label: "Maximum power transfer theorem",
          derivedFrom: "Maximise P = ε²R/(R+r)² with respect to R using dP/dR = 0",
          variables: [],
          conditions: ["At R = r, exactly half the total power is delivered to the external resistor and half is lost internally"],
          commonMistakes: [
            "Maximum power transfer does NOT mean maximum efficiency — efficiency is only 50% at this condition, not 100%",
          ],
          conceptLink: {
            chapterSlug: "current-electricity",
            sectionHeading: "18. Maximum Power Transfer and Bulbs in Series/Parallel",
            concept: "maximum power transfer",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 3, neet: 6 },
          difficulty: "hard",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["maximum power transfer", "R equals r internal resistance"],
        },
        {
          id: "ce-bulb-rating",
          expression: "R(bulb) = V(rated)² / P(rated)",
          expressionLatex: "R = \\dfrac{V_{rated}^2}{P_{rated}}",
          label: "Resistance of a bulb from its power rating",
          derivedFrom: "Rearranging P = V²/R at rated conditions",
          conditions: ["This R is treated as constant — real filament resistance actually changes with temperature, but exam problems assume it's fixed"],
          commonMistakes: [
            "A 100 W bulb has LOWER resistance than a 60 W bulb (at the same rated voltage) — inversely proportional to rated power",
          ],
          variables: [],
          conceptLink: {
            chapterSlug: "current-electricity",
            sectionHeading: "18. Maximum Power Transfer and Bulbs in Series/Parallel",
            concept: "bulb resistance from rating",
          },
          examTags: ["jee-main", "neet", "mht-cet"],
          frequency: "high",
          examStats: { jeeMain: 6, neet: 7, mhtCet: 5 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["bulb resistance rating", "V squared by P rated"],
        },
      ],
    },
  ],
};
