import type { ChapterFormulaSheet } from "./types";

export const currentElectricityFormulaSheet: ChapterFormulaSheet = {
  chapterSlug: "current-electricity",
  chapterName: "Current Electricity",
  className: "12",
  version: "1.0.0",
  lastUpdated: "2026-07-05",
  examCoverage: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
  quickRevisionIds: [
    "ce-ohms-law",
    "ce-resistivity",
    "ce-resistor-combination",
    "ce-emf-terminal-voltage",
    "ce-kirchhoff-laws",
    "ce-wheatstone",
    "ce-power",
  ],
  topicGroups: [
    {
      id: "ce-ohm-resistance",
      title: "Ohm's Law & Resistance",
      intro:
        "Current is drifting charge; resistance opposes it. Ohm's law links the two, and resistivity captures what belongs to the material versus the shape.",
      formulas: [
        {
          id: "ce-current-drift",
          expression: "I = nAe v(d);   v(d) = eEτ/m",
          expressionLatex: "I = nAev_d",
          label: "Current and drift velocity",
          variables: [
            { symbol: "I", name: "current", unit: "A", dimension: "[A]" },
            { symbol: "n", name: "free electron number density", unit: "m⁻³", dimension: "[L⁻³]" },
            { symbol: "v(d)", name: "drift velocity", unit: "m/s", dimension: "[LT⁻¹]" },
            { symbol: "τ", name: "relaxation time between collisions", unit: "s", dimension: "[T]" },
          ],
          conditions: ["Drift speed is tiny (~mm/s) yet current flows instantly — the field sets up near light speed"],
          commonMistakes: [
            "Current density J = I/A = nev(d) = σE is the local, area-independent quantity",
          ],
          conceptLink: {
            chapterSlug: "current-electricity",
            sectionHeading: "1. Electric Current",
            concept: "drift velocity",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 7, neet: 10, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["drift velocity", "I nAe vd", "current density"],
        },
        {
          id: "ce-ohms-law",
          expression: "V = IR",
          expressionLatex: "V = IR",
          label: "Ohm's law",
          variables: [
            { symbol: "V", name: "potential difference", unit: "V", dimension: "[ML²T⁻³A⁻¹]" },
            { symbol: "I", name: "current", unit: "A", dimension: "[A]" },
            { symbol: "R", name: "resistance", unit: "Ω", dimension: "[ML²T⁻³A⁻²]" },
          ],
          conditions: ["Holds for ohmic conductors at constant temperature", "Non-ohmic: diodes, filaments, electrolytes deviate"],
          commonMistakes: [
            "R rises with temperature for metals but FALLS for semiconductors — the sign of the temperature coefficient differs",
          ],
          conceptLink: {
            chapterSlug: "current-electricity",
            sectionHeading: "2. Ohm's Law",
            concept: "Ohm's law",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 14, mhtCet: 11 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["ohms law", "V IR"],
        },
        {
          id: "ce-resistivity",
          expression: "R = ρL/A;   ρ = m/(ne²τ)",
          expressionLatex: "R = \\dfrac{\\rho L}{A}",
          label: "Resistance and resistivity",
          variables: [
            { symbol: "ρ", name: "resistivity of the material", unit: "Ω·m", dimension: "[ML³T⁻³A⁻²]" },
            { symbol: "L", name: "length of the conductor", unit: "m", dimension: "[L]" },
            { symbol: "A", name: "cross-sectional area", unit: "m²", dimension: "[L²]" },
          ],
          conditions: ["ρ is a material property (independent of shape); R depends on shape too"],
          commonMistakes: [
            "Stretching a wire to n times its length makes R go up n² times (length ×n, area ÷n) — a constant-volume trap",
          ],
          usedIn: ["thermal-properties-of-matter"],
          conceptLink: {
            chapterSlug: "current-electricity",
            sectionHeading: "3. Resistivity",
            concept: "resistivity",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 3, neet: 12, mhtCet: 9 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["resistivity", "rho L by A", "stretched wire resistance"],
        },
      ],
      importantObservations: [
        "Temperature dependence: ρ(T) = ρ₀[1 + α(T − T₀)] for metals, α positive and small",
      ],
    },
    {
      id: "ce-networks",
      title: "Resistor Networks & Kirchhoff's Laws",
      intro:
        "Series adds resistance, parallel adds conductance. When symmetry fails, Kirchhoff's two laws crack any network.",
      formulas: [
        {
          id: "ce-resistor-combination",
          expression: "Series: R(eq) = ΣRᵢ;   Parallel: 1/R(eq) = Σ 1/Rᵢ",
          expressionLatex: "R_{series} = \\sum R_i,\\quad \\dfrac{1}{R_{parallel}} = \\sum\\dfrac{1}{R_i}",
          label: "Resistors in series and parallel",
          variables: [
            { symbol: "R(eq)", name: "equivalent resistance", unit: "Ω", dimension: "[ML²T⁻³A⁻²]" },
          ],
          conditions: [
            "Series: same CURRENT; Parallel: same VOLTAGE",
            "Two in parallel: R(eq) = R₁R₂/(R₁ + R₂)",
          ],
          commonMistakes: [
            "Parallel equivalent is always SMALLER than the smallest resistor in the group",
          ],
          usedIn: ["electrostatic-potential-and-capacitance"],
          conceptLink: {
            chapterSlug: "current-electricity",
            sectionHeading: "4. Combination of Resistors",
            concept: "resistors in series and parallel",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 10, jeeAdvanced: 5, neet: 13, mhtCet: 10 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["resistors series parallel", "equivalent resistance"],
        },
        {
          id: "ce-kirchhoff-laws",
          expression: "KCL: ΣI = 0 at a junction;   KVL: ΣV = 0 around a loop",
          expressionLatex: "\\sum I_{junction} = 0,\\quad \\sum V_{loop} = 0",
          label: "Kirchhoff's laws",
          variables: [
            { symbol: "ΣI", name: "algebraic sum of currents at a node (charge conservation)", unit: "A", dimension: "[A]" },
            { symbol: "ΣV", name: "algebraic sum of EMFs and IR drops around a loop (energy conservation)", unit: "V", dimension: "[ML²T⁻³A⁻¹]" },
          ],
          conditions: ["KCL = charge conservation; KVL = energy conservation", "Assign a consistent sign convention and stick to it"],
          commonMistakes: [
            "A negative current from the solution just means the real direction is opposite to your assumed one — the magnitude is still correct",
          ],
          conceptLink: {
            chapterSlug: "current-electricity",
            sectionHeading: "5. Kirchhoff's Laws",
            concept: "Kirchhoff's laws",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 6, neet: 11, mhtCet: 8 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["kirchhoff", "KCL KVL", "junction loop rule"],
        },
        {
          id: "ce-wheatstone",
          expression: "Balanced when P/Q = R/S  (no current through galvanometer)",
          expressionLatex: "\\dfrac{P}{Q} = \\dfrac{R}{S}",
          label: "Wheatstone bridge",
          variables: [
            { symbol: "P, Q, R, S", name: "the four bridge arm resistances", unit: "Ω", dimension: "[ML²T⁻³A⁻²]" },
          ],
          conditions: [
            "At balance the galvanometer arm carries NO current, so it can be removed or shorted",
            "Meter bridge and post-office box are practical Wheatstone bridges",
          ],
          commonMistakes: [
            "At balance the bridge is independent of the galvanometer resistance and the cell EMF — a favourite conceptual question",
          ],
          conceptLink: {
            chapterSlug: "current-electricity",
            sectionHeading: "6. Wheatstone Bridge",
            concept: "Wheatstone bridge",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 12, mhtCet: 9 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["wheatstone bridge", "P by Q R by S", "balanced bridge"],
        },
      ],
      importantObservations: [
        "Balanced-bridge trick: spotting a Wheatstone pattern lets you delete the middle resistor and collapse a scary network instantly",
      ],
      examNotes:
        "NEET favours symmetry and balanced-bridge shortcuts; JEE Advanced demands full Kirchhoff systems and infinite-ladder networks.",
    },
    {
      id: "ce-cells-power",
      title: "EMF, Cells & Electrical Power",
      intro:
        "A real cell has internal resistance, so terminal voltage drops under load. Power delivered peaks when the load matches the internal resistance.",
      formulas: [
        {
          id: "ce-emf-terminal-voltage",
          expression: "V = ε − Ir;   I = ε/(R + r)",
          expressionLatex: "V = \\varepsilon - Ir",
          label: "EMF, internal resistance and terminal voltage",
          variables: [
            { symbol: "ε", name: "electromotive force of the cell", unit: "V", dimension: "[ML²T⁻³A⁻¹]" },
            { symbol: "r", name: "internal resistance", unit: "Ω", dimension: "[ML²T⁻³A⁻²]" },
            { symbol: "V", name: "terminal voltage", unit: "V", dimension: "[ML²T⁻³A⁻¹]" },
          ],
          conditions: [
            "Discharging: V = ε − Ir (V < ε); charging: V = ε + Ir (V > ε)",
            "Open circuit (I = 0): V = ε",
          ],
          commonMistakes: [
            "Cells in series: EMFs add, internal resistances add; identical cells in parallel: EMF unchanged, r becomes r/n",
          ],
          conceptLink: {
            chapterSlug: "current-electricity",
            sectionHeading: "7. EMF and Internal Resistance",
            concept: "terminal voltage",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 13, mhtCet: 10 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["emf terminal voltage", "epsilon minus Ir", "internal resistance"],
        },
        {
          id: "ce-power",
          expression: "P = VI = I²R = V²/R",
          expressionLatex: "P = VI = I^2R = \\dfrac{V^2}{R}",
          label: "Electrical power",
          variables: [
            { symbol: "P", name: "power dissipated / delivered", unit: "W", dimension: "[ML²T⁻³]" },
          ],
          conditions: [
            "Series (same I): use P = I²R — largest R dissipates most",
            "Parallel (same V): use P = V²/R — smallest R dissipates most",
          ],
          commonMistakes: [
            "A bulb rated '100 W, 220 V' has fixed RESISTANCE R = V²/P; its actual power changes if the supply voltage changes",
          ],
          usedIn: ["work-energy-and-power"],
          conceptLink: {
            chapterSlug: "current-electricity",
            sectionHeading: "8. Electrical Power",
            concept: "electrical power",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 13, mhtCet: 10 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["electrical power", "I squared R", "V squared by R", "bulb rating"],
        },
        {
          id: "ce-max-power-transfer",
          expression: "P(max) when R = r;   P(max) = ε²/4r",
          expressionLatex: "P_{max} = \\dfrac{\\varepsilon^2}{4r}\\ \\text{at}\\ R = r",
          label: "Maximum power transfer",
          derivedFrom: "Maximising P = ε²R/(R + r)² with respect to R",
          variables: [
            { symbol: "R", name: "load resistance", unit: "Ω", dimension: "[ML²T⁻³A⁻²]" },
            { symbol: "r", name: "internal (source) resistance", unit: "Ω", dimension: "[ML²T⁻³A⁻²]" },
          ],
          conditions: ["At maximum power the efficiency is only 50% — half the energy heats the source"],
          conceptLink: {
            chapterSlug: "current-electricity",
            sectionHeading: "8. Electrical Power",
            concept: "maximum power transfer",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 4, neet: 7 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["maximum power transfer", "R equals r", "epsilon squared by 4r"],
        },
        {
          id: "ce-meter-bridge-potentiometer",
          expression: "Potentiometer: ε₁/ε₂ = l₁/l₂;   Meter bridge: R/S = l/(100 − l)",
          expressionLatex: "\\dfrac{\\varepsilon_1}{\\varepsilon_2} = \\dfrac{l_1}{l_2}",
          label: "Potentiometer & meter bridge",
          variables: [
            { symbol: "l", name: "balancing length", unit: "cm (or m)", dimension: "[L]" },
          ],
          conditions: [
            "Potentiometer draws NO current at balance, so it measures true EMF (unlike a voltmeter)",
            "Potentiometer is more accurate the LONGER the wire (smaller potential gradient)",
          ],
          commonMistakes: [
            "A potentiometer compares EMFs or measures internal resistance; it never loads the cell at the balance point",
          ],
          conceptLink: {
            chapterSlug: "current-electricity",
            sectionHeading: "9. Potentiometer",
            concept: "potentiometer and meter bridge",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 5, neet: 10, mhtCet: 8 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["potentiometer", "meter bridge", "balancing length"],
        },
      ],
      importantObservations: [
        "Heat produced (Joule's law): H = I²Rt — the basis of fuses, heaters, and the kWh on your electricity bill",
      ],
      examNotes:
        "NEET repeats terminal-voltage, power-rating and potentiometer questions; JEE Advanced blends max-power-transfer with multi-cell networks.",
    },
  ],
};
