import type { ChapterFormulaSheet } from "./types";

export const dualNatureOfRadiationAndMatterFormulaSheet: ChapterFormulaSheet = {
  chapterSlug: "dual-nature-of-radiation-and-matter",
  chapterName: "Dual Nature of Radiation & Matter",
  className: "12",
  version: "1.0.0",
  lastUpdated: "2026-07-09",
  examCoverage: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
  quickRevisionIds: [
    "dn-photon-energy",
    "dn-einstein-photoelectric-equation",
    "dn-stopping-potential",
    "dn-de-broglie-wavelength",
    "dn-de-broglie-accelerated-charge",
  ],
  topicGroups: [
    {
      id: "dn-photon-basics",
      title: "Photon Energy, Momentum & Work Function",
      intro:
        "Einstein treated light as a stream of discrete energy packets — photons — each carrying a fixed energy and momentum set entirely by its frequency.",
      formulas: [
        {
          id: "dn-photon-energy",
          expression: "E = hν = hc/λ",
          expressionLatex: "E = h\\nu = \\dfrac{hc}{\\lambda}",
          label: "Energy of a photon",
          variables: [
            { symbol: "h", name: "Planck's constant", unit: "J·s", dimension: "[ML²T⁻¹]", notes: "h = 6.63 × 10⁻³⁴ J·s" },
            { symbol: "ν", name: "frequency of the radiation", unit: "Hz", dimension: "[T⁻¹]" },
          ],
          conditions: ["Photon energy depends ONLY on frequency (or wavelength) — never on the intensity of the light"],
          usedIn: ["atoms", "electromagnetic-waves"],
          conceptLink: {
            chapterSlug: "dual-nature-of-radiation-and-matter",
            sectionHeading: "3. Quantum Theory: Energy, Momentum and Effective Mass of a Photon",
            concept: "photon energy",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 4, neet: 12, mhtCet: 8 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["photon energy formula", "E equals h nu", "hc by lambda"],
        },
        {
          id: "dn-photon-momentum",
          expression: "p = h/λ = E/c",
          expressionLatex: "p = \\dfrac{h}{\\lambda} = \\dfrac{E}{c}",
          label: "Momentum of a photon",
          variables: [
            { symbol: "p", name: "momentum of the photon", unit: "kg·m/s", dimension: "[MLT⁻¹]" },
          ],
          conditions: ["A photon has zero rest mass but non-zero momentum — momentum here comes entirely from its energy via p = E/c, not from mv"],
          usedIn: ["electromagnetic-waves"],
          conceptLink: {
            chapterSlug: "dual-nature-of-radiation-and-matter",
            sectionHeading: "3. Quantum Theory: Energy, Momentum and Effective Mass of a Photon",
            concept: "photon momentum",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet"],
          frequency: "high",
          examStats: { jeeMain: 7, jeeAdvanced: 4, neet: 8, mhtCet: 6 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["photon momentum formula", "p equals h by lambda"],
        },
        {
          id: "dn-work-function",
          expression: "W₀ = hν₀",
          expressionLatex: "W_0 = h\\nu_0",
          label: "Work function of a metal",
          variables: [
            { symbol: "W₀", name: "work function — minimum energy to free an electron from the metal surface", unit: "J or eV", dimension: "[ML²T⁻²]" },
            { symbol: "ν₀", name: "threshold frequency of the metal", unit: "Hz", dimension: "[T⁻¹]" },
          ],
          conditions: ["A property of the metal's surface — different metals have different W₀ and hence different ν₀"],
          conceptLink: {
            chapterSlug: "dual-nature-of-radiation-and-matter",
            sectionHeading: "2. Types of Electron Emission and Work Function",
            concept: "work function",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 10, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["work function formula", "W0 equals h nu0"],
        },
      ],
    },
    {
      id: "dn-photoelectric-effect",
      title: "The Photoelectric Effect",
      intro:
        "Einstein's photoelectric equation explains every observed feature of the photoelectric effect at once — features that classical wave theory could never account for.",
      formulas: [
        {
          id: "dn-einstein-photoelectric-equation",
          expression: "hν = W₀ + KE(max) ,  KE(max) = h(ν − ν₀)",
          expressionLatex: "h\\nu = W_0 + KE_{max}",
          label: "Einstein's photoelectric equation",
          derivedFrom: "Energy conservation for a single photon absorbed by a single electron: photon energy = work to escape + leftover kinetic energy",
          variables: [
            { symbol: "KE(max)", name: "maximum kinetic energy of emitted photoelectrons", unit: "J or eV", dimension: "[ML²T⁻²]" },
          ],
          conditions: ["Below the threshold frequency ν₀, NO electrons are emitted, however intense the light — a direct contradiction of classical wave theory"],
          commonMistakes: [
            "Increasing intensity increases the NUMBER of photoelectrons (photocurrent), not their maximum kinetic energy — only frequency affects KE(max)",
          ],
          conceptLink: {
            chapterSlug: "dual-nature-of-radiation-and-matter",
            sectionHeading: "10. Einstein's Photoelectric Equation",
            concept: "Einstein's photoelectric equation",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 10, jeeAdvanced: 5, neet: 13, mhtCet: 8 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["einstein photoelectric equation", "h nu equals W0 plus KE max"],
        },
        {
          id: "dn-stopping-potential",
          expression: "eV₀ = KE(max) = h(ν − ν₀)",
          expressionLatex: "eV_0 = h(\\nu-\\nu_0)",
          label: "Stopping potential",
          variables: [
            { symbol: "V₀", name: "stopping potential — the retarding voltage that just stops the fastest photoelectrons", unit: "V", dimension: "[ML²T⁻³A⁻¹]" },
            { symbol: "e", name: "electronic charge", unit: "C", dimension: "[AT]" },
          ],
          conditions: ["V₀ depends on frequency but NOT on intensity — a graph of V₀ vs. ν is a straight line with slope h/e, a classic experimental method to measure Planck's constant"],
          conceptLink: {
            chapterSlug: "dual-nature-of-radiation-and-matter",
            sectionHeading: "11. Graphs: K.E.max vs ν and Stopping Potential vs ν",
            concept: "stopping potential",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 4, neet: 11, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["stopping potential formula", "eV0 equals h nu minus nu0"],
        },
        {
          id: "dn-photon-flux-current",
          expression: "Photon flux = P/(hν) ,  Photocurrent ∝ intensity (at fixed frequency)",
          expressionLatex: "n = \\dfrac{P}{h\\nu}",
          label: "Photon flux and its relation to photocurrent",
          variables: [
            { symbol: "n", name: "number of photons incident per second", unit: "s⁻¹", dimension: "[T⁻¹]" },
            { symbol: "P", name: "power of the incident light beam", unit: "W", dimension: "[ML²T⁻³]" },
          ],
          conditions: ["Each absorbed photon can free at most one electron (in the simplest one-photon picture), so more photons per second (more intensity) directly means more photocurrent"],
          conceptLink: {
            chapterSlug: "dual-nature-of-radiation-and-matter",
            sectionHeading: "4. Intensity of Light and Photon Flux",
            concept: "photon flux",
          },
          examTags: ["jee-main", "neet", "mht-cet"],
          frequency: "medium",
          examStats: { jeeMain: 5, neet: 6, mhtCet: 4 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["photon flux formula", "P by h nu"],
        },
      ],
    },
    {
      id: "dn-matter-waves",
      title: "de Broglie Hypothesis & Matter Waves",
      intro:
        "If light (a wave) can behave like particles, de Broglie proposed the reverse: every moving particle should have an associated wavelength — matter and radiation are symmetric in this respect.",
      formulas: [
        {
          id: "dn-de-broglie-wavelength",
          expression: "λ = h/p = h/(mv)",
          expressionLatex: "\\lambda = \\dfrac{h}{mv}",
          label: "de Broglie wavelength of a moving particle",
          variables: [
            { symbol: "λ", name: "de Broglie wavelength", unit: "m", dimension: "[L]" },
            { symbol: "m", name: "mass of the particle", unit: "kg", dimension: "[M]" },
          ],
          conditions: ["Wavelength is inversely proportional to momentum — heavier or faster particles have shorter (harder to observe) de Broglie wavelengths"],
          commonMistakes: [
            "Wavelength effects are only noticeable for very light particles (electrons) — for macroscopic objects, λ is far too small to ever observe, which is why we don't see everyday objects diffract",
          ],
          conceptLink: {
            chapterSlug: "dual-nature-of-radiation-and-matter",
            sectionHeading: "16. de Broglie Hypothesis and Wavelength of a Moving Particle",
            concept: "de Broglie wavelength",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 4, neet: 12, mhtCet: 8 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["de broglie wavelength formula", "lambda equals h by mv"],
        },
        {
          id: "dn-de-broglie-accelerated-charge",
          expression: "λ = h / √(2mqV)",
          expressionLatex: "\\lambda = \\dfrac{h}{\\sqrt{2mqV}}",
          label: "de Broglie wavelength of a charge accelerated through a potential difference",
          derivedFrom: "Kinetic energy gained qV = p²/2m, solved for p and substituted into λ = h/p",
          variables: [
            { symbol: "q", name: "charge of the particle", unit: "C", dimension: "[AT]" },
            { symbol: "V", name: "accelerating potential difference", unit: "V", dimension: "[ML²T⁻³A⁻¹]" },
          ],
          conditions: ["Assumes the particle starts from rest and is accelerated purely electrostatically (non-relativistic)"],
          usedIn: ["moving-charges-and-magnetism"],
          conceptLink: {
            chapterSlug: "dual-nature-of-radiation-and-matter",
            sectionHeading: "17. de Broglie Wavelength of Charged and Thermal (Uncharged) Particles",
            concept: "de Broglie wavelength of an accelerated charge",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 11, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["de broglie wavelength accelerated charge", "h by root 2mqV"],
        },
        {
          id: "dn-de-broglie-thermal-particle",
          expression: "λ = h / √(2mkT)   (thermal/uncharged particles, e.g. neutrons)",
          expressionLatex: "\\lambda = \\dfrac{h}{\\sqrt{2mkT}}",
          label: "de Broglie wavelength of a thermal (uncharged) particle",
          derivedFrom: "Average kinetic energy from kinetic theory, (3/2)kT, used in place of qV for a neutral particle in thermal equilibrium",
          variables: [
            { symbol: "k", name: "Boltzmann constant", unit: "J/K", dimension: "[ML²T⁻²Θ⁻¹]" },
            { symbol: "T", name: "absolute temperature", unit: "K", dimension: "[Θ]" },
          ],
          conditions: ["Used for particles with no charge to accelerate electrostatically — thermal neutrons, gas molecules"],
          usedIn: ["kinetic-theory-of-gases"],
          conceptLink: {
            chapterSlug: "dual-nature-of-radiation-and-matter",
            sectionHeading: "17. de Broglie Wavelength of Charged and Thermal (Uncharged) Particles",
            concept: "de Broglie wavelength of a thermal particle",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "medium",
          examStats: { jeeMain: 5, jeeAdvanced: 4, neet: 5 },
          difficulty: "hard",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["de broglie wavelength thermal neutron", "h by root 2mkT"],
        },
        {
          id: "dn-bohr-quantisation-de-broglie",
          expression: "2πr = nλ",
          expressionLatex: "2\\pi r = n\\lambda",
          label: "de Broglie's explanation of Bohr's quantisation condition",
          derivedFrom: "An electron orbit is stable only if it forms a whole number of de Broglie wavelengths around the circumference — otherwise the wave destructively interferes with itself",
          variables: [
            { symbol: "r", name: "radius of the electron's orbit", unit: "m", dimension: "[L]" },
            { symbol: "n", name: "principal quantum number", unit: "dimensionless (integer)", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["This is the conceptual bridge connecting matter waves to Bohr's originally ad-hoc angular momentum quantisation rule"],
          usedIn: ["atoms"],
          conceptLink: {
            chapterSlug: "dual-nature-of-radiation-and-matter",
            sectionHeading: "19. Explanation of Bohr's Quantisation Condition",
            concept: "de Broglie explanation of Bohr quantisation",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 7, jeeAdvanced: 4, neet: 8, mhtCet: 5 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["bohr quantisation de broglie", "2 pi r equals n lambda"],
        },
        {
          id: "dn-compton-shift",
          expression: "Δλ = (h/m(e)c)(1 − cosθ)",
          expressionLatex: "\\Delta\\lambda = \\dfrac{h}{m_ec}(1-\\cos\\theta)",
          label: "Compton shift",
          derivedFrom: "Conservation of energy and momentum in a photon-electron collision, treating the photon as a particle with p=h/λ",
          variables: [
            { symbol: "Δλ", name: "increase in wavelength of the scattered photon", unit: "m", dimension: "[L]" },
            { symbol: "m(e)", name: "electron rest mass", unit: "kg", dimension: "[M]" },
            { symbol: "θ", name: "scattering angle of the photon", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["Direct experimental evidence for the particle nature of photons — only explainable by treating light as particles with momentum, not as a pure wave"],
          conceptLink: {
            chapterSlug: "dual-nature-of-radiation-and-matter",
            sectionHeading: "13. Compton Effect and Raman Effect",
            concept: "Compton shift",
          },
          examTags: ["jee-advanced", "neet"],
          frequency: "low",
          examStats: { jeeAdvanced: 2, neet: 3 },
          difficulty: "hard",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["compton shift formula", "h by mec 1 minus cos theta"],
        },
      ],
      examNotes:
        "The Davisson–Germer experiment (electron diffraction from a nickel crystal) is the direct experimental confirmation of de Broglie's hypothesis — boards frequently ask for its significance alongside the wavelength formulas.",
    },
  ],
};
