import type { ChapterFormulaSheet } from "./types";

export const electricChargesAndFieldsFormulaSheet: ChapterFormulaSheet = {
  chapterSlug: "electric-charges-and-fields",
  chapterName: "Electric Charges & Fields",
  className: "12",
  version: "1.0.0",
  lastUpdated: "2026-07-05",
  examCoverage: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
  quickRevisionIds: [
    "ecf-coulombs-law",
    "ecf-field-point-charge",
    "ecf-dipole-field-axial",
    "ecf-dipole-torque",
    "ecf-gauss-law",
    "ecf-field-sphere",
  ],
  topicGroups: [
    {
      id: "ecf-coulomb-field",
      title: "Coulomb's Law & Electric Field",
      intro:
        "Coulomb's law is the electrostatic twin of gravitation — inverse square, but with two signs and vastly stronger. Superpose forces or fields as vectors, always.",
      formulas: [
        {
          id: "ecf-coulombs-law",
          expression: "F = (1/4πε₀) q₁q₂/r² = k q₁q₂/r²",
          expressionLatex: "F = \\dfrac{1}{4\\pi\\varepsilon_0}\\dfrac{q_1q_2}{r^2}",
          label: "Coulomb's law",
          variables: [
            { symbol: "k", name: "Coulomb constant 1/4πε₀", unit: "N·m²/C²", dimension: "[ML³T⁻⁴A⁻²]", notes: "k = 9 × 10⁹ N·m²/C²" },
            { symbol: "ε₀", name: "permittivity of free space", unit: "C²/(N·m²)", dimension: "[M⁻¹L⁻³T⁴A²]", notes: "8.85 × 10⁻¹² C²/(N·m²)" },
            { symbol: "q₁, q₂", name: "the two point charges", unit: "C", dimension: "[AT]" },
            { symbol: "r", name: "separation between charges", unit: "m", dimension: "[L]" },
          ],
          conditions: [
            "Point charges (or spherical charges, centre-to-centre)",
            "In a medium of dielectric constant K, divide by K",
          ],
          commonMistakes: [
            "Coulomb force obeys superposition — the force between two charges is unaffected by a third; add the separate forces as vectors",
          ],
          usedIn: ["gravitation"],
          conceptLink: {
            chapterSlug: "electric-charges-and-fields",
            sectionHeading: "1. Coulomb's Law",
            concept: "Coulomb's law",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, neet: 13, mhtCet: 10 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["coulombs law", "k q1 q2 by r squared", "electrostatic force"],
        },
        {
          id: "ecf-field-point-charge",
          expression: "E = F/q₀ = (1/4πε₀) q/r²",
          expressionLatex: "E = \\dfrac{1}{4\\pi\\varepsilon_0}\\dfrac{q}{r^2}",
          label: "Electric field of a point charge",
          variables: [
            { symbol: "E", name: "electric field strength", unit: "N/C (= V/m)", dimension: "[MLT⁻³A⁻¹]" },
            { symbol: "q₀", name: "small positive test charge", unit: "C", dimension: "[AT]" },
            { symbol: "q", name: "source charge", unit: "C", dimension: "[AT]" },
          ],
          conditions: ["Field points AWAY from positive charge, TOWARD negative"],
          commonMistakes: [
            "E is defined in the LIMIT of a vanishing test charge, so the test charge does not disturb the source",
          ],
          conceptLink: {
            chapterSlug: "electric-charges-and-fields",
            sectionHeading: "2. Electric Field",
            concept: "electric field of a point charge",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 10, jeeAdvanced: 4, neet: 12, mhtCet: 9 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["electric field", "kq by r squared", "field point charge"],
        },
      ],
      importantObservations: [
        "Field lines start on positive, end on negative charge; they never cross, and their density shows field strength",
        "Electrostatic force is ~10³⁹ times stronger than gravity between two protons",
      ],
    },
    {
      id: "ecf-dipole",
      title: "Electric Dipole",
      intro:
        "A dipole is two equal and opposite charges a short distance apart. Its field falls as 1/r³ — faster than a point charge — and it feels torque in a uniform field.",
      formulas: [
        {
          id: "ecf-dipole-moment",
          expression: "p = q(2a),  directed from −q to +q",
          expressionLatex: "\\vec{p} = q(2a)",
          label: "Electric dipole moment",
          variables: [
            { symbol: "p", name: "dipole moment", unit: "C·m", dimension: "[ATL]" },
            { symbol: "2a", name: "separation between the charges", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Convention: points from negative to positive charge"],
          conceptLink: {
            chapterSlug: "electric-charges-and-fields",
            sectionHeading: "3. Electric Dipole",
            concept: "dipole moment",
          },
          examTags: ["neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { neet: 8, mhtCet: 6 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["dipole moment", "q times 2a"],
        },
        {
          id: "ecf-dipole-field-axial",
          expression: "E(axial) = (1/4πε₀) 2p/r³;   E(equatorial) = (1/4πε₀) p/r³",
          expressionLatex: "E_{axial} = \\dfrac{1}{4\\pi\\varepsilon_0}\\dfrac{2p}{r^3}",
          label: "Dipole field — axial and equatorial",
          derivedFrom: "Superposing the fields of +q and −q for r ≫ a",
          variables: [
            { symbol: "r", name: "distance from the dipole centre", unit: "m", dimension: "[L]" },
            { symbol: "p", name: "dipole moment", unit: "C·m", dimension: "[ATL]" },
          ],
          conditions: [
            "Short dipole approximation r ≫ a",
            "Axial field is TWICE the equatorial field at the same distance, and points along p; equatorial points opposite to p",
          ],
          commonMistakes: [
            "Dipole field falls as 1/r³, faster than a point charge's 1/r² — the two charges nearly cancel at large distance",
          ],
          conceptLink: {
            chapterSlug: "electric-charges-and-fields",
            sectionHeading: "3. Electric Dipole",
            concept: "field of a dipole",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 11, mhtCet: 8 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["dipole field", "axial equatorial", "2p by r cubed"],
        },
        {
          id: "ecf-dipole-torque",
          expression: "τ = pE sinθ;   U = −pE cosθ",
          expressionLatex: "\\vec{\\tau} = \\vec{p}\\times\\vec{E},\\quad U = -\\vec{p}\\cdot\\vec{E}",
          label: "Torque and energy of a dipole in a uniform field",
          variables: [
            { symbol: "θ", name: "angle between p and E", unit: "rad (or °)", dimension: "[M⁰L⁰T⁰]" },
            { symbol: "E", name: "external uniform field", unit: "N/C", dimension: "[MLT⁻³A⁻¹]" },
          ],
          conditions: [
            "Uniform field → net force zero, only torque",
            "Stable equilibrium at θ = 0 (p along E), unstable at θ = 180°",
          ],
          commonMistakes: [
            "In a NON-uniform field a dipole also feels a net FORCE, not just torque",
          ],
          usedIn: ["magnetism-and-matter", "system-of-particles-and-rotational-motion"],
          conceptLink: {
            chapterSlug: "electric-charges-and-fields",
            sectionHeading: "3. Electric Dipole",
            concept: "dipole in a uniform field",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 12, mhtCet: 9 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["dipole torque", "pE sin theta", "dipole potential energy"],
        },
      ],
      importantObservations: [
        "Work to rotate a dipole from θ₁ to θ₂: W = pE(cosθ₁ − cosθ₂); flipping from aligned to anti-aligned costs 2pE",
      ],
    },
    {
      id: "ecf-gauss",
      title: "Gauss's Law & Field of Symmetric Bodies",
      intro:
        "Gauss's law turns hard integrals into one-line answers whenever symmetry lets you choose the right closed surface.",
      formulas: [
        {
          id: "ecf-gauss-law",
          expression: "Φ = ∮ E·dA = q(enc)/ε₀",
          expressionLatex: "\\oint \\vec{E}\\cdot d\\vec{A} = \\dfrac{q_{enc}}{\\varepsilon_0}",
          label: "Gauss's law",
          variables: [
            { symbol: "Φ", name: "electric flux through the closed surface", unit: "N·m²/C (= V·m)", dimension: "[ML³T⁻³A⁻¹]" },
            { symbol: "q(enc)", name: "net charge enclosed", unit: "C", dimension: "[AT]" },
          ],
          conditions: [
            "Flux depends ONLY on enclosed charge — external charges contribute zero NET flux",
            "The field E in the integral is due to ALL charges, inside and out",
          ],
          commonMistakes: [
            "A charge at the centre of a cube gives flux q/ε₀ total, so q/6ε₀ through each face — but only by symmetry; a charge at a corner needs q/8 enclosed",
          ],
          usedIn: ["gravitation"],
          conceptLink: {
            chapterSlug: "electric-charges-and-fields",
            sectionHeading: "4. Gauss's Law",
            concept: "Gauss's law",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 10, jeeAdvanced: 6, neet: 12, mhtCet: 9 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["gauss law", "flux q by epsilon", "enclosed charge"],
        },
        {
          id: "ecf-field-sphere",
          expression: "Outside: E = kq/r²;   On surface: kq/R²;   Inside conductor: 0",
          expressionLatex: "E_{out} = \\dfrac{kq}{r^2},\\quad E_{in}^{cond} = 0",
          label: "Field of a charged sphere",
          derivedFrom: "Gauss's law with a concentric spherical surface",
          variables: [
            { symbol: "R", name: "radius of the sphere", unit: "m", dimension: "[L]" },
            { symbol: "r", name: "distance from centre", unit: "m", dimension: "[L]" },
          ],
          conditions: [
            "Outside: behaves as if all charge were at the centre",
            "Solid NON-conductor (uniform charge): inside E = kqr/R³ (grows linearly from centre)",
          ],
          commonMistakes: [
            "Conductor vs uniformly-charged insulator differ INSIDE: conductor has E = 0, insulator has E ∝ r",
          ],
          conceptLink: {
            chapterSlug: "electric-charges-and-fields",
            sectionHeading: "4. Gauss's Law",
            concept: "field of a charged sphere",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 5, neet: 9 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["field of sphere", "conductor inside zero", "gauss sphere"],
        },
        {
          id: "ecf-field-wire-sheet",
          expression: "Line: E = λ/(2πε₀r);   Sheet: E = σ/(2ε₀);   Conductor surface: σ/ε₀",
          expressionLatex: "E_{line} = \\dfrac{\\lambda}{2\\pi\\varepsilon_0 r},\\quad E_{sheet} = \\dfrac{\\sigma}{2\\varepsilon_0}",
          label: "Field of a line charge and a sheet",
          variables: [
            { symbol: "λ", name: "linear charge density", unit: "C/m", dimension: "[ATL⁻¹]" },
            { symbol: "σ", name: "surface charge density", unit: "C/m²", dimension: "[ATL⁻²]" },
          ],
          conditions: [
            "Infinite line: E ∝ 1/r; infinite sheet: E is UNIFORM (independent of distance)",
            "Field just outside a charged conductor is σ/ε₀, twice that of an isolated sheet",
          ],
          commonMistakes: [
            "Between two oppositely charged parallel sheets E = σ/ε₀; outside them the field is zero",
          ],
          conceptLink: {
            chapterSlug: "electric-charges-and-fields",
            sectionHeading: "4. Gauss's Law",
            concept: "field of line charge and sheet",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 4, neet: 10, mhtCet: 8 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["line charge field", "sheet field sigma by 2 epsilon", "infinite sheet"],
        },
      ],
      importantObservations: [
        "Flux through an open surface uses the same E·dA, but only a CLOSED surface gives q(enc)/ε₀",
      ],
      examNotes:
        "NEET asks flux-through-a-face and sphere-field-region questions; JEE Advanced hides Gauss inside cavity and superposition problems (charge in an off-centre cavity).",
    },
  ],
};
