import type { ChapterFormulaSheet } from "./types";

export const potentialCapacitanceFormulaSheet: ChapterFormulaSheet = {
  chapterSlug: "electrostatic-potential-and-capacitance",
  chapterName: "Electrostatic Potential & Capacitance",
  className: "12",
  version: "1.0.0",
  lastUpdated: "2026-07-05",
  examCoverage: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
  quickRevisionIds: [
    "epc-potential-point-charge",
    "epc-potential-energy-system",
    "epc-parallel-plate-cap",
    "epc-cap-combination",
    "epc-energy-stored",
    "epc-dielectric-effect",
  ],
  topicGroups: [
    {
      id: "epc-potential",
      title: "Electric Potential & Potential Energy",
      intro:
        "Potential is potential energy per unit charge, with zero at infinity. Unlike field, it is a scalar — add potentials with signs, no vectors.",
      formulas: [
        {
          id: "epc-potential-point-charge",
          expression: "V = (1/4πε₀) q/r",
          expressionLatex: "V = \\dfrac{1}{4\\pi\\varepsilon_0}\\dfrac{q}{r}",
          label: "Potential due to a point charge",
          variables: [
            { symbol: "V", name: "electric potential", unit: "V (= J/C)", dimension: "[ML²T⁻³A⁻¹]" },
            { symbol: "q", name: "source charge (with sign)", unit: "C", dimension: "[AT]" },
            { symbol: "r", name: "distance from the charge", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Scalar: total potential is the algebraic sum over all charges", "Zero reference at infinity"],
          commonMistakes: [
            "Potential can be zero where the FIELD is non-zero (midpoint of a dipole) and vice versa (inside a charged conductor)",
          ],
          usedIn: ["gravitation"],
          conceptLink: {
            chapterSlug: "electrostatic-potential-and-capacitance",
            sectionHeading: "1. Electric Potential",
            concept: "potential due to a point charge",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, neet: 13, mhtCet: 10 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["potential point charge", "kq by r", "scalar potential"],
        },
        {
          id: "epc-field-potential-relation",
          expression: "E = −dV/dr;   V(B) − V(A) = −∫ E·dl",
          expressionLatex: "E = -\\dfrac{dV}{dr}",
          label: "Field–potential relationship",
          variables: [
            { symbol: "E", name: "electric field", unit: "V/m", dimension: "[MLT⁻³A⁻¹]" },
            { symbol: "dV/dr", name: "potential gradient", unit: "V/m", dimension: "[MLT⁻³A⁻¹]" },
          ],
          conditions: ["Field points from HIGH to LOW potential — down the gradient", "Field is always perpendicular to equipotential surfaces"],
          commonMistakes: [
            "Uniform field between plates: V = Ed, so E = V/d — a much-used shortcut",
          ],
          usedIn: ["work-energy-and-power"],
          conceptLink: {
            chapterSlug: "electrostatic-potential-and-capacitance",
            sectionHeading: "1. Electric Potential",
            concept: "relation between field and potential",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 9, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["E minus dV dr", "field potential gradient", "equipotential"],
        },
        {
          id: "epc-potential-energy-system",
          expression: "U = (1/4πε₀) q₁q₂/r  (pair);  sum over all pairs for a system",
          expressionLatex: "U = \\dfrac{1}{4\\pi\\varepsilon_0}\\dfrac{q_1q_2}{r_{12}}",
          label: "Potential energy of a system of charges",
          variables: [
            { symbol: "U", name: "electrostatic potential energy", unit: "J", dimension: "[ML²T⁻²]" },
            { symbol: "r", name: "separation of a charge pair", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Add over every DISTINCT pair — three charges give three pairs", "Sign matters: unlike charges give negative U"],
          commonMistakes: [
            "Work done by an EXTERNAL agent to assemble the system equals U (with slow, kinetic-energy-free assembly)",
          ],
          usedIn: ["work-energy-and-power"],
          conceptLink: {
            chapterSlug: "electrostatic-potential-and-capacitance",
            sectionHeading: "2. Potential Energy",
            concept: "potential energy of a system of charges",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 5, neet: 11, mhtCet: 8 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["potential energy system", "sum over pairs", "assembly work"],
        },
      ],
      importantObservations: [
        "Every point of a conductor (surface and interior) is at the SAME potential — a conductor is an equipotential volume",
        "A charge moving along an equipotential surface requires zero work",
      ],
    },
    {
      id: "epc-capacitance",
      title: "Capacitance & Capacitor Combinations",
      intro:
        "A capacitor stores charge at a cost of potential; C = Q/V depends only on geometry and the dielectric. Series and parallel are the reverse of resistors.",
      formulas: [
        {
          id: "epc-parallel-plate-cap",
          expression: "C = ε₀A/d;   with dielectric C = Kε₀A/d",
          expressionLatex: "C = \\dfrac{\\varepsilon_0 A}{d}",
          label: "Parallel plate capacitance",
          variables: [
            { symbol: "C", name: "capacitance", unit: "F", dimension: "[M⁻¹L⁻²T⁴A²]" },
            { symbol: "A", name: "plate area", unit: "m²", dimension: "[L²]" },
            { symbol: "d", name: "plate separation", unit: "m", dimension: "[L]" },
            { symbol: "K", name: "dielectric constant of the medium", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["Depends only on geometry and dielectric, NOT on charge or voltage"],
          commonMistakes: [
            "Isolated sphere is also a capacitor: C = 4πε₀R",
          ],
          conceptLink: {
            chapterSlug: "electrostatic-potential-and-capacitance",
            sectionHeading: "3. Capacitance",
            concept: "parallel plate capacitor",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 10, neet: 13, mhtCet: 10 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["parallel plate", "epsilon A by d", "capacitance"],
        },
        {
          id: "epc-cap-combination",
          expression: "Series: 1/C(eq) = Σ 1/Cᵢ;   Parallel: C(eq) = Σ Cᵢ",
          expressionLatex: "\\dfrac{1}{C_{series}} = \\sum\\dfrac{1}{C_i},\\quad C_{parallel} = \\sum C_i",
          label: "Capacitors in series and parallel",
          variables: [
            { symbol: "C(eq)", name: "equivalent capacitance", unit: "F", dimension: "[M⁻¹L⁻²T⁴A²]" },
          ],
          conditions: [
            "OPPOSITE of resistors: capacitors ADD in parallel, combine reciprocally in series",
            "Series: every capacitor holds the SAME charge; Parallel: same VOLTAGE",
          ],
          commonMistakes: [
            "In series the smallest capacitor dominates C(eq) and takes the largest share of voltage",
          ],
          usedIn: ["current-electricity"],
          conceptLink: {
            chapterSlug: "electrostatic-potential-and-capacitance",
            sectionHeading: "4. Combination of Capacitors",
            concept: "capacitors in series and parallel",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 5, neet: 11, mhtCet: 9 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["capacitors series parallel", "equivalent capacitance"],
        },
        {
          id: "epc-dielectric-effect",
          expression: "With battery connected: Q → KQ, V same;  Disconnected: V → V/K, Q same",
          expressionLatex: "C \\to KC",
          label: "Effect of inserting a dielectric",
          variables: [
            { symbol: "K", name: "dielectric constant", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: [
            "Capacitance always increases by K",
            "Battery CONNECTED (V fixed): charge and energy rise; DISCONNECTED (Q fixed): voltage, field and energy fall",
          ],
          commonMistakes: [
            "Track WHICH quantity is held constant — the whole answer flips depending on whether the battery stays connected",
          ],
          conceptLink: {
            chapterSlug: "electrostatic-potential-and-capacitance",
            sectionHeading: "5. Dielectrics",
            concept: "dielectric in a capacitor",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 5, neet: 10, mhtCet: 8 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["dielectric inserted", "battery connected disconnected", "K times C"],
        },
      ],
      importantObservations: [
        "A dielectric slab of thickness t in a gap d: C = ε₀A/(d − t + t/K) — reduces the effective gap",
      ],
    },
    {
      id: "epc-energy",
      title: "Energy Stored in a Capacitor",
      intro:
        "Charging a capacitor stores energy in the field between the plates — half of what the battery supplies; the other half is lost as heat.",
      formulas: [
        {
          id: "epc-energy-stored",
          expression: "U = ½ CV² = ½ QV = Q²/2C",
          expressionLatex: "U = \\tfrac{1}{2}CV^2 = \\tfrac{Q^2}{2C}",
          label: "Energy stored in a capacitor",
          derivedFrom: "Integrating dW = (q/C)dq as charge builds from 0 to Q",
          derivation: {
            startsFrom: "Work to add charge dq when the capacitor already holds q",
            steps: [
              { statement: "Elementary work", expression: "dW = V dq = (q/C) dq" },
              { statement: "Integrate from 0 to Q", expression: "U = ∫₀^Q (q/C) dq = Q²/2C" },
              { statement: "Rewrite using Q = CV", expression: "U = ½CV²" },
            ],
            askedInBoards: true,
          },
          variables: [
            { symbol: "U", name: "energy stored", unit: "J", dimension: "[ML²T⁻²]" },
            { symbol: "Q", name: "charge", unit: "C", dimension: "[AT]" },
            { symbol: "V", name: "voltage across the capacitor", unit: "V", dimension: "[ML²T⁻³A⁻¹]" },
          ],
          conditions: ["Energy density in the field: u = ½ε₀E²"],
          commonMistakes: [
            "The battery supplies QV; only ½QV is stored, the other ½QV is dissipated as heat while charging — independent of the resistance",
          ],
          usedIn: ["work-energy-and-power", "alternating-current"],
          conceptLink: {
            chapterSlug: "electrostatic-potential-and-capacitance",
            sectionHeading: "6. Energy of a Capacitor",
            concept: "energy stored in a capacitor",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 10, jeeAdvanced: 5, neet: 12, mhtCet: 9 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["half CV squared", "energy capacitor", "energy density field"],
        },
        {
          id: "epc-common-potential",
          expression: "V = (C₁V₁ + C₂V₂)/(C₁ + C₂);   heat lost = ½ C₁C₂(V₁ − V₂)²/(C₁ + C₂)",
          expressionLatex: "V = \\dfrac{C_1V_1 + C_2V_2}{C_1 + C_2}",
          label: "Sharing charge between two capacitors",
          derivedFrom: "Charge conservation on connecting the plates",
          variables: [
            { symbol: "V", name: "common potential after connection", unit: "V", dimension: "[ML²T⁻³A⁻¹]" },
          ],
          conditions: ["Energy is ALWAYS lost (as heat/radiation) when two capacitors at different potentials are joined"],
          commonMistakes: [
            "The energy-loss formula mirrors the inelastic-collision energy loss — same reduced-quantity structure",
          ],
          usedIn: ["centre-of-mass-and-collisions"],
          conceptLink: {
            chapterSlug: "electrostatic-potential-and-capacitance",
            sectionHeading: "6. Energy of a Capacitor",
            concept: "common potential and energy loss",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "high",
          examStats: { jeeMain: 7, jeeAdvanced: 4, neet: 7 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["common potential", "charge sharing", "energy loss capacitors"],
        },
      ],
      importantObservations: [
        "Force between capacitor plates F = Q²/2ε₀A = ½ε₀E²A — always attractive",
      ],
      examNotes:
        "NEET focuses on C combinations, dielectric shifts and energy; JEE Advanced adds partial dielectrics, force on plates, and multi-capacitor charge-sharing networks.",
    },
  ],
};
