import type { ChapterFormulaSheet } from "./types";

export const electromagneticInductionFormulaSheet: ChapterFormulaSheet = {
  chapterSlug: "electromagnetic-induction",
  chapterName: "Electromagnetic Induction",
  className: "12",
  version: "1.0.0",
  lastUpdated: "2026-07-09",
  examCoverage: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
  quickRevisionIds: [
    "emi-faradays-law",
    "emi-motional-emf",
    "emi-self-inductance-solenoid",
    "emi-mutual-inductance-solenoids",
    "emi-energy-stored-inductor",
    "emi-ac-generator-emf",
  ],
  topicGroups: [
    {
      id: "emi-flux-and-faraday",
      title: "Magnetic Flux, Faraday's Law & Lenz's Law",
      intro:
        "A changing magnetic flux through a loop induces an EMF — the size of that EMF depends only on how fast the flux changes, not on the flux itself.",
      formulas: [
        {
          id: "emi-magnetic-flux",
          expression: "Φ = B·A = BA cosθ",
          expressionLatex: "\\Phi = \\vec{B}\\cdot\\vec{A} = BA\\cos\\theta",
          label: "Magnetic flux through a surface",
          variables: [
            { symbol: "Φ", name: "magnetic flux", unit: "Wb (weber)", dimension: "[ML²T⁻²A⁻¹]" },
            { symbol: "B", name: "magnetic field", unit: "T", dimension: "[MT⁻²A⁻¹]" },
            { symbol: "A", name: "area of the surface", unit: "m²", dimension: "[L²]" },
            { symbol: "θ", name: "angle between B and the area normal", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["Flux is maximum when B is perpendicular to the loop's plane (θ = 0°), zero when B lies in the plane (θ = 90°)"],
          conceptLink: {
            chapterSlug: "electromagnetic-induction",
            sectionHeading: "1. Magnetic Flux",
            concept: "magnetic flux",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 10, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["magnetic flux formula", "BA cos theta"],
        },
        {
          id: "emi-faradays-law",
          expression: "ε = −N (dΦ/dt)",
          expressionLatex: "\\varepsilon = -N\\dfrac{d\\Phi}{dt}",
          label: "Faraday's law of electromagnetic induction",
          derivedFrom: "The negative sign is Lenz's law built in — the induced EMF always opposes the change producing it",
          variables: [
            { symbol: "ε", name: "induced EMF", unit: "V", dimension: "[ML²T⁻³A⁻¹]" },
            { symbol: "N", name: "number of turns in the coil", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["EMF depends only on the RATE of change of flux, not the flux's absolute value — a large steady flux induces zero EMF"],
          commonMistakes: [
            "The negative sign isn't optional decoration — it encodes energy conservation (Lenz's law); dropping it in a problem with a specified current direction gives the wrong direction",
          ],
          conceptLink: {
            chapterSlug: "electromagnetic-induction",
            sectionHeading: "2. Faraday's Laws of Electromagnetic Induction",
            concept: "Faraday's law",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 10, jeeAdvanced: 5, neet: 13, mhtCet: 8 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["faradays law", "epsilon minus N dphi dt", "law of electromagnetic induction"],
        },
      ],
      importantObservations: [
        "Lenz's law is a statement of energy conservation: the induced current always flows in the direction that opposes the change causing it — you never get induction 'for free'",
        "Eddy currents are induced currents in bulk conductors (not just loops); they cause electromagnetic damping, used deliberately in induction furnaces and speedometers, and avoided by laminating transformer cores",
      ],
    },
    {
      id: "emi-motional-emf",
      title: "Motional EMF",
      intro:
        "A conductor moving through a magnetic field is a special case of Faraday's law — the Lorentz force on free charges inside the moving conductor does the work of separating charge.",
      formulas: [
        {
          id: "emi-motional-emf",
          expression: "ε = Bvl",
          expressionLatex: "\\varepsilon = Bvl",
          label: "Motional EMF — rod moving perpendicular to B and its length",
          derivedFrom: "Force per unit charge on free electrons in the rod is qv×B; integrating along the rod's length gives ε = Bvl",
          variables: [
            { symbol: "v", name: "speed of the rod, perpendicular to both B and the rod", unit: "m/s", dimension: "[LT⁻¹]" },
            { symbol: "l", name: "length of the rod", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Requires v, B, and l all mutually perpendicular for this simple scalar form"],
          usedIn: ["moving-charges-and-magnetism"],
          conceptLink: {
            chapterSlug: "electromagnetic-induction",
            sectionHeading: "4. Motional EMF — the Rod on Rails",
            concept: "motional EMF",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 4, neet: 11, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["motional emf formula", "Bvl rod magnetic field"],
        },
        {
          id: "emi-motional-emf-rotating-rod",
          expression: "ε = ½ B ω l²",
          expressionLatex: "\\varepsilon = \\dfrac{1}{2}B\\omega l^2",
          label: "Motional EMF of a rod rotating about one end",
          derivedFrom: "Integrating ε = ∫Bωr dr from 0 to l, since each element's speed is ωr",
          variables: [
            { symbol: "ω", name: "angular speed of rotation", unit: "rad/s", dimension: "[T⁻¹]" },
          ],
          conditions: ["The rod rotates in a plane perpendicular to B, about an axis through one end"],
          commonMistakes: [
            "Every point on the rod moves at a different speed (ωr), so you cannot use ε = Bvl with a single v — integration is essential here",
          ],
          conceptLink: {
            chapterSlug: "electromagnetic-induction",
            sectionHeading: "6. EMF Induced in a Rotating Rod",
            concept: "EMF of a rotating rod",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "medium",
          examStats: { jeeMain: 5, jeeAdvanced: 4, neet: 5 },
          difficulty: "hard",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["rotating rod motional emf", "half B omega l squared"],
        },
        {
          id: "emi-ac-generator-emf",
          expression: "ε = ε₀ sin(ωt) ,  ε₀ = NBAω",
          expressionLatex: "\\varepsilon = NBA\\omega\\sin(\\omega t)",
          label: "EMF generated by a rotating coil (AC generator)",
          derivedFrom: "Φ = BA cos(ωt) for a coil rotating at constant ω; ε = −N dΦ/dt gives the sinusoidal EMF",
          variables: [
            { symbol: "ε₀", name: "peak (maximum) EMF", unit: "V", dimension: "[ML²T⁻³A⁻¹]" },
          ],
          conditions: ["ω here is the coil's mechanical rotation speed, which becomes the EMF's angular frequency"],
          usedIn: ["alternating-current"],
          conceptLink: {
            chapterSlug: "electromagnetic-induction",
            sectionHeading: "17. AC Generator — Principle, Construction and Working",
            concept: "AC generator EMF",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 10, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["ac generator emf", "NBA omega sin omega t"],
        },
      ],
    },
    {
      id: "emi-inductance",
      title: "Self-Inductance & Mutual Inductance",
      intro:
        "Inductance measures a circuit's opposition to a CHANGING current — it plays the same conceptual role for current change that capacitance plays for charge storage.",
      formulas: [
        {
          id: "emi-self-inductance-def",
          expression: "Φ = LI ,  ε = −L (dI/dt)",
          expressionLatex: "\\varepsilon = -L\\dfrac{dI}{dt}",
          label: "Self-inductance — definition",
          variables: [
            { symbol: "L", name: "self-inductance of the coil", unit: "H (henry)", dimension: "[ML²T⁻²A⁻²]" },
          ],
          conditions: ["Self-induced EMF always opposes the change in the coil's own current — this is what makes an inductor resist sudden current changes"],
          conceptLink: {
            chapterSlug: "electromagnetic-induction",
            sectionHeading: "8. Self-Inductance",
            concept: "self-inductance",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 10, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["self inductance definition", "epsilon minus L dI dt"],
        },
        {
          id: "emi-self-inductance-solenoid",
          expression: "L = μ₀ n² A l = μ₀N²A/l",
          expressionLatex: "L = \\mu_0 n^2 A l = \\dfrac{\\mu_0 N^2 A}{l}",
          label: "Self-inductance of a long solenoid",
          derivedFrom: "Φ = B(nl·A) with B = μ₀nI inside the solenoid, then L = Φ/I = μ₀n²Al",
          variables: [
            { symbol: "n", name: "turns per unit length", unit: "turns/m", dimension: "[L⁻¹]" },
            { symbol: "l", name: "length of the solenoid", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Valid for a long, tightly wound solenoid, same approximation used for its magnetic field formula"],
          usedIn: ["moving-charges-and-magnetism"],
          conceptLink: {
            chapterSlug: "electromagnetic-induction",
            sectionHeading: "9. Self-Inductance of a Long Solenoid",
            concept: "self-inductance of a solenoid",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 10, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["self inductance solenoid", "mu0 n squared A l"],
        },
        {
          id: "emi-mutual-inductance-def",
          expression: "Φ₂ = MI₁ ,  ε₂ = −M (dI₁/dt)",
          expressionLatex: "\\varepsilon_2 = -M\\dfrac{dI_1}{dt}",
          label: "Mutual inductance — definition",
          variables: [
            { symbol: "M", name: "mutual inductance between the two coils", unit: "H", dimension: "[ML²T⁻²A⁻²]" },
          ],
          conditions: ["M is the SAME in both directions (M₁₂ = M₂₁) — a symmetric property of the pair of coils, regardless of which one is driven"],
          conceptLink: {
            chapterSlug: "electromagnetic-induction",
            sectionHeading: "10. Mutual Inductance",
            concept: "mutual inductance",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 6, neet: 8, mhtCet: 5 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["mutual inductance definition", "M12 equals M21"],
        },
        {
          id: "emi-mutual-inductance-solenoids",
          expression: "M = μ₀N₁N₂A / l",
          expressionLatex: "M = \\dfrac{\\mu_0 N_1 N_2 A}{l}",
          label: "Mutual inductance of two coaxial solenoids",
          variables: [
            { symbol: "N₁, N₂", name: "total turns of the two coils", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["Assumes the shorter coil is wound entirely inside/around the longer one, sharing the same cross-sectional area A"],
          conceptLink: {
            chapterSlug: "electromagnetic-induction",
            sectionHeading: "11. Mutual Inductance of Two Coaxial Solenoids",
            concept: "mutual inductance of coaxial solenoids",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 3, neet: 6 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["mutual inductance solenoids", "mu0 N1 N2 A by l"],
        },
        {
          id: "emi-energy-stored-inductor",
          expression: "U = ½ L I²",
          expressionLatex: "U = \\dfrac{1}{2}LI^2",
          label: "Energy stored in an inductor carrying current",
          derivedFrom: "U = ∫₀^I L I' dI', the work done building up the current against the self-induced back-EMF",
          variables: [
            { symbol: "U", name: "energy stored in the magnetic field", unit: "J", dimension: "[ML²T⁻²]" },
          ],
          conditions: ["Structurally identical to ½CV² for a capacitor — inductors store energy in their magnetic field the way capacitors store it in their electric field"],
          usedIn: ["electrostatic-potential-and-capacitance"],
          conceptLink: {
            chapterSlug: "electromagnetic-induction",
            sectionHeading: "13. Energy Stored in an Inductor",
            concept: "energy stored in an inductor",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 10, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["energy stored inductor", "half L I squared"],
        },
        {
          id: "emi-energy-density-magnetic-field",
          expression: "u = B² / (2μ₀)",
          expressionLatex: "u = \\dfrac{B^2}{2\\mu_0}",
          label: "Energy density of a magnetic field",
          derivedFrom: "U/(volume of solenoid) using U = ½LI² and L, B for a solenoid",
          variables: [
            { symbol: "u", name: "energy per unit volume", unit: "J/m³", dimension: "[ML⁻¹T⁻²]" },
          ],
          conditions: ["Parallel structure to u = ½ε₀E² for the electric field — both fields store energy proportional to the square of their strength"],
          usedIn: ["electrostatic-potential-and-capacitance"],
          conceptLink: {
            chapterSlug: "electromagnetic-induction",
            sectionHeading: "14. Energy Density of the Magnetic Field",
            concept: "energy density of the magnetic field",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 3, neet: 7 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["energy density magnetic field", "B squared by 2 mu0"],
        },
      ],
    },
    {
      id: "emi-lr-circuits",
      title: "Growth and Decay of Current in LR Circuits",
      intro:
        "An inductor resists sudden current changes — connecting or disconnecting an LR circuit produces the same exponential growth/decay shape seen in RC circuits, but for current instead of charge.",
      formulas: [
        {
          id: "emi-lr-time-constant",
          expression: "τ = L / R",
          expressionLatex: "\\tau = \\dfrac{L}{R}",
          label: "Time constant of an LR circuit",
          variables: [
            { symbol: "τ", name: "time constant", unit: "s", dimension: "[T]" },
            { symbol: "R", name: "resistance in the circuit", unit: "Ω", dimension: "[ML²T⁻³A⁻²]" },
          ],
          conditions: ["Larger L or smaller R means the current takes longer to reach its steady value"],
          usedIn: ["current-electricity"],
          conceptLink: {
            chapterSlug: "electromagnetic-induction",
            sectionHeading: "15. Growth of Current in an LR Circuit",
            concept: "LR circuit time constant",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 3, neet: 6 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["LR circuit time constant", "tau equals L by R"],
        },
        {
          id: "emi-lr-growth",
          expression: "I(t) = I₀ (1 − e^(−t/τ))",
          expressionLatex: "I(t) = I_0\\left(1-e^{-t/\\tau}\\right)",
          label: "Growth of current in an LR circuit",
          derivedFrom: "Kirchhoff's voltage law: ε = IR + L(dI/dt), solved as a first-order ODE",
          variables: [
            { symbol: "I₀", name: "final steady-state current = ε/R", unit: "A", dimension: "[A]" },
          ],
          conditions: ["Current approaches I₀ asymptotically, never reaching it in finite time, exactly like RC charging"],
          conceptLink: {
            chapterSlug: "electromagnetic-induction",
            sectionHeading: "15. Growth of Current in an LR Circuit",
            concept: "growth of current in an LR circuit",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 4, neet: 6 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["LR circuit current growth", "I0 1 minus e power minus t by tau"],
        },
        {
          id: "emi-lr-decay",
          expression: "I(t) = I₀ e^(−t/τ)",
          expressionLatex: "I(t) = I_0 e^{-t/\\tau}",
          label: "Decay of current in an LR circuit",
          derivedFrom: "Kirchhoff's voltage law with no source: L(dI/dt) + IR = 0",
          variables: [],
          conditions: ["At t = τ, current falls to 36.8% of its initial value — same shape as RC discharge"],
          conceptLink: {
            chapterSlug: "electromagnetic-induction",
            sectionHeading: "16. Decay of Current in an LR Circuit",
            concept: "decay of current in an LR circuit",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 4, neet: 6 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["LR circuit current decay", "I0 e power minus t by tau"],
        },
      ],
      examNotes:
        "Boards commonly ask to sketch and compare LR growth/decay against RC charging/discharging — the mathematical shape is identical, only the physical quantity (current vs. charge) differs.",
    },
  ],
};
