import type { ChapterFormulaSheet } from "./types";

export const electromagneticWavesFormulaSheet: ChapterFormulaSheet = {
  chapterSlug: "electromagnetic-waves",
  chapterName: "Electromagnetic Waves",
  className: "12",
  version: "1.0.0",
  lastUpdated: "2026-07-09",
  examCoverage: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
  quickRevisionIds: [
    "emw-displacement-current",
    "emw-speed-light-vacuum",
    "emw-relation-e0-b0",
    "emw-poynting-vector",
    "emw-radiation-pressure",
  ],
  topicGroups: [
    {
      id: "emw-maxwell-displacement-current",
      title: "Displacement Current & Maxwell's Equations",
      intro:
        "Maxwell noticed Ampère's law was incomplete for circuits with a charging capacitor — displacement current patches this gap and, in doing so, predicts that light itself is an electromagnetic wave.",
      formulas: [
        {
          id: "emw-displacement-current",
          expression: "I(d) = ε₀ (dΦ(E)/dt)",
          expressionLatex: "I_d = \\varepsilon_0\\dfrac{d\\Phi_E}{dt}",
          label: "Displacement current",
          derivedFrom: "Maxwell's fix for Ampère's law inside a charging capacitor's gap, where no conduction current flows but the electric field is still changing",
          variables: [
            { symbol: "I(d)", name: "displacement current", unit: "A", dimension: "[A]" },
            { symbol: "Φ(E)", name: "electric flux through the surface", unit: "V·m", dimension: "[ML³T⁻³A⁻¹]" },
          ],
          conditions: ["Numerically equal to the conduction current charging the capacitor, ensuring current is continuous everywhere in the circuit"],
          commonMistakes: [
            "Displacement current is NOT a flow of charge — it's a changing electric field that acts exactly like a current for the purpose of producing a magnetic field",
          ],
          conceptLink: {
            chapterSlug: "electromagnetic-waves",
            sectionHeading: "2. The Need for Displacement Current",
            concept: "displacement current",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 10, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["displacement current formula", "epsilon0 dphiE dt"],
        },
        {
          id: "emw-ampere-maxwell-law",
          expression: "∮B·dl = μ₀(I + I(d))",
          expressionLatex: "\\oint\\vec{B}\\cdot d\\vec{l} = \\mu_0(I+I_d)",
          label: "Ampère–Maxwell law",
          derivedFrom: "Ampère's circuital law generalised to include displacement current, making it consistent for ALL surfaces bounded by a loop, not just some",
          variables: [
            { symbol: "I", name: "conduction current enclosed", unit: "A", dimension: "[A]" },
          ],
          conditions: ["This is the corrected, fully general form of Ampère's law used throughout electrodynamics"],
          usedIn: ["moving-charges-and-magnetism"],
          conceptLink: {
            chapterSlug: "electromagnetic-waves",
            sectionHeading: "3. Maxwell's Four Equations",
            concept: "Ampère-Maxwell law",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 4, neet: 6 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["ampere maxwell law", "mu0 I plus Id"],
        },
      ],
      importantObservations: [
        "Maxwell's four equations (Gauss's law for E, Gauss's law for B, Faraday's law, Ampère-Maxwell law) together predict electromagnetic waves travelling at exactly the speed of light — this was the first evidence that light IS an electromagnetic phenomenon",
      ],
    },
    {
      id: "emw-wave-properties",
      title: "Speed, Fields and the Wave Equation",
      intro:
        "An electromagnetic wave is a self-sustaining oscillation of E and B fields, each perpendicular to the other and to the direction of propagation, travelling at a speed set entirely by the medium's electric and magnetic properties.",
      formulas: [
        {
          id: "emw-speed-light-vacuum",
          expression: "c = 1/√(μ₀ε₀)",
          expressionLatex: "c = \\dfrac{1}{\\sqrt{\\mu_0\\varepsilon_0}}",
          label: "Speed of light in vacuum",
          derivedFrom: "Falls directly out of combining Maxwell's equations into a wave equation for E and B",
          variables: [
            { symbol: "c", name: "speed of light in vacuum", unit: "m/s", dimension: "[LT⁻¹]", notes: "c ≈ 3 × 10⁸ m/s" },
          ],
          conditions: ["This single formula was historic evidence that light is an electromagnetic wave — μ₀ and ε₀ were measured independently from purely electric/magnetic experiments, yet their combination gives exactly the known speed of light"],
          conceptLink: {
            chapterSlug: "electromagnetic-waves",
            sectionHeading: "5. General Properties of Electromagnetic Waves",
            concept: "speed of light from Maxwell's equations",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 10, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["speed of light formula", "c equals 1 by root mu0 epsilon0"],
        },
        {
          id: "emw-speed-in-medium",
          expression: "v = c/n = 1/√(μ ε)",
          expressionLatex: "v = \\dfrac{c}{n}",
          label: "Speed of an electromagnetic wave in a medium",
          variables: [
            { symbol: "n", name: "refractive index of the medium", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["Speed is always ≤ c in any real medium (n ≥ 1)"],
          usedIn: ["ray-optics-and-optical-instruments"],
          conceptLink: {
            chapterSlug: "electromagnetic-waves",
            sectionHeading: "5. General Properties of Electromagnetic Waves",
            concept: "speed in a medium",
          },
          examTags: ["jee-main", "neet", "mht-cet"],
          frequency: "high",
          examStats: { jeeMain: 6, neet: 8, mhtCet: 5 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["speed of light in medium", "v equals c by n"],
        },
        {
          id: "emw-relation-e0-b0",
          expression: "E₀/B₀ = c",
          expressionLatex: "\\dfrac{E_0}{B_0} = c",
          label: "Relation between the E and B field amplitudes",
          derivedFrom: "Follows directly from Maxwell's equations applied to a plane electromagnetic wave",
          variables: [
            { symbol: "E₀, B₀", name: "peak amplitudes of the electric and magnetic fields", unit: "V/m, T", dimension: "[MLT⁻³A⁻¹], [MT⁻²A⁻¹]" },
          ],
          conditions: ["E and B oscillate IN PHASE with each other — both are zero together and peak together, only their ratio is fixed by c"],
          commonMistakes: [
            "E and B are NOT equal in magnitude — their ratio equals c (a huge number), so E₀ is numerically much larger than B₀ in SI units",
          ],
          conceptLink: {
            chapterSlug: "electromagnetic-waves",
            sectionHeading: "6. Transverse Nature of Electromagnetic Waves",
            concept: "relation between E and B amplitudes",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 4, neet: 7, mhtCet: 5 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["E0 by B0 equals c", "electric magnetic field amplitude ratio"],
        },
        {
          id: "emw-wavelength-frequency-relation",
          expression: "c = νλ",
          expressionLatex: "c = \\nu\\lambda",
          label: "Wave equation for electromagnetic waves",
          variables: [
            { symbol: "ν", name: "frequency", unit: "Hz", dimension: "[T⁻¹]" },
            { symbol: "λ", name: "wavelength", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Frequency stays fixed by the source when a wave crosses into a new medium; wavelength and speed both change together"],
          usedIn: ["waves", "ray-optics-and-optical-instruments"],
          conceptLink: {
            chapterSlug: "electromagnetic-waves",
            sectionHeading: "10. Overview of the Electromagnetic Spectrum",
            concept: "wave equation",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 7, neet: 9, mhtCet: 6 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["c equals nu lambda", "wave equation electromagnetic"],
        },
      ],
    },
    {
      id: "emw-energy-pressure",
      title: "Energy, Intensity & Radiation Pressure",
      intro:
        "An electromagnetic wave carries real energy and momentum — it can exert measurable pressure on a surface it strikes, doubling if the surface reflects rather than absorbs.",
      formulas: [
        {
          id: "emw-poynting-vector",
          expression: "S = (1/μ₀)(E × B) ,  I(avg) = ½ cε₀E₀²",
          expressionLatex: "I_{avg} = \\dfrac{1}{2}c\\varepsilon_0 E_0^2",
          label: "Poynting vector and average intensity",
          derivedFrom: "The Poynting vector gives the instantaneous energy flux; averaging its magnitude over one cycle for a sinusoidal wave gives the intensity",
          variables: [
            { symbol: "S", name: "Poynting vector — power per unit area, direction of energy flow", unit: "W/m²", dimension: "[MT⁻³]" },
            { symbol: "I(avg)", name: "average intensity of the wave", unit: "W/m²", dimension: "[MT⁻³]" },
          ],
          conditions: ["S points in the direction of wave propagation, along E × B"],
          conceptLink: {
            chapterSlug: "electromagnetic-waves",
            sectionHeading: "7. Energy Carried by Electromagnetic Waves — the Poynting Vector",
            concept: "Poynting vector and intensity",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 4, neet: 6 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["poynting vector formula", "average intensity em wave"],
        },
        {
          id: "emw-energy-density-em-wave",
          expression: "u(avg) = ε₀E(rms)²  = ½ε₀E₀²",
          expressionLatex: "u_{avg} = \\dfrac{1}{2}\\varepsilon_0 E_0^2",
          label: "Average energy density of an electromagnetic wave",
          derivedFrom: "Electric and magnetic fields each contribute equally to the total energy density; the electric contribution alone equals half the total when doubled appropriately",
          variables: [
            { symbol: "u(avg)", name: "average total energy density (electric + magnetic)", unit: "J/m³", dimension: "[ML⁻¹T⁻²]" },
          ],
          conditions: ["Electric and magnetic energy densities are exactly EQUAL at every instant in an EM wave — neither dominates"],
          usedIn: ["electrostatic-potential-and-capacitance", "moving-charges-and-magnetism"],
          conceptLink: {
            chapterSlug: "electromagnetic-waves",
            sectionHeading: "8. Energy Density of Electromagnetic Waves",
            concept: "energy density of EM waves",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "medium",
          examStats: { jeeMain: 5, jeeAdvanced: 3, neet: 5 },
          difficulty: "hard",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["energy density electromagnetic wave", "u avg half epsilon0 E0 squared"],
        },
        {
          id: "emw-radiation-pressure",
          expression: "P = I/c   (fully absorbed) ;  P = 2I/c   (fully reflected)",
          expressionLatex: "P_{absorbed} = \\dfrac{I}{c},\\quad P_{reflected} = \\dfrac{2I}{c}",
          label: "Radiation pressure",
          derivedFrom: "Momentum carried by the EM wave (p = E/c) transferred to the surface; a reflecting surface reverses the wave's momentum, delivering twice the impulse",
          variables: [
            { symbol: "P", name: "radiation pressure", unit: "Pa (N/m²)", dimension: "[ML⁻¹T⁻²]" },
            { symbol: "I", name: "intensity of the incident radiation", unit: "W/m²", dimension: "[MT⁻³]" },
          ],
          conditions: ["Doubling for a perfect reflector mirrors the same logic as an elastic vs. inelastic collision transferring momentum"],
          usedIn: ["dual-nature-of-radiation-and-matter"],
          conceptLink: {
            chapterSlug: "electromagnetic-waves",
            sectionHeading: "9. Radiation Pressure",
            concept: "radiation pressure",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "medium",
          examStats: { jeeMain: 5, jeeAdvanced: 3, neet: 5 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["radiation pressure formula", "I by c radiation pressure"],
        },
      ],
      examNotes:
        "NEET and JEE Main both test the electromagnetic spectrum's ORDER of increasing/decreasing wavelength (radio → microwave → IR → visible → UV → X-ray → gamma) as pure recall — memorise this sequence alongside the formulas above.",
    },
  ],
};
