import type { ChapterFormulaSheet } from "./types";

export const electricChargesAndFieldsFormulaSheet: ChapterFormulaSheet = {
  chapterSlug: "electric-charges-and-fields",
  chapterName: "Electric Charges & Fields",
  className: "12",
  version: "1.0.0",
  lastUpdated: "2026-07-08",
  examCoverage: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
  quickRevisionIds: [
    "ecf-coulombs-law",
    "ecf-electric-field-point-charge",
    "ecf-dipole-field-axial",
    "ecf-dipole-torque",
    "ecf-gauss-law",
    "ecf-field-infinite-sheet",
    "ecf-field-conducting-sphere",
  ],
  topicGroups: [
    {
      id: "ecf-coulomb-and-field",
      title: "Coulomb's Law & Electric Field",
      intro:
        "Coulomb's law gives the force between two point charges; dividing by a test charge turns that force into a field — a property of space itself.",
      formulas: [
        {
          id: "ecf-coulombs-law",
          expression: "F = k q₁q₂ / r² ,  k = 1/4πε₀ ≈ 9 × 10⁹ N·m²/C²",
          expressionLatex: "F = \\dfrac{1}{4\\pi\\varepsilon_0}\\dfrac{q_1q_2}{r^2}",
          label: "Coulomb's law (vacuum/air)",
          variables: [
            { symbol: "k", name: "Coulomb constant", unit: "N·m²/C²", dimension: "[ML³T⁻⁴A⁻²]", notes: "k = 1/4πε₀ ≈ 9 × 10⁹ N·m²/C²" },
            { symbol: "q₁, q₂", name: "point charges", unit: "C", dimension: "[AT]" },
            { symbol: "r", name: "separation between charges", unit: "m", dimension: "[L]" },
            { symbol: "ε₀", name: "permittivity of free space", unit: "C²/N·m²", dimension: "[M⁻¹L⁻³T⁴A²]", notes: "ε₀ = 8.85 × 10⁻¹² C²/N·m²" },
          ],
          conditions: ["Point charges, or charge distributions with spherical symmetry measured centre-to-centre", "In a medium of dielectric constant K, F becomes F/K"],
          commonMistakes: [
            "Force is attractive for unlike charges, repulsive for like charges — the sign of q₁q₂ alone does not give direction; treat direction along the line joining the charges separately",
          ],
          conceptLink: {
            chapterSlug: "electric-charges-and-fields",
            sectionHeading: "4. Coulomb's Law",
            concept: "Coulomb's law",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, neet: 13, mhtCet: 9 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["coulombs law", "k q1 q2 by r squared", "electrostatic force"],
        },
        {
          id: "ecf-coulombs-law-medium",
          expression: "F(medium) = F(vacuum) / K",
          expressionLatex: "F_{medium} = \\dfrac{F_{vacuum}}{K}",
          label: "Coulomb's law in a dielectric medium",
          variables: [
            { symbol: "K", name: "dielectric constant (relative permittivity) of the medium", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["K = 1 for vacuum, ≈ 1 for air", "K > 1 always reduces the force compared to vacuum"],
          conceptLink: {
            chapterSlug: "electric-charges-and-fields",
            sectionHeading: "4. Coulomb's Law",
            concept: "effect of medium on Coulomb force",
          },
          examTags: ["jee-main", "neet", "mht-cet"],
          frequency: "medium",
          examStats: { jeeMain: 4, neet: 6, mhtCet: 5 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["dielectric constant force", "force in medium"],
        },
        {
          id: "ecf-electric-field-point-charge",
          expression: "E = k q / r² = F/q₀",
          expressionLatex: "E = \\dfrac{kq}{r^2}",
          label: "Electric field due to a point charge",
          derivedFrom: "Force per unit positive test charge, E = lim(q₀→0) F/q₀",
          variables: [
            { symbol: "E", name: "electric field magnitude", unit: "N/C or V/m", dimension: "[MLT⁻³A⁻¹]" },
            { symbol: "q", name: "source charge", unit: "C", dimension: "[AT]" },
          ],
          conditions: ["Field points away from a positive source charge, toward a negative one"],
          commonMistakes: [
            "E is defined using an infinitesimal test charge so the source charge's own field is not disturbed — don't confuse with the force ON a placed charge",
          ],
          usedIn: ["electrostatic-potential-and-capacitance"],
          conceptLink: {
            chapterSlug: "electric-charges-and-fields",
            sectionHeading: "7. Electric Field — Definition and Properties",
            concept: "electric field of a point charge",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 10, jeeAdvanced: 5, neet: 14, mhtCet: 10 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["electric field point charge", "kq by r squared", "E field"],
        },
        {
          id: "ecf-electric-field-force-relation",
          expression: "F = qE",
          expressionLatex: "\\vec{F} = q\\vec{E}",
          label: "Force on a charge placed in a field",
          variables: [
            { symbol: "q", name: "charge experiencing the force", unit: "C", dimension: "[AT]" },
          ],
          conditions: ["Direction of F is along E for positive q, opposite to E for negative q"],
          conceptLink: {
            chapterSlug: "electric-charges-and-fields",
            sectionHeading: "21. Motion of a Charged Particle in a Uniform Electric Field",
            concept: "force on a charge in an external field",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 11, mhtCet: 8 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["F equals qE", "force on charge in field"],
        },
        {
          id: "ecf-projectile-in-field",
          expression: "y = ½ (qE/m) t²  ;  deflection at exit: y = qEL²/2mv²",
          expressionLatex: "y = \\dfrac{qEL^2}{2mv^2}",
          label: "Deflection of a charged particle entering a uniform field transversely",
          derivedFrom: "Projectile motion with a = qE/m replacing g",
          variables: [
            { symbol: "L", name: "length of the field region along initial velocity", unit: "m", dimension: "[L]" },
            { symbol: "v", name: "initial speed along the field-free direction", unit: "m/s", dimension: "[LT⁻¹]" },
            { symbol: "m", name: "mass of the particle", unit: "kg", dimension: "[M]" },
          ],
          conditions: ["Analogous to projectile motion with a = qE/m; time in field t = L/v"],
          commonMistakes: [
            "Same structural analogy as horizontal projectile motion under gravity — reuse SUVAT with a = qE/m",
          ],
          usedIn: ["kinematics"],
          conceptLink: {
            chapterSlug: "electric-charges-and-fields",
            sectionHeading: "21. Motion of a Charged Particle in a Uniform Electric Field",
            concept: "charged particle projectile motion in a field",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "high",
          examStats: { jeeMain: 5, jeeAdvanced: 3, neet: 4 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["charged particle deflection", "electron deflection plates"],
        },
      ],
      importantObservations: [
        "Superposition applies vectorially: the net field/force from many charges is the vector sum of individual contributions",
        "Electric field lines never cross, start on positive charges (or infinity) and end on negative charges (or infinity)",
      ],
    },
    {
      id: "ecf-dipole",
      title: "Electric Dipole",
      intro:
        "A dipole is two equal and opposite charges separated by a small distance. Its field falls off faster (1/r³) than a monopole's (1/r²) because the far-field contributions partially cancel.",
      formulas: [
        {
          id: "ecf-dipole-moment",
          expression: "p = q × (2a)",
          expressionLatex: "\\vec{p} = q(2\\vec{a})",
          label: "Electric dipole moment",
          variables: [
            { symbol: "p", name: "dipole moment, points from −q to +q", unit: "C·m", dimension: "[LAT]" },
            { symbol: "2a", name: "separation between the two charges", unit: "m", dimension: "[L]" },
          ],
          conceptLink: {
            chapterSlug: "electric-charges-and-fields",
            sectionHeading: "17. Electric Dipole — Dipole Moment",
            concept: "dipole moment",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 7, neet: 10, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["dipole moment", "p equals q 2a"],
        },
        {
          id: "ecf-dipole-field-axial",
          expression: "E(axial) = 2kp/r³  (for r ≫ a)",
          expressionLatex: "E_{axial} = \\dfrac{2kp}{r^3}",
          label: "Electric field on the axial line of a dipole",
          derivedFrom: "Vector sum of fields from +q and −q along the axis, binomial approximation for r ≫ a",
          derivation: {
            startsFrom: "E = kq/(r−a)² − kq/(r+a)² along the axis (net field points along p)",
            steps: [
              { statement: "Combine over common denominator", expression: "E = kq[(r+a)² − (r−a)²] / (r²−a²)²" },
              { statement: "Expand numerator", expression: "E = kq(4ar) / (r²−a²)²" },
              { statement: "For r ≫ a, drop a² in denominator", expression: "E(axial) ≈ 4kqar/r⁴ = 2kp/r³ (p = 2qa)" },
            ],
            askedInBoards: true,
          },
          variables: [
            { symbol: "r", name: "distance from the centre of the dipole along its axis", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Only valid in the far-field limit r ≫ a", "Direction: along p"],
          commonMistakes: [
            "Axial field is exactly twice the equatorial field at the same distance — a very commonly tested ratio",
          ],
          conceptLink: {
            chapterSlug: "electric-charges-and-fields",
            sectionHeading: "19. Electric Field due to a Dipole",
            concept: "dipole field on the axis",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 4, neet: 12, mhtCet: 8 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["dipole axial field", "2kp by r cubed", "end-on position"],
        },
        {
          id: "ecf-dipole-field-equatorial",
          expression: "E(equatorial) = kp/r³  (for r ≫ a)",
          expressionLatex: "E_{eq} = \\dfrac{kp}{r^3}",
          label: "Electric field on the equatorial line of a dipole",
          derivedFrom: "Vector sum of fields from +q and −q at a perpendicular-bisector point; only components along −p survive",
          variables: [
            { symbol: "r", name: "distance from the centre along the perpendicular bisector", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Direction: antiparallel to p", "Valid for r ≫ a"],
          commonMistakes: [
            "Direction is opposite to p, unlike the axial case where it is parallel to p",
          ],
          conceptLink: {
            chapterSlug: "electric-charges-and-fields",
            sectionHeading: "19. Electric Field due to a Dipole",
            concept: "dipole field on the equatorial line",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 11, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["dipole equatorial field", "kp by r cubed", "broadside-on position"],
        },
        {
          id: "ecf-dipole-torque",
          expression: "τ = pE sinθ = p × E",
          expressionLatex: "\\vec{\\tau} = \\vec{p} \\times \\vec{E}",
          label: "Torque on a dipole in a uniform external field",
          derivedFrom: "Two equal and opposite forces qE separated by perpendicular distance 2a sinθ form a couple",
          variables: [
            { symbol: "θ", name: "angle between p and E", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["Net force on the dipole is zero in a UNIFORM field — only a torque acts"],
          commonMistakes: [
            "Torque is maximum at θ = 90° (τ = pE), zero at θ = 0° or 180° even though those are equilibrium positions",
          ],
          conceptLink: {
            chapterSlug: "electric-charges-and-fields",
            sectionHeading: "18. Dipole in a Uniform Electric Field — Torque, Work, and Potential Energy",
            concept: "torque on a dipole",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 10, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["torque on dipole", "pE sin theta", "p cross E"],
        },
        {
          id: "ecf-dipole-pe",
          expression: "U = −pE cosθ = −p·E",
          expressionLatex: "U = -\\vec{p}\\cdot\\vec{E}",
          label: "Potential energy of a dipole in a uniform field",
          derivedFrom: "Work done rotating the dipole from θ = 90° (reference) to θ: W = ∫τ dθ = pE(cosθ₀−cosθ)",
          variables: [
            { symbol: "U", name: "potential energy, reference U = 0 at θ = 90°", unit: "J", dimension: "[ML²T⁻²]" },
          ],
          conditions: ["Stable equilibrium at θ = 0° (U = −pE, minimum)", "Unstable equilibrium at θ = 180° (U = +pE, maximum)"],
          commonMistakes: [
            "θ = 0° is the STABLE minimum, not θ = 90° — students often assume the zero-reference angle is also the equilibrium",
          ],
          conceptLink: {
            chapterSlug: "electric-charges-and-fields",
            sectionHeading: "18. Dipole in a Uniform Electric Field — Torque, Work, and Potential Energy",
            concept: "potential energy of a dipole",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 3, neet: 8, mhtCet: 5 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["dipole potential energy", "minus pE cos theta"],
        },
        {
          id: "ecf-force-nonuniform-dipole",
          expression: "F = p (dE/dx)",
          expressionLatex: "F = p\\dfrac{dE}{dx}",
          label: "Net force on a dipole in a non-uniform field",
          variables: [
            { symbol: "dE/dx", name: "spatial gradient of the field along the dipole axis", unit: "N/C·m", dimension: "[MLT⁻³A⁻¹L⁻¹]" },
          ],
          conditions: ["In a uniform field this force is zero since dE/dx = 0 — only in non-uniform fields does a dipole experience net translational force"],
          conceptLink: {
            chapterSlug: "electric-charges-and-fields",
            sectionHeading: "20. Force on a Dipole in a Non-Uniform Electric Field",
            concept: "force on a dipole in a non-uniform field",
          },
          examTags: ["jee-advanced", "neet"],
          frequency: "low",
          examStats: { jeeAdvanced: 2, neet: 3 },
          difficulty: "hard",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["dipole non-uniform field force", "p dE dx"],
        },
      ],
      importantObservations: [
        "At any general point (not just axial/equatorial), E has both radial and tangential components; axial and equatorial are the two special symmetric cases",
      ],
      examNotes:
        "NEET frequently asks for the ratio E(axial)/E(equatorial) = 2 at the same distance — memorise this shortcut instead of re-deriving.",
    },
    {
      id: "ecf-gauss-law-group",
      title: "Electric Flux & Gauss's Law",
      intro:
        "Gauss's law converts a hard vector-calculus problem into simple algebra whenever the charge distribution has enough symmetry to choose a smart Gaussian surface.",
      formulas: [
        {
          id: "ecf-electric-flux",
          expression: "Φ = E·A = EA cosθ  (general: Φ = ∮E·dA)",
          expressionLatex: "\\Phi = \\oint \\vec{E}\\cdot d\\vec{A}",
          label: "Electric flux through a surface",
          variables: [
            { symbol: "Φ", name: "electric flux", unit: "N·m²/C", dimension: "[ML³T⁻³A⁻¹]" },
            { symbol: "θ", name: "angle between E and the outward area normal", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
          ],
          conceptLink: {
            chapterSlug: "electric-charges-and-fields",
            sectionHeading: "11. Electric Flux",
            concept: "electric flux",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 6, neet: 8, mhtCet: 6 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["electric flux", "EA cos theta"],
        },
        {
          id: "ecf-gauss-law",
          expression: "Φ(net) = q(enclosed) / ε₀",
          expressionLatex: "\\oint \\vec{E}\\cdot d\\vec{A} = \\dfrac{q_{enc}}{\\varepsilon_0}",
          label: "Gauss's law",
          variables: [
            { symbol: "q(enclosed)", name: "total charge enclosed by the Gaussian surface", unit: "C", dimension: "[AT]" },
          ],
          conditions: ["Only charge STRICTLY inside the surface contributes — charge outside contributes zero net flux (though it may still create field on the surface)"],
          commonMistakes: [
            "The E in Gauss's law is the TOTAL field due to all charges (inside and outside), even though only enclosed charge determines the net flux",
          ],
          conceptLink: {
            chapterSlug: "electric-charges-and-fields",
            sectionHeading: "12. Gauss's Theorem",
            concept: "Gauss's law",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 10, jeeAdvanced: 5, neet: 13, mhtCet: 9 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["gauss law", "q enclosed by epsilon0", "flux charge enclosed"],
        },
        {
          id: "ecf-field-infinite-line",
          expression: "E = λ / (2πε₀ r) = 2kλ/r",
          expressionLatex: "E = \\dfrac{\\lambda}{2\\pi\\varepsilon_0 r}",
          label: "Electric field due to an infinite line charge",
          derivedFrom: "Gauss's law with a cylindrical Gaussian surface coaxial with the line",
          derivation: {
            startsFrom: "Cylindrical Gaussian surface of radius r, length L, coaxial with the wire",
            steps: [
              { statement: "Flux only through curved surface (flat ends have E ∥ surface)", expression: "Φ = E(2πrL)" },
              { statement: "Charge enclosed", expression: "q(enc) = λL" },
              { statement: "Apply Gauss's law", expression: "E(2πrL) = λL/ε₀  ⟹  E = λ/2πε₀r" },
            ],
            askedInBoards: true,
          },
          variables: [
            { symbol: "λ", name: "linear charge density", unit: "C/m", dimension: "[AT L⁻¹]" },
            { symbol: "r", name: "perpendicular distance from the line", unit: "m", dimension: "[L]" },
          ],
          conditions: ["E falls off as 1/r, NOT 1/r² — a key contrast with a point charge"],
          conceptLink: {
            chapterSlug: "electric-charges-and-fields",
            sectionHeading: "16. Electric Field due to an Infinite Line Charge and an Infinite Charged Sheet",
            concept: "field due to an infinite line charge",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 10, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["infinite line charge field", "lambda by 2 pi epsilon0 r"],
        },
        {
          id: "ecf-field-infinite-sheet",
          expression: "E = σ / (2ε₀)",
          expressionLatex: "E = \\dfrac{\\sigma}{2\\varepsilon_0}",
          label: "Electric field due to an infinite charged plane sheet",
          derivedFrom: "Gauss's law with a pillbox Gaussian surface straddling the sheet",
          variables: [
            { symbol: "σ", name: "surface charge density", unit: "C/m²", dimension: "[AT L⁻²]" },
          ],
          conditions: ["Field is uniform — independent of distance from the sheet", "Direction: perpendicular to sheet, away from it if σ > 0"],
          commonMistakes: [
            "Between two oppositely, equally charged parallel sheets, field adds to σ/ε₀ inside and cancels to zero outside — a very common exam trap",
          ],
          conceptLink: {
            chapterSlug: "electric-charges-and-fields",
            sectionHeading: "16. Electric Field due to an Infinite Line Charge and an Infinite Charged Sheet",
            concept: "field due to an infinite charged sheet",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 4, neet: 12, mhtCet: 8 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["infinite sheet field", "sigma by 2 epsilon0", "charged plane"],
        },
        {
          id: "ecf-field-conductor-surface",
          expression: "E = σ / ε₀  (just outside a charged conductor's surface)",
          expressionLatex: "E = \\dfrac{\\sigma}{\\varepsilon_0}",
          label: "Electric field just outside a charged conductor",
          conditions: ["Twice the isolated-sheet value because all the charge is on the outer surface and the field inside the conductor is zero"],
          variables: [
            { symbol: "σ", name: "local surface charge density on the conductor", unit: "C/m²", dimension: "[AT L⁻²]" },
          ],
          conceptLink: {
            chapterSlug: "electric-charges-and-fields",
            sectionHeading: "13. Key Properties and Special Cases of Gaussian Surfaces",
            concept: "field just outside a conductor",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "medium",
          examStats: { jeeMain: 4, jeeAdvanced: 2, neet: 5 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["field outside conductor", "sigma by epsilon0"],
        },
        {
          id: "ecf-field-conducting-sphere",
          expression: "E(out) = kQ/r² (r > R);  E(surface) = kQ/R²;  E(in) = 0",
          expressionLatex: "E_{out} = \\dfrac{kQ}{r^2},\\quad E_{in} = 0",
          label: "Field due to a charged conducting sphere/shell",
          derivedFrom: "Gauss's law with a concentric spherical Gaussian surface; all charge resides on the outer surface",
          variables: [
            { symbol: "Q", name: "total charge on the sphere", unit: "C", dimension: "[AT]" },
            { symbol: "R", name: "radius of the sphere/shell", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Outside, behaves exactly like a point charge Q at the centre", "Field is exactly zero everywhere inside, regardless of shell thickness"],
          commonMistakes: [
            "This is the electrostatic-shielding formula — used to explain why the inside of a charged conductor (even with a cavity) has zero field",
          ],
          usedIn: ["gravitation"],
          conceptLink: {
            chapterSlug: "electric-charges-and-fields",
            sectionHeading: "14. Electric Field due to a Charged Conducting Sphere or Shell",
            concept: "field due to a conducting sphere",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 11, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["conducting sphere field", "field inside conductor zero", "charged shell field"],
        },
        {
          id: "ecf-field-nonconducting-sphere",
          expression: "E(out) = kQ/r² (r>R);  E(surface) = kQ/R²;  E(in) = kQr/R³ (r<R)",
          expressionLatex: "E_{in} = \\dfrac{kQr}{R^3}",
          label: "Field due to a uniformly charged non-conducting (insulating) sphere",
          derivedFrom: "Gauss's law; enclosed charge inside radius r scales as (r/R)³ for uniform volume charge density",
          derivation: {
            startsFrom: "Uniform volume charge density ρ = Q/(4/3 πR³)",
            steps: [
              { statement: "Charge enclosed within radius r < R", expression: "q(enc) = ρ × (4/3)πr³ = Q(r/R)³" },
              { statement: "Apply Gauss's law on a sphere of radius r", expression: "E(4πr²) = Q(r/R)³/ε₀" },
              { statement: "Simplify", expression: "E(in) = kQr/R³ — increases linearly with r" },
            ],
          },
          variables: [
            { symbol: "ρ", name: "uniform volume charge density", unit: "C/m³", dimension: "[AT L⁻³]" },
          ],
          conditions: ["Unlike a conducting sphere, the field is NON-zero inside and grows linearly with r, peaking at the surface"],
          commonMistakes: [
            "Do not confuse with the conducting-sphere case: here charge is spread through the volume, so E(in) ∝ r, not zero",
          ],
          conceptLink: {
            chapterSlug: "electric-charges-and-fields",
            sectionHeading: "15. Electric Field due to a Uniformly Charged Non-Conducting Sphere",
            concept: "field due to an insulating charged sphere",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet"],
          frequency: "high",
          examStats: { jeeMain: 7, jeeAdvanced: 4, neet: 9, mhtCet: 6 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["insulating sphere field", "field inside non-conducting sphere", "kQr by R cubed"],
        },
      ],
      importantObservations: [
        "Choosing the right Gaussian surface (spherical / cylindrical / pillbox) matching the charge symmetry is the entire skill of this topic — Gauss's law itself is always true but useless without a matching symmetric surface",
      ],
      examNotes:
        "JEE Advanced loves combining conducting-sphere-with-cavity problems using superposition (real charge distribution = uniform sphere + a negative sphere at the cavity location).",
    },
  ],
};
