import type { ChapterFormulaSheet } from "./types";

export const electrostaticPotentialAndCapacitanceFormulaSheet: ChapterFormulaSheet = {
  chapterSlug: "electrostatic-potential-and-capacitance",
  chapterName: "Electrostatic Potential & Capacitance",
  className: "12",
  version: "1.0.0",
  lastUpdated: "2026-07-08",
  examCoverage: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
  quickRevisionIds: [
    "epc-potential-point-charge",
    "epc-relation-e-v",
    "epc-capacitance-parallel-plate",
    "epc-energy-stored-capacitor",
    "epc-series-capacitors",
    "epc-parallel-capacitors",
    "epc-common-potential",
  ],
  topicGroups: [
    {
      id: "epc-potential-basics",
      title: "Electrostatic Potential & Potential Energy",
      intro:
        "Potential is potential energy per unit charge — a scalar bookkeeping tool that replaces vector field addition with simple algebraic addition.",
      formulas: [
        {
          id: "epc-potential-point-charge",
          expression: "V = k Q / r",
          expressionLatex: "V = \\dfrac{kQ}{r}",
          label: "Electrostatic potential due to a point charge",
          derivedFrom: "V = −∫(from ∞ to r) E·dl with E = kQ/r²",
          variables: [
            { symbol: "V", name: "electrostatic potential, zero at infinity", unit: "V (J/C)", dimension: "[ML²T⁻³A⁻¹]" },
            { symbol: "Q", name: "source point charge", unit: "C", dimension: "[AT]" },
            { symbol: "r", name: "distance from the charge", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Scalar quantity — net potential from multiple charges is a simple algebraic sum, not a vector sum"],
          commonMistakes: [
            "Potential can be zero at a finite point (between charges of opposite sign) even where the field is not zero, and vice versa",
          ],
          conceptLink: {
            chapterSlug: "electrostatic-potential-and-capacitance",
            sectionHeading: "1. Capacitance — Concept and Definition",
            concept: "electrostatic potential due to a point charge",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 4, neet: 12, mhtCet: 8 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["potential point charge", "kQ by r", "electrostatic potential"],
        },
        {
          id: "epc-potential-dipole",
          expression: "V = k p cosθ / r²  (axial: θ=0 gives V=kp/r²; equatorial: θ=90° gives V=0)",
          expressionLatex: "V = \\dfrac{kp\\cos\\theta}{r^2}",
          label: "Electrostatic potential due to a dipole",
          variables: [
            { symbol: "θ", name: "angle between the dipole axis and the line to the point", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["Falls off as 1/r², faster than a monopole's 1/r, and is exactly zero on the equatorial plane"],
          commonMistakes: [
            "Zero potential on the equatorial line does NOT mean zero field there — field on the equatorial line is kp/r³, non-zero",
          ],
          conceptLink: {
            chapterSlug: "electric-charges-and-fields",
            sectionHeading: "19. Electric Field due to a Dipole",
            concept: "potential due to a dipole",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 3, neet: 7 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["dipole potential", "kp cos theta by r squared"],
        },
        {
          id: "epc-relation-e-v",
          expression: "E = −dV/dr  (radial); in general E = −∇V",
          expressionLatex: "\\vec{E} = -\\nabla V",
          label: "Relation between electric field and potential",
          derivedFrom: "Field is the negative gradient of potential — it points in the direction of steepest potential decrease",
          variables: [
            { symbol: "dV/dr", name: "rate of change of potential with distance", unit: "V/m", dimension: "[MLT⁻³A⁻¹]" },
          ],
          conditions: ["E = 0 wherever V is constant (equipotential region) — the converse is also true"],
          commonMistakes: [
            "The negative sign is essential: field points from high to low potential, not the reverse",
          ],
          conceptLink: {
            chapterSlug: "electrostatic-potential-and-capacitance",
            sectionHeading: "1. Capacitance — Concept and Definition",
            concept: "relation between E and V",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 10, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["E minus dV dr", "field potential gradient relation"],
        },
        {
          id: "epc-potential-energy-two-charges",
          expression: "U = k q₁q₂ / r",
          expressionLatex: "U = \\dfrac{kq_1q_2}{r}",
          label: "Potential energy of a two-charge system",
          derivedFrom: "Work done in assembling the configuration, bringing q₂ from infinity to distance r from q₁",
          variables: [
            { symbol: "U", name: "electrostatic potential energy of the pair, zero at infinite separation", unit: "J", dimension: "[ML²T⁻²]" },
          ],
          conditions: ["Positive U for like charges (repulsive, work must be done against the field to assemble)", "Negative U for unlike charges"],
          conceptLink: {
            chapterSlug: "electrostatic-potential-and-capacitance",
            sectionHeading: "1. Capacitance — Concept and Definition",
            concept: "potential energy of a charge system",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 10, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["potential energy two charges", "kq1q2 by r"],
        },
        {
          id: "epc-potential-energy-system",
          expression: "U = k[q₁q₂/r₁₂ + q₂q₃/r₂₃ + q₁q₃/r₁₃]",
          expressionLatex: "U = k\\left(\\dfrac{q_1q_2}{r_{12}} + \\dfrac{q_2q_3}{r_{23}} + \\dfrac{q_1q_3}{r_{13}}\\right)",
          label: "Potential energy of a system of three (or more) point charges",
          derivedFrom: "Sum over all distinct pairs — each pair's mutual PE added once",
          variables: [
            { symbol: "r₁₂, r₂₃, r₁₃", name: "pairwise separations", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Number of pair terms for n charges is n(n−1)/2 — a common counting trap"],
          commonMistakes: [
            "Do not double-count pairs (q₁q₂ and q₂q₁ are the same pair) or add self-energy terms",
          ],
          conceptLink: {
            chapterSlug: "electrostatic-potential-and-capacitance",
            sectionHeading: "1. Capacitance — Concept and Definition",
            concept: "potential energy of a multi-charge system",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 3, neet: 6 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["potential energy three charges", "system of charges energy"],
        },
        {
          id: "epc-work-done-moving-charge",
          expression: "W = q(V(B) − V(A))",
          expressionLatex: "W = q\\left(V_B - V_A\\right)",
          label: "Work done moving a charge between two points",
          derivedFrom: "Work-energy theorem for the electrostatic (conservative) force",
          variables: [
            { symbol: "V(A), V(B)", name: "potentials at the initial and final points", unit: "V", dimension: "[ML²T⁻³A⁻¹]" },
          ],
          conditions: ["Work is PATH-INDEPENDENT since the electrostatic force is conservative", "Zero work moving a charge along/between points on the same equipotential surface"],
          commonMistakes: [
            "Sign convention: W = q(V_B − V_A), not q(V_A − V_B) — easy to flip under exam pressure",
          ],
          conceptLink: {
            chapterSlug: "electrostatic-potential-and-capacitance",
            sectionHeading: "1. Capacitance — Concept and Definition",
            concept: "work done in an electric field",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 10, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["work done moving charge", "q times V B minus V A"],
        },
      ],
      importantObservations: [
        "Equipotential surfaces are always perpendicular to field lines at every point of intersection",
        "No work is done moving a charge ALONG an equipotential surface, however long the path",
      ],
    },
    {
      id: "epc-capacitance-basics",
      title: "Capacitance & Standard Capacitor Geometries",
      intro:
        "A capacitor stores charge (and energy) proportional to the potential difference across it. The proportionality constant, capacitance, depends only on geometry and the dielectric — not on Q or V individually.",
      formulas: [
        {
          id: "epc-capacitance-def",
          expression: "C = Q / V",
          expressionLatex: "C = \\dfrac{Q}{V}",
          label: "Definition of capacitance",
          variables: [
            { symbol: "C", name: "capacitance", unit: "F (farad)", dimension: "[M⁻¹L⁻²T⁴A²]" },
            { symbol: "Q", name: "charge stored on either plate", unit: "C", dimension: "[AT]" },
            { symbol: "V", name: "potential difference between the plates", unit: "V", dimension: "[ML²T⁻³A⁻¹]" },
          ],
          conditions: ["C depends only on geometry (and dielectric), not on Q or V — a purely geometric property"],
          conceptLink: {
            chapterSlug: "electrostatic-potential-and-capacitance",
            sectionHeading: "1. Capacitance — Concept and Definition",
            concept: "definition of capacitance",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 7, neet: 9, mhtCet: 6 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["capacitance definition", "C equals Q by V"],
        },
        {
          id: "epc-capacitance-isolated-sphere",
          expression: "C = 4πε₀R = R / (k)",
          expressionLatex: "C = 4\\pi\\varepsilon_0 R",
          label: "Capacitance of an isolated spherical conductor",
          derivedFrom: "V = kQ/R at the surface, so C = Q/V = R/k = 4πε₀R",
          variables: [
            { symbol: "R", name: "radius of the sphere", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Sphere in vacuum/air with the 'other plate' taken conceptually at infinity"],
          conceptLink: {
            chapterSlug: "electrostatic-potential-and-capacitance",
            sectionHeading: "4. Capacitance of an Isolated Spherical Conductor",
            concept: "capacitance of an isolated sphere",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 6, neet: 8, mhtCet: 6 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["isolated sphere capacitance", "4 pi epsilon0 R"],
        },
        {
          id: "epc-capacitance-spherical-capacitor",
          expression: "C = 4πε₀ ab / (b − a)",
          expressionLatex: "C = \\dfrac{4\\pi\\varepsilon_0 ab}{b-a}",
          label: "Capacitance of a spherical capacitor (two concentric shells)",
          derivedFrom: "V = kQ(1/a − 1/b) between the shells; C = Q/V",
          variables: [
            { symbol: "a", name: "radius of the inner sphere", unit: "m", dimension: "[L]" },
            { symbol: "b", name: "radius of the outer sphere", unit: "m", dimension: "[L]" },
          ],
          conditions: ["As b → ∞, reduces to the isolated-sphere formula C = 4πε₀a"],
          conceptLink: {
            chapterSlug: "electrostatic-potential-and-capacitance",
            sectionHeading: "5. Spherical Capacitor",
            concept: "spherical capacitor",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet"],
          frequency: "medium",
          examStats: { jeeMain: 5, jeeAdvanced: 3, neet: 5, mhtCet: 4 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["spherical capacitor capacitance", "concentric shells capacitor"],
        },
        {
          id: "epc-capacitance-parallel-plate",
          expression: "C = ε₀A / d",
          expressionLatex: "C = \\dfrac{\\varepsilon_0 A}{d}",
          label: "Capacitance of a parallel plate capacitor (vacuum/air)",
          derivedFrom: "E = σ/ε₀ between the plates; V = Ed; C = Q/V = ε₀A/d",
          derivation: {
            startsFrom: "Uniform field between plates E = σ/ε₀ = Q/(ε₀A)",
            steps: [
              { statement: "Potential difference", expression: "V = Ed = Qd/(ε₀A)" },
              { statement: "Capacitance", expression: "C = Q/V = ε₀A/d" },
            ],
            askedInBoards: true,
          },
          variables: [
            { symbol: "A", name: "overlapping area of each plate", unit: "m²", dimension: "[L²]" },
            { symbol: "d", name: "separation between the plates", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Ignores fringing/edge effects; assumes d ≪ plate dimensions"],
          commonMistakes: [
            "C increases as d decreases — capacitance is inversely proportional to separation, easy to invert under pressure",
          ],
          conceptLink: {
            chapterSlug: "electrostatic-potential-and-capacitance",
            sectionHeading: "6. The Parallel Plate Capacitor",
            concept: "parallel plate capacitor",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 10, jeeAdvanced: 5, neet: 13, mhtCet: 9 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["parallel plate capacitor", "epsilon0 A by d"],
        },
        {
          id: "epc-capacitance-parallel-plate-dielectric",
          expression: "C = K ε₀A / d",
          expressionLatex: "C = \\dfrac{K\\varepsilon_0 A}{d}",
          label: "Capacitance of a parallel plate capacitor with a dielectric filling the gap",
          variables: [
            { symbol: "K", name: "dielectric constant of the medium filling the gap", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["Dielectric always INCREASES capacitance (K > 1)", "For a partially filled slab of thickness t: C = ε₀A / [d − t(1 − 1/K)]"],
          commonMistakes: [
            "If the capacitor is disconnected from the battery (Q fixed) inserting a dielectric reduces V and U; if connected (V fixed) it increases Q and U — track which quantity is held constant",
          ],
          conceptLink: {
            chapterSlug: "electrostatic-potential-and-capacitance",
            sectionHeading: "9. Effect of a Dielectric on Capacitance",
            concept: "effect of dielectric on capacitance",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 11, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["dielectric capacitance", "K epsilon0 A by d"],
        },
        {
          id: "epc-slab-partial-fill",
          expression: "C = ε₀A / [d − t(1 − 1/K)]",
          expressionLatex: "C = \\dfrac{\\varepsilon_0 A}{d - t\\left(1 - \\dfrac{1}{K}\\right)}",
          label: "Capacitance with a dielectric slab partially filling the gap",
          variables: [
            { symbol: "t", name: "thickness of the dielectric slab", unit: "m", dimension: "[L]" },
          ],
          conditions: ["For a conducting slab (K → ∞), reduces to C = ε₀A/(d−t)"],
          commonMistakes: [
            "Setting K → ∞ for a metal slab is a common and useful check — the term (1 − 1/K) → 1, giving the conducting-slab result",
          ],
          conceptLink: {
            chapterSlug: "electrostatic-potential-and-capacitance",
            sectionHeading: "10. Dielectric or Conducting Slab Partially Filling a Parallel Plate Capacitor",
            concept: "partially filled capacitor",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "medium",
          examStats: { jeeMain: 5, jeeAdvanced: 3, neet: 5 },
          difficulty: "hard",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["dielectric slab partial capacitor", "conducting slab capacitor"],
        },
        {
          id: "epc-energy-stored-capacitor",
          expression: "U = ½CV² = Q²/2C = ½QV",
          expressionLatex: "U = \\dfrac{1}{2}CV^2 = \\dfrac{Q^2}{2C}",
          label: "Energy stored in a charged capacitor",
          derivedFrom: "U = ∫₀^Q (q/C) dq, the work done charging the capacitor incrementally",
          variables: [
            { symbol: "U", name: "energy stored", unit: "J", dimension: "[ML²T⁻²]" },
          ],
          conditions: ["Use Q²/2C when Q is fixed (isolated capacitor); use ½CV² when V is fixed (connected to a battery)"],
          commonMistakes: [
            "Energy supplied by the battery (QV) is TWICE the energy stored (½QV) — the other half is dissipated as heat in the connecting wires' resistance",
          ],
          usedIn: ["current-electricity"],
          conceptLink: {
            chapterSlug: "electrostatic-potential-and-capacitance",
            sectionHeading: "3. Energy Stored in a Charged Capacitor",
            concept: "energy stored in a capacitor",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 4, neet: 12, mhtCet: 8 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["energy stored capacitor", "half CV squared", "Q squared by 2C"],
        },
        {
          id: "epc-energy-density",
          expression: "u = ½ ε₀E²",
          expressionLatex: "u = \\dfrac{1}{2}\\varepsilon_0 E^2",
          label: "Energy density of the electric field",
          derivedFrom: "U/(A·d) using U = ½CV², C = ε₀A/d, V = Ed",
          variables: [
            { symbol: "u", name: "energy stored per unit volume", unit: "J/m³", dimension: "[ML⁻¹T⁻²]" },
          ],
          conditions: ["Multiply by K for a dielectric-filled region: u = ½Kε₀E²"],
          conceptLink: {
            chapterSlug: "electrostatic-potential-and-capacitance",
            sectionHeading: "3. Energy Stored in a Charged Capacitor",
            concept: "energy density of electric field",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 3, neet: 7 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["energy density electric field", "half epsilon0 E squared"],
        },
        {
          id: "epc-force-between-plates",
          expression: "F = Q² / (2ε₀A) = σ²A / (2ε₀)",
          expressionLatex: "F = \\dfrac{Q^2}{2\\varepsilon_0 A}",
          label: "Force of attraction between the plates of a parallel plate capacitor",
          derivedFrom: "Each plate sits in the field of the OTHER plate alone (σ/2ε₀), not the total field",
          variables: [
            { symbol: "σ", name: "surface charge density on a plate", unit: "C/m²", dimension: "[AT L⁻²]" },
          ],
          conditions: ["Force uses HALF the total field between the plates — a classic conceptual trap"],
          commonMistakes: [
            "Using E = σ/ε₀ (the total field) instead of σ/2ε₀ (the field due to the other plate alone) gives an answer twice too large",
          ],
          conceptLink: {
            chapterSlug: "electrostatic-potential-and-capacitance",
            sectionHeading: "7. Force Between the Plates and Electrostatic Pressure",
            concept: "force between capacitor plates",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "medium",
          examStats: { jeeMain: 5, jeeAdvanced: 3, neet: 4 },
          difficulty: "hard",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["force between capacitor plates", "electrostatic pressure", "Q squared by 2 epsilon0 A"],
        },
      ],
      importantObservations: [
        "Capacitance is purely a function of geometry and dielectric — never of the charge or voltage applied",
      ],
    },
    {
      id: "epc-combinations",
      title: "Combinations of Capacitors & Charge Sharing",
      intro:
        "Series and parallel rules for capacitors are the OPPOSITE of resistors — series capacitors combine like parallel resistors, and vice versa.",
      formulas: [
        {
          id: "epc-series-capacitors",
          expression: "1/C(eq) = 1/C₁ + 1/C₂ + ⋯",
          expressionLatex: "\\dfrac{1}{C_{eq}} = \\dfrac{1}{C_1} + \\dfrac{1}{C_2} + \\cdots",
          label: "Equivalent capacitance in series",
          derivedFrom: "Same charge Q on every capacitor in series; total V = sum of individual V's = Q(1/C₁+1/C₂+...)",
          variables: [
            { symbol: "C(eq)", name: "equivalent series capacitance", unit: "F", dimension: "[M⁻¹L⁻²T⁴A²]" },
          ],
          conditions: ["Same charge Q resides on each capacitor's plates in series", "C(eq) is always SMALLER than the smallest individual capacitance"],
          conceptLink: {
            chapterSlug: "electrostatic-potential-and-capacitance",
            sectionHeading: "11. Combination of Capacitors",
            concept: "series combination of capacitors",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 10, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["series capacitors", "1 by C equivalent series"],
        },
        {
          id: "epc-parallel-capacitors",
          expression: "C(eq) = C₁ + C₂ + ⋯",
          expressionLatex: "C_{eq} = C_1 + C_2 + \\cdots",
          label: "Equivalent capacitance in parallel",
          derivedFrom: "Same voltage V across every capacitor in parallel; total Q = sum of individual Q's = V(C₁+C₂+...)",
          variables: [
            { symbol: "C(eq)", name: "equivalent parallel capacitance", unit: "F", dimension: "[M⁻¹L⁻²T⁴A²]" },
          ],
          conditions: ["Same potential difference V across each capacitor in parallel", "C(eq) is always LARGER than the largest individual capacitance"],
          conceptLink: {
            chapterSlug: "electrostatic-potential-and-capacitance",
            sectionHeading: "11. Combination of Capacitors",
            concept: "parallel combination of capacitors",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 10, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["parallel capacitors", "C equivalent sum"],
        },
        {
          id: "epc-common-potential",
          expression: "V(common) = (C₁V₁ + C₂V₂) / (C₁ + C₂)",
          expressionLatex: "V_{common} = \\dfrac{C_1V_1 + C_2V_2}{C_1+C_2}",
          label: "Common potential after connecting two charged capacitors",
          derivedFrom: "Conservation of total charge: (C₁+C₂)V(common) = C₁V₁ + C₂V₂",
          variables: [
            { symbol: "V₁, V₂", name: "initial potentials of the two capacitors before connection", unit: "V", dimension: "[ML²T⁻³A⁻¹]" },
          ],
          conditions: ["Total charge is conserved; total energy is NOT (some is dissipated)"],
          conceptLink: {
            chapterSlug: "electrostatic-potential-and-capacitance",
            sectionHeading: "13. Sharing of Charges — Common Potential",
            concept: "common potential after sharing",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet"],
          frequency: "high",
          examStats: { jeeMain: 7, jeeAdvanced: 4, neet: 7, mhtCet: 5 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["common potential capacitors", "charge sharing capacitors"],
        },
        {
          id: "epc-energy-loss-sharing",
          expression: "ΔU = C₁C₂(V₁ − V₂)² / [2(C₁+C₂)]",
          expressionLatex: "\\Delta U = \\dfrac{C_1C_2(V_1-V_2)^2}{2(C_1+C_2)}",
          label: "Energy lost when two charged capacitors are connected",
          derivedFrom: "U(initial) − U(final), using conservation of charge to find V(common)",
          variables: [
            { symbol: "ΔU", name: "energy dissipated as heat/radiation during redistribution", unit: "J", dimension: "[ML²T⁻²]" },
          ],
          conditions: ["ΔU is always ≥ 0 and is exactly zero only when V₁ = V₂ (no redistribution occurs)"],
          commonMistakes: [
            "Students often forget this loss exists and try to equate initial and final energies — energy is NOT conserved here, only charge is",
          ],
          conceptLink: {
            chapterSlug: "electrostatic-potential-and-capacitance",
            sectionHeading: "14. Loss of Energy in Charge Redistribution",
            concept: "energy loss on connecting capacitors",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 4, neet: 6 },
          difficulty: "hard",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["energy loss capacitor sharing", "heat dissipated connecting capacitors"],
        },
      ],
      importantObservations: [
        "Series/parallel rules for capacitors are inverted relative to resistors — a frequent source of confusion when switching topics",
      ],
    },
    {
      id: "epc-rc-circuits",
      title: "Charging & Discharging of Capacitors (RC Circuits)",
      intro:
        "An RC circuit approaches its final charge exponentially — never instantly and never exactly reaching it, characterised by a single time constant τ = RC.",
      formulas: [
        {
          id: "epc-time-constant",
          expression: "τ = RC",
          expressionLatex: "\\tau = RC",
          label: "Time constant of an RC circuit",
          variables: [
            { symbol: "τ", name: "time constant — time to reach 63.2% of final charge (charging) or fall to 36.8% (discharging)", unit: "s", dimension: "[T]" },
            { symbol: "R", name: "resistance in the circuit", unit: "Ω", dimension: "[ML²T⁻³A⁻²]" },
          ],
          conditions: ["Larger R or C means slower charging/discharging"],
          conceptLink: {
            chapterSlug: "electrostatic-potential-and-capacitance",
            sectionHeading: "15. Charging and Discharging of a Capacitor (RC Circuit)",
            concept: "RC time constant",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 3, neet: 6 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["RC time constant", "tau equals RC"],
        },
        {
          id: "epc-charging-rc",
          expression: "q(t) = Q₀(1 − e^(−t/RC))",
          expressionLatex: "q(t) = Q_0\\left(1 - e^{-t/RC}\\right)",
          label: "Charge during charging of a capacitor through a resistor",
          derivedFrom: "Kirchhoff's voltage law: ε = iR + q/C, with i = dq/dt, solved as a first-order ODE",
          variables: [
            { symbol: "Q₀", name: "final (maximum) charge = Cε", unit: "C", dimension: "[AT]" },
            { symbol: "t", name: "time elapsed since charging began", unit: "s", dimension: "[T]" },
          ],
          conditions: ["Charge approaches Q₀ asymptotically — theoretically never reaches it exactly", "At t = τ = RC, q = 0.632 Q₀"],
          conceptLink: {
            chapterSlug: "electrostatic-potential-and-capacitance",
            sectionHeading: "15. Charging and Discharging of a Capacitor (RC Circuit)",
            concept: "charging of a capacitor",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 4, neet: 6 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["charging capacitor RC", "Q0 1 minus e power minus t by RC"],
        },
        {
          id: "epc-discharging-rc",
          expression: "q(t) = Q₀ e^(−t/RC)",
          expressionLatex: "q(t) = Q_0 e^{-t/RC}",
          label: "Charge during discharging of a capacitor through a resistor",
          derivedFrom: "Kirchhoff's voltage law with no source: 0 = iR + q/C, solved as an exponential decay",
          variables: [
            { symbol: "Q₀", name: "initial charge at t = 0", unit: "C", dimension: "[AT]" },
          ],
          conditions: ["At t = τ = RC, q falls to 0.368 Q₀ (36.8%)"],
          commonMistakes: [
            "Current also decays as i(t) = i₀e^(−t/RC) with the same time constant — don't derive it separately from scratch",
          ],
          conceptLink: {
            chapterSlug: "electrostatic-potential-and-capacitance",
            sectionHeading: "15. Charging and Discharging of a Capacitor (RC Circuit)",
            concept: "discharging of a capacitor",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 4, neet: 6 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["discharging capacitor RC", "Q0 e power minus t by RC"],
        },
      ],
      examNotes:
        "JEE Advanced sometimes asks for the fraction of energy dissipated vs stored during charging — exactly half the battery's work goes to heat in R, independent of R's value.",
    },
  ],
};
