import type { ChapterFormulaSheet } from "./types";

export const gravitationFormulaSheet: ChapterFormulaSheet = {
  chapterSlug: "gravitation",
  chapterName: "Gravitation",
  className: "11",
  version: "1.0.1",
  lastUpdated: "2026-07-03",
  examCoverage: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
  quickRevisionIds: [
    "grav-newtons-law",
    "grav-g-variation-height",
    "grav-orbital-velocity",
    "grav-escape-velocity",
    "grav-time-period-satellite",
    "grav-total-energy-satellite",
  ],
  topicGroups: [
    {
      id: "grav-law-and-field",
      title: "Newton's Law of Gravitation & Field",
      intro:
        "Every mass attracts every other mass. The inverse-square law plus superposition is the entire foundation of this chapter.",
      formulas: [
        {
          id: "grav-newtons-law",
          expression: "F = G m₁m₂ / r²",
          expressionLatex: "F = \\dfrac{Gm_1m_2}{r^2}",
          label: "Newton's law of gravitation",
          variables: [
            { symbol: "G", name: "universal gravitational constant", unit: "N·m²/kg²", dimension: "[M⁻¹L³T⁻²]", notes: "G = 6.67 × 10⁻¹¹ N·m²/kg²" },
            { symbol: "m₁, m₂", name: "the two point masses", unit: "kg", dimension: "[M]" },
            { symbol: "r", name: "separation between their centres", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Point masses, or spheres with uniform (radial) density measured centre-to-centre"],
          commonMistakes: [
            "Gravitational force is ALWAYS attractive — no gravitational shielding exists",
          ],
          conceptLink: {
            chapterSlug: "gravitation",
            sectionHeading: "1. Newton's Law of Gravitation",
            concept: "universal law of gravitation",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 12, mhtCet: 9 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["gravitation law", "G m1 m2 by r squared", "inverse square"],
        },
        {
          id: "grav-surface-g",
          expression: "g = GM / R²",
          expressionLatex: "g = \\dfrac{GM}{R^2}",
          label: "Acceleration due to gravity at a planet's surface",
          derivedFrom: "mg = GMm/R² on a surface mass",
          variables: [
            { symbol: "M", name: "mass of the planet", unit: "kg", dimension: "[M]" },
            { symbol: "R", name: "radius of the planet", unit: "m", dimension: "[L]" },
          ],
          commonMistakes: [
            "g is independent of the falling body's mass — that is the equivalence of inertial and gravitational mass",
          ],
          conceptLink: {
            chapterSlug: "gravitation",
            sectionHeading: "2. Acceleration due to Gravity",
            concept: "g at the surface",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 7, neet: 11, mhtCet: 8 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["g GM by R squared", "surface gravity"],
        },
        {
          id: "grav-g-variation-height",
          expression: "g(h) = g (1 − 2h/R)  for h ≪ R;   g(h) = gR²/(R+h)²  exactly",
          expressionLatex: "g_h = g\\left(1 - \\dfrac{2h}{R}\\right)",
          label: "Variation of g with height",
          derivedFrom: "Binomial expansion of gR²/(R+h)² for small h/R",
          variables: [
            { symbol: "h", name: "height above the surface", unit: "m", dimension: "[L]" },
            { symbol: "R", name: "planet radius", unit: "m", dimension: "[L]" },
          ],
          conditions: ["The (1 − 2h/R) form is an approximation valid only for h ≪ R"],
          commonMistakes: [
            "Depth variation is DIFFERENT: g(d) = g(1 − d/R) — factor 1, not 2; g falls linearly to zero at the centre",
          ],
          conceptLink: {
            chapterSlug: "gravitation",
            sectionHeading: "2. Acceleration due to Gravity",
            concept: "variation of g with height and depth",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, neet: 14, mhtCet: 10 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["g variation height", "1 minus 2h by R", "g depth"],
        },
      ],
      importantObservations: [
        "Inside a uniform spherical SHELL, the gravitational field is exactly zero everywhere",
        "At depth d, only the inner sphere of radius (R − d) attracts — the outer shell contributes nothing",
      ],
    },
    {
      id: "grav-potential-energy-group",
      title: "Gravitational Potential & Energy",
      intro:
        "With the zero of potential energy at infinity, all bound systems have negative energy — the sign carries the physics.",
      formulas: [
        {
          id: "grav-potential-energy",
          expression: "U = − G M m / r",
          expressionLatex: "U = -\\dfrac{GMm}{r}",
          label: "Gravitational potential energy (zero at infinity)",
          derivedFrom: "Work done by gravity bringing m from infinity to r",
          variables: [
            { symbol: "U", name: "potential energy of the pair", unit: "J", dimension: "[ML²T⁻²]" },
            { symbol: "r", name: "centre-to-centre separation", unit: "m", dimension: "[L]" },
          ],
          conditions: ["U = mgh is this formula's near-surface approximation for the CHANGE in U"],
          commonMistakes: [
            "U is negative and INCREASES (toward zero) as r increases — 'less negative' means higher energy",
          ],
          usedIn: ["work-energy-and-power"],
          conceptLink: {
            chapterSlug: "gravitation",
            sectionHeading: "3. Gravitational Potential Energy",
            concept: "gravitational potential energy",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 10, mhtCet: 8 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["minus GMm by r", "gravitational potential energy"],
        },
        {
          id: "grav-potential",
          expression: "V = − G M / r",
          expressionLatex: "V = -\\dfrac{GM}{r}",
          label: "Gravitational potential",
          variables: [
            { symbol: "V", name: "potential (PE per unit mass)", unit: "J/kg", dimension: "[L²T⁻²]" },
          ],
          conditions: ["Inside a uniform solid sphere the potential at the CENTRE is −3GM/2R (1.5× the surface value)"],
          conceptLink: {
            chapterSlug: "gravitation",
            sectionHeading: "3. Gravitational Potential Energy",
            concept: "gravitational potential",
          },
          examTags: ["jee-main", "neet", "mht-cet"],
          frequency: "high",
          examStats: { jeeMain: 6, neet: 8, mhtCet: 6 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["gravitational potential", "minus GM by r"],
        },
        {
          id: "grav-escape-velocity",
          expression: "v(e) = √(2GM/R) = √(2gR)",
          expressionLatex: "v_e = \\sqrt{\\dfrac{2GM}{R}} = \\sqrt{2gR}",
          label: "Escape velocity",
          derivedFrom: "Total energy zero at launch: ½mv² − GMm/R = 0",
          derivation: {
            startsFrom: "Escape = just barely reach infinity with zero speed (total energy = 0)",
            steps: [
              { statement: "Energy at the surface", expression: "½mv(e)² − GMm/R = 0" },
              { statement: "Solve for v(e)", expression: "v(e) = √(2GM/R)" },
              { statement: "Substitute GM = gR²", expression: "v(e) = √(2gR) ≈ 11.2 km/s for Earth" },
            ],
            askedInBoards: true,
          },
          variables: [
            { symbol: "v(e)", name: "escape speed from the surface", unit: "m/s", dimension: "[LT⁻¹]", notes: "11.2 km/s for Earth" },
          ],
          conditions: ["Independent of the projectile's mass AND of launch direction (ignoring rotation and atmosphere)"],
          commonMistakes: [
            "v(e) = √2 × v(orbital, low orbit) — remember the √2 bridge between the two speeds",
          ],
          conceptLink: {
            chapterSlug: "gravitation",
            sectionHeading: "4. Escape Velocity",
            concept: "escape velocity",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 10, jeeAdvanced: 4, neet: 15, mhtCet: 11 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["escape velocity", "root 2gR", "11.2 km/s"],
        },
      ],
      importantObservations: [
        "Total energy decides fate: E < 0 bound (ellipse/circle), E = 0 parabola (barely escapes), E > 0 hyperbola",
      ],
    },
    {
      id: "grav-satellites",
      title: "Satellites & Kepler's Laws",
      intro:
        "A satellite is perpetual free fall — gravity supplies exactly the centripetal force. Every orbital formula falls out of that single equation.",
      formulas: [
        {
          id: "grav-orbital-velocity",
          expression: "v(o) = √(GM/r);  near surface v(o) = √(gR) ≈ 7.9 km/s",
          expressionLatex: "v_o = \\sqrt{\\dfrac{GM}{r}}",
          label: "Orbital velocity",
          derivedFrom: "Gravity as centripetal force: GMm/r² = mv²/r",
          variables: [
            { symbol: "v(o)", name: "orbital speed for a circular orbit of radius r", unit: "m/s", dimension: "[LT⁻¹]" },
            { symbol: "r", name: "orbit radius from the planet's CENTRE (r = R + h)", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Circular orbit", "Higher orbit → SLOWER speed"],
          commonMistakes: [
            "r is measured from the planet's centre, not from the surface — forgetting to add R to the height is the classic slip",
          ],
          usedIn: ["laws-of-motion"],
          conceptLink: {
            chapterSlug: "gravitation",
            sectionHeading: "5. Satellites",
            concept: "orbital velocity",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 4, neet: 13, mhtCet: 10 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["orbital velocity", "root GM by r", "7.9 km/s"],
        },
        {
          id: "grav-time-period-satellite",
          expression: "T = 2π √(r³/GM)",
          expressionLatex: "T = 2\\pi\\sqrt{\\dfrac{r^3}{GM}}",
          label: "Time period of a satellite",
          derivedFrom: "T = 2πr / v(o)",
          variables: [
            { symbol: "T", name: "orbital period", unit: "s", dimension: "[T]" },
          ],
          conditions: ["This IS Kepler's third law: T² ∝ r³", "Geostationary orbit: T = 24 h, r ≈ 42000 km, equatorial plane, west-to-east"],
          conceptLink: {
            chapterSlug: "gravitation",
            sectionHeading: "5. Satellites",
            concept: "satellite time period",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 12, mhtCet: 9 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["satellite period", "T squared r cubed", "geostationary"],
        },
        {
          id: "grav-total-energy-satellite",
          expression: "E = −GMm/2r;   K = +GMm/2r;   U = −GMm/r",
          expressionLatex: "E = -\\dfrac{GMm}{2r}",
          label: "Energies of an orbiting satellite",
          derivedFrom: "K = ½mv(o)² with v(o)² = GM/r; E = K + U",
          derivation: {
            startsFrom: "Kinetic energy in circular orbit",
            steps: [
              { statement: "From orbital speed", expression: "K = ½m(GM/r) = GMm/2r" },
              { statement: "Potential energy", expression: "U = −GMm/r" },
              { statement: "Total", expression: "E = K + U = −GMm/2r" },
            ],
          },
          variables: [
            { symbol: "E", name: "total mechanical energy of the orbit", unit: "J", dimension: "[ML²T⁻²]" },
          ],
          conditions: ["The memory pattern: U = 2E, K = −E, |U| = 2K"],
          commonMistakes: [
            "Binding energy = +GMm/2r — the energy you must SUPPLY to free the satellite",
          ],
          conceptLink: {
            chapterSlug: "gravitation",
            sectionHeading: "5. Satellites",
            concept: "energy of a satellite",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 5, neet: 11, mhtCet: 8 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["satellite energy", "minus GMm by 2r", "binding energy"],
        },
        {
          id: "grav-keplers-laws",
          expression: "T² ∝ a³  (a = semi-major axis)",
          expressionLatex: "T^2 \\propto a^3",
          label: "Kepler's three laws",
          variables: [
            { symbol: "a", name: "semi-major axis of the elliptical orbit", unit: "m", dimension: "[L]" },
          ],
          conditions: [
            "1st law: orbits are ellipses with the Sun at one focus",
            "2nd law: equal areas in equal times (angular momentum conservation)",
            "3rd law: T² ∝ a³",
          ],
          commonMistakes: [
            "2nd law consequence: a planet moves FASTEST at perihelion (closest approach), slowest at aphelion",
          ],
          usedIn: ["system-of-particles-and-rotational-motion"],
          conceptLink: {
            chapterSlug: "gravitation",
            sectionHeading: "6. Kepler's Laws",
            concept: "Kepler's laws of planetary motion",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 6, neet: 10, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["kepler laws", "T squared a cubed", "equal areas"],
        },
      ],
      importantObservations: [
        "A satellite needs no fuel to stay in orbit but plenty to CHANGE orbit — raising the orbit costs energy even though the speed decreases",
        "Weightlessness in orbit is free fall, not absence of gravity — g at ISS altitude is still ≈ 90% of surface g",
      ],
      examNotes:
        "NEET repeats escape/orbital velocity ratios yearly; JEE Advanced uses elliptical orbits where only L and E are conserved — apply both at perigee and apogee.",
    },
  ],
};
