import type { ChapterFormulaSheet } from "./types";

export const kineticTheoryFormulaSheet: ChapterFormulaSheet = {
  chapterSlug: "kinetic-theory-of-gases",
  chapterName: "Kinetic Theory of Gases",
  className: "11",
  version: "1.0.1",
  lastUpdated: "2026-07-04",
  examCoverage: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
  quickRevisionIds: [
    "ktg-ideal-gas-law",
    "ktg-pressure-formula",
    "ktg-rms-speed",
    "ktg-avg-ke-per-molecule",
    "ktg-equipartition-dof",
  ],
  topicGroups: [
    {
      id: "ktg-gas-laws",
      title: "Ideal Gas Equation & Gas Laws",
      intro:
        "One equation, PV = nRT, contains Boyle, Charles and Gay-Lussac as special cases — fix one variable and read off the rest.",
      formulas: [
        {
          id: "ktg-ideal-gas-law",
          expression: "PV = nRT = NkT",
          expressionLatex: "PV = nRT = Nk_BT",
          label: "Ideal gas equation",
          variables: [
            { symbol: "n", name: "number of moles", unit: "mol", dimension: "[N]" },
            { symbol: "N", name: "number of molecules", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
            { symbol: "k", name: "Boltzmann constant (R/Nₐ)", unit: "J/K", dimension: "[ML²T⁻²Θ⁻¹]", notes: "k = 1.38 × 10⁻²³ J/K" },
            { symbol: "R", name: "universal gas constant", unit: "J/(mol·K)", dimension: "[ML²T⁻²Θ⁻¹N⁻¹]" },
          ],
          conditions: [
            "Boyle: PV = const at fixed T; Charles: V ∝ T at fixed P; Gay-Lussac: P ∝ T at fixed V",
            "Density form: PM = ρRT (M = molar mass)",
          ],
          commonMistakes: [
            "Two connected containers share PRESSURE, not temperature — conserve total moles n₁ + n₂ when gas redistributes",
          ],
          usedIn: ["thermodynamics"],
          conceptLink: {
            chapterSlug: "kinetic-theory-of-gases",
            sectionHeading: "1. Ideal Gas Equation",
            concept: "ideal gas law",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 10, neet: 14, mhtCet: 10 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["PV nRT", "ideal gas", "boyle charles"],
        },
      ],
      importantObservations: [
        "Real gases approach ideal behaviour at LOW pressure and HIGH temperature — far from liquefaction",
      ],
    },
    {
      id: "ktg-pressure-speeds",
      title: "Kinetic Pressure & Molecular Speeds",
      intro:
        "Pressure is molecular bombardment. From one formula, P = ⅓ρv̄², every speed and energy result follows.",
      formulas: [
        {
          id: "ktg-pressure-formula",
          expression: "P = ⅓ ρ v(rms)² = ⅓ (mN/V) v(rms)²",
          expressionLatex: "P = \\tfrac{1}{3}\\rho v_{rms}^2",
          label: "Pressure of an ideal gas (kinetic theory)",
          derivedFrom: "Momentum transfer of molecules bouncing off the walls, averaged over random directions",
          variables: [
            { symbol: "ρ", name: "density of the gas", unit: "kg/m³", dimension: "[ML⁻³]" },
            { symbol: "v(rms)", name: "root-mean-square speed", unit: "m/s", dimension: "[LT⁻¹]" },
            { symbol: "m", name: "mass of ONE molecule", unit: "kg", dimension: "[M]" },
          ],
          conditions: ["Point molecules, elastic collisions, no intermolecular forces — the ideal gas postulates"],
          commonMistakes: [
            "Kinetic energy density link: P = ⅔ × (translational KE per unit volume)",
          ],
          conceptLink: {
            chapterSlug: "kinetic-theory-of-gases",
            sectionHeading: "2. Pressure of an Ideal Gas",
            concept: "kinetic interpretation of pressure",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 12, mhtCet: 9 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["one third rho v squared", "kinetic pressure"],
        },
        {
          id: "ktg-rms-speed",
          expression: "v(rms) = √(3RT/M) = √(3kT/m) = √(3P/ρ)",
          expressionLatex: "v_{rms} = \\sqrt{\\dfrac{3RT}{M}}",
          label: "RMS speed",
          derivedFrom: "Equating ⅓ρv(rms)² with P from the ideal gas law",
          variables: [
            { symbol: "M", name: "molar mass (in kg/mol!)", unit: "kg/mol", dimension: "[MN⁻¹]" },
            { symbol: "T", name: "absolute temperature", unit: "K", dimension: "[Θ]" },
          ],
          conditions: ["v(rms) ∝ √T and ∝ 1/√M — lighter and hotter means faster"],
          commonMistakes: [
            "Using M in g/mol with R = 8.314 gives answers off by √1000 — convert to kg/mol",
            "Speed ORDER at the same T: v(rms) > v(avg) > v(mp), in ratio √3 : √(8/π) : √2",
          ],
          usedIn: ["waves"],
          conceptLink: {
            chapterSlug: "kinetic-theory-of-gases",
            sectionHeading: "3. Molecular Speeds",
            concept: "rms speed",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 11, jeeAdvanced: 3, neet: 15, mhtCet: 11 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["rms speed", "root 3RT by M", "most probable average"],
        },
        {
          id: "ktg-avg-mp-speeds",
          expression: "v(avg) = √(8RT/πM);   v(mp) = √(2RT/M)",
          expressionLatex: "v_{avg} = \\sqrt{\\dfrac{8RT}{\\pi M}},\\quad v_{mp} = \\sqrt{\\dfrac{2RT}{M}}",
          label: "Average and most-probable speeds",
          variables: [
            { symbol: "v(avg)", name: "mean speed of the Maxwell distribution", unit: "m/s", dimension: "[LT⁻¹]" },
            { symbol: "v(mp)", name: "most probable speed (peak of the distribution)", unit: "m/s", dimension: "[LT⁻¹]" },
          ],
          conditions: ["Maxwell-Boltzmann speed distribution"],
          conceptLink: {
            chapterSlug: "kinetic-theory-of-gases",
            sectionHeading: "3. Molecular Speeds",
            concept: "Maxwell speed distribution",
          },
          examTags: ["jee-main", "neet", "mht-cet"],
          frequency: "high",
          examStats: { jeeMain: 6, neet: 9, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["average speed", "most probable speed", "8RT by pi M"],
        },
      ],
      importantObservations: [
        "At the same temperature all gases share the same average translational KE — but NOT the same speeds (lighter gas moves faster)",
      ],
    },
    {
      id: "ktg-energy-dof",
      title: "Energy, Degrees of Freedom & Mean Free Path",
      intro:
        "Equipartition hands each quadratic degree of freedom ½kT. Count the degrees and every heat capacity in the chapter writes itself.",
      formulas: [
        {
          id: "ktg-avg-ke-per-molecule",
          expression: "KE(trans) = (3/2) kT per molecule = (3/2) RT per mole",
          expressionLatex: "\\bar{E}_{trans} = \\tfrac{3}{2}k_BT",
          label: "Average translational kinetic energy",
          derivedFrom: "½m v(rms)² with v(rms)² = 3kT/m",
          variables: [
            { symbol: "k", name: "Boltzmann constant", unit: "J/K", dimension: "[ML²T⁻²Θ⁻¹]" },
            { symbol: "T", name: "absolute temperature", unit: "K", dimension: "[Θ]" },
          ],
          conditions: ["Depends ONLY on temperature — identical for every gas", "Translational part is (3/2)kT even for polyatomic molecules"],
          commonMistakes: [
            "Doubling the CELSIUS temperature does not double KE — kelvin only",
          ],
          usedIn: ["thermodynamics", "dual-nature-of-radiation-and-matter"],
          conceptLink: {
            chapterSlug: "kinetic-theory-of-gases",
            sectionHeading: "4. Kinetic Energy and Temperature",
            concept: "average kinetic energy",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, neet: 14, mhtCet: 10 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["3 by 2 kT", "average kinetic energy", "temperature meaning"],
        },
        {
          id: "ktg-equipartition-dof",
          expression: "U = (f/2) nRT;   Cᵥ = (f/2)R;   γ = 1 + 2/f",
          expressionLatex: "C_v = \\tfrac{f}{2}R,\\quad \\gamma = 1 + \\tfrac{2}{f}",
          label: "Equipartition: energy and heat capacity from degrees of freedom",
          derivedFrom: "Each quadratic degree of freedom carries ½kT on average",
          derivation: {
            startsFrom: "Equipartition theorem: energy per molecule = (f/2)kT",
            steps: [
              { statement: "Per mole", expression: "U = (f/2)RT × n" },
              { statement: "Differentiate at constant volume", expression: "Cᵥ = (f/2)R" },
              { statement: "Mayer's relation gives", expression: "γ = Cₚ/Cᵥ = 1 + 2/f" },
            ],
          },
          variables: [
            { symbol: "f", name: "degrees of freedom", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]", notes: "monatomic 3; diatomic 5 (7 with vibration at high T); nonlinear polyatomic 6" },
          ],
          conditions: ["Vibrational modes freeze out at ordinary temperatures for diatomic gases"],
          commonMistakes: [
            "Mixture of gases: Cᵥ(mix) = (n₁Cᵥ₁ + n₂Cᵥ₂)/(n₁ + n₂) — mole-weighted, and γ(mix) comes from Cₚ(mix)/Cᵥ(mix), never by averaging γ values",
          ],
          usedIn: ["thermodynamics"],
          conceptLink: {
            chapterSlug: "kinetic-theory-of-gases",
            sectionHeading: "5. Degrees of Freedom",
            concept: "equipartition of energy",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 10, jeeAdvanced: 4, neet: 13, mhtCet: 9 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["degrees of freedom", "f by 2 R", "gamma 1 plus 2 by f", "gas mixture"],
        },
        {
          id: "ktg-mean-free-path",
          expression: "λ = 1/(√2 π d² n(v)) = kT/(√2 π d² P)",
          expressionLatex: "\\lambda = \\dfrac{k_BT}{\\sqrt{2}\\pi d^2 P}",
          label: "Mean free path",
          variables: [
            { symbol: "λ", name: "average distance between collisions", unit: "m", dimension: "[L]" },
            { symbol: "d", name: "molecular diameter", unit: "m", dimension: "[L]" },
            { symbol: "n(v)", name: "number density N/V", unit: "m⁻³", dimension: "[L⁻³]" },
          ],
          conditions: ["λ ∝ T at fixed pressure; λ ∝ 1/P at fixed temperature"],
          conceptLink: {
            chapterSlug: "kinetic-theory-of-gases",
            sectionHeading: "6. Mean Free Path",
            concept: "mean free path",
          },
          examTags: ["jee-main", "neet"],
          frequency: "medium",
          examStats: { jeeMain: 5, neet: 6 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["mean free path", "root 2 pi d squared"],
        },
      ],
      importantObservations: [
        "Absolute zero in kinetic language: the temperature at which molecular translational KE would vanish",
      ],
      examNotes:
        "NEET loves speed-ratio and KE-per-molecule one-liners; JEE Main's favourite is the gas-mixture γ — always via Cᵥ, never by averaging γ.",
    },
  ],
};
