import type { ChapterFormulaSheet } from "./types";

// ─────────────────────────────────────────────────────────────────
// Kinematics — Formula Sheet (Pilot Chapter)
// Class 11 · Motion in a Straight Line + Motion in a Plane
// ─────────────────────────────────────────────────────────────────

export const kinematicsFormulaSheet: ChapterFormulaSheet = {
  chapterSlug: "kinematics",
  chapterName: "Kinematics",
  className: "11",
  version: "1.0.0",
  lastUpdated: "2026-07-02",
  examCoverage: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
  quickRevisionIds: [
    "kin-first-equation",
    "kin-second-equation",
    "kin-third-equation",
    "kin-projectile-range",
    "kin-projectile-max-height",
    "kin-projectile-time-of-flight",
    "kin-relative-velocity",
  ],
  topicGroups: [
    // ── 1. Basic Definitions ─────────────────────────────────────
    {
      id: "kin-basic-definitions",
      title: "Basic Definitions",
      intro:
        "Every kinematics problem starts here — distance vs displacement, speed vs velocity, and what acceleration really measures.",
      formulas: [
        {
          id: "kin-average-velocity",
          expression: "v̄ = Δx / Δt",
          expressionLatex: "\\vec{v}_{avg} = \\dfrac{\\Delta \\vec{x}}{\\Delta t}",
          label: "Average velocity",
          variables: [
            { symbol: "v̄", name: "average velocity", unit: "m/s", dimension: "[LT⁻¹]" },
            { symbol: "Δx", name: "displacement", unit: "m", dimension: "[L]" },
            { symbol: "Δt", name: "time interval", unit: "s", dimension: "[T]" },
          ],
          conditions: ["Uses displacement, not distance"],
          commonMistakes: [
            "Using total distance instead of displacement — that gives average speed, not average velocity",
          ],
          conceptLink: {
            chapterSlug: "kinematics",
            sectionHeading: "2. Speed and Velocity",
            concept: "average velocity vs average speed",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 6, neet: 8, mhtCet: 5 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["average velocity", "displacement over time"],
        },
        {
          id: "kin-average-speed",
          expression: "Average speed = Total distance / Total time",
          label: "Average speed",
          variables: [
            { symbol: "v̄", name: "average speed", unit: "m/s", dimension: "[LT⁻¹]" },
          ],
          commonMistakes: [
            "For a two-part journey at speeds v₁ and v₂ over equal distances, average speed is the harmonic mean 2v₁v₂/(v₁+v₂), NOT the arithmetic mean",
          ],
          usedIn: ["kinematics"],
          conceptLink: {
            chapterSlug: "kinematics",
            sectionHeading: "2. Speed and Velocity",
            concept: "average speed",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, neet: 12, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["average speed", "harmonic mean speed", "two speeds equal distance"],
        },
        {
          id: "kin-instantaneous-velocity",
          expression: "v = dx/dt",
          expressionLatex: "v = \\dfrac{dx}{dt}",
          label: "Instantaneous velocity",
          derivedFrom: "Limit of average velocity as Δt → 0",
          variables: [
            { symbol: "v", name: "instantaneous velocity", unit: "m/s", dimension: "[LT⁻¹]" },
            { symbol: "x", name: "position", unit: "m", dimension: "[L]" },
            { symbol: "t", name: "time", unit: "s", dimension: "[T]" },
          ],
          conceptLink: {
            chapterSlug: "kinematics",
            sectionHeading: "2. Speed and Velocity",
            concept: "instantaneous velocity as derivative of position",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet"],
          frequency: "high",
          examStats: { jeeMain: 7, jeeAdvanced: 4, neet: 6 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["instantaneous velocity", "derivative of position", "dx/dt"],
        },
        {
          id: "kin-instantaneous-acceleration",
          expression: "a = dv/dt = v (dv/dx)",
          expressionLatex: "a = \\dfrac{dv}{dt} = v\\dfrac{dv}{dx}",
          label: "Instantaneous acceleration (both forms)",
          derivedFrom: "Chain rule: dv/dt = (dv/dx)(dx/dt) = v·dv/dx",
          variables: [
            { symbol: "a", name: "acceleration", unit: "m/s²", dimension: "[LT⁻²]" },
            { symbol: "v", name: "velocity", unit: "m/s", dimension: "[LT⁻¹]" },
          ],
          conditions: ["The v·dv/dx form is for when velocity is given as a function of position"],
          commonMistakes: [
            "Forgetting the v·dv/dx form — JEE loves giving v(x) and asking for acceleration",
          ],
          conceptLink: {
            chapterSlug: "kinematics",
            sectionHeading: "3. Acceleration",
            concept: "acceleration as derivative of velocity",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "very-high",
          examStats: { jeeMain: 11, jeeAdvanced: 7, neet: 5 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["acceleration", "v dv dx", "velocity as function of position"],
        },
      ],
      importantObservations: [
        "Distance ≥ |displacement| always; equality holds only for straight-line motion without reversal",
        "A body can have zero velocity and non-zero acceleration at the same instant (top of vertical throw)",
      ],
    },

    // ── 2. Equations of Motion ───────────────────────────────────
    {
      id: "kin-equations-of-motion",
      title: "Equations of Motion (Constant Acceleration)",
      intro:
        "The three SUVAT equations — valid ONLY when acceleration is constant. This is the most-used formula set in all of Class 11 physics.",
      formulas: [
        {
          id: "kin-first-equation",
          expression: "v = u + at",
          expressionLatex: "v = u + at",
          label: "First equation of motion",
          derivedFrom: "Integrating a = dv/dt with constant a",
          derivation: {
            startsFrom: "Definition of acceleration: a = dv/dt",
            steps: [
              { statement: "Since a is constant, separate variables", expression: "dv = a·dt" },
              { statement: "Integrate v from u to v, and t from 0 to t", expression: "∫ᵤᵛ dv = a ∫₀ᵗ dt" },
              { statement: "Evaluate both integrals", expression: "v − u = at" },
              { statement: "Rearrange", expression: "v = u + at" },
            ],
            askedInBoards: true,
          },
          variables: [
            { symbol: "v", name: "final velocity", unit: "m/s", dimension: "[LT⁻¹]" },
            { symbol: "u", name: "initial velocity", unit: "m/s", dimension: "[LT⁻¹]" },
            { symbol: "a", name: "acceleration", unit: "m/s²", dimension: "[LT⁻²]" },
            { symbol: "t", name: "time", unit: "s", dimension: "[T]" },
          ],
          conditions: ["Constant acceleration only", "Straight-line motion (or apply per-component)"],
          commonMistakes: [
            "Using it when acceleration varies with time — integrate instead",
            "Sign errors: choose a positive direction and stick to it for u, v, a",
          ],
          usedIn: ["laws-of-motion", "work-energy-and-power"],
          conceptLink: {
            chapterSlug: "kinematics",
            sectionHeading: "4. Equations of Motion",
            concept: "uniformly accelerated motion",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 15, jeeAdvanced: 6, neet: 18, mhtCet: 12 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["SUVAT", "first equation", "v u at"],
        },
        {
          id: "kin-second-equation",
          expression: "s = ut + ½at²",
          expressionLatex: "s = ut + \\tfrac{1}{2}at^2",
          label: "Second equation of motion",
          derivedFrom: "Integrating v = dx/dt after substituting v = u + at",
          derivation: {
            startsFrom: "v = dx/dt and v = u + at",
            steps: [
              { statement: "Substitute", expression: "dx/dt = u + at" },
              { statement: "Separate and integrate x from 0 to s, t from 0 to t", expression: "∫₀ˢ dx = ∫₀ᵗ (u + at) dt" },
              { statement: "Evaluate", expression: "s = ut + ½at²" },
            ],
            askedInBoards: true,
          },
          variables: [
            { symbol: "s", name: "displacement", unit: "m", dimension: "[L]" },
            { symbol: "u", name: "initial velocity", unit: "m/s", dimension: "[LT⁻¹]" },
            { symbol: "a", name: "acceleration", unit: "m/s²", dimension: "[LT⁻²]" },
            { symbol: "t", name: "time", unit: "s", dimension: "[T]" },
          ],
          conditions: ["Constant acceleration only"],
          commonMistakes: [
            "s is displacement from the STARTING point, not total distance if direction reverses",
          ],
          usedIn: ["laws-of-motion"],
          conceptLink: {
            chapterSlug: "kinematics",
            sectionHeading: "4. Equations of Motion",
            concept: "displacement under uniform acceleration",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 14, jeeAdvanced: 5, neet: 16, mhtCet: 11 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["SUVAT", "second equation", "ut half at squared"],
        },
        {
          id: "kin-third-equation",
          expression: "v² = u² + 2as",
          expressionLatex: "v^2 = u^2 + 2as",
          label: "Third equation of motion",
          derivedFrom: "Eliminating t between the first two equations (or from v·dv/dx = a)",
          variables: [
            { symbol: "v", name: "final velocity", unit: "m/s", dimension: "[LT⁻¹]" },
            { symbol: "u", name: "initial velocity", unit: "m/s", dimension: "[LT⁻¹]" },
            { symbol: "a", name: "acceleration", unit: "m/s²", dimension: "[LT⁻²]" },
            { symbol: "s", name: "displacement", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Constant acceleration only", "Time-independent — use when t is not given/needed"],
          usedIn: ["laws-of-motion", "work-energy-and-power"],
          conceptLink: {
            chapterSlug: "kinematics",
            sectionHeading: "4. Equations of Motion",
            concept: "time-independent equation of motion",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 13, jeeAdvanced: 6, neet: 15, mhtCet: 10 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["SUVAT", "third equation", "v squared u squared 2as"],
        },
        {
          id: "kin-nth-second",
          expression: "sₙ = u + a(2n−1)/2",
          expressionLatex: "s_n = u + \\dfrac{a(2n-1)}{2}",
          label: "Displacement in the nth second",
          derivedFrom: "s(n) − s(n−1) using the second equation",
          variables: [
            { symbol: "sₙ", name: "displacement in the nth second", unit: "m", dimension: "[L]", notes: "numerically equals metres covered during that one second" },
            { symbol: "n", name: "second number (1st, 2nd, ...)", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["Constant acceleration only"],
          commonMistakes: [
            "Dimensional panic: the formula looks dimensionally odd but is correct — it is displacement per unit (1 s) interval",
          ],
          conceptLink: {
            chapterSlug: "kinematics",
            sectionHeading: "4. Equations of Motion",
            concept: "displacement in nth second",
          },
          examTags: ["jee-main", "neet", "mht-cet"],
          frequency: "medium",
          examStats: { jeeMain: 4, neet: 7, mhtCet: 5 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["nth second", "displacement in nth second"],
        },
      ],
      importantObservations: [
        "For free fall take a = +g downward if you choose down as positive — consistency beats convention",
        "Under gravity alone, time up = time down and speed of projection = speed of return (no air resistance)",
      ],
      examNotes:
        "NEET asks these directly; JEE Main wraps them in graphs; JEE Advanced hides them inside multi-body constraint problems.",
    },

    // ── 3. Motion Under Gravity ──────────────────────────────────
    {
      id: "kin-motion-under-gravity",
      title: "Motion Under Gravity (Free Fall)",
      intro:
        "Equations of motion with a = g ≈ 9.8 m/s², taking consistent sign convention.",
      formulas: [
        {
          id: "kin-max-height-vertical",
          expression: "H = u²/2g",
          expressionLatex: "H = \\dfrac{u^2}{2g}",
          label: "Maximum height (vertical throw)",
          derivedFrom: "Third equation with v = 0 at the top",
          variables: [
            { symbol: "H", name: "maximum height", unit: "m", dimension: "[L]" },
            { symbol: "u", name: "initial upward speed", unit: "m/s", dimension: "[LT⁻¹]" },
            { symbol: "g", name: "acceleration due to gravity", unit: "m/s²", dimension: "[LT⁻²]" },
          ],
          conditions: ["No air resistance"],
          usedIn: ["work-energy-and-power"],
          conceptLink: {
            chapterSlug: "kinematics",
            sectionHeading: "5. Motion Under Gravity",
            concept: "vertical projection maximum height",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 8, neet: 11, mhtCet: 6 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["maximum height", "vertical throw", "u squared by 2g"],
        },
        {
          id: "kin-time-of-flight-vertical",
          expression: "T = 2u/g",
          expressionLatex: "T = \\dfrac{2u}{g}",
          label: "Total time of flight (vertical throw, return to launch point)",
          derivedFrom: "Time up (u/g) doubled by symmetry",
          variables: [
            { symbol: "T", name: "total time of flight", unit: "s", dimension: "[T]" },
            { symbol: "u", name: "initial upward speed", unit: "m/s", dimension: "[LT⁻¹]" },
            { symbol: "g", name: "acceleration due to gravity", unit: "m/s²", dimension: "[LT⁻²]" },
          ],
          conditions: ["Returns to the same height", "No air resistance"],
          conceptLink: {
            chapterSlug: "kinematics",
            sectionHeading: "5. Motion Under Gravity",
            concept: "time of flight symmetry",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 6, neet: 9, mhtCet: 5 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["time of flight", "vertical throw", "2u by g"],
        },
      ],
      importantObservations: [
        "Velocity at any height h on the way up equals velocity at the same h on the way down (magnitude)",
        "Galileo's odd-number rule: distances in successive seconds of free fall from rest are in ratio 1:3:5:7...",
      ],
    },

    // ── 4. Projectile Motion ─────────────────────────────────────
    {
      id: "kin-projectile-motion",
      title: "Projectile Motion",
      intro:
        "Two independent motions: uniform velocity horizontally, uniform acceleration (g) vertically. Every projectile result comes from treating them separately.",
      formulas: [
        {
          id: "kin-projectile-time-of-flight",
          expression: "T = (2u sinθ) / g",
          expressionLatex: "T = \\dfrac{2u\\sin\\theta}{g}",
          label: "Time of flight",
          derivedFrom: "Vertical motion: uᵧ = u·sinθ, returns when vertical displacement = 0",
          variables: [
            { symbol: "T", name: "time of flight", unit: "s", dimension: "[T]" },
            { symbol: "u", name: "launch speed", unit: "m/s", dimension: "[LT⁻¹]" },
            { symbol: "θ", name: "launch angle from horizontal", unit: "rad (or °)", dimension: "[M⁰L⁰T⁰]" },
            { symbol: "g", name: "acceleration due to gravity", unit: "m/s²", dimension: "[LT⁻²]" },
          ],
          conditions: ["Level ground (launch and landing at same height)", "No air resistance"],
          usedIn: ["laws-of-motion"],
          conceptLink: {
            chapterSlug: "kinematics",
            sectionHeading: "6. Projectile Motion",
            concept: "projectile time of flight",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 10, jeeAdvanced: 4, neet: 13, mhtCet: 9 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["projectile", "time of flight", "2u sin theta by g"],
        },
        {
          id: "kin-projectile-max-height",
          expression: "H = (u² sin²θ) / 2g",
          expressionLatex: "H = \\dfrac{u^2\\sin^2\\theta}{2g}",
          label: "Maximum height",
          derivedFrom: "Third equation applied to vertical component with vᵧ = 0 at top",
          variables: [
            { symbol: "H", name: "maximum height", unit: "m", dimension: "[L]" },
            { symbol: "u", name: "launch speed", unit: "m/s", dimension: "[LT⁻¹]" },
            { symbol: "θ", name: "launch angle from horizontal", unit: "rad (or °)", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["No air resistance"],
          conceptLink: {
            chapterSlug: "kinematics",
            sectionHeading: "6. Projectile Motion",
            concept: "projectile maximum height",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 3, neet: 12, mhtCet: 8 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["projectile", "maximum height", "u squared sin squared theta"],
        },
        {
          id: "kin-projectile-range",
          expression: "R = (u² sin 2θ) / g",
          expressionLatex: "R = \\dfrac{u^2\\sin 2\\theta}{g}",
          label: "Horizontal range",
          derivedFrom: "R = (u·cosθ)·T with T = 2u·sinθ/g and identity 2sinθcosθ = sin2θ",
          variables: [
            { symbol: "R", name: "horizontal range", unit: "m", dimension: "[L]" },
            { symbol: "u", name: "launch speed", unit: "m/s", dimension: "[LT⁻¹]" },
            { symbol: "θ", name: "launch angle from horizontal", unit: "rad (or °)", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["Level ground", "No air resistance"],
          commonMistakes: [
            "Range is maximum at θ = 45°, and R(θ) = R(90°−θ): complementary angles give equal ranges",
            "sin2θ means sin(2θ), not (sinθ)² — read carefully under exam pressure",
          ],
          conceptLink: {
            chapterSlug: "kinematics",
            sectionHeading: "6. Projectile Motion",
            concept: "projectile range and complementary angles",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 12, jeeAdvanced: 5, neet: 14, mhtCet: 10 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["projectile", "range", "u squared sin 2 theta", "45 degrees maximum range"],
        },
        {
          id: "kin-projectile-trajectory",
          expression: "y = x tanθ − gx² / (2u² cos²θ)",
          expressionLatex: "y = x\\tan\\theta - \\dfrac{gx^2}{2u^2\\cos^2\\theta}",
          label: "Equation of trajectory",
          derivedFrom: "Eliminate t between x = u·cosθ·t and y = u·sinθ·t − ½gt²",
          derivation: {
            startsFrom: "x = (u cosθ)t and y = (u sinθ)t − ½gt²",
            steps: [
              { statement: "Solve the x-equation for t", expression: "t = x / (u cosθ)" },
              { statement: "Substitute into the y-equation", expression: "y = x tanθ − gx²/(2u²cos²θ)" },
              { statement: "This is of the form y = Ax − Bx², a parabola" },
            ],
          },
          variables: [
            { symbol: "y", name: "height at horizontal distance x", unit: "m", dimension: "[L]" },
            { symbol: "x", name: "horizontal distance", unit: "m", dimension: "[L]" },
          ],
          conditions: ["No air resistance"],
          commonMistakes: [
            "Alternate form y = x·tanθ(1 − x/R) is faster when range R is known",
          ],
          conceptLink: {
            chapterSlug: "kinematics",
            sectionHeading: "6. Projectile Motion",
            concept: "parabolic trajectory",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "high",
          examStats: { jeeMain: 7, jeeAdvanced: 5, neet: 6 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["trajectory", "parabola", "equation of path"],
        },
        {
          id: "kin-horizontal-projectile-time",
          expression: "t = √(2h/g)",
          expressionLatex: "t = \\sqrt{\\dfrac{2h}{g}}",
          label: "Fall time — horizontal projectile from height h",
          derivedFrom: "Vertical motion from rest: h = ½gt²",
          variables: [
            { symbol: "t", name: "time to reach ground", unit: "s", dimension: "[T]" },
            { symbol: "h", name: "initial height", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Launched horizontally (uᵧ = 0)", "No air resistance"],
          commonMistakes: [
            "Fall time is independent of the horizontal launch speed — a dropped ball and a horizontally-thrown ball land together",
          ],
          conceptLink: {
            chapterSlug: "kinematics",
            sectionHeading: "6. Projectile Motion",
            concept: "horizontal projectile",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 6, neet: 10, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["horizontal projectile", "fall time", "root 2h by g"],
        },
      ],
      importantObservations: [
        "At maximum height, velocity is purely horizontal: v = u·cosθ (never zero unless θ = 90°)",
        "Kinetic energy at top = (initial KE)·cos²θ — a favourite one-liner in NEET",
      ],
      examNotes:
        "JEE Advanced frequently launches projectiles from moving platforms or inclines — the level-ground formulas above then need re-derivation from components.",
    },

    // ── 5. Relative Motion ───────────────────────────────────────
    {
      id: "kin-relative-motion",
      title: "Relative Motion",
      intro:
        "Velocity of A as seen from B. One vector subtraction solves rain-man, river-boat, and chase problems.",
      formulas: [
        {
          id: "kin-relative-velocity",
          expression: "v(AB) = v(A) − v(B)",
          expressionLatex: "\\vec{v}_{AB} = \\vec{v}_A - \\vec{v}_B",
          label: "Relative velocity of A with respect to B",
          variables: [
            { symbol: "v(AB)", name: "velocity of A relative to B", unit: "m/s", dimension: "[LT⁻¹]" },
            { symbol: "v(A)", name: "velocity of A (ground frame)", unit: "m/s", dimension: "[LT⁻¹]" },
            { symbol: "v(B)", name: "velocity of B (ground frame)", unit: "m/s", dimension: "[LT⁻¹]" },
          ],
          commonMistakes: [
            "This is a VECTOR subtraction — for opposite directions magnitudes add, for same direction they subtract",
          ],
          usedIn: ["laws-of-motion", "centre-of-mass-and-collisions"],
          conceptLink: {
            chapterSlug: "kinematics",
            sectionHeading: "7. Relative Motion",
            concept: "relative velocity",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet"],
          frequency: "very-high",
          examStats: { jeeMain: 10, jeeAdvanced: 6, neet: 8, mhtCet: 6 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["relative velocity", "vA minus vB", "rain man", "river boat"],
        },
        {
          id: "kin-river-shortest-path",
          expression: "sin α = vᵣ / vᵇ  (upstream tilt for straight crossing)",
          label: "River crossing — shortest path condition",
          derivedFrom: "Boat's upstream velocity component must cancel the river flow",
          variables: [
            { symbol: "α", name: "angle of boat heading upstream from the perpendicular", unit: "rad (or °)", dimension: "[M⁰L⁰T⁰]" },
            { symbol: "vᵣ", name: "river flow speed", unit: "m/s", dimension: "[LT⁻¹]" },
            { symbol: "vᵇ", name: "boat speed in still water", unit: "m/s", dimension: "[LT⁻¹]" },
          ],
          conditions: ["Only possible when vᵇ > vᵣ"],
          commonMistakes: [
            "Shortest PATH needs the upstream tilt; shortest TIME needs heading straight across (perpendicular) — students swap these constantly",
          ],
          conceptLink: {
            chapterSlug: "kinematics",
            sectionHeading: "7. Relative Motion",
            concept: "river boat problems",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "high",
          examStats: { jeeMain: 5, jeeAdvanced: 3, neet: 6 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["river boat", "shortest path", "shortest time", "crossing river"],
        },
      ],
      importantObservations: [
        "Rain-man problems: tanθ of the tilted umbrella comes from the vector triangle of the rain velocity and the man's velocity",
      ],
    },

    // ── 6. Graphical Analysis ────────────────────────────────────
    {
      id: "kin-graphs",
      title: "Graphical Analysis",
      intro:
        "What slopes and areas mean on each graph — JEE Main's favourite way to disguise simple kinematics.",
      formulas: [
        {
          id: "kin-graph-xt-slope",
          expression: "slope of x–t graph = velocity",
          label: "Position–time graph slope",
          variables: [
            { symbol: "x", name: "position", unit: "m", dimension: "[L]" },
            { symbol: "t", name: "time", unit: "s", dimension: "[T]" },
          ],
          conceptLink: {
            chapterSlug: "kinematics",
            sectionHeading: "8. Graphs of Motion",
            concept: "graphical interpretation of motion",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, neet: 11, mhtCet: 8 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["position time graph", "slope velocity"],
        },
        {
          id: "kin-graph-vt-slope-area",
          expression: "slope of v–t = acceleration;  area under v–t = displacement",
          label: "Velocity–time graph: slope and area",
          variables: [
            { symbol: "v", name: "velocity", unit: "m/s", dimension: "[LT⁻¹]" },
            { symbol: "t", name: "time", unit: "s", dimension: "[T]" },
          ],
          commonMistakes: [
            "Area BELOW the time axis is negative displacement; take |areas| and add for total distance",
          ],
          conceptLink: {
            chapterSlug: "kinematics",
            sectionHeading: "8. Graphs of Motion",
            concept: "velocity-time graph analysis",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 11, jeeAdvanced: 4, neet: 13, mhtCet: 9 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["velocity time graph", "area displacement", "slope acceleration"],
        },
      ],
      importantObservations: [
        "An x–t graph can never be a vertical line or double back — that would mean two positions at one time",
        "Uniform acceleration ⇒ straight-line v–t graph and parabolic x–t graph",
      ],
      examNotes:
        "When a graph question appears, first write what slope and area mean for THAT graph — half the question solves itself.",
    },
  ],
};
