import type { ChapterFormulaSheet } from "./types";

export const magnetismAndMatterFormulaSheet: ChapterFormulaSheet = {
  chapterSlug: "magnetism-and-matter",
  chapterName: "Magnetism & Matter",
  className: "12",
  version: "1.0.0",
  lastUpdated: "2026-07-05",
  examCoverage: ["jee-main", "neet", "mht-cet", "boards"],
  quickRevisionIds: [
    "mm-bar-magnet-field",
    "mm-magnet-torque",
    "mm-magnetic-intensity",
    "mm-susceptibility",
    "mm-magnet-oscillation",
  ],
  topicGroups: [
    {
      id: "mm-bar-magnet",
      title: "Bar Magnet as a Dipole",
      intro:
        "A bar magnet is a magnetic dipole — every electrostatic dipole result carries over with p → m and 1/4πε₀ → μ₀/4π.",
      formulas: [
        {
          id: "mm-bar-magnet-field",
          expression: "Axial: B = (μ₀/4π) 2m/r³;   Equatorial: B = (μ₀/4π) m/r³",
          expressionLatex: "B_{axial} = \\dfrac{\\mu_0}{4\\pi}\\dfrac{2m}{r^3}",
          label: "Field of a bar magnet (short dipole)",
          variables: [
            { symbol: "m", name: "magnetic dipole moment", unit: "A·m²", dimension: "[AL²]" },
            { symbol: "r", name: "distance from the magnet's centre", unit: "m", dimension: "[L]" },
            { symbol: "μ₀", name: "permeability of free space", unit: "T·m/A", dimension: "[MLT⁻²A⁻²]" },
          ],
          conditions: ["Short-dipole approximation r ≫ magnet length", "Axial field is twice the equatorial at equal distance"],
          commonMistakes: [
            "Direct analogy to the electric dipole: swap p → m and 1/4πε₀ → μ₀/4π and the formulas match exactly",
          ],
          usedIn: ["electric-charges-and-fields"],
          conceptLink: {
            chapterSlug: "magnetism-and-matter",
            sectionHeading: "1. Bar Magnet",
            concept: "field of a bar magnet",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 5, neet: 9, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["bar magnet field", "axial equatorial magnet", "2m by r cubed"],
        },
        {
          id: "mm-magnet-torque",
          expression: "τ = mB sinθ;   U = −mB cosθ",
          expressionLatex: "\\vec{\\tau} = \\vec{m}\\times\\vec{B},\\quad U = -\\vec{m}\\cdot\\vec{B}",
          label: "Torque and energy of a magnet in a field",
          variables: [
            { symbol: "θ", name: "angle between m and B", unit: "rad (or °)", dimension: "[M⁰L⁰T⁰]" },
            { symbol: "B", name: "external magnetic field", unit: "T", dimension: "[MT⁻²A⁻¹]" },
          ],
          conditions: ["Stable equilibrium at θ = 0 (aligned with B), unstable at θ = 180°"],
          commonMistakes: [
            "Work to rotate from θ₁ to θ₂: W = mB(cosθ₁ − cosθ₂); flipping a magnet end-for-end costs 2mB",
          ],
          usedIn: ["moving-charges-and-magnetism", "electric-charges-and-fields"],
          conceptLink: {
            chapterSlug: "magnetism-and-matter",
            sectionHeading: "1. Bar Magnet",
            concept: "magnet in a uniform field",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 5, neet: 9, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["magnet torque", "mB sin theta", "magnet potential energy"],
        },
        {
          id: "mm-magnet-oscillation",
          expression: "T = 2π √(I/(mB))",
          expressionLatex: "T = 2\\pi\\sqrt{\\dfrac{I}{mB}}",
          label: "Oscillation of a magnet in a field",
          derivedFrom: "Restoring torque −mB sinθ ≈ −mBθ for small angles (angular SHM)",
          variables: [
            { symbol: "I", name: "moment of inertia of the magnet", unit: "kg·m²", dimension: "[ML²]" },
            { symbol: "m", name: "magnetic moment", unit: "A·m²", dimension: "[AL²]" },
            { symbol: "B", name: "field the magnet oscillates in", unit: "T", dimension: "[MT⁻²A⁻¹]" },
          ],
          conditions: ["Small-angle angular SHM — the magnetic analogue of a pendulum", "Used in vibration magnetometers to compare field strengths"],
          usedIn: ["oscillations"],
          conceptLink: {
            chapterSlug: "magnetism-and-matter",
            sectionHeading: "1. Bar Magnet",
            concept: "oscillating magnet",
          },
          examTags: ["jee-main", "neet", "mht-cet"],
          frequency: "medium",
          examStats: { jeeMain: 4, neet: 7, mhtCet: 5 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["magnet oscillation", "2 pi root I by mB", "vibration magnetometer"],
        },
      ],
      importantObservations: [
        "Isolated magnetic poles (monopoles) have never been found — cutting a magnet just makes two smaller dipoles",
        "Gauss's law for magnetism: ∮B·dA = 0 always — net magnetic flux through any closed surface is zero",
      ],
    },
    {
      id: "mm-materials",
      title: "Magnetic Materials & Properties",
      intro:
        "Materials respond to a field through their susceptibility. The sign and size of χ sort every substance into dia-, para-, or ferromagnetic.",
      formulas: [
        {
          id: "mm-magnetic-intensity",
          expression: "B = μ₀(H + M);   M = χH;   μ(r) = 1 + χ",
          expressionLatex: "\\vec{B} = \\mu_0(\\vec{H} + \\vec{M})",
          label: "Magnetising field, magnetisation & permeability",
          variables: [
            { symbol: "H", name: "magnetising field intensity", unit: "A/m", dimension: "[L⁻¹A]" },
            { symbol: "M", name: "magnetisation (dipole moment per volume)", unit: "A/m", dimension: "[L⁻¹A]" },
            { symbol: "χ", name: "magnetic susceptibility", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
            { symbol: "μ(r)", name: "relative permeability", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["B is the net field; H is the applied/free-current part; M is the material's response"],
          conceptLink: {
            chapterSlug: "magnetism-and-matter",
            sectionHeading: "2. Magnetisation and Intensity",
            concept: "magnetising field and magnetisation",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 5, neet: 9, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["B mu0 H plus M", "magnetisation", "permeability susceptibility"],
        },
        {
          id: "mm-susceptibility",
          expression: "Dia: χ small negative;  Para: χ small positive, χ ∝ 1/T;  Ferro: χ large positive",
          expressionLatex: "\\chi_{para} \\propto \\dfrac{1}{T}\\ \\text{(Curie law)}",
          label: "Classification of magnetic materials",
          variables: [
            { symbol: "χ", name: "magnetic susceptibility", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
            { symbol: "T", name: "absolute temperature", unit: "K", dimension: "[Θ]" },
          ],
          conditions: [
            "Diamagnetic: χ ≈ −10⁻⁵, repelled, moves to weak-field region (e.g. bismuth, water)",
            "Paramagnetic: χ small +, Curie law χ = C/T (e.g. aluminium)",
            "Ferromagnetic: χ ≫ 1, becomes paramagnetic above the Curie temperature",
          ],
          commonMistakes: [
            "Diamagnetism is the only material property INDEPENDENT of temperature; para- and ferro- weaken as T rises",
          ],
          conceptLink: {
            chapterSlug: "magnetism-and-matter",
            sectionHeading: "3. Magnetic Materials",
            concept: "dia para ferromagnetism",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 6, neet: 12, mhtCet: 9 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["diamagnetic paramagnetic ferromagnetic", "curie law", "susceptibility"],
        },
      ],
      importantObservations: [
        "Curie temperature: above it a ferromagnet loses spontaneous magnetisation and turns paramagnetic (iron ≈ 1043 K)",
        "Hysteresis loop area = energy lost per cycle; soft iron (thin loop) for transformers, steel (fat loop) for permanent magnets",
      ],
      examNotes:
        "NEET and Boards lean heavily on the dia/para/ferro classification and Curie law; JEE Main occasionally computes with B = μ₀(H + M). Note: this chapter is not in the JEE Advanced syllabus.",
    },
  ],
};
