import type { ChapterFormulaSheet } from "./types";

export const magnetismAndMatterFormulaSheet: ChapterFormulaSheet = {
  chapterSlug: "magnetism-and-matter",
  chapterName: "Magnetism & Matter",
  className: "12",
  version: "1.0.0",
  lastUpdated: "2026-07-08",
  examCoverage: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
  quickRevisionIds: [
    "mm-magnetic-moment-bar-magnet",
    "mm-field-axial-bar-magnet",
    "mm-field-equatorial-bar-magnet",
    "mm-torque-dipole-field",
    "mm-tangent-law",
    "mm-susceptibility-permeability",
    "mm-curies-law",
  ],
  topicGroups: [
    {
      id: "mm-bar-magnet-basics",
      title: "Bar Magnet as a Magnetic Dipole",
      intro:
        "A bar magnet behaves like a pair of equal and opposite magnetic poles — mathematically identical in structure to the electric dipole, just with pole strength replacing charge.",
      formulas: [
        {
          id: "mm-magnetic-moment-bar-magnet",
          expression: "m = q(m) × (2l)",
          expressionLatex: "m = q_m (2l)",
          label: "Magnetic dipole moment of a bar magnet",
          variables: [
            { symbol: "q(m)", name: "pole strength", unit: "A·m", dimension: "[AL]" },
            { symbol: "2l", name: "magnetic length (distance between the poles)", unit: "m", dimension: "[L]" },
            { symbol: "m", name: "magnetic dipole moment, points from S to N pole inside the magnet", unit: "A·m²", dimension: "[AL²]" },
          ],
          conditions: ["Magnetic length is slightly less than the geometric length of the bar (≈ 5/6 of it, by convention)"],
          conceptLink: {
            chapterSlug: "magnetism-and-matter",
            sectionHeading: "1. The Bar Magnet: Pole Strength and Magnetic Moment",
            concept: "magnetic moment of a bar magnet",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 7, neet: 10, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["magnetic moment bar magnet", "m equals qm times 2l"],
        },
        {
          id: "mm-field-axial-bar-magnet",
          expression: "B(axial) = μ₀ 2m / (4πd³)  (short magnet, d ≫ l)",
          expressionLatex: "B_{axial} = \\dfrac{\\mu_0}{4\\pi}\\dfrac{2m}{d^3}",
          label: "Magnetic field on the axial line of a bar magnet",
          derivedFrom: "Superposition of fields from the two poles, exactly analogous to the electric dipole axial field derivation",
          variables: [
            { symbol: "d", name: "distance from the centre of the magnet along its axis", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Valid only in the short-magnet (far-field) approximation d ≫ l", "Direction: along m"],
          commonMistakes: [
            "Structurally identical to E(axial) = 2kp/r³ for electric dipoles — reuse the pattern instead of re-deriving from scratch",
          ],
          usedIn: ["electric-charges-and-fields"],
          conceptLink: {
            chapterSlug: "magnetism-and-matter",
            sectionHeading: "3. Magnetic Field Due to a Bar Magnet — Axial and Equatorial Points",
            concept: "axial field of a bar magnet",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 11, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["bar magnet axial field", "mu0 2m by 4 pi d cubed"],
        },
        {
          id: "mm-field-equatorial-bar-magnet",
          expression: "B(equatorial) = μ₀ m / (4πd³)  (short magnet, d ≫ l)",
          expressionLatex: "B_{eq} = \\dfrac{\\mu_0}{4\\pi}\\dfrac{m}{d^3}",
          label: "Magnetic field on the equatorial line of a bar magnet",
          variables: [
            { symbol: "d", name: "distance from the centre along the perpendicular bisector", unit: "m", dimension: "[L]" },
          ],
          conditions: ["B(axial) = 2 × B(equatorial) at the same distance — same ratio as the electric dipole case", "Direction: antiparallel to m"],
          conceptLink: {
            chapterSlug: "magnetism-and-matter",
            sectionHeading: "3. Magnetic Field Due to a Bar Magnet — Axial and Equatorial Points",
            concept: "equatorial field of a bar magnet",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 7, jeeAdvanced: 4, neet: 10, mhtCet: 6 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["bar magnet equatorial field", "mu0 m by 4 pi d cubed"],
        },
        {
          id: "mm-torque-dipole-field",
          expression: "τ = mB sinθ = m × B",
          expressionLatex: "\\vec{\\tau} = \\vec{m}\\times\\vec{B}",
          label: "Torque on a bar magnet in a uniform magnetic field",
          variables: [
            { symbol: "θ", name: "angle between m and B", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["Zero net force in a uniform field — only torque, same structure as electric and current-loop dipoles"],
          conceptLink: {
            chapterSlug: "magnetism-and-matter",
            sectionHeading: "4. Torque, Potential Energy and Work Done — Dipole in a Uniform Field",
            concept: "torque on a bar magnet",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 7, neet: 9, mhtCet: 6 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["torque bar magnet", "mB sin theta"],
        },
        {
          id: "mm-pe-dipole-field",
          expression: "U = −mB cosθ = −m·B",
          expressionLatex: "U = -\\vec{m}\\cdot\\vec{B}",
          label: "Potential energy of a bar magnet in a magnetic field",
          conditions: ["Minimum (most stable) at θ = 0° when m aligns with B; maximum (unstable) at θ = 180°"],
          variables: [],
          conceptLink: {
            chapterSlug: "magnetism-and-matter",
            sectionHeading: "4. Torque, Potential Energy and Work Done — Dipole in a Uniform Field",
            concept: "potential energy of a bar magnet",
          },
          examTags: ["jee-main", "neet", "mht-cet"],
          frequency: "high",
          examStats: { jeeMain: 5, neet: 7, mhtCet: 5 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["potential energy bar magnet", "minus mB cos theta"],
        },
      ],
    },
    {
      id: "mm-earth-magnetism",
      title: "Earth's Magnetism & Magnetometers",
      intro:
        "The Earth behaves like it has a giant bar magnet tilted from its rotation axis — its field at any point splits into horizontal and vertical components measured by dip and declination.",
      formulas: [
        {
          id: "mm-tangent-law",
          expression: "B = B(H) tanθ",
          expressionLatex: "B = B_H\\tan\\theta",
          label: "Tangent law of magnetism",
          derivedFrom: "Equilibrium of a compass needle under two mutually perpendicular fields: the applied field B and the horizontal component of Earth's field B(H)",
          variables: [
            { symbol: "B(H)", name: "horizontal component of Earth's magnetic field", unit: "T", dimension: "[MT⁻²A⁻¹]" },
            { symbol: "θ", name: "deflection angle of the compass needle from magnetic north", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["Requires the applied field B to be perpendicular to B(H) — the standard tangent galvanometer/deflection magnetometer setup"],
          conceptLink: {
            chapterSlug: "magnetism-and-matter",
            sectionHeading: "8. Tangent Galvanometer",
            concept: "tangent law",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 7, neet: 10, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["tangent law magnetism", "B equals BH tan theta"],
        },
        {
          id: "mm-tangent-galvanometer",
          expression: "I = (2rB(H) / μ₀N) tanθ = K tanθ",
          expressionLatex: "I = \\dfrac{2rB_H}{\\mu_0 N}\\tan\\theta",
          label: "Tangent galvanometer current formula",
          derivedFrom: "Applying the tangent law with the coil's own field at its centre, B = μ₀NI/2r, playing the role of the deflecting field",
          variables: [
            { symbol: "r", name: "radius of the tangent galvanometer coil", unit: "m", dimension: "[L]" },
            { symbol: "K", name: "reduction factor of the galvanometer", unit: "A", dimension: "[A]" },
          ],
          conditions: ["Most sensitive near θ = 45° (where d(tanθ)/dθ is smallest relative rate of change, minimising reading error)"],
          conceptLink: {
            chapterSlug: "magnetism-and-matter",
            sectionHeading: "8. Tangent Galvanometer",
            concept: "tangent galvanometer",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 5, neet: 8, mhtCet: 6 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["tangent galvanometer formula", "reduction factor K tan theta"],
        },
        {
          id: "mm-dip-components",
          expression: "B(H) = B cosδ ;  B(V) = B sinδ ;  tanδ = B(V)/B(H)",
          expressionLatex: "\\tan\\delta = \\dfrac{B_V}{B_H}",
          label: "Angle of dip and Earth's field components",
          variables: [
            { symbol: "B", name: "total magnitude of Earth's magnetic field at a location", unit: "T", dimension: "[MT⁻²A⁻¹]" },
            { symbol: "δ", name: "angle of dip (inclination) from horizontal", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
            { symbol: "B(V)", name: "vertical component of Earth's field", unit: "T", dimension: "[MT⁻²A⁻¹]" },
          ],
          conditions: ["δ = 0° at the magnetic equator (field purely horizontal)", "δ = 90° at the magnetic poles (field purely vertical)"],
          conceptLink: {
            chapterSlug: "magnetism-and-matter",
            sectionHeading: "6. Declination, Dip and the Components of Earth's Magnetic Field",
            concept: "angle of dip and Earth's field components",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 7, neet: 10, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["angle of dip formula", "BH BV tan delta", "earths magnetic field components"],
        },
        {
          id: "mm-apparent-dip",
          expression: "tanδ(apparent) = tanδ / cosα",
          expressionLatex: "\\tan\\delta_{app} = \\dfrac{\\tan\\delta}{\\cos\\alpha}",
          label: "Apparent dip in a plane other than the magnetic meridian",
          variables: [
            { symbol: "α", name: "angle between the vertical plane of observation and the magnetic meridian", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["Apparent dip is always ≥ true dip (equality only when α = 0, i.e. in the magnetic meridian itself)"],
          conceptLink: {
            chapterSlug: "magnetism-and-matter",
            sectionHeading: "7. Apparent Dip",
            concept: "apparent dip",
          },
          examTags: ["jee-main", "neet"],
          frequency: "medium",
          examStats: { jeeMain: 4, neet: 5 },
          difficulty: "hard",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["apparent dip formula", "tan delta apparent by cos alpha"],
        },
        {
          id: "mm-vibration-magnetometer-period",
          expression: "T = 2π √(I / mB)",
          expressionLatex: "T = 2\\pi\\sqrt{\\dfrac{I}{mB}}",
          label: "Time period of oscillation in a vibration (oscillation) magnetometer",
          derivedFrom: "SHM analogy: restoring torque −mBsinθ ≈ −mBθ for small θ, giving angular frequency ω² = mB/I",
          variables: [
            { symbol: "I", name: "moment of inertia of the oscillating magnet about the suspension axis", unit: "kg·m²", dimension: "[ML²]" },
            { symbol: "T", name: "period of oscillation", unit: "s", dimension: "[T]" },
          ],
          conditions: ["Small-angle (SHM) approximation required, same structural form as a torsion pendulum"],
          usedIn: ["oscillations"],
          conceptLink: {
            chapterSlug: "magnetism-and-matter",
            sectionHeading: "9. Vibration (Oscillation) Magnetometer",
            concept: "vibration magnetometer period",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 3, neet: 8, mhtCet: 6 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["vibration magnetometer time period", "2 pi root I by mB"],
        },
        {
          id: "mm-comparing-moments",
          expression: "m₁/m₂ = T₂²/T₁²  (equal field, method of oscillations)",
          expressionLatex: "\\dfrac{m_1}{m_2} = \\dfrac{T_2^2}{T_1^2}",
          label: "Comparing magnetic moments using oscillation periods",
          derivedFrom: "From T = 2π√(I/mB): m ∝ 1/T² at fixed I and B",
          conditions: ["Both magnets must have the same moment of inertia I and be tested in the same field B for a direct ratio comparison"],
          variables: [],
          conceptLink: {
            chapterSlug: "magnetism-and-matter",
            sectionHeading: "10. Comparing Magnetic Moments and Earth's Field Using a Magnetometer",
            concept: "comparing magnetic moments",
          },
          examTags: ["jee-main", "neet", "mht-cet"],
          frequency: "medium",
          examStats: { jeeMain: 4, neet: 6, mhtCet: 4 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["comparing magnetic moments", "m1 by m2 T2 squared T1 squared"],
        },
      ],
      examNotes:
        "Boards frequently ask for the 'method of oscillations combined with deflection' to find m and B(H) simultaneously — know both formulas together, not in isolation.",
    },
    {
      id: "mm-magnetic-materials",
      title: "Magnetic Materials, Susceptibility & Permeability",
      intro:
        "Every material responds to an external field to some degree — the sign and size of that response (susceptibility) classifies it as diamagnetic, paramagnetic, or ferromagnetic.",
      formulas: [
        {
          id: "mm-magnetising-field",
          expression: "B = μ₀(H + M)",
          expressionLatex: "\\vec{B} = \\mu_0(\\vec{H}+\\vec{M})",
          label: "Relation between B, H and M",
          variables: [
            { symbol: "H", name: "magnetising field intensity (from free/external currents alone)", unit: "A/m", dimension: "[AL⁻¹]" },
            { symbol: "M", name: "intensity of magnetisation (induced by the material)", unit: "A/m", dimension: "[AL⁻¹]" },
            { symbol: "B", name: "total (net) magnetic field inside the material", unit: "T", dimension: "[MT⁻²A⁻¹]" },
          ],
          conditions: ["H depends only on external (free) currents; M depends on the material's response"],
          conceptLink: {
            chapterSlug: "magnetism-and-matter",
            sectionHeading: "12. Magnetising Field, Intensity of Magnetisation and Susceptibility",
            concept: "relation between B, H and M",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 3, neet: 7, mhtCet: 5 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["B H M relation", "B equals mu0 H plus M"],
        },
        {
          id: "mm-susceptibility-permeability",
          expression: "χ = M/H ;  μ(r) = 1 + χ ;  μ = μ₀μ(r)",
          expressionLatex: "\\chi = \\dfrac{M}{H},\\quad \\mu_r = 1+\\chi",
          label: "Magnetic susceptibility and relative permeability",
          variables: [
            { symbol: "χ", name: "magnetic susceptibility", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
            { symbol: "μ(r)", name: "relative permeability", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
            { symbol: "μ", name: "absolute permeability of the material", unit: "T·m/A", dimension: "[MLT⁻²A⁻²]" },
          ],
          conditions: [
            "Diamagnetic: χ small and negative (μ(r) slightly < 1)",
            "Paramagnetic: χ small and positive (μ(r) slightly > 1)",
            "Ferromagnetic: χ very large and positive (μ(r) ≫ 1)",
          ],
          commonMistakes: [
            "Diamagnetism is present in ALL materials but is masked by stronger para/ferromagnetic effects when those are present",
          ],
          conceptLink: {
            chapterSlug: "magnetism-and-matter",
            sectionHeading: "13. Magnetic Permeability and the Relation Between μ and χ",
            concept: "susceptibility and permeability",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 7, jeeAdvanced: 4, neet: 10, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["susceptibility permeability relation", "mu r equals 1 plus chi"],
        },
        {
          id: "mm-curies-law",
          expression: "χ = C / T  (Curie's law, paramagnetic materials)",
          expressionLatex: "\\chi = \\dfrac{C}{T}",
          label: "Curie's law for paramagnetic materials",
          derivedFrom: "Increasing thermal agitation randomises atomic dipole alignment, weakening net magnetisation as T rises",
          variables: [
            { symbol: "C", name: "Curie constant (material-specific)", unit: "K", dimension: "[Θ]" },
            { symbol: "T", name: "absolute temperature", unit: "K", dimension: "[Θ]" },
          ],
          conditions: ["Valid only for paramagnetic materials; ferromagnetics follow the Curie–Weiss law above their Curie temperature instead"],
          commonMistakes: [
            "Above the Curie temperature, a ferromagnetic material turns paramagnetic and follows χ = C/(T − T(c)), the Curie–Weiss law, not plain Curie's law",
          ],
          conceptLink: {
            chapterSlug: "magnetism-and-matter",
            sectionHeading: "15. Curie's Law, Curie–Weiss Law and Magnetic Hysteresis",
            concept: "Curie's law",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 6, neet: 8, mhtCet: 5 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["curies law", "chi equals C by T", "paramagnetic temperature dependence"],
        },
        {
          id: "mm-curie-weiss-law",
          expression: "χ = C / (T − T(c))  (T > T(c), Curie–Weiss law)",
          expressionLatex: "\\chi = \\dfrac{C}{T - T_c}",
          label: "Curie–Weiss law for ferromagnetic materials above the Curie point",
          variables: [
            { symbol: "T(c)", name: "Curie temperature — above this, ferromagnetic order breaks down", unit: "K", dimension: "[Θ]" },
          ],
          conditions: ["Applies only for T > T(c); below T(c) the material remains spontaneously ferromagnetic and this formula does not apply"],
          conceptLink: {
            chapterSlug: "magnetism-and-matter",
            sectionHeading: "15. Curie's Law, Curie–Weiss Law and Magnetic Hysteresis",
            concept: "Curie–Weiss law",
          },
          examTags: ["jee-advanced", "neet"],
          frequency: "medium",
          examStats: { jeeAdvanced: 2, neet: 4 },
          difficulty: "hard",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["curie weiss law", "ferromagnetic above curie temperature"],
        },
      ],
      importantObservations: [
        "Soft magnetic materials (e.g. soft iron) have a thin hysteresis loop — low retentivity/coercivity, ideal for electromagnets and transformer cores",
        "Hard magnetic materials (e.g. steel/alnico) have a fat hysteresis loop — high retentivity/coercivity, ideal for permanent magnets",
      ],
      examNotes:
        "NEET frequently tests qualitative classification (dia/para/ferro) with real-world examples — pair the formula knowledge with example recall (bismuth/copper = dia; aluminium/platinum = para; iron/cobalt/nickel = ferro).",
    },
  ],
};
