import type { ChapterFormulaSheet } from "./types";

export const solidsFormulaSheet: ChapterFormulaSheet = {
  chapterSlug: "mechanical-properties-of-solids",
  chapterName: "Mechanical Properties of Solids",
  className: "11",
  version: "1.0.0",
  lastUpdated: "2026-07-03",
  examCoverage: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
  quickRevisionIds: [
    "sol-stress",
    "sol-strain",
    "sol-youngs-modulus",
    "sol-elastic-pe-density",
    "sol-wire-elongation",
  ],
  topicGroups: [
    {
      id: "sol-stress-strain",
      title: "Stress & Strain",
      intro:
        "Stress is the internal restoring force per unit area; strain is the fractional deformation. Their ratio — within the elastic limit — defines the material.",
      formulas: [
        {
          id: "sol-stress",
          expression: "Stress = F / A",
          expressionLatex: "\\sigma = \\dfrac{F}{A}",
          label: "Stress",
          variables: [
            { symbol: "F", name: "internal restoring force (equals applied force in equilibrium)", unit: "N", dimension: "[MLT⁻²]" },
            { symbol: "A", name: "cross-sectional area", unit: "m²", dimension: "[L²]" },
          ],
          conditions: ["Unit N/m² (pascal) — same unit and dimensions as pressure, but stress is not a scalar like pressure"],
          commonMistakes: [
            "Longitudinal (tensile/compressive), shear (tangential) and volumetric stress are three different animals — identify which before picking a modulus",
          ],
          conceptLink: {
            chapterSlug: "mechanical-properties-of-solids",
            sectionHeading: "1. Stress and Strain",
            concept: "stress",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 6, neet: 10, mhtCet: 8 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["stress", "force per area", "pascal"],
        },
        {
          id: "sol-strain",
          expression: "Strain = ΔL / L  (longitudinal);  ΔV/V (volumetric);  tanφ ≈ φ (shear)",
          expressionLatex: "\\varepsilon = \\dfrac{\\Delta L}{L}",
          label: "Strain (three types)",
          variables: [
            { symbol: "ΔL", name: "change in length", unit: "m", dimension: "[L]" },
            { symbol: "L", name: "original length", unit: "m", dimension: "[L]" },
            { symbol: "φ", name: "shear angle", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["Dimensionless — it is a ratio"],
          conceptLink: {
            chapterSlug: "mechanical-properties-of-solids",
            sectionHeading: "1. Stress and Strain",
            concept: "strain",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 5, neet: 9, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["strain", "delta L by L", "shear strain"],
        },
      ],
      importantObservations: [
        "Hooke's law (stress ∝ strain) holds only up to the proportional limit — the stress-strain curve then bends through elastic limit, yield point, and fracture",
        "Elastomers (rubber) stretch enormously WITHOUT obeying Hooke's law and without permanent set",
      ],
    },
    {
      id: "sol-moduli",
      title: "Elastic Moduli",
      intro:
        "Three moduli for three deformation modes: Young's for stretching, bulk for squeezing, shear for twisting. All share the unit of stress.",
      formulas: [
        {
          id: "sol-youngs-modulus",
          expression: "Y = (F/A) / (ΔL/L) = FL / (A ΔL)",
          expressionLatex: "Y = \\dfrac{FL}{A\\,\\Delta L}",
          label: "Young's modulus",
          variables: [
            { symbol: "Y", name: "Young's modulus of the material", unit: "N/m²", dimension: "[ML⁻¹T⁻²]", notes: "steel ≈ 2 × 10¹¹ N/m² — property of MATERIAL, not of the wire" },
          ],
          conditions: ["Within the proportional limit", "Solids only"],
          commonMistakes: [
            "A thicker or longer wire has the SAME Y — geometry changes ΔL, never Y",
            "Y(steel) > Y(copper) > Y(rubber): larger Y means HARDER to stretch, so steel is more elastic than rubber in physics language",
          ],
          usedIn: ["oscillations", "waves"],
          conceptLink: {
            chapterSlug: "mechanical-properties-of-solids",
            sectionHeading: "2. Elastic Moduli",
            concept: "Young's modulus",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 3, neet: 13, mhtCet: 10 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["youngs modulus", "FL by A delta L"],
        },
        {
          id: "sol-wire-elongation",
          expression: "ΔL = FL / (AY) = MgL / (πr²Y)",
          expressionLatex: "\\Delta L = \\dfrac{FL}{AY}",
          label: "Elongation of a loaded wire",
          derivedFrom: "Rearranging the Young's modulus definition",
          variables: [
            { symbol: "ΔL", name: "extension", unit: "m", dimension: "[L]" },
            { symbol: "r", name: "wire radius", unit: "m", dimension: "[L]" },
          ],
          conditions: [
            "Wire stretching under its OWN weight: ΔL = ρgL²/2Y (half the naive value, because tension varies along the wire)",
          ],
          commonMistakes: [
            "Same load, wire of double radius → ΔL becomes ¼ (A ∝ r²) — ratio questions live here",
          ],
          conceptLink: {
            chapterSlug: "mechanical-properties-of-solids",
            sectionHeading: "2. Elastic Moduli",
            concept: "elongation of a wire",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 12, mhtCet: 9 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["elongation", "FL by AY", "wire own weight"],
        },
        {
          id: "sol-bulk-modulus",
          expression: "B = −ΔP / (ΔV/V);   compressibility k = 1/B",
          expressionLatex: "B = -\\dfrac{\\Delta P}{\\Delta V / V}",
          label: "Bulk modulus & compressibility",
          variables: [
            { symbol: "B", name: "bulk modulus", unit: "N/m²", dimension: "[ML⁻¹T⁻²]" },
            { symbol: "ΔP", name: "change in pressure", unit: "N/m²", dimension: "[ML⁻¹T⁻²]" },
            { symbol: "ΔV/V", name: "fractional volume change", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["Minus sign keeps B positive (pressure up, volume down)", "Defined for solids, liquids AND gases"],
          commonMistakes: [
            "For gases B depends on the process: isothermal B = P, adiabatic B = γP",
          ],
          usedIn: ["waves", "mechanical-properties-of-fluids"],
          conceptLink: {
            chapterSlug: "mechanical-properties-of-solids",
            sectionHeading: "2. Elastic Moduli",
            concept: "bulk modulus",
          },
          examTags: ["jee-main", "neet", "mht-cet"],
          frequency: "high",
          examStats: { jeeMain: 6, neet: 9, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["bulk modulus", "compressibility", "gamma P"],
        },
        {
          id: "sol-shear-modulus",
          expression: "η = (F/A) / φ",
          expressionLatex: "\\eta = \\dfrac{F/A}{\\varphi}",
          label: "Shear modulus (modulus of rigidity)",
          variables: [
            { symbol: "η", name: "shear modulus", unit: "N/m²", dimension: "[ML⁻¹T⁻²]" },
            { symbol: "φ", name: "shear angle", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["Solids only — fluids cannot sustain shear stress at rest (that is what makes them fluids)"],
          conceptLink: {
            chapterSlug: "mechanical-properties-of-solids",
            sectionHeading: "2. Elastic Moduli",
            concept: "shear modulus",
          },
          examTags: ["jee-main", "neet", "mht-cet"],
          frequency: "medium",
          examStats: { jeeMain: 4, neet: 6, mhtCet: 5 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["shear modulus", "modulus of rigidity"],
        },
        {
          id: "sol-poisson-ratio",
          expression: "σ = − (lateral strain) / (longitudinal strain)",
          expressionLatex: "\\sigma = -\\dfrac{\\Delta d / d}{\\Delta L / L}",
          label: "Poisson's ratio",
          variables: [
            { symbol: "σ", name: "Poisson's ratio", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]", notes: "theoretical range −1 to 0.5; most metals ≈ 0.3" },
          ],
          conditions: ["σ = 0.5 means volume stays constant on stretching (ideal rubber)"],
          conceptLink: {
            chapterSlug: "mechanical-properties-of-solids",
            sectionHeading: "2. Elastic Moduli",
            concept: "Poisson's ratio",
          },
          examTags: ["jee-main", "neet"],
          frequency: "medium",
          examStats: { jeeMain: 4, neet: 5 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["poisson ratio", "lateral strain"],
        },
      ],
      importantObservations: [
        "Y, B and η exist only within elastic behaviour; beyond the yield point the material flows plastically and no modulus applies",
      ],
    },
    {
      id: "sol-elastic-energy",
      title: "Elastic Potential Energy",
      intro:
        "Stretching a wire stores energy exactly like compressing a spring — the wire IS a very stiff spring with k = YA/L.",
      formulas: [
        {
          id: "sol-elastic-pe-density",
          expression: "u = ½ × stress × strain = ½ Y (strain)²",
          expressionLatex: "u = \\tfrac{1}{2}\\,\\sigma\\varepsilon",
          label: "Elastic energy density",
          derivedFrom: "Work done per unit volume = area under the stress-strain curve",
          derivation: {
            startsFrom: "Work to stretch = area under the F–ΔL graph (a triangle in the linear region)",
            steps: [
              { statement: "Total energy stored", expression: "U = ½ F ΔL" },
              { statement: "Divide by volume AL", expression: "u = ½ (F/A)(ΔL/L)" },
              { statement: "Recognise stress and strain", expression: "u = ½ × stress × strain" },
            ],
          },
          variables: [
            { symbol: "u", name: "energy stored per unit volume", unit: "J/m³", dimension: "[ML⁻¹T⁻²]" },
          ],
          commonMistakes: [
            "The factor ½ exists because force GROWS from zero — using full F × ΔL doubles the answer",
          ],
          usedIn: ["work-energy-and-power"],
          conceptLink: {
            chapterSlug: "mechanical-properties-of-solids",
            sectionHeading: "3. Elastic Potential Energy",
            concept: "elastic energy density",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 7, neet: 11, mhtCet: 8 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["energy density", "half stress strain"],
        },
        {
          id: "sol-wire-spring-constant",
          expression: "k(wire) = YA / L",
          expressionLatex: "k = \\dfrac{YA}{L}",
          label: "Effective spring constant of a wire",
          derivedFrom: "Comparing F = (YA/L)ΔL with F = kx",
          variables: [
            { symbol: "k(wire)", name: "equivalent spring constant", unit: "N/m", dimension: "[MT⁻²]" },
          ],
          conditions: ["Wires in series/parallel combine exactly like springs"],
          usedIn: ["oscillations"],
          conceptLink: {
            chapterSlug: "mechanical-properties-of-solids",
            sectionHeading: "3. Elastic Potential Energy",
            concept: "wire as a spring",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "medium",
          examStats: { jeeMain: 5, jeeAdvanced: 3, neet: 5 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["YA by L", "wire spring constant"],
        },
      ],
      importantObservations: [
        "Breaking force depends on AREA only, not length — a longer rope is not weaker; breaking STRESS is the material property",
      ],
      examNotes:
        "NEET keeps to direct modulus and energy-density substitutions; JEE builds composite rods and wire-block oscillation systems from k = YA/L.",
    },
  ],
};
