import type { ChapterFormulaSheet } from "./types";

export const fluidsFormulaSheet: ChapterFormulaSheet = {
  chapterSlug: "mechanical-properties-of-fluids",
  chapterName: "Mechanical Properties of Fluids",
  className: "11",
  version: "1.0.0",
  lastUpdated: "2026-07-03",
  examCoverage: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
  quickRevisionIds: [
    "flu-pressure-depth",
    "flu-archimedes",
    "flu-continuity",
    "flu-bernoulli",
    "flu-stokes-terminal",
    "flu-capillary-rise",
  ],
  topicGroups: [
    {
      id: "flu-pressure",
      title: "Fluid Pressure & Pascal's Law",
      intro:
        "Pressure in a static fluid depends on depth alone — not on the shape or width of the container.",
      formulas: [
        {
          id: "flu-pressure-depth",
          expression: "P = P₀ + ρgh",
          expressionLatex: "P = P_0 + \\rho g h",
          label: "Pressure at depth h",
          variables: [
            { symbol: "P₀", name: "pressure at the surface (usually atmospheric)", unit: "N/m²", dimension: "[ML⁻¹T⁻²]", notes: "1 atm = 1.013 × 10⁵ Pa = 760 mm of Hg" },
            { symbol: "ρ", name: "density of the fluid", unit: "kg/m³", dimension: "[ML⁻³]" },
            { symbol: "h", name: "depth below the surface", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Static fluid, uniform density", "Points at the same depth in a CONNECTED fluid have equal pressure"],
          commonMistakes: [
            "In an accelerating container the free surface tilts with tanθ = a/g and pressure varies along the horizontal too",
          ],
          conceptLink: {
            chapterSlug: "mechanical-properties-of-fluids",
            sectionHeading: "1. Fluid Pressure",
            concept: "pressure variation with depth",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 12, mhtCet: 9 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["rho g h", "pressure depth", "hydrostatic"],
        },
        {
          id: "flu-pascal-hydraulic",
          expression: "F₂ = F₁ (A₂/A₁)",
          expressionLatex: "F_2 = F_1\\dfrac{A_2}{A_1}",
          label: "Hydraulic lift (Pascal's law)",
          derivedFrom: "Equal pressure transmitted: F₁/A₁ = F₂/A₂",
          variables: [
            { symbol: "F₁, F₂", name: "forces on the small and large pistons", unit: "N", dimension: "[MLT⁻²]" },
            { symbol: "A₁, A₂", name: "piston areas", unit: "m²", dimension: "[L²]" },
          ],
          conditions: ["Force multiplies, but work does not — the small piston moves proportionally farther"],
          conceptLink: {
            chapterSlug: "mechanical-properties-of-fluids",
            sectionHeading: "1. Fluid Pressure",
            concept: "Pascal's law and hydraulic machines",
          },
          examTags: ["neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { neet: 8, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["hydraulic lift", "pascal law", "force multiplication"],
        },
      ],
      importantObservations: [
        "A barometer reads absolute pressure; a manometer reads gauge pressure (difference from atmospheric)",
      ],
    },
    {
      id: "flu-buoyancy",
      title: "Buoyancy & Archimedes' Principle",
      intro:
        "A submerged body is pushed up by the weight of the fluid it displaces — nothing more, nothing less.",
      formulas: [
        {
          id: "flu-archimedes",
          expression: "F(B) = ρ(fluid) V(sub) g",
          expressionLatex: "F_B = \\rho_{fluid}\\,V_{sub}\\,g",
          label: "Buoyant force (Archimedes' principle)",
          variables: [
            { symbol: "F(B)", name: "buoyant force (upward)", unit: "N", dimension: "[MLT⁻²]" },
            { symbol: "V(sub)", name: "SUBMERGED volume of the body", unit: "m³", dimension: "[L³]" },
            { symbol: "ρ(fluid)", name: "density of the fluid", unit: "kg/m³", dimension: "[ML⁻³]" },
          ],
          conditions: [
            "Floating: weight = buoyant force, so fraction submerged = ρ(body)/ρ(fluid)",
            "Apparent weight when fully submerged = W(1 − ρ(fluid)/ρ(body))",
          ],
          commonMistakes: [
            "Ice melting in a glass of water does NOT change the level — the melt exactly fills the displaced volume",
            "Buoyant force acts at the centre of the DISPLACED fluid (centre of buoyancy), not the body's COM",
          ],
          conceptLink: {
            chapterSlug: "mechanical-properties-of-fluids",
            sectionHeading: "2. Buoyancy",
            concept: "Archimedes principle",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 4, neet: 14, mhtCet: 10 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["buoyant force", "archimedes", "floating fraction"],
        },
      ],
      importantObservations: [
        "In a freely falling lift (or orbit), buoyancy vanishes — no effective gravity, no pressure gradient",
      ],
    },
    {
      id: "flu-flow",
      title: "Fluid Dynamics — Continuity & Bernoulli",
      intro:
        "Continuity is mass conservation; Bernoulli is energy conservation per unit volume. Together they solve every ideal-flow problem.",
      formulas: [
        {
          id: "flu-continuity",
          expression: "A₁v₁ = A₂v₂",
          expressionLatex: "A_1v_1 = A_2v_2",
          label: "Equation of continuity",
          derivedFrom: "Mass conservation for incompressible steady flow",
          variables: [
            { symbol: "A", name: "cross-sectional area of the tube", unit: "m²", dimension: "[L²]" },
            { symbol: "v", name: "flow speed at that section", unit: "m/s", dimension: "[LT⁻¹]" },
          ],
          conditions: ["Incompressible fluid, steady flow", "Narrow section → FAST flow"],
          conceptLink: {
            chapterSlug: "mechanical-properties-of-fluids",
            sectionHeading: "3. Fluid Dynamics",
            concept: "equation of continuity",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 7, neet: 11, mhtCet: 8 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["continuity equation", "Av constant"],
        },
        {
          id: "flu-bernoulli",
          expression: "P + ½ρv² + ρgh = constant",
          expressionLatex: "P + \\tfrac{1}{2}\\rho v^2 + \\rho gh = \\text{constant}",
          label: "Bernoulli's equation",
          derivedFrom: "Work-energy theorem per unit volume of flowing fluid",
          derivation: {
            startsFrom: "Work-energy theorem applied to a fluid element moving along a streamline",
            steps: [
              { statement: "Net pressure work per unit volume", expression: "(P₁ − P₂)" },
              { statement: "Equals the change in kinetic + potential energy per unit volume", expression: "½ρ(v₂² − v₁²) + ρg(h₂ − h₁)" },
              { statement: "Rearrange into the sum form", expression: "P + ½ρv² + ρgh = constant" },
            ],
            askedInBoards: true,
          },
          variables: [
            { symbol: "P", name: "pressure", unit: "N/m²", dimension: "[ML⁻¹T⁻²]" },
            { symbol: "v", name: "flow speed", unit: "m/s", dimension: "[LT⁻¹]" },
            { symbol: "h", name: "height of the point", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Ideal fluid: non-viscous, incompressible, steady, irrotational — along a streamline"],
          commonMistakes: [
            "Fast flow means LOW pressure — students invert this; it explains aerofoil lift, roofs blowing off, and the Venturi meter",
          ],
          conceptLink: {
            chapterSlug: "mechanical-properties-of-fluids",
            sectionHeading: "3. Fluid Dynamics",
            concept: "Bernoulli's principle",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 10, jeeAdvanced: 5, neet: 13, mhtCet: 9 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["bernoulli", "half rho v squared", "venturi"],
        },
        {
          id: "flu-torricelli",
          expression: "v = √(2gh)",
          expressionLatex: "v = \\sqrt{2gh}",
          label: "Torricelli's law (speed of efflux)",
          derivedFrom: "Bernoulli between the free surface and the hole, with the tank wide enough that the surface barely moves",
          variables: [
            { symbol: "v", name: "efflux speed from the hole", unit: "m/s", dimension: "[LT⁻¹]" },
            { symbol: "h", name: "depth of the hole below the free surface", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Open tank, small hole", "Same as free-fall speed from height h"],
          commonMistakes: [
            "Range of the emerging jet from a hole at depth h in a tank of height H: x = 2√(h(H−h)), maximum when the hole is at mid-height",
          ],
          usedIn: ["kinematics"],
          conceptLink: {
            chapterSlug: "mechanical-properties-of-fluids",
            sectionHeading: "3. Fluid Dynamics",
            concept: "Torricelli's theorem",
          },
          examTags: ["jee-main", "neet", "mht-cet"],
          frequency: "high",
          examStats: { jeeMain: 6, neet: 9, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["torricelli", "efflux", "root 2gh"],
        },
      ],
      importantObservations: [
        "Bernoulli fails in viscous or turbulent flow — that is why real pipes need pumps",
      ],
      examNotes:
        "NEET asks Bernoulli applications conceptually (aerofoil, atomiser); JEE computes with the Venturi meter and moving-tank efflux setups.",
    },
    {
      id: "flu-viscosity",
      title: "Viscosity & Stokes' Law",
      intro:
        "Viscosity is internal friction between fluid layers. It caps the speed of anything falling through a fluid at the terminal velocity.",
      formulas: [
        {
          id: "flu-viscous-force",
          expression: "F = −ηA (dv/dx)",
          expressionLatex: "F = -\\eta A\\dfrac{dv}{dx}",
          label: "Newton's law of viscosity",
          variables: [
            { symbol: "η", name: "coefficient of viscosity", unit: "Pa·s (poiseuille)", dimension: "[ML⁻¹T⁻¹]", notes: "1 poise (CGS) = 0.1 Pa·s" },
            { symbol: "dv/dx", name: "velocity gradient between layers", unit: "s⁻¹", dimension: "[T⁻¹]" },
            { symbol: "A", name: "area of the layer", unit: "m²", dimension: "[L²]" },
          ],
          conditions: ["Liquids: η DECREASES with temperature; gases: η INCREASES with temperature"],
          conceptLink: {
            chapterSlug: "mechanical-properties-of-fluids",
            sectionHeading: "4. Viscosity",
            concept: "viscous force between layers",
          },
          examTags: ["jee-main", "neet", "mht-cet"],
          frequency: "medium",
          examStats: { jeeMain: 4, neet: 7, mhtCet: 5 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["viscosity", "velocity gradient", "eta"],
        },
        {
          id: "flu-stokes-terminal",
          expression: "F = 6πηrv;   v(t) = 2r²(ρ − σ)g / 9η",
          expressionLatex: "v_t = \\dfrac{2r^2(\\rho-\\sigma)g}{9\\eta}",
          label: "Stokes' law & terminal velocity",
          derivedFrom: "Weight = buoyancy + viscous drag at terminal speed",
          derivation: {
            startsFrom: "At terminal velocity the sphere's acceleration is zero",
            steps: [
              { statement: "Force balance", expression: "(4/3)πr³ρg = (4/3)πr³σg + 6πηr v(t)" },
              { statement: "Solve for v(t)", expression: "v(t) = 2r²(ρ − σ)g / 9η" },
            ],
          },
          variables: [
            { symbol: "r", name: "radius of the sphere", unit: "m", dimension: "[L]" },
            { symbol: "ρ, σ", name: "densities of the sphere and the fluid", unit: "kg/m³", dimension: "[ML⁻³]" },
            { symbol: "v(t)", name: "terminal velocity", unit: "m/s", dimension: "[LT⁻¹]" },
          ],
          conditions: ["Small sphere, laminar flow", "v(t) ∝ r² — a drop of double radius falls four times faster"],
          commonMistakes: [
            "When n identical drops merge, the big drop's terminal velocity = n²ᐟ³ × (small drop's) — radius grows as n¹ᐟ³, v(t) as r²",
          ],
          conceptLink: {
            chapterSlug: "mechanical-properties-of-fluids",
            sectionHeading: "4. Viscosity",
            concept: "Stokes law and terminal velocity",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 3, neet: 12, mhtCet: 9 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["stokes law", "terminal velocity", "6 pi eta r v", "merged drops"],
        },
        {
          id: "flu-reynolds",
          expression: "Re = ρvd / η",
          expressionLatex: "Re = \\dfrac{\\rho v d}{\\eta}",
          label: "Reynolds number",
          variables: [
            { symbol: "Re", name: "Reynolds number", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]", notes: "≲ 1000 laminar, ≳ 2000 turbulent, in-between unsteady" },
            { symbol: "d", name: "characteristic dimension (pipe diameter)", unit: "m", dimension: "[L]" },
          ],
          conceptLink: {
            chapterSlug: "mechanical-properties-of-fluids",
            sectionHeading: "4. Viscosity",
            concept: "Reynolds number and turbulence",
          },
          examTags: ["jee-main", "neet"],
          frequency: "medium",
          examStats: { jeeMain: 4, neet: 6 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["reynolds number", "laminar turbulent"],
        },
      ],
      importantObservations: [
        "Raindrops land gently because of terminal velocity — without air viscosity they would arrive at hundreds of m/s",
      ],
    },
    {
      id: "flu-surface-tension",
      title: "Surface Tension & Capillarity",
      intro:
        "Surface tension is energy per unit area of a liquid surface — it makes drops spherical, powers capillary rise, and sets the excess pressure inside bubbles.",
      formulas: [
        {
          id: "flu-surface-tension-def",
          expression: "T = F/L = (surface energy)/(area)",
          expressionLatex: "T = \\dfrac{F}{L}",
          label: "Surface tension",
          variables: [
            { symbol: "T", name: "surface tension", unit: "N/m (= J/m²)", dimension: "[MT⁻²]" },
            { symbol: "L", name: "length of the line on the surface", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Decreases with temperature; vanishes at the critical point", "Soap LOWERS water's surface tension"],
          commonMistakes: [
            "Work to blow a soap BUBBLE of radius r: W = 8πr²T (two surfaces) — a drop has one surface: W = 4πr²T",
          ],
          conceptLink: {
            chapterSlug: "mechanical-properties-of-fluids",
            sectionHeading: "5. Surface Tension",
            concept: "surface tension and surface energy",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 7, neet: 10, mhtCet: 8 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["surface tension", "surface energy", "soap bubble work"],
        },
        {
          id: "flu-excess-pressure",
          expression: "ΔP = 2T/r (drop);   ΔP = 4T/r (soap bubble)",
          expressionLatex: "\\Delta P = \\dfrac{2T}{r}\\ \\text{(drop)},\\quad \\dfrac{4T}{r}\\ \\text{(bubble)}",
          label: "Excess pressure inside a drop / bubble",
          derivedFrom: "Balancing pressure force against surface tension around the equator; the bubble's factor 4 comes from its TWO surfaces",
          variables: [
            { symbol: "ΔP", name: "pressure inside minus outside", unit: "N/m²", dimension: "[ML⁻¹T⁻²]" },
            { symbol: "r", name: "radius", unit: "m", dimension: "[L]" },
          ],
          conditions: ["SMALLER bubble → HIGHER inside pressure — connect two bubbles and the small one empties into the big one"],
          commonMistakes: [
            "Air bubble INSIDE water is a single surface: ΔP = 2T/r, not 4T/r",
          ],
          conceptLink: {
            chapterSlug: "mechanical-properties-of-fluids",
            sectionHeading: "5. Surface Tension",
            concept: "excess pressure",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 3, neet: 11, mhtCet: 8 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["excess pressure", "2T by r", "4T by r", "soap bubble"],
        },
        {
          id: "flu-capillary-rise",
          expression: "h = 2T cosθ / (ρgr)",
          expressionLatex: "h = \\dfrac{2T\\cos\\theta}{\\rho g r}",
          label: "Capillary rise",
          derivedFrom: "Weight of the raised column balanced by the vertical component of surface tension around the meniscus",
          variables: [
            { symbol: "h", name: "rise (or fall) of the liquid in the tube", unit: "m", dimension: "[L]" },
            { symbol: "θ", name: "contact angle", unit: "rad (or °)", dimension: "[M⁰L⁰T⁰]", notes: "θ > 90° (mercury–glass) makes h negative — depression" },
            { symbol: "r", name: "tube radius", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Thin tube", "In a tube of insufficient length the liquid does NOT overflow — the meniscus radius adjusts instead"],
          commonMistakes: [
            "h ∝ 1/r: halving the tube radius DOUBLES the rise",
          ],
          conceptLink: {
            chapterSlug: "mechanical-properties-of-fluids",
            sectionHeading: "5. Surface Tension",
            concept: "capillary action",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 7, neet: 12, mhtCet: 9 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["capillary rise", "2T cos theta", "meniscus"],
        },
      ],
      importantObservations: [
        "In free fall (satellite), capillary liquid rises to fill the ENTIRE tube — g → 0 removes the counterweight",
      ],
      examNotes:
        "NEET rotates between capillary rise, excess pressure and merged-drops energy release; JEE combines surface energy changes with temperature rise of the coalesced drop.",
    },
  ],
};
