import type { ChapterFormulaSheet } from "./types";

export const movingChargesAndMagnetismFormulaSheet: ChapterFormulaSheet = {
  chapterSlug: "moving-charges-and-magnetism",
  chapterName: "Moving Charges & Magnetism",
  className: "12",
  version: "1.0.0",
  lastUpdated: "2026-07-08",
  examCoverage: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
  quickRevisionIds: [
    "mcm-biot-savart",
    "mcm-field-infinite-wire",
    "mcm-field-centre-loop",
    "mcm-field-solenoid",
    "mcm-lorentz-force",
    "mcm-radius-circular-motion",
    "mcm-force-between-parallel-wires",
    "mcm-torque-current-loop",
  ],
  topicGroups: [
    {
      id: "mcm-biot-savart-fields",
      title: "Biot–Savart Law & Field due to Currents",
      intro:
        "The Biot–Savart law is to magnetism what Coulomb's law is to electrostatics — the fundamental source law from which every standard current-geometry field formula is built.",
      formulas: [
        {
          id: "mcm-biot-savart",
          expression: "dB = (μ₀/4π) I dl sinθ / r²",
          expressionLatex: "d\\vec{B} = \\dfrac{\\mu_0}{4\\pi}\\dfrac{I\\,d\\vec{l}\\times\\hat{r}}{r^2}",
          label: "Biot–Savart law",
          variables: [
            { symbol: "μ₀", name: "permeability of free space", unit: "T·m/A", dimension: "[MLT⁻²A⁻²]", notes: "μ₀ = 4π × 10⁻⁷ T·m/A" },
            { symbol: "I dl", name: "current element", unit: "A·m", dimension: "[AL]" },
            { symbol: "θ", name: "angle between dl and the position vector r̂ to the field point", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["Direction of dB given by the right-hand rule: dl × r̂"],
          commonMistakes: [
            "dB = 0 along the axis of the current element itself (θ = 0°), maximum perpendicular to it (θ = 90°)",
          ],
          conceptLink: {
            chapterSlug: "moving-charges-and-magnetism",
            sectionHeading: "2. Biot–Savart Law",
            concept: "Biot-Savart law",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 10, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["biot savart law", "mu0 by 4 pi I dl sin theta by r squared"],
        },
        {
          id: "mcm-field-straight-wire-finite",
          expression: "B = (μ₀I / 4πd)(sinθ₁ + sinθ₂)",
          expressionLatex: "B = \\dfrac{\\mu_0 I}{4\\pi d}(\\sin\\theta_1+\\sin\\theta_2)",
          label: "Magnetic field due to a finite straight current-carrying wire",
          derivedFrom: "Integrating the Biot–Savart law along the length of the wire",
          variables: [
            { symbol: "d", name: "perpendicular distance from the wire", unit: "m", dimension: "[L]" },
            { symbol: "θ₁, θ₂", name: "angles subtended at the field point by the two ends of the wire, measured from the perpendicular", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["For a point symmetrically placed opposite the wire's midpoint, θ₁ = θ₂"],
          conceptLink: {
            chapterSlug: "moving-charges-and-magnetism",
            sectionHeading: "4. Magnetic Field Due to a Straight Current-Carrying Wire",
            concept: "field due to a finite straight wire",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 4, neet: 7, mhtCet: 5 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["finite wire magnetic field", "mu0 I by 4 pi d sin theta1 theta2"],
        },
        {
          id: "mcm-field-infinite-wire",
          expression: "B = μ₀I / 2πd",
          expressionLatex: "B = \\dfrac{\\mu_0 I}{2\\pi d}",
          label: "Magnetic field due to an infinitely long straight wire",
          derivedFrom: "Finite-wire formula with θ₁ = θ₂ = 90° (both ends at infinity)",
          variables: [
            { symbol: "d", name: "perpendicular distance from the wire", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Field lines are concentric circles around the wire; direction from the right-hand thumb rule"],
          conceptLink: {
            chapterSlug: "moving-charges-and-magnetism",
            sectionHeading: "4. Magnetic Field Due to a Straight Current-Carrying Wire",
            concept: "field due to an infinite straight wire",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 4, neet: 12, mhtCet: 8 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["infinite wire magnetic field", "mu0 I by 2 pi d"],
        },
        {
          id: "mcm-field-centre-loop",
          expression: "B = μ₀I / 2R  (centre of a circular loop); for an arc of angle φ: B = μ₀Iφ / 4πR",
          expressionLatex: "B = \\dfrac{\\mu_0 I}{2R}",
          label: "Magnetic field at the centre of a circular current loop",
          derivedFrom: "Integrating Biot–Savart around a full loop where every element is perpendicular to r and equidistant",
          variables: [
            { symbol: "R", name: "radius of the loop", unit: "m", dimension: "[L]" },
          ],
          conditions: ["For N turns, B = μ₀NI/2R", "For a quarter/half arc, scale by the fraction of 2π subtended"],
          conceptLink: {
            chapterSlug: "moving-charges-and-magnetism",
            sectionHeading: "5. Magnetic Field at the Centre of a Circular Loop, Coil and Arc",
            concept: "field at the centre of a circular loop",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 11, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["circular loop centre field", "mu0 I by 2R"],
        },
        {
          id: "mcm-field-axis-coil",
          expression: "B = μ₀NIR² / [2(R²+x²)^(3/2)]",
          expressionLatex: "B = \\dfrac{\\mu_0 N I R^2}{2(R^2+x^2)^{3/2}}",
          label: "Magnetic field on the axis of a circular coil",
          derivedFrom: "Only the axial components of dB survive by symmetry; perpendicular components cancel in pairs",
          variables: [
            { symbol: "N", name: "number of turns", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
            { symbol: "x", name: "distance from the centre along the axis", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Reduces to μ₀NI/2R at the centre (x = 0)", "For x ≫ R, behaves like a magnetic dipole field ∝ 1/x³"],
          conceptLink: {
            chapterSlug: "moving-charges-and-magnetism",
            sectionHeading: "6. Magnetic Field on the Axis of a Circular Coil",
            concept: "field on the axis of a circular coil",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 4, neet: 7, mhtCet: 5 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["field axis circular coil", "mu0 N I R squared"],
        },
        {
          id: "mcm-ampere-law",
          expression: "∮B·dl = μ₀ I(enclosed)",
          expressionLatex: "\\oint \\vec{B}\\cdot d\\vec{l} = \\mu_0 I_{enc}",
          label: "Ampère's circuital law",
          variables: [
            { symbol: "I(enclosed)", name: "net current enclosed by the Amperian loop", unit: "A", dimension: "[A]" },
          ],
          conditions: ["Useful only with high-symmetry current distributions (straight wire, solenoid, toroid) — analogous to how Gauss's law needs symmetric charge distributions"],
          conceptLink: {
            chapterSlug: "moving-charges-and-magnetism",
            sectionHeading: "7. Ampère's Circuital Law",
            concept: "Ampère's circuital law",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 10, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["amperes circuital law", "line integral B dl mu0 I enclosed"],
        },
        {
          id: "mcm-field-solenoid",
          expression: "B = μ₀nI",
          expressionLatex: "B = \\mu_0 n I",
          label: "Magnetic field inside a long solenoid",
          derivedFrom: "Ampère's law with a rectangular Amperian loop, half inside and half outside the solenoid",
          variables: [
            { symbol: "n", name: "number of turns per unit length", unit: "turns/m", dimension: "[L⁻¹]" },
          ],
          conditions: ["Field is uniform inside (away from the ends) and essentially zero outside — valid for a long, tightly wound solenoid"],
          commonMistakes: [
            "Field is INDEPENDENT of the solenoid's radius and of position inside (as long as away from the ends) — a frequently tested subtlety",
          ],
          conceptLink: {
            chapterSlug: "moving-charges-and-magnetism",
            sectionHeading: "9. Magnetic Field Due to a Solenoid",
            concept: "field inside a solenoid",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 11, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["solenoid magnetic field", "mu0 n I", "field inside solenoid"],
        },
        {
          id: "mcm-field-toroid",
          expression: "B = μ₀NI / 2πr",
          expressionLatex: "B = \\dfrac{\\mu_0 NI}{2\\pi r}",
          label: "Magnetic field inside a toroid",
          derivedFrom: "Ampère's law with a circular Amperian loop of radius r inside the toroid's core",
          variables: [
            { symbol: "N", name: "total number of turns on the toroid", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
            { symbol: "r", name: "radius of the circular Amperian loop, along the toroid's central circle", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Field is exactly zero both outside the toroid and in the hollow centre — completely confined to the core"],
          conceptLink: {
            chapterSlug: "moving-charges-and-magnetism",
            sectionHeading: "10. Magnetic Field Due to a Toroid",
            concept: "field inside a toroid",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 3, neet: 7, mhtCet: 5 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["toroid magnetic field", "mu0 N I by 2 pi r"],
        },
      ],
      importantObservations: [
        "The right-hand thumb rule (grip rule) gives field direction around a wire; the right-hand rule with curled fingers along current gives field direction inside a loop/solenoid",
      ],
    },
    {
      id: "mcm-force-on-charges",
      title: "Force on Moving Charges & Currents",
      intro:
        "A magnetic field does no work on a moving charge — it only changes direction, never speed. This single fact underlies every circular/helical trajectory in this chapter.",
      formulas: [
        {
          id: "mcm-lorentz-force",
          expression: "F = q(E + v × B)",
          expressionLatex: "\\vec{F} = q(\\vec{E} + \\vec{v}\\times\\vec{B})",
          label: "Lorentz force",
          variables: [
            { symbol: "v", name: "velocity of the charge", unit: "m/s", dimension: "[LT⁻¹]" },
          ],
          conditions: ["The magnetic part qv×B is always perpendicular to v, so it does zero work — speed (and KE) stays constant, only direction changes"],
          conceptLink: {
            chapterSlug: "moving-charges-and-magnetism",
            sectionHeading: "11. Force on a Moving Charge in a Magnetic Field",
            concept: "Lorentz force",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 5, neet: 12, mhtCet: 8 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["lorentz force", "q v cross B plus E"],
        },
        {
          id: "mcm-magnetic-force-magnitude",
          expression: "F = qvB sinθ",
          expressionLatex: "F = qvB\\sin\\theta",
          label: "Magnitude of magnetic force on a moving charge",
          variables: [
            { symbol: "θ", name: "angle between velocity v and field B", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["Force is zero when v is parallel/antiparallel to B (θ = 0° or 180°), maximum when perpendicular"],
          conceptLink: {
            chapterSlug: "moving-charges-and-magnetism",
            sectionHeading: "11. Force on a Moving Charge in a Magnetic Field",
            concept: "magnetic force on a charge",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 11, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["magnetic force qvB sin theta"],
        },
        {
          id: "mcm-radius-circular-motion",
          expression: "r = mv / qB",
          expressionLatex: "r = \\dfrac{mv}{qB}",
          label: "Radius of circular path of a charged particle in a magnetic field",
          derivedFrom: "Magnetic force provides centripetal force: qvB = mv²/r",
          variables: [
            { symbol: "r", name: "radius of the circular path", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Requires v perpendicular to B for pure circular motion (no helix)"],
          conceptLink: {
            chapterSlug: "moving-charges-and-magnetism",
            sectionHeading: "12. Circular Motion of a Charged Particle in a Magnetic Field",
            concept: "radius of circular motion in a magnetic field",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 4, neet: 12, mhtCet: 8 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["radius circular motion magnetic field", "r equals mv by qB"],
        },
        {
          id: "mcm-time-period-cyclotron",
          expression: "T = 2πm / qB",
          expressionLatex: "T = \\dfrac{2\\pi m}{qB}",
          label: "Time period of circular motion in a magnetic field (cyclotron period)",
          derivedFrom: "T = 2πr/v combined with r = mv/qB",
          variables: [
            { symbol: "T", name: "time period", unit: "s", dimension: "[T]" },
          ],
          conditions: ["Independent of speed v and radius r — this is the key principle that makes the cyclotron work"],
          commonMistakes: [
            "Because T is independent of v, the cyclotron frequency stays fixed even as the particle speeds up and spirals outward",
          ],
          conceptLink: {
            chapterSlug: "moving-charges-and-magnetism",
            sectionHeading: "14. The Cyclotron",
            concept: "cyclotron time period",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 4, neet: 8, mhtCet: 5 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["cyclotron time period", "T equals 2 pi m by qB"],
        },
        {
          id: "mcm-cyclotron-frequency",
          expression: "f = qB / 2πm",
          expressionLatex: "f = \\dfrac{qB}{2\\pi m}",
          label: "Cyclotron frequency",
          conditions: ["Also called the gyrofrequency; the oscillating voltage applied to the dees must match this frequency"],
          variables: [],
          conceptLink: {
            chapterSlug: "moving-charges-and-magnetism",
            sectionHeading: "14. The Cyclotron",
            concept: "cyclotron frequency",
          },
          examTags: ["jee-main", "neet", "mht-cet"],
          frequency: "medium",
          examStats: { jeeMain: 5, neet: 6, mhtCet: 4 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["cyclotron frequency", "f equals qB by 2 pi m"],
        },
        {
          id: "mcm-helical-pitch",
          expression: "pitch = v(∥) T = (2πm v cosθ) / (qB)",
          expressionLatex: "\\text{pitch} = v_\\parallel T",
          label: "Pitch of helical motion in a magnetic field",
          derivedFrom: "Velocity component along B is unaffected (v∥); component perpendicular to B (v⊥) causes circular motion of period T",
          variables: [
            { symbol: "v(∥)", name: "velocity component parallel to B", unit: "m/s", dimension: "[LT⁻¹]" },
          ],
          conditions: ["Occurs when velocity has a component both along and perpendicular to B — a helix results, not a circle"],
          conceptLink: {
            chapterSlug: "moving-charges-and-magnetism",
            sectionHeading: "13. Helical Motion and the Lorentz Force",
            concept: "helical motion pitch",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "medium",
          examStats: { jeeMain: 5, jeeAdvanced: 3, neet: 5 },
          difficulty: "hard",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["helical motion pitch", "helix magnetic field"],
        },
        {
          id: "mcm-force-current-conductor",
          expression: "F = BIL sinθ",
          expressionLatex: "\\vec{F} = I\\vec{L}\\times\\vec{B}",
          label: "Force on a current-carrying conductor in a magnetic field",
          derivedFrom: "Sum of Lorentz forces on all drifting charges in the conductor: F = (nAL)ev(d)B → F = BIL",
          variables: [
            { symbol: "L", name: "length of the conductor in the field", unit: "m", dimension: "[L]" },
          ],
          conditions: ["θ measured between current direction and B; force is zero when current is along B"],
          conceptLink: {
            chapterSlug: "moving-charges-and-magnetism",
            sectionHeading: "15. Force on a Current-Carrying Conductor",
            concept: "force on a current-carrying conductor",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 10, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["force current carrying conductor", "F equals BIL sin theta"],
        },
        {
          id: "mcm-force-between-parallel-wires",
          expression: "F/L = μ₀I₁I₂ / (2πd)",
          expressionLatex: "\\dfrac{F}{L} = \\dfrac{\\mu_0 I_1 I_2}{2\\pi d}",
          label: "Force per unit length between two parallel current-carrying wires",
          derivedFrom: "Field of one wire (μ₀I₁/2πd) acting on the current I₂ in the other via F = BI₂L",
          variables: [
            { symbol: "I₁, I₂", name: "currents in the two wires", unit: "A", dimension: "[A]" },
            { symbol: "d", name: "separation between the wires", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Like currents (same direction) attract; unlike currents (opposite direction) repel — opposite convention from charges"],
          commonMistakes: [
            "This formula historically DEFINED the ampere (1 A produces 2×10⁻⁷ N/m force per metre at 1 m separation) — note the definition may have shifted with the 2019 SI redefinition",
          ],
          conceptLink: {
            chapterSlug: "moving-charges-and-magnetism",
            sectionHeading: "16. Force Between Two Parallel Current-Carrying Conductors",
            concept: "force between parallel currents",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 11, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["force between parallel wires", "mu0 I1 I2 by 2 pi d"],
        },
      ],
    },
    {
      id: "mcm-dipole-torque-galvanometer",
      title: "Current Loop as a Dipole, Torque & Galvanometer",
      intro:
        "A current loop behaves exactly like a magnetic dipole in an external field — this equivalence is what makes a moving-coil galvanometer possible.",
      formulas: [
        {
          id: "mcm-magnetic-moment-loop",
          expression: "m = NIA",
          expressionLatex: "\\vec{m} = NI\\vec{A}",
          label: "Magnetic dipole moment of a current loop",
          variables: [
            { symbol: "m", name: "magnetic dipole moment", unit: "A·m²", dimension: "[AL²]" },
            { symbol: "N", name: "number of turns", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
            { symbol: "A", name: "area enclosed by the loop", unit: "m²", dimension: "[L²]" },
          ],
          conditions: ["Direction given by the right-hand curl rule: curl fingers along current, thumb gives m direction"],
          conceptLink: {
            chapterSlug: "moving-charges-and-magnetism",
            sectionHeading: "17. Current Loop as a Magnetic Dipole",
            concept: "magnetic moment of a current loop",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 10, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["magnetic moment current loop", "m equals NIA"],
        },
        {
          id: "mcm-torque-current-loop",
          expression: "τ = NIAB sinθ = m × B",
          expressionLatex: "\\vec{\\tau} = \\vec{m}\\times\\vec{B}",
          label: "Torque on a current loop in a uniform magnetic field",
          derivedFrom: "Forces on opposite sides of the loop form a couple; identical mathematical structure to the electric dipole torque",
          variables: [
            { symbol: "θ", name: "angle between the loop's normal (m direction) and B", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["Net force on a current loop in a UNIFORM field is always zero — only torque acts, exactly parallel to the electric dipole case"],
          usedIn: ["electric-charges-and-fields"],
          conceptLink: {
            chapterSlug: "moving-charges-and-magnetism",
            sectionHeading: "18. Torque on a Current Loop and the Moving Coil Galvanometer",
            concept: "torque on a current loop",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 11, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["torque current loop", "NIAB sin theta", "m cross B"],
        },
        {
          id: "mcm-galvanometer-current-sensitivity",
          expression: "θ/I = NAB/k  (current sensitivity)",
          expressionLatex: "\\dfrac{\\theta}{I} = \\dfrac{NAB}{k}",
          label: "Current sensitivity of a moving-coil galvanometer",
          derivedFrom: "Equilibrium of magnetic torque NIAB and restoring torque kθ from the suspension",
          variables: [
            { symbol: "k", name: "torsional restoring constant of the suspension", unit: "N·m/rad", dimension: "[ML²T⁻²]" },
            { symbol: "θ", name: "deflection angle of the coil", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["Radial field design (via curved pole pieces) keeps θ ∝ I with sinθ always ≈ 1 in the actual instrument"],
          conceptLink: {
            chapterSlug: "moving-charges-and-magnetism",
            sectionHeading: "18. Torque on a Current Loop and the Moving Coil Galvanometer",
            concept: "galvanometer current sensitivity",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 6, neet: 8, mhtCet: 5 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["galvanometer current sensitivity", "NAB by k"],
        },
        {
          id: "mcm-magnetic-moment-electron",
          expression: "m(orbital) = evr/2 = (e/2m)L",
          expressionLatex: "m = \\dfrac{e}{2m}L",
          label: "Magnetic dipole moment of a revolving electron (Bohr model)",
          derivedFrom: "Orbiting electron is equivalent to a current loop: I = e/T = ef, with m = IA",
          variables: [
            { symbol: "v", name: "orbital speed of the electron", unit: "m/s", dimension: "[LT⁻¹]" },
            { symbol: "L", name: "orbital angular momentum of the electron", unit: "kg·m²/s", dimension: "[ML²T⁻¹]" },
          ],
          conditions: ["Gyromagnetic ratio m/L = e/2m is constant — independent of the orbit radius or speed"],
          conceptLink: {
            chapterSlug: "moving-charges-and-magnetism",
            sectionHeading: "19. Magnetic Dipole Moment of a Revolving Electron",
            concept: "magnetic moment of a revolving electron",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "medium",
          examStats: { jeeMain: 5, jeeAdvanced: 3, neet: 5 },
          difficulty: "hard",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["magnetic moment revolving electron", "gyromagnetic ratio", "e by 2m L"],
        },
      ],
      examNotes:
        "JEE Advanced often asks to find the ratio τ(max)/τ(some angle) or to combine cyclotron/helical motion with force-on-conductor problems in a single multi-step question.",
    },
  ],
};
