import type { ChapterFormulaSheet } from "./types";

export const movingChargesFormulaSheet: ChapterFormulaSheet = {
  chapterSlug: "moving-charges-and-magnetism",
  chapterName: "Moving Charges & Magnetism",
  className: "12",
  version: "1.0.0",
  lastUpdated: "2026-07-05",
  examCoverage: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
  quickRevisionIds: [
    "mcm-lorentz-force",
    "mcm-circular-motion-radius",
    "mcm-force-on-wire",
    "mcm-biot-savart",
    "mcm-field-straight-wire",
    "mcm-field-solenoid",
  ],
  topicGroups: [
    {
      id: "mcm-force",
      title: "Magnetic Force on Charges & Currents",
      intro:
        "A magnetic field does no work — it only bends paths. The Lorentz force is always perpendicular to velocity, turning charges into circles.",
      formulas: [
        {
          id: "mcm-lorentz-force",
          expression: "F = qvB sinθ;   F = q(v × B)",
          expressionLatex: "\\vec{F} = q(\\vec{v}\\times\\vec{B})",
          label: "Lorentz (magnetic) force on a charge",
          variables: [
            { symbol: "F", name: "magnetic force", unit: "N", dimension: "[MLT⁻²]" },
            { symbol: "q", name: "charge", unit: "C", dimension: "[AT]" },
            { symbol: "v", name: "velocity of the charge", unit: "m/s", dimension: "[LT⁻¹]" },
            { symbol: "B", name: "magnetic field", unit: "T (tesla)", dimension: "[MT⁻²A⁻¹]" },
            { symbol: "θ", name: "angle between v and B", unit: "rad (or °)", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: [
            "Force is perpendicular to BOTH v and B — magnetic force does zero work, so speed and KE never change",
            "Zero force when v is parallel to B (θ = 0)",
          ],
          commonMistakes: [
            "A magnetic field cannot change a particle's speed or kinetic energy — only its direction",
          ],
          conceptLink: {
            chapterSlug: "moving-charges-and-magnetism",
            sectionHeading: "1. Magnetic Force",
            concept: "Lorentz force",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 10, jeeAdvanced: 5, neet: 13, mhtCet: 10 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["lorentz force", "qvB sin theta", "q v cross B"],
        },
        {
          id: "mcm-circular-motion-radius",
          expression: "r = mv/(qB);   T = 2πm/(qB);   f = qB/(2πm)",
          expressionLatex: "r = \\dfrac{mv}{qB},\\quad T = \\dfrac{2\\pi m}{qB}",
          label: "Charged particle in a magnetic field",
          derivedFrom: "Magnetic force supplies the centripetal force: qvB = mv²/r",
          variables: [
            { symbol: "r", name: "radius of the circular path", unit: "m", dimension: "[L]" },
            { symbol: "T", name: "time period of revolution", unit: "s", dimension: "[T]" },
          ],
          conditions: [
            "Period is INDEPENDENT of speed and radius — the cyclotron principle",
            "Velocity component along B is unaffected → helical path when v has a parallel component",
          ],
          commonMistakes: [
            "Faster particles trace BIGGER circles but take the SAME time per revolution",
          ],
          usedIn: ["laws-of-motion"],
          conceptLink: {
            chapterSlug: "moving-charges-and-magnetism",
            sectionHeading: "2. Motion in a Magnetic Field",
            concept: "circular motion in a magnetic field",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 5, neet: 12, mhtCet: 9 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["radius mv by qB", "cyclotron period", "helical path"],
        },
        {
          id: "mcm-force-on-wire",
          expression: "F = BIL sinθ;   F = I(L × B)",
          expressionLatex: "\\vec{F} = I(\\vec{L}\\times\\vec{B})",
          label: "Force on a current-carrying wire",
          variables: [
            { symbol: "I", name: "current", unit: "A", dimension: "[A]" },
            { symbol: "L", name: "length of the wire in the field", unit: "m", dimension: "[L]" },
            { symbol: "θ", name: "angle between the wire and B", unit: "rad (or °)", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["Force per unit length between two parallel wires: F/L = μ₀I₁I₂/(2πd) — attract if currents are parallel"],
          commonMistakes: [
            "A closed current loop in a UNIFORM field feels zero NET force (but a torque) — the side forces cancel",
          ],
          usedIn: ["system-of-particles-and-rotational-motion"],
          conceptLink: {
            chapterSlug: "moving-charges-and-magnetism",
            sectionHeading: "3. Force on a Conductor",
            concept: "force on a current-carrying wire",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 11, mhtCet: 9 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["BIL sin theta", "force on wire", "parallel wires force"],
        },
      ],
      importantObservations: [
        "Velocity selector: E and B crossed so qE = qvB, passing only v = E/B undeflected",
        "Cyclotron frequency qB/2πm sets the RF driving frequency — independent of the ion's energy",
      ],
    },
    {
      id: "mcm-biot-savart-group",
      title: "Magnetic Field of Currents",
      intro:
        "Biot-Savart is to magnetism what Coulomb is to electricity — the elementary law you integrate. Ampère's law is its Gauss-style shortcut for symmetric cases.",
      formulas: [
        {
          id: "mcm-biot-savart",
          expression: "dB = (μ₀/4π) I dl sinθ / r²",
          expressionLatex: "dB = \\dfrac{\\mu_0}{4\\pi}\\dfrac{I\\,dl\\sin\\theta}{r^2}",
          label: "Biot-Savart law",
          variables: [
            { symbol: "μ₀", name: "permeability of free space", unit: "T·m/A", dimension: "[MLT⁻²A⁻²]", notes: "μ₀ = 4π × 10⁻⁷ T·m/A" },
            { symbol: "dl", name: "current element length", unit: "m", dimension: "[L]" },
            { symbol: "θ", name: "angle between dl and the position vector r", unit: "rad (or °)", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["dB is perpendicular to both dl and r (right-hand rule)"],
          conceptLink: {
            chapterSlug: "moving-charges-and-magnetism",
            sectionHeading: "4. Biot-Savart Law",
            concept: "Biot-Savart law",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 4, neet: 8, mhtCet: 6 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["biot savart", "mu0 by 4 pi", "magnetic field element"],
        },
        {
          id: "mcm-field-straight-wire",
          expression: "B = μ₀I/(2πr)  (infinite wire);  B = (μ₀I/4πr)(sinθ₁ + sinθ₂)  (finite)",
          expressionLatex: "B = \\dfrac{\\mu_0 I}{2\\pi r}",
          label: "Field of a straight current-carrying wire",
          derivedFrom: "Integrating Biot-Savart along the wire",
          variables: [
            { symbol: "r", name: "perpendicular distance from the wire", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Field circles the wire (right-hand grip rule); B ∝ 1/r"],
          commonMistakes: [
            "The infinite-wire formula μ₀I/2πr is a special case of the finite formula with θ₁ = θ₂ = 90°",
          ],
          conceptLink: {
            chapterSlug: "moving-charges-and-magnetism",
            sectionHeading: "5. Field of a Wire",
            concept: "field of a straight wire",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 4, neet: 11, mhtCet: 9 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["field straight wire", "mu0 I by 2 pi r", "finite wire"],
        },
        {
          id: "mcm-field-loop-center",
          expression: "Centre of loop: B = μ₀NI/(2R);   On axis: B = μ₀NIR²/[2(R² + x²)^(3/2)]",
          expressionLatex: "B_{centre} = \\dfrac{\\mu_0 NI}{2R}",
          label: "Field of a circular current loop",
          variables: [
            { symbol: "N", name: "number of turns", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
            { symbol: "R", name: "loop radius", unit: "m", dimension: "[L]" },
            { symbol: "x", name: "distance along the axis from the centre", unit: "m", dimension: "[L]" },
          ],
          conditions: ["A current loop behaves like a magnetic dipole of moment m = NIA"],
          usedIn: ["magnetism-and-matter"],
          conceptLink: {
            chapterSlug: "moving-charges-and-magnetism",
            sectionHeading: "5. Field of a Loop",
            concept: "field of a circular loop",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 10, mhtCet: 8 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["field loop centre", "mu0 NI by 2R", "axis of loop"],
        },
        {
          id: "mcm-field-solenoid",
          expression: "Solenoid: B = μ₀nI;   Toroid: B = μ₀NI/(2πr)",
          expressionLatex: "B_{solenoid} = \\mu_0 nI",
          label: "Field of a solenoid and toroid",
          derivedFrom: "Ampère's law ∮B·dl = μ₀I(enc) applied to a rectangular / circular loop",
          variables: [
            { symbol: "n", name: "turns per unit length", unit: "m⁻¹", dimension: "[L⁻¹]" },
            { symbol: "N", name: "total number of turns (toroid)", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: [
            "Field inside a long solenoid is UNIFORM and independent of position; outside ≈ 0",
            "Field at the END of a solenoid is half the interior value: μ₀nI/2",
          ],
          commonMistakes: [
            "Solenoid field depends on turns per unit LENGTH (n), not total turns N",
          ],
          conceptLink: {
            chapterSlug: "moving-charges-and-magnetism",
            sectionHeading: "6. Ampère's Law",
            concept: "solenoid and toroid",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 11, mhtCet: 9 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["solenoid field", "mu0 n I", "toroid", "amperes law"],
        },
      ],
      importantObservations: [
        "Ampère's law ∮B·dl = μ₀I(enc) works only where symmetry makes B constant along the chosen loop",
      ],
    },
    {
      id: "mcm-torque-instruments",
      title: "Torque on Loops & the Galvanometer",
      intro:
        "A current loop in a field is a magnetic dipole; the torque it feels is the working principle of every moving-coil meter.",
      formulas: [
        {
          id: "mcm-torque-loop",
          expression: "τ = NIAB sinθ = mB sinθ;   m = NIA",
          expressionLatex: "\\vec{\\tau} = \\vec{m}\\times\\vec{B},\\quad m = NIA",
          label: "Torque on a current loop; magnetic moment",
          variables: [
            { symbol: "m", name: "magnetic dipole moment", unit: "A·m²", dimension: "[AL²]" },
            { symbol: "A", name: "area of the loop", unit: "m²", dimension: "[L²]" },
            { symbol: "θ", name: "angle between the loop's normal (m) and B", unit: "rad (or °)", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["Maximum torque when the loop PLANE is parallel to B (θ = 90°); zero when the plane is perpendicular"],
          commonMistakes: [
            "θ is measured from the NORMAL to the loop, not from the loop plane — the two differ by 90°",
          ],
          usedIn: ["electric-charges-and-fields", "magnetism-and-matter"],
          conceptLink: {
            chapterSlug: "moving-charges-and-magnetism",
            sectionHeading: "7. Torque on a Loop",
            concept: "torque on a current loop",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 11, mhtCet: 8 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["torque on loop", "NIAB sin theta", "magnetic moment NIA"],
        },
        {
          id: "mcm-galvanometer-conversion",
          expression: "Ammeter: shunt S = I(g)G/(I − I(g));   Voltmeter: series R = V/I(g) − G",
          expressionLatex: "S = \\dfrac{I_g G}{I - I_g}",
          label: "Galvanometer to ammeter / voltmeter",
          variables: [
            { symbol: "G", name: "galvanometer resistance", unit: "Ω", dimension: "[ML²T⁻³A⁻²]" },
            { symbol: "I(g)", name: "full-scale deflection current", unit: "A", dimension: "[A]" },
            { symbol: "S", name: "shunt resistance (small, parallel)", unit: "Ω", dimension: "[ML²T⁻³A⁻²]" },
          ],
          conditions: [
            "Ammeter: low resistance in SERIES with the circuit, needs a small PARALLEL shunt — ideal ammeter has zero resistance",
            "Voltmeter: high resistance in PARALLEL with the element, needs a large SERIES resistor — ideal voltmeter has infinite resistance",
          ],
          commonMistakes: [
            "Swapping shunt (parallel, ammeter) and series-resistor (voltmeter) roles is the classic instrument-conversion error",
          ],
          conceptLink: {
            chapterSlug: "moving-charges-and-magnetism",
            sectionHeading: "8. Moving Coil Galvanometer",
            concept: "galvanometer conversion",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 6, neet: 10, mhtCet: 8 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["galvanometer to ammeter", "shunt", "voltmeter series resistance"],
        },
      ],
      importantObservations: [
        "Moving-coil galvanometer sensitivity rises with N, A and B, and falls with the spring constant k",
      ],
      examNotes:
        "NEET repeats radius/period, solenoid field and galvanometer-conversion; JEE Advanced favours helical motion, crossed fields, and Ampère's law on non-obvious geometries.",
    },
  ],
};
