import type { ChapterFormulaSheet } from "./types";

export const nucleiFormulaSheet: ChapterFormulaSheet = {
  chapterSlug: "nuclei",
  chapterName: "Nuclei",
  className: "12",
  version: "1.0.0",
  lastUpdated: "2026-07-09",
  examCoverage: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
  quickRevisionIds: [
    "nuc-nuclear-radius",
    "nuc-mass-energy-equivalence",
    "nuc-binding-energy",
    "nuc-radioactive-decay-law",
    "nuc-half-life-decay-constant",
  ],
  topicGroups: [
    {
      id: "nuc-nuclear-structure",
      title: "Nuclear Size, Density & Composition",
      intro:
        "Every nucleus, however different its mass, has almost exactly the same density — a striking clue that nucleons are packed together at a fixed spacing, like incompressible drops of nuclear fluid.",
      formulas: [
        {
          id: "nuc-nuclear-radius",
          expression: "R = R₀ A^(1/3) ,  R₀ ≈ 1.2 fm",
          expressionLatex: "R = R_0 A^{1/3}",
          label: "Nuclear radius",
          variables: [
            { symbol: "R", name: "nuclear radius", unit: "fm (femtometre)", dimension: "[L]" },
            { symbol: "A", name: "mass number (total nucleons)", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
            { symbol: "R₀", name: "empirical constant", unit: "fm", dimension: "[L]", notes: "R₀ ≈ 1.2 × 10⁻¹⁵ m" },
          ],
          conditions: ["The A^(1/3) scaling (not A directly) is what keeps nuclear density roughly constant across all nuclei"],
          conceptLink: {
            chapterSlug: "nuclei",
            sectionHeading: "3. Size, Volume, Mass and Density of the Nucleus",
            concept: "nuclear radius",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 11, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["nuclear radius formula", "R0 A to the 1 third"],
        },
        {
          id: "nuc-nuclear-density",
          expression: "ρ = mass / volume ≈ 2.3 × 10¹⁷ kg/m³   (constant, independent of A)",
          expressionLatex: "\\rho = \\dfrac{m}{\\frac{4}{3}\\pi R^3}",
          label: "Nuclear density",
          derivedFrom: "Mass ∝ A and volume ∝ R³ ∝ A both scale identically with A, so their ratio (density) is independent of A",
          variables: [
            { symbol: "ρ", name: "nuclear density", unit: "kg/m³", dimension: "[ML⁻³]" },
          ],
          conditions: ["Nearly identical for every nucleus, light or heavy — direct evidence that nucleons pack together at a fixed characteristic spacing"],
          commonMistakes: [
            "Nuclear density is essentially THE SAME for all elements — a very commonly tested one-line fact, don't assume heavier nuclei are denser",
          ],
          conceptLink: {
            chapterSlug: "nuclei",
            sectionHeading: "3. Size, Volume, Mass and Density of the Nucleus",
            concept: "nuclear density",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 6, neet: 8, mhtCet: 5 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["nuclear density formula", "constant nuclear density independent of A"],
        },
      ],
    },
    {
      id: "nuc-mass-energy-binding",
      title: "Mass–Energy Equivalence & Binding Energy",
      intro:
        "A nucleus weighs slightly LESS than the sum of its free, separated nucleons — that missing mass has been converted into the binding energy holding the nucleus together.",
      formulas: [
        {
          id: "nuc-mass-energy-equivalence",
          expression: "E = mc²",
          expressionLatex: "E = mc^2",
          label: "Einstein's mass–energy equivalence",
          variables: [
            { symbol: "E", name: "energy equivalent of mass m", unit: "J", dimension: "[ML²T⁻²]" },
          ],
          conditions: ["The conversion factor used throughout nuclear physics: 1 u (atomic mass unit) = 931.5 MeV of energy"],
          conceptLink: {
            chapterSlug: "nuclei",
            sectionHeading: "6. Einstein's Mass–Energy Equivalence",
            concept: "mass-energy equivalence",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 11, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["mass energy equivalence", "E equals mc squared"],
        },
        {
          id: "nuc-mass-defect",
          expression: "Δm = [Zm(p) + (A−Z)m(n)] − M(nucleus)",
          expressionLatex: "\\Delta m = [Zm_p+(A-Z)m_n]-M",
          label: "Mass defect",
          variables: [
            { symbol: "Δm", name: "mass defect — the 'missing' mass", unit: "u or kg", dimension: "[M]" },
            { symbol: "m(p), m(n)", name: "mass of a free proton and free neutron", unit: "u", dimension: "[M]" },
            { symbol: "M", name: "actual measured mass of the nucleus", unit: "u", dimension: "[M]" },
          ],
          conditions: ["Δm is always positive — a bound nucleus is always lighter than its separated, free constituent nucleons"],
          conceptLink: {
            chapterSlug: "nuclei",
            sectionHeading: "7. Mass Defect and Binding Energy",
            concept: "mass defect",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 11, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["mass defect formula", "delta m Zmp A minus Z mn minus M"],
        },
        {
          id: "nuc-binding-energy",
          expression: "BE = Δm c²   (BE in MeV = Δm in u × 931.5)",
          expressionLatex: "BE = \\Delta m\\, c^2",
          label: "Binding energy of a nucleus",
          derivedFrom: "Direct application of E = mc² to the mass defect",
          variables: [
            { symbol: "BE", name: "binding energy — energy needed to completely separate the nucleus into free nucleons", unit: "MeV", dimension: "[ML²T⁻²]" },
          ],
          conditions: ["Higher BE means a MORE stable (more tightly bound) nucleus"],
          conceptLink: {
            chapterSlug: "nuclei",
            sectionHeading: "7. Mass Defect and Binding Energy",
            concept: "binding energy",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 11, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["binding energy formula", "BE equals delta m c squared 931.5"],
        },
        {
          id: "nuc-binding-energy-per-nucleon",
          expression: "BE per nucleon = BE / A",
          expressionLatex: "\\dfrac{BE}{A}",
          label: "Binding energy per nucleon",
          derivedFrom: "The single most important quantity for judging nuclear stability, plotted against A gives the famous BE/A curve",
          variables: [],
          conditions: ["Peaks around A ≈ 56 (iron) — nuclei near this peak are the most stable; both fission (splitting heavy nuclei) and fusion (combining light nuclei) release energy by moving TOWARD this peak"],
          commonMistakes: [
            "Both fission AND fusion release energy because both move the resulting nuclei's BE/A closer to the peak at iron — not because one 'always releases more' than the other in every case",
          ],
          usedIn: ["kinetic-theory-of-gases"],
          conceptLink: {
            chapterSlug: "nuclei",
            sectionHeading: "8. Binding Energy per Nucleon: The Stability Curve",
            concept: "binding energy per nucleon",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 10, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["binding energy per nucleon", "BE by A stability curve"],
        },
      ],
    },
    {
      id: "nuc-fission-fusion",
      title: "Nuclear Fission & Fusion",
      intro:
        "Both processes release energy from the SAME underlying source — moving nuclei toward the binding-energy peak near iron — but they operate at opposite ends of the periodic table.",
      formulas: [
        {
          id: "nuc-q-value-nuclear-reaction",
          expression: "Q = [Σm(reactants) − Σm(products)] c²",
          expressionLatex: "Q = [\\Sigma m_{reactants}-\\Sigma m_{products}]c^2",
          label: "Q-value of a nuclear reaction (fission or fusion)",
          derivedFrom: "Conservation of mass-energy applied to the reactants and products of any nuclear reaction",
          variables: [
            { symbol: "Q", name: "energy released (Q > 0) or absorbed (Q < 0) in the reaction", unit: "MeV", dimension: "[ML²T⁻²]" },
          ],
          conditions: ["Q > 0 means an exothermic (energy-releasing) reaction — true for both typical fission of heavy nuclei and fusion of light nuclei"],
          conceptLink: {
            chapterSlug: "nuclei",
            sectionHeading: "9. Nuclear Fission",
            concept: "Q-value of a nuclear reaction",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 10, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["Q value nuclear reaction", "mass defect energy released fission fusion"],
        },
      ],
      importantObservations: [
        "A nuclear chain reaction is self-sustaining only above a CRITICAL SIZE (critical mass) of fissile material — below it, too many neutrons escape without causing further fission",
        "Fusion requires extremely high temperatures (tens of millions of kelvin) to overcome the strong electrostatic repulsion between positively charged nuclei before the short-range nuclear force can take over",
      ],
    },
    {
      id: "nuc-radioactivity",
      title: "Radioactive Decay",
      intro:
        "Radioactive decay is a purely random, memoryless process at the level of any single nucleus — yet a large enough sample decays with perfect statistical predictability, following one clean exponential law.",
      formulas: [
        {
          id: "nuc-radioactive-decay-law",
          expression: "N = N₀ e^(−λt)",
          expressionLatex: "N = N_0 e^{-\\lambda t}",
          label: "Law of radioactive decay",
          derivedFrom: "Rate of decay is proportional to the number of undecayed nuclei present: dN/dt = −λN, solved as an exponential decay",
          variables: [
            { symbol: "N", name: "number of undecayed nuclei at time t", unit: "dimensionless (a count)", dimension: "[M⁰L⁰T⁰]" },
            { symbol: "N₀", name: "initial number of undecayed nuclei", unit: "dimensionless (a count)", dimension: "[M⁰L⁰T⁰]" },
            { symbol: "λ", name: "decay constant, a property of the specific radioactive isotope", unit: "s⁻¹", dimension: "[T⁻¹]" },
          ],
          conditions: ["Decay constant λ is completely independent of external conditions (temperature, pressure, chemical state) — purely a nuclear property"],
          conceptLink: {
            chapterSlug: "nuclei",
            sectionHeading: "22. The Law of Radioactive Decay and Half-Life",
            concept: "law of radioactive decay",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 10, jeeAdvanced: 5, neet: 13, mhtCet: 8 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["radioactive decay law", "N equals N0 e power minus lambda t"],
        },
        {
          id: "nuc-half-life-decay-constant",
          expression: "T(1/2) = ln2 / λ = 0.693/λ",
          expressionLatex: "T_{1/2} = \\dfrac{\\ln 2}{\\lambda} = \\dfrac{0.693}{\\lambda}",
          label: "Half-life in terms of the decay constant",
          derivedFrom: "Time for N to fall to N₀/2 in the decay law: ½ = e^(−λT(1/2))",
          variables: [
            { symbol: "T(1/2)", name: "half-life — time for half the sample to decay", unit: "s", dimension: "[T]" },
          ],
          conditions: ["Half-life is CONSTANT regardless of how much sample remains — it doesn't matter if you start with 1 gram or 1 kg, half of whatever is left decays in each successive half-life"],
          conceptLink: {
            chapterSlug: "nuclei",
            sectionHeading: "22. The Law of Radioactive Decay and Half-Life",
            concept: "half-life",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 4, neet: 12, mhtCet: 8 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["half life decay constant", "T half equals 0.693 by lambda"],
        },
        {
          id: "nuc-mean-life",
          expression: "τ = 1/λ = T(1/2) / ln2 ≈ 1.44 T(1/2)",
          expressionLatex: "\\tau = \\dfrac{1}{\\lambda} = 1.44\\,T_{1/2}",
          label: "Mean life (average life) of a radioactive sample",
          variables: [
            { symbol: "τ", name: "mean life — average lifetime of a nucleus before decaying", unit: "s", dimension: "[T]" },
          ],
          conditions: ["Mean life is always LONGER than half-life (τ ≈ 1.44 T(1/2)) — a frequently tested numeric ratio"],
          commonMistakes: [
            "Mean life and half-life are NOT the same quantity — mixing them up in a calculation gives an answer off by the factor 1.44 (or 0.693, its reciprocal)",
          ],
          conceptLink: {
            chapterSlug: "nuclei",
            sectionHeading: "22. The Law of Radioactive Decay and Half-Life",
            concept: "mean life",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 4, neet: 7, mhtCet: 5 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["mean life radioactive", "tau equals 1 by lambda", "1.44 half life"],
        },
        {
          id: "nuc-activity",
          expression: "A = λN = A₀ e^(−λt)",
          expressionLatex: "A = \\lambda N = A_0 e^{-\\lambda t}",
          label: "Activity of a radioactive sample",
          variables: [
            { symbol: "A", name: "activity — number of decays per second", unit: "Bq (becquerel) or Ci (curie)", dimension: "[T⁻¹]", notes: "1 Ci = 3.7 × 10¹⁰ Bq" },
          ],
          conditions: ["Activity decays with the SAME time constant λ as N itself — halving N also halves the activity"],
          conceptLink: {
            chapterSlug: "nuclei",
            sectionHeading: "22. The Law of Radioactive Decay and Half-Life",
            concept: "activity",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 10, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["activity radioactive formula", "A equals lambda N", "becquerel curie"],
        },
        {
          id: "nuc-fraction-remaining",
          expression: "N/N₀ = (1/2)^(t/T(1/2))",
          expressionLatex: "\\dfrac{N}{N_0} = \\left(\\dfrac{1}{2}\\right)^{t/T_{1/2}}",
          label: "Fraction of a sample remaining after n half-lives",
          derivedFrom: "Equivalent restatement of the decay law directly in terms of the number of elapsed half-lives",
          variables: [],
          conditions: ["Often the fastest way to solve a problem when t is given as a whole-number multiple of T(1/2)"],
          conceptLink: {
            chapterSlug: "nuclei",
            sectionHeading: "22. The Law of Radioactive Decay and Half-Life",
            concept: "fraction remaining after half-lives",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 10, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["fraction remaining half life", "N by N0 half power t by T half"],
        },
      ],
      examNotes:
        "Alpha decay reduces mass number by 4 and atomic number by 2; beta-minus decay keeps mass number the same but increases atomic number by 1 — boards frequently ask to balance a decay equation using these rules alongside the decay-law formulas.",
    },
  ],
};
