import type { ChapterFormulaSheet } from "./types";

export const oscillationsFormulaSheet: ChapterFormulaSheet = {
  chapterSlug: "oscillations",
  chapterName: "Oscillations",
  className: "11",
  version: "1.0.0",
  lastUpdated: "2026-07-04",
  examCoverage: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
  quickRevisionIds: [
    "osc-shm-equation",
    "osc-velocity-displacement",
    "osc-spring-period",
    "osc-pendulum-period",
    "osc-energy-shm",
    "osc-springs-combination",
  ],
  topicGroups: [
    {
      id: "osc-shm-basics",
      title: "SHM — Equation of Motion & Kinematics",
      intro:
        "SHM is defined by one property: restoring acceleration proportional to displacement, a = −ω²x. Spot that, and T = 2π/ω follows instantly.",
      formulas: [
        {
          id: "osc-shm-equation",
          expression: "a = −ω²x;   x = A sin(ωt + φ);   T = 2π/ω",
          expressionLatex: "a = -\\omega^2 x,\\quad x = A\\sin(\\omega t + \\varphi)",
          label: "Defining equation and solution of SHM",
          variables: [
            { symbol: "ω", name: "angular frequency", unit: "rad/s", dimension: "[T⁻¹]" },
            { symbol: "A", name: "amplitude", unit: "m", dimension: "[L]" },
            { symbol: "φ", name: "initial phase", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
            { symbol: "T", name: "time period", unit: "s", dimension: "[T]" },
          ],
          conditions: ["a ∝ −x is the TEST for SHM — check it before quoting any period formula"],
          commonMistakes: [
            "Time from mean to extreme is T/4, but mean to A/2 takes only T/12 — SHM is fast near the mean, slow near the extremes",
          ],
          usedIn: ["waves"],
          conceptLink: {
            chapterSlug: "oscillations",
            sectionHeading: "1. Simple Harmonic Motion",
            concept: "defining equation of SHM",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 12, jeeAdvanced: 6, neet: 15, mhtCet: 11 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["SHM equation", "a minus omega squared x", "A sin omega t"],
        },
        {
          id: "osc-velocity-displacement",
          expression: "v = ω√(A² − x²);   a = −ω²x",
          expressionLatex: "v = \\omega\\sqrt{A^2 - x^2}",
          label: "Velocity and acceleration at displacement x",
          derivedFrom: "Differentiating x(t), then eliminating t",
          variables: [
            { symbol: "v", name: "speed at displacement x", unit: "m/s", dimension: "[LT⁻¹]" },
            { symbol: "x", name: "displacement from the mean position", unit: "m", dimension: "[L]" },
          ],
          conditions: [
            "v(max) = ωA at the mean position; a(max) = ω²A at the extremes",
            "v and a are 90° out of phase; a and x are 180° out of phase",
          ],
          commonMistakes: [
            "At the extreme, v = 0 but a is MAXIMUM — zero speed never means zero acceleration in SHM",
          ],
          conceptLink: {
            chapterSlug: "oscillations",
            sectionHeading: "2. Kinematics of SHM",
            concept: "velocity and acceleration in SHM",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 10, neet: 13, mhtCet: 9 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["omega root A squared minus x squared", "vmax omega A"],
        },
      ],
      importantObservations: [
        "SHM is the projection of uniform circular motion on a diameter — the reference-circle picture solves every phase/timing question",
      ],
    },
    {
      id: "osc-systems",
      title: "Oscillating Systems — Springs & Pendulums",
      intro:
        "Every system reduces to finding its ω. Spring: √(k/m). Pendulum: √(g/L). Everything else is variations on these two.",
      formulas: [
        {
          id: "osc-spring-period",
          expression: "T = 2π √(m/k)",
          expressionLatex: "T = 2\\pi\\sqrt{\\dfrac{m}{k}}",
          label: "Period of a spring-mass system",
          derivedFrom: "F = −kx compared with F = −mω²x",
          variables: [
            { symbol: "m", name: "oscillating mass", unit: "kg", dimension: "[M]" },
            { symbol: "k", name: "spring constant", unit: "N/m", dimension: "[MT⁻²]" },
          ],
          conditions: [
            "Independent of gravity — the same on Earth, in a lift, or in orbit",
            "Vertical spring: gravity only SHIFTS the mean position, period unchanged",
          ],
          commonMistakes: [
            "Cutting a spring into n equal parts makes each piece n times STIFFER (k' = nk), so the period drops by √n",
          ],
          usedIn: ["mechanical-properties-of-solids"],
          conceptLink: {
            chapterSlug: "oscillations",
            sectionHeading: "3. Spring-Mass System",
            concept: "spring-mass oscillator",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 11, jeeAdvanced: 5, neet: 14, mhtCet: 10 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["2 pi root m by k", "spring period", "cut spring"],
        },
        {
          id: "osc-springs-combination",
          expression: "Series: 1/k(eq) = 1/k₁ + 1/k₂;   Parallel: k(eq) = k₁ + k₂",
          expressionLatex: "k_{series} = \\dfrac{k_1k_2}{k_1+k_2},\\quad k_{parallel} = k_1 + k_2",
          label: "Combination of springs",
          variables: [
            { symbol: "k(eq)", name: "equivalent spring constant", unit: "N/m", dimension: "[MT⁻²]" },
          ],
          conditions: ["OPPOSITE of resistors: springs side-by-side (or one on each side of the mass) ADD; end-to-end combine reciprocally"],
          commonMistakes: [
            "A mass between two springs attached to opposite walls is a PARALLEL combination — both springs push it back together",
          ],
          conceptLink: {
            chapterSlug: "oscillations",
            sectionHeading: "3. Spring-Mass System",
            concept: "springs in series and parallel",
          },
          examTags: ["jee-main", "neet", "mht-cet"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 10, mhtCet: 8 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["springs series parallel", "equivalent spring constant"],
        },
        {
          id: "osc-pendulum-period",
          expression: "T = 2π √(L/g)",
          expressionLatex: "T = 2\\pi\\sqrt{\\dfrac{L}{g}}",
          label: "Period of a simple pendulum",
          derivedFrom: "Restoring torque −mgL sinθ ≈ −mgLθ for small angles",
          derivation: {
            startsFrom: "Tangential restoring force on the bob at small angular displacement θ",
            steps: [
              { statement: "Restoring force along the arc", expression: "F = −mg sinθ ≈ −mgθ" },
              { statement: "With arc displacement x = Lθ", expression: "a = −(g/L)x" },
              { statement: "Compare with a = −ω²x", expression: "ω = √(g/L) ⟹ T = 2π√(L/g)" },
            ],
            askedInBoards: true,
          },
          variables: [
            { symbol: "L", name: "length from pivot to the bob's centre", unit: "m", dimension: "[L]" },
            { symbol: "g", name: "effective gravitational acceleration", unit: "m/s²", dimension: "[LT⁻²]" },
          ],
          conditions: [
            "Small angles only (sinθ ≈ θ)",
            "Independent of the bob's mass",
            "In an accelerating frame use g(eff): lift up → g + a; free fall → T infinite (no oscillation)",
          ],
          commonMistakes: [
            "The seconds pendulum has T = 2 s (not 1 s) — one second per HALF swing, L ≈ 1 m on Earth",
          ],
          usedIn: ["thermal-properties-of-matter", "gravitation"],
          conceptLink: {
            chapterSlug: "oscillations",
            sectionHeading: "4. Simple Pendulum",
            concept: "simple pendulum",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 10, jeeAdvanced: 4, neet: 15, mhtCet: 11 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["2 pi root L by g", "simple pendulum", "seconds pendulum", "g effective"],
        },
        {
          id: "osc-physical-pendulum",
          expression: "T = 2π √(I/(mgd))",
          expressionLatex: "T = 2\\pi\\sqrt{\\dfrac{I}{mgd}}",
          label: "Period of a physical (compound) pendulum",
          variables: [
            { symbol: "I", name: "moment of inertia about the pivot", unit: "kg·m²", dimension: "[ML²]" },
            { symbol: "d", name: "distance from pivot to the centre of mass", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Reduces to the simple pendulum when I = mL² and d = L", "Rod pivoted at one end: T = 2π√(2L/3g)"],
          usedIn: ["system-of-particles-and-rotational-motion"],
          conceptLink: {
            chapterSlug: "oscillations",
            sectionHeading: "4. Simple Pendulum",
            concept: "physical pendulum",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "medium",
          examStats: { jeeMain: 5, jeeAdvanced: 4, neet: 5 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["physical pendulum", "compound pendulum", "I by mgd"],
        },
      ],
      importantObservations: [
        "A floating cylinder pushed down, liquid in a U-tube, and a ball in a spherical bowl all execute SHM — derive ω from a = −ω²x each time rather than memorising",
      ],
      examNotes:
        "NEET repeats pendulum-in-lift and spring-cutting; JEE Advanced favours energy-method derivations of ω for unusual systems.",
    },
    {
      id: "osc-energy-damping",
      title: "Energy in SHM, Damping & Resonance",
      intro:
        "Total energy in SHM is constant and proportional to A² — kinetic and potential merely trade places twice every period.",
      formulas: [
        {
          id: "osc-energy-shm",
          expression: "E = ½kA² = ½mω²A²;   KE = ½mω²(A² − x²);   PE = ½mω²x²",
          expressionLatex: "E = \\tfrac{1}{2}m\\omega^2A^2",
          label: "Energy in SHM",
          derivedFrom: "KE + PE at any x, using v = ω√(A² − x²)",
          variables: [
            { symbol: "E", name: "total mechanical energy", unit: "J", dimension: "[ML²T⁻²]" },
            { symbol: "A", name: "amplitude", unit: "m", dimension: "[L]" },
          ],
          conditions: [
            "KE = PE at x = A/√2, not at A/2",
            "KE and PE each oscillate at TWICE the SHM frequency",
          ],
          commonMistakes: [
            "Doubling the amplitude quadruples the energy — E ∝ A²",
          ],
          usedIn: ["work-energy-and-power", "waves"],
          conceptLink: {
            chapterSlug: "oscillations",
            sectionHeading: "5. Energy in SHM",
            concept: "energy in simple harmonic motion",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 4, neet: 13, mhtCet: 9 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["energy SHM", "half k A squared", "KE PE equal"],
        },
        {
          id: "osc-damped",
          expression: "x = A e^(−bt/2m) cos(ω't + φ)",
          expressionLatex: "x = Ae^{-bt/2m}\\cos(\\omega' t + \\varphi)",
          label: "Damped oscillation",
          variables: [
            { symbol: "b", name: "damping constant (F(damp) = −bv)", unit: "kg/s", dimension: "[MT⁻¹]" },
            { symbol: "ω'", name: "damped angular frequency √(k/m − b²/4m²)", unit: "rad/s", dimension: "[T⁻¹]" },
          ],
          conditions: ["Amplitude decays exponentially; energy decays as e^(−bt/m) — twice as fast as amplitude"],
          conceptLink: {
            chapterSlug: "oscillations",
            sectionHeading: "6. Damped and Forced Oscillations",
            concept: "damped oscillations",
          },
          examTags: ["jee-main", "neet"],
          frequency: "medium",
          examStats: { jeeMain: 5, neet: 6 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["damped oscillation", "exponential decay amplitude"],
        },
        {
          id: "osc-resonance",
          expression: "Resonance: driving frequency = natural frequency (ω(d) = ω₀)",
          label: "Forced oscillations and resonance",
          variables: [
            { symbol: "ω(d)", name: "driving (forcing) frequency", unit: "rad/s", dimension: "[T⁻¹]" },
            { symbol: "ω₀", name: "natural frequency of the system", unit: "rad/s", dimension: "[T⁻¹]" },
          ],
          conditions: [
            "Steady state: the system oscillates at the DRIVING frequency, not its own",
            "Amplitude peaks at resonance; lighter damping → sharper, taller peak",
          ],
          usedIn: ["waves", "alternating-current"],
          conceptLink: {
            chapterSlug: "oscillations",
            sectionHeading: "6. Damped and Forced Oscillations",
            concept: "resonance",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "medium",
          examStats: { jeeMain: 4, neet: 7, mhtCet: 5 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["resonance", "forced oscillation", "natural frequency"],
        },
      ],
      importantObservations: [
        "Soldiers break step on bridges to avoid resonance — the Tacoma Narrows collapse is the textbook cautionary tale",
      ],
    },
  ],
};
