import type { ChapterFormulaSheet } from "./types";

export const physicalWorldAndMeasurementFormulaSheet: ChapterFormulaSheet = {
  chapterSlug: "physical-world-and-measurement",
  chapterName: "Physical World & Measurement",
  className: "11",
  version: "1.0.0",
  lastUpdated: "2026-07-08",
  examCoverage: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
  quickRevisionIds: [
    "pwm-unit-conversion-dimensions",
    "pwm-error-product-quotient",
    "pwm-error-power",
    "pwm-vernier-least-count",
    "pwm-screw-gauge-least-count",
  ],
  topicGroups: [
    {
      id: "pwm-dimensional-analysis",
      title: "Units & Dimensional Analysis",
      intro:
        "Dimensions are the DNA of a physical quantity — every valid physics equation must have matching dimensions on both sides, and this single check catches a huge fraction of algebra mistakes.",
      formulas: [
        {
          id: "pwm-principle-homogeneity",
          expression: "[LHS] = [RHS]  for any dimensionally correct equation",
          expressionLatex: "[\\text{LHS}] = [\\text{RHS}]",
          label: "Principle of homogeneity of dimensions",
          variables: [],
          conditions: ["A necessary but NOT sufficient condition for an equation to be correct — dimensionally consistent equations can still be numerically wrong (missing a dimensionless constant like 2 or π)"],
          commonMistakes: [
            "Dimensional correctness does not prove an equation right, only that it's not obviously wrong — purely numeric constants (2, ½, π) are invisible to dimensional analysis",
          ],
          conceptLink: {
            chapterSlug: "physical-world-and-measurement",
            sectionHeading: "5. Applications of Dimensional Analysis",
            concept: "principle of homogeneity of dimensions",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 10, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["principle of homogeneity", "dimensional consistency check"],
        },
        {
          id: "pwm-unit-conversion-dimensions",
          expression: "n₁u₁ = n₂u₂  ⟹  n₂ = n₁ [M₁/M₂]ᵃ [L₁/L₂]ᵇ [T₁/T₂]ᶜ",
          expressionLatex: "n_2 = n_1\\left(\\dfrac{M_1}{M_2}\\right)^a\\left(\\dfrac{L_1}{L_2}\\right)^b\\left(\\dfrac{T_1}{T_2}\\right)^c",
          label: "Converting a physical quantity between unit systems using dimensions",
          derivedFrom: "The MAGNITUDE of a physical quantity (n×u) is invariant — only the numerical value n changes when the unit u changes",
          derivation: {
            startsFrom: "A quantity Q has dimensional formula [MᵃLᵇTᶜ] and numerical value n₁ in system 1 (units M₁, L₁, T₁)",
            steps: [
              { statement: "The physical quantity itself is unchanged across systems", expression: "n₁[M₁ᵃL₁ᵇT₁ᶜ] = n₂[M₂ᵃL₂ᵇT₂ᶜ]" },
              { statement: "Solve for the new numerical value", expression: "n₂ = n₁(M₁/M₂)ᵃ(L₁/L₂)ᵇ(T₁/T₂)ᶜ" },
            ],
            askedInBoards: true,
          },
          variables: [
            { symbol: "a, b, c", name: "powers of mass, length, time in the quantity's dimensional formula", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["Requires knowing the correct dimensional formula [MᵃLᵇTᶜ] of the quantity being converted"],
          conceptLink: {
            chapterSlug: "physical-world-and-measurement",
            sectionHeading: "5. Applications of Dimensional Analysis",
            concept: "unit conversion using dimensional analysis",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 11, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["unit conversion dimensional analysis", "n1u1 equals n2u2"],
        },
      ],
      importantObservations: [
        "Dimensional analysis can also derive the FORM of a relation (e.g. T = 2π√(l/g) for a pendulum) up to an unknown dimensionless constant — but it can never find that constant",
        "Purely dimensionless quantities (angle, strain, refractive index) cannot be checked or derived by dimensional analysis at all",
      ],
    },
    {
      id: "pwm-errors",
      title: "Significant Figures & Errors in Measurement",
      intro:
        "No measurement is exact. Knowing how small errors in individual readings combine — adding, multiplying, or raised to powers — decides how much you can trust a calculated final answer.",
      formulas: [
        {
          id: "pwm-percentage-error",
          expression: "% error = (Δa / a) × 100",
          expressionLatex: "\\%\\,\\text{error} = \\dfrac{\\Delta a}{a}\\times 100",
          label: "Percentage error in a single measured quantity",
          variables: [
            { symbol: "Δa", name: "mean absolute error in the measurement", unit: "same as a", dimension: "same as a" },
            { symbol: "a", name: "mean (true) value of the quantity", unit: "context-dependent", dimension: "context-dependent" },
          ],
          conceptLink: {
            chapterSlug: "physical-world-and-measurement",
            sectionHeading: "9. Errors of Measurement",
            concept: "percentage error",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 7, neet: 9, mhtCet: 6 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["percentage error formula", "delta a by a times 100"],
        },
        {
          id: "pwm-error-sum-difference",
          expression: "Δ(a ± b) = Δa + Δb   (maximum possible error)",
          expressionLatex: "\\Delta(a\\pm b) = \\Delta a + \\Delta b",
          label: "Error propagation in sum or difference",
          derivedFrom: "Worst-case scenario: both individual errors act in the same unfavourable direction simultaneously",
          variables: [],
          conditions: ["Errors ADD even when the quantities are SUBTRACTED — this is the single most commonly missed point in error analysis"],
          commonMistakes: [
            "For a difference (a − b), students often (wrongly) subtract the errors too — absolute errors always add, regardless of whether the quantities add or subtract",
          ],
          conceptLink: {
            chapterSlug: "physical-world-and-measurement",
            sectionHeading: "10. Propagation of Errors",
            concept: "error propagation in addition/subtraction",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 3, neet: 10, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["error propagation addition subtraction", "delta a plus delta b"],
        },
        {
          id: "pwm-error-product-quotient",
          expression: "Δ(ab)/(ab) = Δa/a + Δb/b   (same rule for a/b)",
          expressionLatex: "\\dfrac{\\Delta(ab)}{ab} = \\dfrac{\\Delta a}{a}+\\dfrac{\\Delta b}{b}",
          label: "Error propagation in product or quotient",
          derivedFrom: "Taking logarithms of Z = ab (or a/b) turns multiplication into addition, then differentiating",
          variables: [],
          conditions: ["RELATIVE (fractional) errors add for both multiplication AND division — errors never partially cancel"],
          commonMistakes: [
            "For a quotient a/b, the relative errors still ADD — they do not subtract even though the operation is division",
          ],
          usedIn: ["mechanical-properties-of-solids"],
          conceptLink: {
            chapterSlug: "physical-world-and-measurement",
            sectionHeading: "10. Propagation of Errors",
            concept: "error propagation in multiplication/division",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 4, neet: 11, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["error propagation product quotient", "relative error multiplication division"],
        },
        {
          id: "pwm-error-power",
          expression: "For Z = AᵖBᵍ/Cʳ:  ΔZ/Z = p(ΔA/A) + q(ΔB/B) + r(ΔC/C)",
          expressionLatex: "\\dfrac{\\Delta Z}{Z} = p\\dfrac{\\Delta A}{A} + q\\dfrac{\\Delta B}{B} + r\\dfrac{\\Delta C}{C}",
          label: "Error propagation with powers",
          derivedFrom: "Generalisation of the product rule — an exponent multiplies through the relative error term",
          variables: [
            { symbol: "p, q, r", name: "powers to which A, B, C are raised in the formula for Z", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["A quantity that appears SQUARED contributes DOUBLE its own relative error — this is the classic source of dominant error in a calculation"],
          commonMistakes: [
            "Forgetting to multiply by the power — e.g. for g = 4π²l/T², the error in T contributes TWICE (since T² appears), making timing the dominant source of error in a pendulum experiment",
          ],
          usedIn: ["oscillations"],
          conceptLink: {
            chapterSlug: "physical-world-and-measurement",
            sectionHeading: "10. Propagation of Errors",
            concept: "error propagation with powers",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 10, mhtCet: 6 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["error propagation powers", "relative error exponent multiply"],
        },
      ],
      examNotes:
        "Boards and JEE Main both love pendulum-experiment error questions (g = 4π²l/T²) — the T² term means a small timing error dominates the final error in g. Recognise this pattern instantly.",
    },
    {
      id: "pwm-instruments",
      title: "Vernier Calipers & Screw Gauge",
      intro:
        "Both instruments work on the same idea — a fixed main scale plus a sliding/rotating scale that lets you read a fraction of the smallest main-scale division.",
      formulas: [
        {
          id: "pwm-vernier-least-count",
          expression: "LC = 1 MSD − 1 VSD",
          expressionLatex: "LC = 1\\,\\text{MSD} - 1\\,\\text{VSD}",
          label: "Least count of a Vernier caliper",
          derivedFrom: "If n vernier divisions span (n−1) main-scale divisions, each VSD is slightly smaller than each MSD by exactly this amount",
          variables: [
            { symbol: "MSD", name: "main scale division", unit: "typically mm", dimension: "[L]" },
            { symbol: "VSD", name: "vernier scale division", unit: "typically mm", dimension: "[L]" },
          ],
          conditions: ["Standard vernier: 1 MSD = 1 mm, 10 VSD = 9 MSD, giving LC = 0.1 mm = 0.01 cm"],
          conceptLink: {
            chapterSlug: "physical-world-and-measurement",
            sectionHeading: "11. Vernier Calipers",
            concept: "least count of a Vernier caliper",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 7, neet: 10, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["vernier caliper least count", "LC 1 MSD minus 1 VSD"],
        },
        {
          id: "pwm-vernier-reading",
          expression: "True reading = MSR + (VSC × LC) ± zero error correction",
          expressionLatex: "R = \\text{MSR} + (\\text{VSC}\\times LC)",
          label: "Total reading of a Vernier caliper",
          variables: [
            { symbol: "MSR", name: "main scale reading (before the vernier zero)", unit: "cm or mm", dimension: "[L]" },
            { symbol: "VSC", name: "vernier scale coincidence — which vernier division exactly lines up with a main scale division", unit: "dimensionless (a count)", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["Zero error must be SUBTRACTED if positive, ADDED if negative — sign convention is a frequent source of mistakes"],
          commonMistakes: [
            "Positive zero error means the instrument OVER-reads, so it must be subtracted from the observed reading — many students add it by mistake",
          ],
          conceptLink: {
            chapterSlug: "physical-world-and-measurement",
            sectionHeading: "11. Vernier Calipers",
            concept: "Vernier caliper reading and zero error",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 7, neet: 10, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["vernier caliper reading formula", "zero error correction vernier"],
        },
        {
          id: "pwm-screw-gauge-pitch",
          expression: "Pitch = distance moved on main scale / number of full rotations of the screw",
          expressionLatex: "\\text{Pitch} = \\dfrac{\\text{distance moved}}{\\text{number of rotations}}",
          label: "Pitch of a screw gauge",
          variables: [],
          conditions: ["Typical pitch values: 0.5 mm or 1 mm per full rotation"],
          conceptLink: {
            chapterSlug: "physical-world-and-measurement",
            sectionHeading: "12. Screw Gauge (Micrometer Screw)",
            concept: "pitch of a screw gauge",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 6, neet: 8, mhtCet: 5 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["screw gauge pitch formula", "pitch distance by rotations"],
        },
        {
          id: "pwm-screw-gauge-least-count",
          expression: "LC = Pitch / (number of divisions on the circular scale)",
          expressionLatex: "LC = \\dfrac{\\text{Pitch}}{\\text{circular scale divisions}}",
          label: "Least count of a screw gauge",
          variables: [],
          conditions: ["Typical: pitch 1 mm, 100 circular divisions gives LC = 0.01 mm — ten times finer than a standard Vernier caliper"],
          commonMistakes: [
            "A screw gauge is finer than a Vernier caliper (LC ~0.01 mm vs ~0.01 cm) — a factor-of-10 difference that's easy to misremember under pressure",
          ],
          conceptLink: {
            chapterSlug: "physical-world-and-measurement",
            sectionHeading: "12. Screw Gauge (Micrometer Screw)",
            concept: "least count of a screw gauge",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 7, neet: 10, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["screw gauge least count", "LC pitch by circular scale divisions"],
        },
        {
          id: "pwm-screw-gauge-reading",
          expression: "Reading = MSR + (CSR × LC) − zero error correction",
          expressionLatex: "R = \\text{MSR} + (\\text{CSR}\\times LC)",
          label: "Total reading of a screw gauge",
          variables: [
            { symbol: "CSR", name: "circular scale reading — division on the circular scale coinciding with the reference line", unit: "dimensionless (a count)", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["Same zero-error sign convention as the Vernier caliper: positive zero error is subtracted, negative is added"],
          conceptLink: {
            chapterSlug: "physical-world-and-measurement",
            sectionHeading: "12. Screw Gauge (Micrometer Screw)",
            concept: "screw gauge reading and zero error",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 6, neet: 9, mhtCet: 6 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["screw gauge reading formula", "MSR CSR LC zero error"],
        },
      ],
      importantObservations: [
        "Backlash error (screw gauge) — always turn the screw in the SAME direction when approaching a measurement to avoid this instrumental error",
      ],
    },
  ],
};
