import type { ChapterFormulaSheet } from "./types";

export const rayOpticsAndOpticalInstrumentsFormulaSheet: ChapterFormulaSheet = {
  chapterSlug: "ray-optics-and-optical-instruments",
  chapterName: "Ray Optics & Optical Instruments",
  className: "12",
  version: "1.0.0",
  lastUpdated: "2026-07-09",
  examCoverage: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
  quickRevisionIds: [
    "opt-mirror-formula",
    "opt-snells-law",
    "opt-critical-angle",
    "opt-lens-makers-formula",
    "opt-lens-formula",
    "opt-prism-formula",
    "opt-telescope-magnification",
  ],
  topicGroups: [
    {
      id: "opt-mirrors",
      title: "Spherical Mirrors",
      intro:
        "Mirror formula and magnification apply identically to concave and convex mirrors once the sign convention is fixed — the formula never changes, only the signs of the quantities plugged in.",
      formulas: [
        {
          id: "opt-mirror-focal-length-radius",
          expression: "f = R/2",
          expressionLatex: "f = \\dfrac{R}{2}",
          label: "Focal length of a spherical mirror",
          variables: [
            { symbol: "f", name: "focal length", unit: "m", dimension: "[L]" },
            { symbol: "R", name: "radius of curvature", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Valid for paraxial rays (close to the principal axis, small aperture) — wide-aperture mirrors suffer spherical aberration"],
          conceptLink: {
            chapterSlug: "ray-optics-and-optical-instruments",
            sectionHeading: "6. Spherical Aberration and the Mirror Formula",
            concept: "focal length of a spherical mirror",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 7, neet: 9, mhtCet: 6 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["focal length radius of curvature", "f equals R by 2"],
        },
        {
          id: "opt-mirror-formula",
          expression: "1/v + 1/u = 1/f",
          expressionLatex: "\\dfrac{1}{v}+\\dfrac{1}{u} = \\dfrac{1}{f}",
          label: "Mirror formula",
          variables: [
            { symbol: "v", name: "image distance from the mirror", unit: "m", dimension: "[L]" },
            { symbol: "u", name: "object distance from the mirror", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Requires the Cartesian sign convention: distances measured from the pole, against the incident light direction are negative"],
          commonMistakes: [
            "Mixing up sign conventions between mirrors and lenses is the single biggest source of errors in this chapter — mirror formula uses 1/v + 1/u, lens formula uses 1/v − 1/u",
          ],
          conceptLink: {
            chapterSlug: "ray-optics-and-optical-instruments",
            sectionHeading: "6. Spherical Aberration and the Mirror Formula",
            concept: "mirror formula",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 10, jeeAdvanced: 4, neet: 13, mhtCet: 8 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["mirror formula", "1 by v plus 1 by u equals 1 by f"],
        },
        {
          id: "opt-mirror-magnification",
          expression: "m = h'/h = −v/u",
          expressionLatex: "m = \\dfrac{h'}{h} = -\\dfrac{v}{u}",
          label: "Magnification of a spherical mirror",
          variables: [
            { symbol: "m", name: "linear magnification", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
            { symbol: "h', h", name: "image and object heights", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Negative m means an inverted, real image; positive m means an erect, virtual image (with the standard sign convention)"],
          conceptLink: {
            chapterSlug: "ray-optics-and-optical-instruments",
            sectionHeading: "7. Magnification for Spherical Mirrors",
            concept: "magnification of a spherical mirror",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 10, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["mirror magnification formula", "m equals minus v by u"],
        },
        {
          id: "opt-mirror-power",
          expression: "P = 1/f   (f in metres)",
          expressionLatex: "P = \\dfrac{1}{f}",
          label: "Power of a mirror",
          variables: [
            { symbol: "P", name: "power of the mirror", unit: "D (dioptre)", dimension: "[L⁻¹]" },
          ],
          conditions: ["Concave mirror: P is positive (converging); convex mirror: P is negative (diverging), by the standard convention"],
          conceptLink: {
            chapterSlug: "ray-optics-and-optical-instruments",
            sectionHeading: "9. Image Formation by a Convex Mirror and Power of a Mirror",
            concept: "power of a mirror",
          },
          examTags: ["jee-main", "neet", "mht-cet"],
          frequency: "medium",
          examStats: { jeeMain: 5, neet: 6, mhtCet: 4 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["power of mirror formula", "P equals 1 by f dioptre"],
        },
        {
          id: "opt-newtons-formula-mirror",
          expression: "xy = f²",
          expressionLatex: "xy = f^2",
          label: "Newton's formula for mirrors",
          derivedFrom: "Substituting u = −(f+x), v = −(f+y) into the mirror formula, where x, y are distances measured from the focus",
          variables: [
            { symbol: "x, y", name: "object and image distances measured from the FOCUS (not the pole)", unit: "m", dimension: "[L]" },
          ],
          conditions: ["An alternative to the standard mirror formula, occasionally faster when distances are naturally given from the focus"],
          conceptLink: {
            chapterSlug: "ray-optics-and-optical-instruments",
            sectionHeading: "10. Newton's Formula and Velocity of the Image (Mirrors)",
            concept: "Newton's formula for mirrors",
          },
          examTags: ["jee-advanced", "neet"],
          frequency: "low",
          examStats: { jeeAdvanced: 2, neet: 3 },
          difficulty: "hard",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["newtons formula mirror", "xy equals f squared"],
        },
      ],
    },
    {
      id: "opt-refraction-basics",
      title: "Refraction, Total Internal Reflection & Curved Surfaces",
      intro:
        "Light bends when crossing between media of different optical density — pushed far enough, it stops crossing at all and reflects entirely back, the basis of optical fibres.",
      formulas: [
        {
          id: "opt-snells-law",
          expression: "n₁ sinθ₁ = n₂ sinθ₂ ,  n = c/v",
          expressionLatex: "n_1\\sin\\theta_1 = n_2\\sin\\theta_2",
          label: "Snell's law of refraction",
          variables: [
            { symbol: "n₁, n₂", name: "refractive indices of the two media", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
            { symbol: "θ₁, θ₂", name: "angles of incidence and refraction, measured from the normal", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["Light bends TOWARD the normal when entering a denser medium (n increases), away from it when entering a rarer medium"],
          usedIn: ["electromagnetic-waves"],
          conceptLink: {
            chapterSlug: "ray-optics-and-optical-instruments",
            sectionHeading: "11. Refraction: Laws, Refractive Index and Bending of Light",
            concept: "Snell's law",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 4, neet: 12, mhtCet: 8 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["snells law", "n1 sin theta1 equals n2 sin theta2"],
        },
        {
          id: "opt-apparent-depth",
          expression: "Apparent depth = Real depth / n",
          expressionLatex: "d_{apparent} = \\dfrac{d_{real}}{n}",
          label: "Apparent depth (normal viewing)",
          derivedFrom: "Small-angle approximation applied to Snell's law for near-normal viewing through a refracting surface",
          variables: [],
          conditions: ["Object viewed from a rarer medium looking into a denser one appears CLOSER (shallower) than it really is — valid only for near-normal viewing"],
          conceptLink: {
            chapterSlug: "ray-optics-and-optical-instruments",
            sectionHeading: "12. Apparent Depth, Normal Shift and Lateral Shift",
            concept: "apparent depth",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 10, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["apparent depth formula", "real depth by n"],
        },
        {
          id: "opt-lateral-shift",
          expression: "Lateral shift = t sin(i−r) / cos r",
          expressionLatex: "s = \\dfrac{t\\sin(i-r)}{\\cos r}",
          label: "Lateral shift through a parallel-sided glass slab",
          variables: [
            { symbol: "t", name: "thickness of the slab", unit: "m", dimension: "[L]" },
            { symbol: "i, r", name: "angles of incidence and refraction at the first surface", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["The emergent ray is parallel to the incident ray but laterally displaced — no net deviation in direction through a slab"],
          conceptLink: {
            chapterSlug: "ray-optics-and-optical-instruments",
            sectionHeading: "12. Apparent Depth, Normal Shift and Lateral Shift",
            concept: "lateral shift through a slab",
          },
          examTags: ["jee-main", "neet", "mht-cet"],
          frequency: "medium",
          examStats: { jeeMain: 5, neet: 6, mhtCet: 4 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["lateral shift glass slab", "t sin i minus r by cos r"],
        },
        {
          id: "opt-critical-angle",
          expression: "sinθ(c) = 1/n   (denser to rarer medium)",
          expressionLatex: "\\sin\\theta_c = \\dfrac{1}{n}",
          label: "Critical angle for total internal reflection",
          derivedFrom: "Setting θ₂ = 90° in Snell's law for light going from a denser medium (n) into a rarer one (n=1, e.g. air)",
          variables: [
            { symbol: "θ(c)", name: "critical angle", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["Total internal reflection requires BOTH conditions: light travelling from denser to rarer medium, AND angle of incidence greater than θ(c)"],
          commonMistakes: [
            "TIR can only happen going from denser to rarer — it's impossible in the reverse direction, however large the angle of incidence",
          ],
          usedIn: ["electromagnetic-waves"],
          conceptLink: {
            chapterSlug: "ray-optics-and-optical-instruments",
            sectionHeading: "13. Total Internal Reflection: Critical Angle and Conditions",
            concept: "critical angle",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 11, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["critical angle formula", "sin theta c 1 by n", "total internal reflection condition"],
        },
        {
          id: "opt-refraction-single-curved-surface",
          expression: "n₂/v − n₁/u = (n₂ − n₁)/R",
          expressionLatex: "\\dfrac{n_2}{v}-\\dfrac{n_1}{u} = \\dfrac{n_2-n_1}{R}",
          label: "Refraction at a single spherical surface",
          derivedFrom: "Applying Snell's law with paraxial (small-angle) approximation at a single curved boundary between two media",
          variables: [
            { symbol: "R", name: "radius of curvature of the surface", unit: "m", dimension: "[L]" },
          ],
          conditions: ["The building block from which the lens maker's formula is derived by applying this twice (once per lens surface)"],
          usedIn: ["ray-optics-and-optical-instruments"],
          conceptLink: {
            chapterSlug: "ray-optics-and-optical-instruments",
            sectionHeading: "15. Refraction at a Single Curved Surface",
            concept: "refraction at a single curved surface",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "medium",
          examStats: { jeeMain: 5, jeeAdvanced: 4, neet: 5 },
          difficulty: "hard",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["refraction single curved surface", "n2 by v minus n1 by u"],
        },
      ],
    },
    {
      id: "opt-lenses",
      title: "Thin Lenses",
      intro:
        "The lens maker's formula ties a lens's focal length to its material and curvature; the lens formula then does the same job the mirror formula does for mirrors.",
      formulas: [
        {
          id: "opt-lens-makers-formula",
          expression: "1/f = (n − 1)(1/R₁ − 1/R₂)",
          expressionLatex: "\\dfrac{1}{f} = (n-1)\\left(\\dfrac{1}{R_1}-\\dfrac{1}{R_2}\\right)",
          label: "Lens maker's formula",
          derivedFrom: "Applying refraction-at-a-single-surface twice in succession — once for each face of the thin lens",
          variables: [
            { symbol: "n", name: "refractive index of the lens material relative to the surrounding medium", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
            { symbol: "R₁, R₂", name: "radii of curvature of the two lens surfaces (signed)", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Thin lens approximation (thickness ≪ radii of curvature)"],
          conceptLink: {
            chapterSlug: "ray-optics-and-optical-instruments",
            sectionHeading: "16. Lens Basics, Lens Maker's Formula and Lens Formula",
            concept: "lens maker's formula",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 4, neet: 12, mhtCet: 8 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["lens makers formula", "n minus 1 1 by R1 minus 1 by R2"],
        },
        {
          id: "opt-lens-formula",
          expression: "1/v − 1/u = 1/f",
          expressionLatex: "\\dfrac{1}{v}-\\dfrac{1}{u} = \\dfrac{1}{f}",
          label: "Thin lens formula",
          variables: [],
          conditions: ["Uses the SAME sign convention as mirrors, but the formula's sign differs: subtraction here, addition for mirrors"],
          commonMistakes: [
            "Copying the mirror formula's '+' sign into the lens formula by habit is one of the most common algebra slips in this chapter",
          ],
          conceptLink: {
            chapterSlug: "ray-optics-and-optical-instruments",
            sectionHeading: "16. Lens Basics, Lens Maker's Formula and Lens Formula",
            concept: "thin lens formula",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 10, jeeAdvanced: 4, neet: 13, mhtCet: 8 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["lens formula", "1 by v minus 1 by u equals 1 by f"],
        },
        {
          id: "opt-lens-magnification",
          expression: "m = v/u",
          expressionLatex: "m = \\dfrac{v}{u}",
          label: "Magnification of a thin lens",
          variables: [],
          conditions: ["No negative sign here, unlike the mirror magnification formula — a frequent point of confusion when switching between chapters"],
          conceptLink: {
            chapterSlug: "ray-optics-and-optical-instruments",
            sectionHeading: "17. Image Formation by a Convex (Converging) Lens",
            concept: "lens magnification",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 10, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["lens magnification formula", "m equals v by u"],
        },
        {
          id: "opt-lens-power",
          expression: "P = 1/f  (f in metres) ;  P(combination) = P₁ + P₂ + ⋯",
          expressionLatex: "P = \\dfrac{1}{f},\\quad P_{net} = \\sum P_i",
          label: "Power of a lens and lenses in contact",
          variables: [
            { symbol: "P", name: "power of the lens", unit: "D (dioptre)", dimension: "[L⁻¹]" },
          ],
          conditions: ["Convex (converging) lens: P positive; concave (diverging) lens: P negative"],
          conceptLink: {
            chapterSlug: "ray-optics-and-optical-instruments",
            sectionHeading: "18. Image Formation by a Concave (Diverging) Lens and Power of a Lens",
            concept: "power of a lens",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 10, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["power of lens formula", "P equals 1 by f dioptre"],
        },
        {
          id: "opt-combination-lenses-contact",
          expression: "1/F = 1/f₁ + 1/f₂ + ⋯",
          expressionLatex: "\\dfrac{1}{F} = \\dfrac{1}{f_1}+\\dfrac{1}{f_2}",
          label: "Equivalent focal length of lenses in contact",
          variables: [
            { symbol: "F", name: "equivalent focal length of the combination", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Lenses must be thin and placed in direct contact (negligible separation) for this simple sum to hold"],
          conceptLink: {
            chapterSlug: "ray-optics-and-optical-instruments",
            sectionHeading: "19. Combination of Lenses, Cutting a Lens and Silvering",
            concept: "combination of lenses",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 7, jeeAdvanced: 3, neet: 8, mhtCet: 6 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["combination lenses in contact", "1 by F equals 1 by f1 plus 1 by f2"],
        },
        {
          id: "opt-displacement-method",
          expression: "f = (d² − x²) / 4d",
          expressionLatex: "f = \\dfrac{d^2-x^2}{4d}",
          label: "Displacement method for focal length of a convex lens",
          derivedFrom: "Two lens positions between a fixed object and screen both give a sharp image (conjugate foci property); combining the two equations gives this result",
          variables: [
            { symbol: "d", name: "fixed distance between object and screen", unit: "m", dimension: "[L]" },
            { symbol: "x", name: "distance between the two lens positions giving a sharp image", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Requires d > 4f — a real image is only possible for object-screen separations beyond this minimum"],
          conceptLink: {
            chapterSlug: "ray-optics-and-optical-instruments",
            sectionHeading: "20. Displacement Method for Focal Length of a Convex Lens",
            concept: "displacement method",
          },
          examTags: ["jee-main", "neet", "mht-cet"],
          frequency: "medium",
          examStats: { jeeMain: 5, neet: 6, mhtCet: 4 },
          difficulty: "hard",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["displacement method focal length", "f equals d squared minus x squared by 4d"],
        },
        {
          id: "opt-achromatism-condition",
          expression: "ω₁/f₁ + ω₂/f₂ = 0",
          expressionLatex: "\\dfrac{\\omega_1}{f_1}+\\dfrac{\\omega_2}{f_2}=0",
          label: "Condition for an achromatic combination of two lenses",
          derivedFrom: "Requires the net dispersive effect of both lenses to cancel while retaining some overall converging power",
          variables: [
            { symbol: "ω₁, ω₂", name: "dispersive powers of the two lens materials", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["Since ω values are always positive, f₁ and f₂ must have OPPOSITE signs — one converging, one diverging lens"],
          conceptLink: {
            chapterSlug: "ray-optics-and-optical-instruments",
            sectionHeading: "21. Chromatic Aberration and Achromatism",
            concept: "achromatic combination",
          },
          examTags: ["jee-advanced", "neet"],
          frequency: "low",
          examStats: { jeeAdvanced: 2, neet: 3 },
          difficulty: "hard",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["achromatic lens combination condition", "omega1 f1 plus omega2 f2"],
        },
      ],
    },
    {
      id: "opt-prism-dispersion",
      title: "Prism and Dispersion",
      intro:
        "A prism bends light twice (once at each face); at one special angle of incidence the total deviation is minimised, and this minimum-deviation condition is how refractive index is measured experimentally.",
      formulas: [
        {
          id: "opt-prism-formula",
          expression: "n = sin[(A + δ(m))/2] / sin(A/2)",
          expressionLatex: "n = \\dfrac{\\sin\\left(\\dfrac{A+\\delta_m}{2}\\right)}{\\sin\\left(\\dfrac{A}{2}\\right)}",
          label: "Prism formula (at minimum deviation)",
          derivedFrom: "At minimum deviation, the ray path is symmetric inside the prism (i = e, r₁ = r₂ = A/2)",
          variables: [
            { symbol: "A", name: "angle of the prism", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
            { symbol: "δ(m)", name: "angle of minimum deviation", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["Only valid AT the minimum-deviation condition, not for a general angle of incidence"],
          conceptLink: {
            chapterSlug: "ray-optics-and-optical-instruments",
            sectionHeading: "22. Prism: Deviation, Minimum Deviation and Emergence Conditions",
            concept: "prism formula at minimum deviation",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 10, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["prism formula minimum deviation", "n sin A plus delta m by 2"],
        },
        {
          id: "opt-prism-general-relations",
          expression: "A = r₁ + r₂ ,  δ = i + e − A",
          expressionLatex: "A = r_1+r_2,\\quad \\delta = i+e-A",
          label: "General prism relations",
          variables: [
            { symbol: "i, e", name: "angles of incidence and emergence", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
            { symbol: "r₁, r₂", name: "angles of refraction at the two prism faces", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["Valid for any angle of incidence, not just at minimum deviation — these are the general bookkeeping relations for a prism"],
          conceptLink: {
            chapterSlug: "ray-optics-and-optical-instruments",
            sectionHeading: "22. Prism: Deviation, Minimum Deviation and Emergence Conditions",
            concept: "general prism relations",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 4, neet: 6 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["prism general relations", "A r1 plus r2", "delta i plus e minus A"],
        },
        {
          id: "opt-dispersive-power",
          expression: "ω = (n(v) − n(r)) / (n(y) − 1)",
          expressionLatex: "\\omega = \\dfrac{n_v-n_r}{n_y-1}",
          label: "Dispersive power of a prism material",
          variables: [
            { symbol: "n(v), n(r), n(y)", name: "refractive indices for violet, red, and yellow (mean) light", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["Measures how strongly a material spreads white light into its spectrum, independent of the prism's actual angle"],
          conceptLink: {
            chapterSlug: "ray-optics-and-optical-instruments",
            sectionHeading: "23. Dispersion of Light and Combination of Prisms",
            concept: "dispersive power",
          },
          examTags: ["jee-main", "neet", "mht-cet"],
          frequency: "medium",
          examStats: { jeeMain: 5, neet: 6, mhtCet: 4 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["dispersive power prism", "nv minus nr by ny minus 1"],
        },
      ],
    },
    {
      id: "opt-instruments",
      title: "Optical Instruments",
      intro:
        "Microscopes and telescopes both use a two-lens system to magnify — a microscope magnifies a small NEARBY object, a telescope magnifies the apparent size of a distant one.",
      formulas: [
        {
          id: "opt-simple-microscope-magnification",
          expression: "m = 1 + D/f   (image at near point) ;  m = D/f   (image at infinity)",
          expressionLatex: "m = 1+\\dfrac{D}{f}",
          label: "Magnifying power of a simple microscope",
          variables: [
            { symbol: "D", name: "least distance of distinct vision", unit: "m", dimension: "[L]", notes: "standard value D = 25 cm" },
            { symbol: "f", name: "focal length of the magnifying lens", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Shorter focal length gives greater magnification — this is why magnifying glasses use strongly converging (short f) lenses"],
          conceptLink: {
            chapterSlug: "ray-optics-and-optical-instruments",
            sectionHeading: "24. Optical Instruments: Simple and Compound Microscope",
            concept: "simple microscope magnification",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 7, neet: 9, mhtCet: 6 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["simple microscope magnification", "1 plus D by f"],
        },
        {
          id: "opt-compound-microscope-magnification",
          expression: "m ≈ (L/f(o)) × (D/f(e))   (image at near point, normal adjustment)",
          expressionLatex: "m \\approx \\dfrac{L}{f_o}\\times\\dfrac{D}{f_e}",
          label: "Magnifying power of a compound microscope",
          derivedFrom: "Product of the objective's linear magnification and the eyepiece's angular magnification (acting as a simple microscope on the intermediate image)",
          variables: [
            { symbol: "L", name: "tube length — distance between the objective's image and the eyepiece's focal point (approx.)", unit: "m", dimension: "[L]" },
            { symbol: "f(o), f(e)", name: "focal lengths of the objective and eyepiece", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Both f(o) and f(e) are kept small (especially f(o)) to maximise magnification — the defining design choice of a microscope"],
          conceptLink: {
            chapterSlug: "ray-optics-and-optical-instruments",
            sectionHeading: "24. Optical Instruments: Simple and Compound Microscope",
            concept: "compound microscope magnification",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 3, neet: 10, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["compound microscope magnification", "L by fo D by fe"],
        },
        {
          id: "opt-telescope-magnification",
          expression: "m = f(o)/f(e)   (normal adjustment, image at infinity)",
          expressionLatex: "m = \\dfrac{f_o}{f_e}",
          label: "Magnifying power of an astronomical telescope",
          derivedFrom: "Ratio of the angles subtended by the final image and the object, using the objective's long focal length and the eyepiece's short one",
          variables: [],
          conditions: ["Objective has a LARGE focal length (opposite design choice to a microscope), eyepiece has a small one — maximising this ratio maximises magnification"],
          commonMistakes: [
            "Telescope wants f(o) LARGE and f(e) SMALL for high magnification — exactly the opposite emphasis from a microscope, where both are small but the ratio L/f(o) matters more",
          ],
          conceptLink: {
            chapterSlug: "ray-optics-and-optical-instruments",
            sectionHeading: "25. Optical Instruments: Astronomical and Galilean Telescope, Camera",
            concept: "telescope magnification",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 10, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["telescope magnification formula", "m equals fo by fe"],
        },
        {
          id: "opt-telescope-tube-length",
          expression: "Tube length (normal adjustment) = f(o) + f(e)",
          expressionLatex: "L = f_o+f_e",
          label: "Tube length of an astronomical telescope (normal adjustment)",
          variables: [],
          conditions: ["Applies when the final image forms at infinity — the eyepiece's focal point coincides with the objective's focal point"],
          conceptLink: {
            chapterSlug: "ray-optics-and-optical-instruments",
            sectionHeading: "25. Optical Instruments: Astronomical and Galilean Telescope, Camera",
            concept: "telescope tube length",
          },
          examTags: ["jee-main", "neet", "mht-cet"],
          frequency: "medium",
          examStats: { jeeMain: 5, neet: 6, mhtCet: 4 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["telescope tube length", "fo plus fe"],
        },
      ],
      examNotes:
        "Boards routinely ask for a labelled ray diagram alongside the magnification formula for both microscope and telescope — know the diagram, not just the number.",
    },
  ],
};
