import type { ChapterFormulaSheet } from "./types";

// NOTE: Semiconductor Electronics has no Notes page yet (source content not
// uploaded). Every formula below therefore OMITS conceptLink rather than
// fabricating a sectionHeading that doesn't exist in a real Notes file —
// conceptLink is optional on the Formula type precisely for this case.
// Add conceptLink to each card once Notes are built for this chapter.

export const semiconductorElectronicsFormulaSheet: ChapterFormulaSheet = {
  chapterSlug: "semiconductor-electronics",
  chapterName: "Semiconductor Electronics",
  className: "12",
  version: "1.0.0",
  lastUpdated: "2026-07-09",
  examCoverage: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
  quickRevisionIds: [
    "semi-mass-action-law",
    "semi-diode-equation",
    "semi-current-gain-beta",
    "semi-relation-alpha-beta",
    "semi-voltage-gain-ce-amplifier",
  ],
  topicGroups: [
    {
      id: "semi-basics",
      title: "Semiconductor Basics",
      intro:
        "Doping deliberately unbalances a semiconductor's electron and hole populations — but their PRODUCT stays fixed at a given temperature, a constraint that underlies almost every device calculation in this chapter.",
      formulas: [
        {
          id: "semi-conductivity-semiconductor",
          expression: "σ = e(n μ(e) + p μ(h))",
          expressionLatex: "\\sigma = e(n\\mu_e+p\\mu_h)",
          label: "Conductivity of a semiconductor",
          variables: [
            { symbol: "n, p", name: "electron and hole concentrations", unit: "m⁻³", dimension: "[L⁻³]" },
            { symbol: "μ(e), μ(h)", name: "mobilities of electrons and holes", unit: "m²/(V·s)", dimension: "[M⁻¹T²A]" },
          ],
          conditions: ["BOTH charge carriers (electrons AND holes) contribute to conduction in a semiconductor — unlike a metal, where only electrons carry current"],
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 6, neet: 8, mhtCet: 5 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["semiconductor conductivity formula", "e n mue p muh"],
        },
        {
          id: "semi-mass-action-law",
          expression: "n·p = n(i)²",
          expressionLatex: "np = n_i^2",
          label: "Law of mass action",
          derivedFrom: "At thermal equilibrium, the product of electron and hole concentrations depends only on temperature, not on the doping level",
          variables: [
            { symbol: "n(i)", name: "intrinsic carrier concentration (equal electron and hole density in pure semiconductor)", unit: "m⁻³", dimension: "[L⁻³]" },
          ],
          conditions: ["Holds for both intrinsic and doped (extrinsic) semiconductors at thermal equilibrium — doping increases one carrier type while suppressing the other, keeping the product fixed"],
          commonMistakes: [
            "Doping does NOT change n(i) itself (a material/temperature property) — it only redistributes n and p while keeping their product constant",
          ],
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 10, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["law of mass action semiconductor", "np equals ni squared"],
        },
      ],
    },
    {
      id: "semi-diode",
      title: "p-n Junction Diode",
      intro:
        "A p-n junction conducts easily in one direction and barely at all in the other — the ideal diode equation captures this asymmetry in a single exponential expression.",
      formulas: [
        {
          id: "semi-diode-equation",
          expression: "I = I₀ (e^(eV/kT) − 1)",
          expressionLatex: "I = I_0\\left(e^{eV/kT}-1\\right)",
          label: "Ideal diode equation",
          variables: [
            { symbol: "I", name: "diode current", unit: "A", dimension: "[A]" },
            { symbol: "I₀", name: "reverse saturation current", unit: "A", dimension: "[A]" },
            { symbol: "V", name: "applied voltage across the diode (positive for forward bias)", unit: "V", dimension: "[ML²T⁻³A⁻¹]" },
          ],
          conditions: ["Forward bias (V>0): current grows exponentially, extremely fast", "Reverse bias (V<0, |eV|≫kT): current saturates at approximately −I₀, essentially constant and tiny"],
          commonMistakes: [
            "Reverse current does NOT go to zero — it saturates at the small but non-zero value I₀, driven by minority carriers",
          ],
          examTags: ["jee-advanced", "neet"],
          frequency: "medium",
          examStats: { jeeAdvanced: 3, neet: 4 },
          difficulty: "hard",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["diode equation formula", "I0 e power eV by kT minus 1"],
        },
      ],
    },
    {
      id: "semi-rectifiers",
      title: "Rectifiers",
      intro:
        "A rectifier converts AC to (pulsating) DC using diodes' one-way conduction — a full-wave design uses the negative half-cycle too, doubling the theoretical maximum efficiency of a half-wave rectifier.",
      formulas: [
        {
          id: "semi-half-wave-rectifier-efficiency",
          expression: "η(max) = 40.6%",
          expressionLatex: "\\eta_{max} \\approx 40.6\\%",
          label: "Maximum theoretical efficiency of a half-wave rectifier",
          derivedFrom: "Ratio of DC output power to total AC input power, maximised over one full input cycle where only one half is utilised",
          variables: [
            { symbol: "η", name: "rectification efficiency", unit: "dimensionless (%)", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["Only one half of each input cycle is used — the other half is entirely wasted, capping efficiency well below 100%"],
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 5, neet: 7, mhtCet: 5 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["half wave rectifier efficiency", "40.6 percent"],
        },
        {
          id: "semi-full-wave-rectifier-efficiency",
          expression: "η(max) = 81.2%",
          expressionLatex: "\\eta_{max} \\approx 81.2\\%",
          label: "Maximum theoretical efficiency of a full-wave rectifier",
          derivedFrom: "Both half-cycles of the input are utilised (via a centre-tapped transformer or bridge configuration), exactly doubling the half-wave result",
          variables: [],
          conditions: ["Exactly twice the half-wave rectifier's maximum efficiency — a directly testable numeric relationship"],
          commonMistakes: [
            "Full-wave efficiency (81.2%) is EXACTLY double half-wave efficiency (40.6%) — a clean 2× relationship worth memorising directly",
          ],
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 5, neet: 7, mhtCet: 5 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["full wave rectifier efficiency", "81.2 percent"],
        },
      ],
    },
    {
      id: "semi-transistors",
      title: "Transistors as Amplifiers",
      intro:
        "A transistor's three currents are locked together by simple conservation, and the ratios between them (α and β) are the single numbers that determine how much an amplifier circuit boosts a signal.",
      formulas: [
        {
          id: "semi-transistor-current-relation",
          expression: "I(E) = I(B) + I(C)",
          expressionLatex: "I_E = I_B+I_C",
          label: "Transistor terminal current relation (KCL applied to a transistor)",
          variables: [
            { symbol: "I(E), I(B), I(C)", name: "emitter, base, and collector currents", unit: "A", dimension: "[A]" },
          ],
          conditions: ["A direct consequence of charge conservation at the transistor's base — always true regardless of configuration (CE, CB, CC)"],
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 10, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["transistor current relation", "IE equals IB plus IC"],
        },
        {
          id: "semi-current-gain-alpha",
          expression: "α = I(C)/I(E)   (common-base current gain)",
          expressionLatex: "\\alpha = \\dfrac{I_C}{I_E}",
          label: "Common-base current gain (α)",
          variables: [
            { symbol: "α", name: "common-base current gain, always slightly less than 1", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["α is always < 1 since I(C) < I(E) (a small fraction of emitter current is lost as base current)"],
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 6, neet: 8, mhtCet: 5 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["common base current gain alpha", "IC by IE"],
        },
        {
          id: "semi-current-gain-beta",
          expression: "β = I(C)/I(B)   (common-emitter current gain)",
          expressionLatex: "\\beta = \\dfrac{I_C}{I_B}",
          label: "Common-emitter current gain (β)",
          variables: [
            { symbol: "β", name: "common-emitter current gain, typically large (tens to hundreds)", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["The most commonly used gain figure since common-emitter is the standard amplifier configuration"],
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 3, neet: 10, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["common emitter current gain beta", "IC by IB"],
        },
        {
          id: "semi-relation-alpha-beta",
          expression: "β = α/(1−α) ,  α = β/(1+β)",
          expressionLatex: "\\beta = \\dfrac{\\alpha}{1-\\alpha}",
          label: "Relation between α and β",
          derivedFrom: "Combining I(E)=I(B)+I(C) with the definitions of α and β algebraically",
          variables: [],
          conditions: ["Since α is very close to 1, small changes in α produce LARGE changes in β — this sensitivity is why β varies a lot between individual transistors of the same type"],
          commonMistakes: [
            "A tiny difference between two α values (e.g. 0.98 vs 0.99) corresponds to a huge difference in β (49 vs 99) — always convert carefully rather than eyeballing",
          ],
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 10, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["relation alpha beta transistor", "beta equals alpha by 1 minus alpha"],
        },
        {
          id: "semi-voltage-gain-ce-amplifier",
          expression: "A(v) = β (R(C)/R(in))",
          expressionLatex: "A_v = \\beta\\dfrac{R_C}{R_{in}}",
          label: "Voltage gain of a common-emitter amplifier",
          derivedFrom: "Output voltage change (ΔI(C)·R(C)) divided by input voltage change (ΔI(B)·R(in)), using β = ΔI(C)/ΔI(B)",
          variables: [
            { symbol: "A(v)", name: "voltage gain", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
            { symbol: "R(C)", name: "collector (output) resistance", unit: "Ω", dimension: "[ML²T⁻³A⁻²]" },
            { symbol: "R(in)", name: "input resistance of the base circuit", unit: "Ω", dimension: "[ML²T⁻³A⁻²]" },
          ],
          conditions: ["A common-emitter amplifier inverts the signal (180° phase shift) in addition to amplifying it — a qualitative fact often paired with this formula"],
          usedIn: ["current-electricity"],
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 4, neet: 7, mhtCet: 5 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["voltage gain CE amplifier", "beta RC by Rin"],
        },
        {
          id: "semi-power-gain",
          expression: "A(p) = A(v) × A(i) = β² (R(C)/R(in))",
          expressionLatex: "A_p = A_v \\times A_i",
          label: "Power gain of a common-emitter amplifier",
          variables: [
            { symbol: "A(p)", name: "power gain", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
            { symbol: "A(i)", name: "current gain, equal to β for this configuration", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["Power gain is the PRODUCT of voltage gain and current gain, not their sum — a common slip under exam pressure"],
          examTags: ["jee-main", "neet", "mht-cet"],
          frequency: "medium",
          examStats: { jeeMain: 5, neet: 6, mhtCet: 4 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["power gain amplifier", "Av times Ai power gain"],
        },
      ],
      examNotes:
        "Boards frequently ask to sketch input and output waveforms for a CE amplifier showing the 180° phase inversion alongside these gain formulas — know the diagram as well as the numbers.",
    },
  ],
};
