import type { ChapterFormulaSheet } from "./types";

export const rotationalMotionFormulaSheet: ChapterFormulaSheet = {
  chapterSlug: "system-of-particles-and-rotational-motion",
  chapterName: "System of Particles & Rotational Motion",
  className: "11",
  version: "1.0.1",
  lastUpdated: "2026-07-03",
  examCoverage: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
  quickRevisionIds: [
    "rot-torque",
    "rot-second-law",
    "rot-angular-momentum",
    "rot-am-conservation",
    "rot-rolling-ke",
    "rot-rolling-incline-acceleration",
  ],
  topicGroups: [
    {
      id: "rot-moment-of-inertia",
      title: "Moment of Inertia",
      intro:
        "Moment of inertia is rotational mass — it measures how far the mass sits from the axis, not just how much mass there is.",
      formulas: [
        {
          id: "rot-moi-definition",
          expression: "I = Σ mᵢrᵢ²  =  ∫ r² dm",
          expressionLatex: "I = \\sum m_i r_i^2 = \\int r^2\\,dm",
          label: "Moment of inertia (definition)",
          variables: [
            { symbol: "I", name: "moment of inertia about the chosen axis", unit: "kg·m²", dimension: "[ML²]" },
            { symbol: "rᵢ", name: "perpendicular distance of mass mᵢ from the axis", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Depends on the AXIS — the same body has different I about different axes"],
          commonMistakes: [
            "r is the perpendicular distance from the AXIS, not from any point",
          ],
          conceptLink: {
            chapterSlug: "system-of-particles-and-rotational-motion",
            sectionHeading: "1. Moment of Inertia",
            concept: "moment of inertia definition",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 7, neet: 9, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["moment of inertia", "rotational inertia", "mr squared"],
        },
        {
          id: "rot-parallel-axis",
          expression: "I = I(cm) + Md²",
          expressionLatex: "I = I_{cm} + Md^2",
          label: "Parallel axis theorem",
          variables: [
            { symbol: "I(cm)", name: "moment of inertia about the parallel axis through the COM", unit: "kg·m²", dimension: "[ML²]" },
            { symbol: "d", name: "distance between the two parallel axes", unit: "m", dimension: "[L]" },
            { symbol: "M", name: "total mass", unit: "kg", dimension: "[M]" },
          ],
          conditions: ["The reference axis MUST pass through the centre of mass"],
          commonMistakes: [
            "Applying it between two arbitrary parallel axes — one of them must be the COM axis; go via the COM in two steps otherwise",
          ],
          conceptLink: {
            chapterSlug: "system-of-particles-and-rotational-motion",
            sectionHeading: "1. Moment of Inertia",
            concept: "parallel axis theorem",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 10, jeeAdvanced: 5, neet: 11, mhtCet: 9 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["parallel axis theorem", "I cm plus M d squared"],
        },
        {
          id: "rot-perpendicular-axis",
          expression: "I(z) = I(x) + I(y)",
          expressionLatex: "I_z = I_x + I_y",
          label: "Perpendicular axis theorem",
          variables: [
            { symbol: "I(z)", name: "MOI about the axis perpendicular to the lamina", unit: "kg·m²", dimension: "[ML²]" },
            { symbol: "I(x), I(y)", name: "MOI about two perpendicular in-plane axes meeting the z-axis", unit: "kg·m²", dimension: "[ML²]" },
          ],
          conditions: ["PLANAR bodies (laminas) only — invalid for spheres, cylinders, cubes"],
          commonMistakes: [
            "Using it on a 3-D body is the most common theorem misuse in this chapter",
          ],
          conceptLink: {
            chapterSlug: "system-of-particles-and-rotational-motion",
            sectionHeading: "1. Moment of Inertia",
            concept: "perpendicular axis theorem",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 6, neet: 8, mhtCet: 6 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["perpendicular axis theorem", "lamina"],
        },
      ],
      importantObservations: [
        "Standard MOIs (about symmetry axis through COM): ring MR², disc ½MR², solid sphere ⅖MR², hollow sphere ⅔MR², rod (centre) ML²/12, rod (end) ML²/3, solid cylinder ½MR²",
        "Radius of gyration: k = √(I/M) — the distance at which all mass could sit and give the same I",
      ],
      examNotes:
        "NEET asks the standard values directly; JEE combines both theorems on composite bodies — always route through the COM axis.",
    },
    {
      id: "rot-torque-dynamics",
      title: "Torque & Rotational Dynamics",
      intro:
        "Torque is to rotation what force is to translation. The whole of rotational dynamics is Newton's second law with I replacing m and α replacing a.",
      formulas: [
        {
          id: "rot-torque",
          expression: "τ = r F sinθ",
          expressionLatex: "\\vec{\\tau} = \\vec{r}\\times\\vec{F},\\ \\ \\tau = rF\\sin\\theta",
          label: "Torque of a force",
          variables: [
            { symbol: "τ", name: "torque about the chosen point/axis", unit: "N·m", dimension: "[ML²T⁻²]" },
            { symbol: "r", name: "position vector magnitude from axis to point of application", unit: "m", dimension: "[L]" },
            { symbol: "θ", name: "angle between r and F", unit: "rad (or °)", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["r sinθ is the lever arm — the perpendicular distance from the axis to the LINE of the force"],
          commonMistakes: [
            "A force whose line of action passes through the axis has ZERO torque, however large the force",
          ],
          usedIn: ["magnetism-and-matter"],
          conceptLink: {
            chapterSlug: "system-of-particles-and-rotational-motion",
            sectionHeading: "2. Torque",
            concept: "torque as moment of force",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 11, jeeAdvanced: 5, neet: 12, mhtCet: 9 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["torque", "r cross F", "lever arm", "moment of force"],
        },
        {
          id: "rot-second-law",
          expression: "τ(net) = Iα",
          expressionLatex: "\\tau_{net} = I\\alpha",
          label: "Rotational form of Newton's second law",
          variables: [
            { symbol: "α", name: "angular acceleration", unit: "rad/s²", dimension: "[T⁻²]" },
            { symbol: "I", name: "moment of inertia about the rotation axis", unit: "kg·m²", dimension: "[ML²]" },
          ],
          conditions: ["About a fixed axis, or about the COM axis even when the COM accelerates"],
          commonMistakes: [
            "Pulley problems with massive pulleys: the two string tensions are DIFFERENT — their difference provides the pulley's τ = Iα",
          ],
          usedIn: ["laws-of-motion"],
          conceptLink: {
            chapterSlug: "system-of-particles-and-rotational-motion",
            sectionHeading: "3. Rotational Dynamics",
            concept: "torque equals I alpha",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 12, jeeAdvanced: 7, neet: 13, mhtCet: 10 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["tau I alpha", "rotational newton second law", "massive pulley"],
        },
        {
          id: "rot-rotational-ke-work",
          expression: "K(rot) = ½Iω²,   W = τθ,   P = τω",
          expressionLatex: "K_{rot} = \\tfrac{1}{2}I\\omega^2",
          label: "Rotational kinetic energy, work and power",
          variables: [
            { symbol: "ω", name: "angular speed", unit: "rad/s", dimension: "[T⁻¹]" },
            { symbol: "θ", name: "angle turned", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["Perfect analogues of ½mv², W = Fs and P = Fv with m→I, v→ω, F→τ, s→θ"],
          usedIn: ["work-energy-and-power"],
          conceptLink: {
            chapterSlug: "system-of-particles-and-rotational-motion",
            sectionHeading: "3. Rotational Dynamics",
            concept: "rotational kinetic energy",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 8, neet: 10, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["rotational kinetic energy", "half I omega squared", "tau omega power"],
        },
      ],
      importantObservations: [
        "Every translational equation has a rotational twin — build the analogy table once and the chapter halves in size",
      ],
    },
    {
      id: "rot-angular-momentum-group",
      title: "Angular Momentum",
      intro:
        "Angular momentum is conserved whenever net external torque vanishes — the physics behind spinning skaters, shrinking orbits, and neutron stars.",
      formulas: [
        {
          id: "rot-angular-momentum",
          expression: "L = Iω  (rigid body),   L = mvr sinθ  (particle)",
          expressionLatex: "\\vec{L} = I\\vec{\\omega},\\quad L = mvr\\sin\\theta",
          label: "Angular momentum",
          variables: [
            { symbol: "L", name: "angular momentum about the axis/point", unit: "kg·m²/s", dimension: "[ML²T⁻¹]" },
            { symbol: "r sinθ", name: "perpendicular distance from the point to the velocity line", unit: "m", dimension: "[L]" },
          ],
          conditions: ["τ = dL/dt — the rotational twin of F = dp/dt"],
          commonMistakes: [
            "A particle moving in a STRAIGHT line still has angular momentum about any point off that line: L = mv × (perpendicular distance)",
          ],
          usedIn: ["gravitation", "atoms"],
          conceptLink: {
            chapterSlug: "system-of-particles-and-rotational-motion",
            sectionHeading: "4. Angular Momentum",
            concept: "angular momentum",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 10, jeeAdvanced: 6, neet: 11, mhtCet: 8 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["angular momentum", "I omega", "mvr"],
        },
        {
          id: "rot-am-conservation",
          expression: "I₁ω₁ = I₂ω₂  (when τ(ext) = 0)",
          expressionLatex: "I_1\\omega_1 = I_2\\omega_2",
          label: "Conservation of angular momentum",
          derivedFrom: "τ(ext) = dL/dt = 0 ⟹ L constant",
          variables: [
            { symbol: "I₁, I₂", name: "moments of inertia before and after", unit: "kg·m²", dimension: "[ML²]" },
            { symbol: "ω₁, ω₂", name: "angular speeds before and after", unit: "rad/s", dimension: "[T⁻¹]" },
          ],
          conditions: ["Net external TORQUE zero (forces may exist — a skater's weight and normal force have no torque about the spin axis)"],
          commonMistakes: [
            "When a skater pulls arms in, KE INCREASES (K = L²/2I with L fixed, I smaller) — the extra energy comes from muscular work",
          ],
          usedIn: ["gravitation"],
          conceptLink: {
            chapterSlug: "system-of-particles-and-rotational-motion",
            sectionHeading: "4. Angular Momentum",
            concept: "conservation of angular momentum",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 5, neet: 13, mhtCet: 9 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["conservation angular momentum", "skater", "I1 omega1"],
        },
        {
          id: "rot-angular-impulse",
          expression: "∫τ dt = ΔL",
          expressionLatex: "\\int \\tau\\,dt = \\Delta L",
          label: "Angular impulse–angular momentum theorem",
          derivedFrom: "Integrating τ = dL/dt over the interaction time",
          variables: [
            { symbol: "∫τ dt", name: "angular impulse about the axis", unit: "N·m·s", dimension: "[ML²T⁻¹]" },
            { symbol: "ΔL", name: "change in angular momentum", unit: "kg·m²/s", dimension: "[ML²T⁻¹]" },
          ],
          conditions: ["The rotational twin of J = Δp — use it for sudden hits, sticky collisions with rods, and struck billiard balls"],
          commonMistakes: [
            "A rod hit at its centre of percussion produces zero reaction at the pivot — the sweet spot of a cricket bat",
          ],
          usedIn: ["centre-of-mass-and-collisions"],
          conceptLink: {
            chapterSlug: "system-of-particles-and-rotational-motion",
            sectionHeading: "4. Angular Momentum",
            concept: "angular impulse",
          },
          examTags: ["jee-main", "jee-advanced"],
          frequency: "medium",
          examStats: { jeeMain: 4, jeeAdvanced: 5 },
          difficulty: "hard",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["angular impulse", "tau dt delta L", "centre of percussion"],
        },
      ],
      importantObservations: [
        "Kepler's second law (equal areas) is just conservation of angular momentum in disguise: dA/dt = L/2m",
      ],
    },
    {
      id: "rot-rolling",
      title: "Rolling Motion",
      intro:
        "Rolling without slipping ties translation to rotation through v = ωR — one constraint that unlocks every rolling problem.",
      formulas: [
        {
          id: "rot-rolling-condition",
          expression: "v(cm) = ωR,   a(cm) = αR",
          expressionLatex: "v_{cm} = \\omega R",
          label: "Rolling without slipping condition",
          variables: [
            { symbol: "v(cm)", name: "speed of the centre", unit: "m/s", dimension: "[LT⁻¹]" },
            { symbol: "R", name: "radius of the rolling body", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Contact point is instantaneously at REST relative to the ground"],
          commonMistakes: [
            "Speed of the TOP point is 2v(cm), bottom point is 0 — a favourite one-mark trap",
          ],
          conceptLink: {
            chapterSlug: "system-of-particles-and-rotational-motion",
            sectionHeading: "5. Rolling Motion",
            concept: "rolling constraint",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 9 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["rolling without slipping", "v omega R", "contact point rest"],
        },
        {
          id: "rot-rolling-ke",
          expression: "K = ½mv² (1 + k²/R²)",
          expressionLatex: "K = \\tfrac{1}{2}mv^2\\left(1 + \\dfrac{k^2}{R^2}\\right)",
          label: "Total KE of a rolling body",
          derivedFrom: "K(trans) + K(rot) with ω = v/R and I = mk²",
          derivation: {
            startsFrom: "Total KE = translational + rotational about the COM",
            steps: [
              { statement: "Write both parts", expression: "K = ½mv² + ½Iω²" },
              { statement: "Substitute I = mk² and ω = v/R", expression: "K = ½mv² + ½mk²v²/R²" },
              { statement: "Factor", expression: "K = ½mv²(1 + k²/R²)" },
            ],
          },
          variables: [
            { symbol: "k", name: "radius of gyration", unit: "m", dimension: "[L]", notes: "k²/R²: ring 1, disc ½, solid sphere ⅖, hollow sphere ⅔" },
          ],
          usedIn: ["work-energy-and-power"],
          conceptLink: {
            chapterSlug: "system-of-particles-and-rotational-motion",
            sectionHeading: "5. Rolling Motion",
            concept: "kinetic energy of rolling",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 4, neet: 12, mhtCet: 8 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["rolling kinetic energy", "1 plus k squared by R squared"],
        },
        {
          id: "rot-rolling-incline-acceleration",
          expression: "a = g sinθ / (1 + k²/R²)",
          expressionLatex: "a = \\dfrac{g\\sin\\theta}{1 + k^2/R^2}",
          label: "Acceleration rolling down an incline",
          derivedFrom: "Energy method or force-torque pair on the incline",
          variables: [
            { symbol: "θ", name: "incline angle", unit: "rad (or °)", dimension: "[M⁰L⁰T⁰]" },
            { symbol: "k²/R²", name: "shape factor", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: [
            "Rolling without slipping (needs enough friction: it supplies torque but does NO work here)",
            "Independent of mass and radius — only the SHAPE matters",
          ],
          commonMistakes: [
            "Race down an incline: solid sphere beats disc beats hollow sphere beats ring — smaller k²/R² wins",
          ],
          conceptLink: {
            chapterSlug: "system-of-particles-and-rotational-motion",
            sectionHeading: "5. Rolling Motion",
            concept: "rolling down an incline",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 5, neet: 11, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["rolling down incline", "g sin theta rolling", "sphere disc ring race"],
        },
        {
          id: "rot-slipping-to-rolling",
          expression: "L(contact) conserved:  mv₀R = mvR + Iω  ⟹  v = v₀/(1 + k²/R²)",
          expressionLatex: "mv_0R = mvR + I\\omega",
          label: "Slipping → rolling transition (angular momentum about the contact point)",
          derivedFrom: "Friction acts AT the contact point, so its torque about that point is zero — L about the contact line is conserved",
          variables: [
            { symbol: "v₀", name: "initial sliding speed (no spin)", unit: "m/s", dimension: "[LT⁻¹]" },
            { symbol: "v", name: "final speed when pure rolling begins (ω = v/R)", unit: "m/s", dimension: "[LT⁻¹]" },
            { symbol: "k", name: "radius of gyration", unit: "m", dimension: "[L]", notes: "solid sphere: v = 5v₀/7; disc: v = 2v₀/3; ring: v = v₀/2" },
          ],
          conditions: ["Horizontal surface, no external torque about the contact line other than friction (which passes through it)"],
          commonMistakes: [
            "Kinetic energy is NOT conserved during the skid — friction burns some; only L about the contact point survives",
          ],
          usedIn: ["centre-of-mass-and-collisions"],
          conceptLink: {
            chapterSlug: "system-of-particles-and-rotational-motion",
            sectionHeading: "5. Rolling Motion",
            concept: "transition from sliding to rolling",
          },
          examTags: ["jee-main", "jee-advanced"],
          frequency: "high",
          examStats: { jeeMain: 5, jeeAdvanced: 6 },
          difficulty: "hard",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["slipping to rolling", "angular momentum contact point", "5v0 by 7"],
        },
      ],
      importantObservations: [
        "Friction in perfect rolling on a FIXED incline does zero work — mechanical energy is conserved even though friction acts",
      ],
      examNotes:
        "NEET tests the incline race and KE split; JEE Advanced adds slipping-to-rolling transitions where angular momentum about the contact point is the shortcut.",
    },
  ],
};
