import type { ChapterFormulaSheet } from "./types";

export const thermalPropertiesFormulaSheet: ChapterFormulaSheet = {
  chapterSlug: "thermal-properties-of-matter",
  chapterName: "Thermal Properties of Matter",
  className: "11",
  version: "1.0.0",
  lastUpdated: "2026-07-04",
  examCoverage: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
  quickRevisionIds: [
    "thm-linear-expansion",
    "thm-heat-capacity",
    "thm-latent-heat",
    "thm-conduction-rate",
    "thm-stefan-law",
    "thm-newtons-cooling",
  ],
  topicGroups: [
    {
      id: "thm-temperature-expansion",
      title: "Temperature Scales & Thermal Expansion",
      intro:
        "Temperature scales are linear maps of each other; expansion coefficients are linked by the simple chain α : β : γ = 1 : 2 : 3.",
      formulas: [
        {
          id: "thm-scale-conversion",
          expression: "C/5 = (F − 32)/9 = (K − 273.15)/5",
          expressionLatex: "\\dfrac{C}{5} = \\dfrac{F-32}{9}",
          label: "Temperature scale conversion",
          variables: [
            { symbol: "C, F, K", name: "temperature in Celsius, Fahrenheit, Kelvin", unit: "°C, °F, K", dimension: "[Θ]" },
          ],
          conditions: ["−40° is the same on Celsius and Fahrenheit"],
          commonMistakes: [
            "A temperature DIFFERENCE of 1 °C equals a difference of 1 K but 1.8 °F — conversions differ for readings vs differences",
          ],
          conceptLink: {
            chapterSlug: "thermal-properties-of-matter",
            sectionHeading: "1. Temperature and Heat",
            concept: "temperature scales",
          },
          examTags: ["neet", "mht-cet", "boards"],
          frequency: "medium",
          examStats: { neet: 6, mhtCet: 5 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["celsius fahrenheit", "temperature conversion"],
        },
        {
          id: "thm-linear-expansion",
          expression: "ΔL = L α ΔT;   α : β : γ = 1 : 2 : 3",
          expressionLatex: "\\Delta L = L\\alpha\\Delta T",
          label: "Thermal expansion (linear, areal, volumetric)",
          variables: [
            { symbol: "α", name: "coefficient of linear expansion", unit: "K⁻¹ (or °C⁻¹)", dimension: "[Θ⁻¹]" },
            { symbol: "β", name: "areal coefficient (= 2α)", unit: "K⁻¹", dimension: "[Θ⁻¹]" },
            { symbol: "γ", name: "volumetric coefficient (= 3α)", unit: "K⁻¹", dimension: "[Θ⁻¹]" },
            { symbol: "ΔT", name: "temperature change", unit: "K (or °C)", dimension: "[Θ]" },
          ],
          conditions: ["Isotropic solids", "A hole in a plate EXPANDS on heating, exactly like a disc of the same material"],
          commonMistakes: [
            "Thermal stress in a clamped rod: stress = YαΔT — no ΔL appears because the rod is NOT allowed to expand",
            "Apparent expansion of liquid in a vessel: γ(apparent) = γ(liquid) − γ(vessel)",
          ],
          usedIn: ["mechanical-properties-of-solids"],
          conceptLink: {
            chapterSlug: "thermal-properties-of-matter",
            sectionHeading: "2. Thermal Expansion",
            concept: "thermal expansion",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, neet: 12, mhtCet: 9 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["linear expansion", "alpha beta gamma", "thermal stress"],
        },
        {
          id: "thm-pendulum-clock",
          expression: "ΔT/T = ½ α Δθ  (fractional time change of a pendulum clock)",
          expressionLatex: "\\dfrac{\\Delta T}{T} = \\tfrac{1}{2}\\alpha\\Delta\\theta",
          label: "Pendulum clock error due to temperature",
          derivedFrom: "T ∝ √L with ΔL/L = αΔθ, then binomial approximation",
          variables: [
            { symbol: "ΔT/T", name: "fractional change in the period", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
            { symbol: "Δθ", name: "rise in temperature", unit: "K (or °C)", dimension: "[Θ]" },
          ],
          conditions: ["Clock LOSES time in summer (pendulum longer, slower), gains in winter", "Time lost per day = ½αΔθ × 86400 s"],
          usedIn: ["oscillations"],
          conceptLink: {
            chapterSlug: "thermal-properties-of-matter",
            sectionHeading: "2. Thermal Expansion",
            concept: "pendulum clock and expansion",
          },
          examTags: ["jee-main", "neet"],
          frequency: "medium",
          examStats: { jeeMain: 5, neet: 6 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["pendulum clock", "time lost per day", "half alpha delta theta"],
        },
      ],
      importantObservations: [
        "Water is anomalous: it CONTRACTS on heating from 0 °C to 4 °C — maximum density at 4 °C is why lakes freeze from the top",
      ],
    },
    {
      id: "thm-calorimetry",
      title: "Heat, Calorimetry & Change of State",
      intro:
        "Heat either raises temperature (mcΔT) or changes phase (mL) — never both at once. Mixture problems are pure bookkeeping of these two.",
      formulas: [
        {
          id: "thm-heat-capacity",
          expression: "Q = m c ΔT",
          expressionLatex: "Q = mc\\Delta T",
          label: "Heat for a temperature change",
          variables: [
            { symbol: "Q", name: "heat supplied", unit: "J", dimension: "[ML²T⁻²]" },
            { symbol: "c", name: "specific heat capacity", unit: "J/(kg·K)", dimension: "[L²T⁻²Θ⁻¹]", notes: "water: 4186 J/(kg·K) ≈ 1 cal/(g·°C)" },
            { symbol: "ΔT", name: "temperature change", unit: "K (or °C)", dimension: "[Θ]" },
          ],
          conditions: ["Principle of calorimetry: heat lost = heat gained (isolated system)"],
          commonMistakes: [
            "In mixture problems, first CHECK whether all the ice melts (compare available heat with required mL) before assuming a final temperature above 0 °C",
          ],
          usedIn: ["thermodynamics"],
          conceptLink: {
            chapterSlug: "thermal-properties-of-matter",
            sectionHeading: "3. Calorimetry",
            concept: "specific heat and calorimetry",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 13, mhtCet: 10 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["mc delta T", "calorimetry", "specific heat"],
        },
        {
          id: "thm-latent-heat",
          expression: "Q = m L",
          expressionLatex: "Q = mL",
          label: "Heat for a change of state (latent heat)",
          variables: [
            { symbol: "L", name: "latent heat of fusion/vaporisation", unit: "J/kg", dimension: "[L²T⁻²]", notes: "ice: 3.34 × 10⁵ J/kg; steam: 22.6 × 10⁵ J/kg" },
          ],
          conditions: ["Temperature stays CONSTANT during the phase change"],
          commonMistakes: [
            "Steam at 100 °C burns far worse than water at 100 °C — it carries the huge latent heat of vaporisation extra",
          ],
          conceptLink: {
            chapterSlug: "thermal-properties-of-matter",
            sectionHeading: "3. Calorimetry",
            concept: "latent heat",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 7, neet: 12, mhtCet: 9 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["latent heat", "mL", "ice steam mixture"],
        },
      ],
      importantObservations: [
        "The classic mixture: equal masses of ice at 0 °C and steam at 100 °C end as ALL water at 100 °C with some steam left — steam's latent heat dominates",
      ],
    },
    {
      id: "thm-heat-transfer",
      title: "Heat Transfer — Conduction, Radiation & Cooling",
      intro:
        "Conduction is Ohm's law with temperature in place of voltage; radiation follows Stefan's T⁴ law; Newton's cooling is its small-difference limit.",
      formulas: [
        {
          id: "thm-conduction-rate",
          expression: "H = dQ/dt = kA(T₁ − T₂)/L",
          expressionLatex: "H = \\dfrac{kA(T_1 - T_2)}{L}",
          label: "Rate of heat conduction",
          variables: [
            { symbol: "H", name: "heat current", unit: "W", dimension: "[ML²T⁻³]" },
            { symbol: "k", name: "thermal conductivity of the material", unit: "W/(m·K)", dimension: "[MLT⁻³Θ⁻¹]" },
            { symbol: "A", name: "cross-sectional area", unit: "m²", dimension: "[L²]" },
            { symbol: "L", name: "length of the conductor", unit: "m", dimension: "[L]" },
          ],
          conditions: [
            "Steady state, no lateral loss",
            "Thermal resistance R = L/kA — series and parallel rods combine exactly like electrical resistors",
          ],
          commonMistakes: [
            "Two rods in series: the JUNCTION temperature divides in the ratio of thermal resistances, not lengths alone",
          ],
          usedIn: ["current-electricity"],
          conceptLink: {
            chapterSlug: "thermal-properties-of-matter",
            sectionHeading: "4. Heat Transfer",
            concept: "thermal conduction",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 10, jeeAdvanced: 4, neet: 12, mhtCet: 9 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["conduction", "kA delta T by L", "thermal resistance"],
        },
        {
          id: "thm-stefan-law",
          expression: "P = σ A e T⁴;   net loss: P = σAe(T⁴ − T₀⁴)",
          expressionLatex: "P = \\sigma A e T^4",
          label: "Stefan-Boltzmann law of radiation",
          variables: [
            { symbol: "σ", name: "Stefan-Boltzmann constant", unit: "W/(m²·K⁴)", dimension: "[MT⁻³Θ⁻⁴]", notes: "σ = 5.67 × 10⁻⁸ W/(m²·K⁴)" },
            { symbol: "e", name: "emissivity (1 for a perfect black body)", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
            { symbol: "T", name: "absolute temperature of the surface", unit: "K", dimension: "[Θ]" },
            { symbol: "T₀", name: "temperature of the surroundings", unit: "K", dimension: "[Θ]" },
          ],
          conditions: ["Temperatures MUST be in kelvin — the T⁴ makes this unforgiving"],
          commonMistakes: [
            "Doubling absolute temperature multiplies radiated power by 16, not 2",
          ],
          conceptLink: {
            chapterSlug: "thermal-properties-of-matter",
            sectionHeading: "4. Heat Transfer",
            concept: "Stefan-Boltzmann law",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 11, mhtCet: 8 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["stefan law", "sigma T 4", "black body radiation"],
        },
        {
          id: "thm-wien-law",
          expression: "λ(max) T = b",
          expressionLatex: "\\lambda_{max}T = b",
          label: "Wien's displacement law",
          variables: [
            { symbol: "λ(max)", name: "wavelength of peak emission", unit: "m", dimension: "[L]" },
            { symbol: "b", name: "Wien's constant", unit: "m·K", dimension: "[LΘ]", notes: "b = 2.9 × 10⁻³ m·K" },
          ],
          conditions: ["Hotter body → peak shifts to SHORTER wavelength (red hot → white hot → blue)"],
          commonMistakes: [
            "λ(max) is where the emission CURVE peaks — it is not the maximum wavelength emitted",
          ],
          conceptLink: {
            chapterSlug: "thermal-properties-of-matter",
            sectionHeading: "4. Heat Transfer",
            concept: "Wien's displacement law",
          },
          examTags: ["jee-main", "neet", "mht-cet"],
          frequency: "high",
          examStats: { jeeMain: 6, neet: 9, mhtCet: 6 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["wien law", "lambda max T", "star colour temperature"],
        },
        {
          id: "thm-newtons-cooling",
          expression: "dT/dt = −K(T − T₀)",
          expressionLatex: "\\dfrac{dT}{dt} = -K(T - T_0)",
          label: "Newton's law of cooling",
          derivedFrom: "Stefan's law linearised for small (T − T₀)",
          derivation: {
            startsFrom: "Net radiated power σAe(T⁴ − T₀⁴) with T close to T₀",
            steps: [
              { statement: "Factor the fourth-power difference", expression: "T⁴ − T₀⁴ = (T − T₀)(T³ + T²T₀ + TT₀² + T₀³)" },
              { statement: "For T ≈ T₀ the bracket ≈ 4T₀³", expression: "P ≈ 4σAeT₀³(T − T₀)" },
              { statement: "Rate of temperature fall is proportional to excess temperature", expression: "dT/dt = −K(T − T₀)" },
            ],
          },
          variables: [
            { symbol: "T", name: "body temperature at time t", unit: "K (or °C)", dimension: "[Θ]" },
            { symbol: "T₀", name: "surrounding temperature", unit: "K (or °C)", dimension: "[Θ]" },
            { symbol: "K", name: "cooling constant (setup-dependent)", unit: "s⁻¹", dimension: "[T⁻¹]" },
          ],
          conditions: [
            "Small temperature excess only",
            "Approximate form for intervals: (T₁ − T₂)/t = K[(T₁ + T₂)/2 − T₀]",
          ],
          commonMistakes: [
            "Cooling is EXPONENTIAL, not linear — equal temperature drops take progressively longer",
          ],
          conceptLink: {
            chapterSlug: "thermal-properties-of-matter",
            sectionHeading: "4. Heat Transfer",
            concept: "Newton's law of cooling",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 7, neet: 10, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["newton cooling", "rate of cooling", "excess temperature"],
        },
      ],
      importantObservations: [
        "Good absorbers are good emitters (Kirchhoff) — a black cup of tea cools faster than a shiny one",
      ],
      examNotes:
        "NEET rotates Stefan-ratio and Newton's-cooling interval questions yearly; JEE builds composite-slab conduction ladders — solve them as resistor networks.",
    },
  ],
};
