import type { ChapterFormulaSheet } from "./types";

export const thermodynamicsFormulaSheet: ChapterFormulaSheet = {
  chapterSlug: "thermodynamics",
  chapterName: "Thermodynamics",
  className: "11",
  version: "1.0.0",
  lastUpdated: "2026-07-04",
  examCoverage: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
  quickRevisionIds: [
    "td-first-law",
    "td-work-by-gas",
    "td-adiabatic-relation",
    "td-carnot-efficiency",
    "td-cp-cv-mayer",
    "td-cop-refrigerator",
  ],
  topicGroups: [
    {
      id: "td-first-law-group",
      title: "First Law & Work Done by a Gas",
      intro:
        "Energy bookkeeping: heat in = internal energy change + work out. Signs are everything in this chapter.",
      formulas: [
        {
          id: "td-first-law",
          expression: "Q = ΔU + W",
          expressionLatex: "Q = \\Delta U + W",
          label: "First law of thermodynamics",
          variables: [
            { symbol: "Q", name: "heat SUPPLIED to the gas (positive in)", unit: "J", dimension: "[ML²T⁻²]" },
            { symbol: "ΔU", name: "change in internal energy", unit: "J", dimension: "[ML²T⁻²]" },
            { symbol: "W", name: "work done BY the gas (positive out)", unit: "J", dimension: "[ML²T⁻²]" },
          ],
          conditions: ["Sign convention above is the NCERT/exam standard — chemistry uses W done ON the gas"],
          commonMistakes: [
            "ΔU depends ONLY on temperature change for an ideal gas — same ΔT means same ΔU regardless of the process",
          ],
          usedIn: ["kinetic-theory-of-gases"],
          conceptLink: {
            chapterSlug: "thermodynamics",
            sectionHeading: "1. First Law of Thermodynamics",
            concept: "first law of thermodynamics",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 12, jeeAdvanced: 5, neet: 15, mhtCet: 11 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["first law", "Q delta U W", "sign convention"],
        },
        {
          id: "td-work-by-gas",
          expression: "W = ∫ P dV  (area under the P–V curve)",
          expressionLatex: "W = \\int P\\,dV",
          label: "Work done by a gas",
          variables: [
            { symbol: "P", name: "gas pressure", unit: "N/m²", dimension: "[ML⁻¹T⁻²]" },
            { symbol: "dV", name: "infinitesimal volume change", unit: "m³", dimension: "[L³]" },
          ],
          conditions: [
            "Expansion → W positive; compression → W negative",
            "For a CYCLE, net work = area enclosed by the loop (positive if clockwise on a P–V diagram)",
          ],
          commonMistakes: [
            "Work is PATH-dependent — two processes between the same states generally do different work",
          ],
          conceptLink: {
            chapterSlug: "thermodynamics",
            sectionHeading: "1. First Law of Thermodynamics",
            concept: "work done by a gas",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 11, jeeAdvanced: 6, neet: 13, mhtCet: 9 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["P dV", "area under PV", "cycle work"],
        },
        {
          id: "td-internal-energy",
          expression: "ΔU = n Cᵥ ΔT  (any process, ideal gas)",
          expressionLatex: "\\Delta U = nC_v\\Delta T",
          label: "Internal energy change of an ideal gas",
          variables: [
            { symbol: "n", name: "number of moles", unit: "mol", dimension: "[N]" },
            { symbol: "Cᵥ", name: "molar heat capacity at constant volume", unit: "J/(mol·K)", dimension: "[ML²T⁻²Θ⁻¹N⁻¹]" },
          ],
          conditions: ["Holds for EVERY process of an ideal gas, not only isochoric — U is a state function of T alone"],
          usedIn: ["kinetic-theory-of-gases"],
          conceptLink: {
            chapterSlug: "thermodynamics",
            sectionHeading: "1. First Law of Thermodynamics",
            concept: "internal energy of ideal gas",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 5, neet: 11 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["n Cv delta T", "internal energy ideal gas"],
        },
        {
          id: "td-cp-cv-mayer",
          expression: "Cₚ − Cᵥ = R;   γ = Cₚ/Cᵥ",
          expressionLatex: "C_p - C_v = R",
          label: "Mayer's relation & adiabatic exponent",
          derivedFrom: "First law applied to an isobaric process of an ideal gas",
          variables: [
            { symbol: "Cₚ, Cᵥ", name: "molar heat capacities at constant pressure and volume", unit: "J/(mol·K)", dimension: "[ML²T⁻²Θ⁻¹N⁻¹]", notes: "monatomic: Cᵥ = 3R/2, γ = 5/3; diatomic: Cᵥ = 5R/2, γ = 7/5" },
            { symbol: "R", name: "universal gas constant", unit: "J/(mol·K)", dimension: "[ML²T⁻²Θ⁻¹N⁻¹]", notes: "R = 8.314 J/(mol·K)" },
          ],
          conditions: ["Cₚ > Cᵥ always: at constant pressure some heat leaves as expansion work"],
          usedIn: ["kinetic-theory-of-gases", "waves"],
          conceptLink: {
            chapterSlug: "thermodynamics",
            sectionHeading: "2. Specific Heat Capacities",
            concept: "Mayer's relation",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 12, mhtCet: 9 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["mayer relation", "Cp minus Cv", "gamma"],
        },
      ],
      importantObservations: [
        "Free expansion into vacuum: W = 0, Q = 0, so ΔU = 0 and temperature is unchanged (ideal gas) — no formula, pure first law",
      ],
    },
    {
      id: "td-processes",
      title: "Thermodynamic Processes",
      intro:
        "Each named process kills one variable: isothermal fixes T, isochoric fixes V, isobaric fixes P, adiabatic blocks heat. Know W and Q for each.",
      formulas: [
        {
          id: "td-isothermal-work",
          expression: "W = nRT ln(V₂/V₁)  (isothermal)",
          expressionLatex: "W = nRT\\ln\\dfrac{V_2}{V_1}",
          label: "Work in an isothermal process",
          derivedFrom: "W = ∫P dV with P = nRT/V",
          variables: [
            { symbol: "V₁, V₂", name: "initial and final volumes", unit: "m³", dimension: "[L³]" },
            { symbol: "T", name: "constant temperature", unit: "K", dimension: "[Θ]" },
          ],
          conditions: ["ΔU = 0, so Q = W — all heat becomes work", "Slow (quasi-static) process in a conducting vessel"],
          conceptLink: {
            chapterSlug: "thermodynamics",
            sectionHeading: "3. Thermodynamic Processes",
            concept: "isothermal process",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 4, neet: 11, mhtCet: 8 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["isothermal work", "nRT ln", "V2 by V1"],
        },
        {
          id: "td-adiabatic-relation",
          expression: "PV^γ = constant;   TV^(γ−1) = constant",
          expressionLatex: "PV^{\\gamma} = \\text{const}",
          label: "Adiabatic process relations",
          derivedFrom: "First law with Q = 0 combined with the ideal gas law",
          variables: [
            { symbol: "γ", name: "adiabatic exponent Cₚ/Cᵥ", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: [
            "No heat exchange (fast process or insulated walls)",
            "Adiabatic curve is STEEPER than the isothermal through the same point (slope ratio = γ)",
          ],
          commonMistakes: [
            "Adiabatic expansion COOLS the gas — work is paid from internal energy",
          ],
          usedIn: ["waves"],
          conceptLink: {
            chapterSlug: "thermodynamics",
            sectionHeading: "3. Thermodynamic Processes",
            concept: "adiabatic process",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 11, jeeAdvanced: 6, neet: 13, mhtCet: 10 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["PV gamma", "adiabatic", "TV gamma minus 1"],
        },
        {
          id: "td-adiabatic-work",
          expression: "W = (P₁V₁ − P₂V₂)/(γ − 1) = nR(T₁ − T₂)/(γ − 1)",
          expressionLatex: "W = \\dfrac{nR(T_1 - T_2)}{\\gamma - 1}",
          label: "Work in an adiabatic process",
          derivedFrom: "W = −ΔU = −nCᵥΔT with Cᵥ = R/(γ−1)",
          variables: [
            { symbol: "T₁, T₂", name: "initial and final temperatures", unit: "K", dimension: "[Θ]" },
          ],
          conditions: ["Positive for expansion (T₂ < T₁)"],
          conceptLink: {
            chapterSlug: "thermodynamics",
            sectionHeading: "3. Thermodynamic Processes",
            concept: "adiabatic work",
          },
          examTags: ["jee-main", "neet", "mht-cet"],
          frequency: "high",
          examStats: { jeeMain: 7, neet: 8, mhtCet: 6 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["adiabatic work", "nR T1 minus T2 by gamma minus 1"],
        },
        {
          id: "td-polytropic-heat-capacity",
          expression: "C = Cᵥ + R/(1 − x)  for PV^x = constant",
          expressionLatex: "C = C_v + \\dfrac{R}{1-x}",
          label: "Molar heat capacity of a polytropic process",
          variables: [
            { symbol: "x", name: "polytropic index", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]", notes: "x = 0 isobaric, 1 isothermal, γ adiabatic, ∞ isochoric" },
            { symbol: "C", name: "molar heat capacity of the process", unit: "J/(mol·K)", dimension: "[ML²T⁻²Θ⁻¹N⁻¹]" },
          ],
          conditions: ["C can be NEGATIVE for 1 < x < γ — the gas cools while absorbing heat"],
          conceptLink: {
            chapterSlug: "thermodynamics",
            sectionHeading: "3. Thermodynamic Processes",
            concept: "polytropic process",
          },
          examTags: ["jee-main", "jee-advanced"],
          frequency: "medium",
          examStats: { jeeMain: 5, jeeAdvanced: 4 },
          difficulty: "hard",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["polytropic", "PV x constant", "negative heat capacity"],
        },
      ],
      importantObservations: [
        "Process-spotting on a P–V diagram: hyperbola = isothermal, steeper falling curve = adiabatic, vertical = isochoric, horizontal = isobaric",
      ],
      examNotes:
        "NEET asks W/Q/ΔU signs per process; JEE Advanced chains processes into cycles and asks for net quantities — tabulate each leg first.",
    },
    {
      id: "td-engines",
      title: "Heat Engines, Refrigerators & Second Law",
      intro:
        "No engine beats Carnot between the same two reservoirs. Efficiency and COP are just ratios of the same three energy flows.",
      formulas: [
        {
          id: "td-engine-efficiency",
          expression: "η = W/Q₁ = 1 − Q₂/Q₁",
          expressionLatex: "\\eta = 1 - \\dfrac{Q_2}{Q_1}",
          label: "Efficiency of a heat engine",
          variables: [
            { symbol: "Q₁", name: "heat absorbed from the hot reservoir", unit: "J", dimension: "[ML²T⁻²]" },
            { symbol: "Q₂", name: "heat rejected to the cold reservoir", unit: "J", dimension: "[ML²T⁻²]" },
            { symbol: "W", name: "net work output (= Q₁ − Q₂)", unit: "J", dimension: "[ML²T⁻²]" },
          ],
          conceptLink: {
            chapterSlug: "thermodynamics",
            sectionHeading: "4. Heat Engines",
            concept: "heat engine efficiency",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 12, mhtCet: 9 },
          difficulty: "easy",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["engine efficiency", "1 minus Q2 by Q1"],
        },
        {
          id: "td-carnot-efficiency",
          expression: "η(Carnot) = 1 − T₂/T₁",
          expressionLatex: "\\eta_{Carnot} = 1 - \\dfrac{T_2}{T_1}",
          label: "Carnot efficiency",
          derivedFrom: "For the reversible Carnot cycle, Q₂/Q₁ = T₂/T₁",
          derivation: {
            startsFrom: "Carnot cycle: two isotherms (T₁, T₂) + two adiabatics",
            steps: [
              { statement: "Isothermal heats", expression: "Q₁ = nRT₁ ln(V₂/V₁), Q₂ = nRT₂ ln(V₃/V₄)" },
              { statement: "Adiabatic legs give the volume-ratio equality", expression: "V₂/V₁ = V₃/V₄" },
              { statement: "Therefore", expression: "Q₂/Q₁ = T₂/T₁ ⟹ η = 1 − T₂/T₁" },
            ],
            askedInBoards: true,
          },
          variables: [
            { symbol: "T₁, T₂", name: "hot and cold reservoir temperatures", unit: "K", dimension: "[Θ]" },
          ],
          conditions: [
            "Temperatures in KELVIN, always",
            "This is the maximum possible efficiency between T₁ and T₂ — no real engine reaches it",
            "η = 1 only if T₂ = 0 K, which is unattainable",
          ],
          commonMistakes: [
            "Plugging Celsius values is the single most common thermodynamics error in NEET",
          ],
          conceptLink: {
            chapterSlug: "thermodynamics",
            sectionHeading: "4. Heat Engines",
            concept: "Carnot engine",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 10, jeeAdvanced: 4, neet: 14, mhtCet: 10 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["carnot", "1 minus T2 by T1", "maximum efficiency"],
        },
        {
          id: "td-cop-refrigerator",
          expression: "COP = Q₂/W = T₂/(T₁ − T₂)  (Carnot refrigerator)",
          expressionLatex: "\\beta = \\dfrac{Q_2}{W} = \\dfrac{T_2}{T_1 - T_2}",
          label: "Coefficient of performance of a refrigerator",
          variables: [
            { symbol: "COP", name: "coefficient of performance", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]", notes: "can exceed 1 — and usually does" },
            { symbol: "Q₂", name: "heat extracted from the cold space", unit: "J", dimension: "[ML²T⁻²]" },
          ],
          conditions: ["Relation to the same-reservoir engine: COP = (1 − η)/η"],
          commonMistakes: [
            "A refrigerator does not 'create cold' — it pumps Q₂ + W into the room; running one with the door open WARMS the room",
          ],
          conceptLink: {
            chapterSlug: "thermodynamics",
            sectionHeading: "5. Refrigerators and Second Law",
            concept: "refrigerator COP",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "high",
          examStats: { jeeMain: 6, neet: 9, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["COP", "refrigerator", "T2 by T1 minus T2"],
        },
      ],
      importantObservations: [
        "Second law in one line: heat cannot flow spontaneously from cold to hot, and no cyclic engine can convert heat entirely into work",
      ],
      examNotes:
        "NEET recycles Carnot-with-changed-reservoirs numericals; JEE Main likes 'efficiency becomes double when T₂ is lowered by x' algebra.",
    },
  ],
};
