import type { ChapterFormulaSheet } from "./types";

export const wavesFormulaSheet: ChapterFormulaSheet = {
  chapterSlug: "waves",
  chapterName: "Waves",
  className: "11",
  version: "1.0.1",
  lastUpdated: "2026-07-04",
  examCoverage: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
  quickRevisionIds: [
    "wav-wave-equation",
    "wav-string-speed",
    "wav-sound-speed",
    "wav-string-harmonics",
    "wav-organ-pipes",
    "wav-beats",
    "wav-doppler",
  ],
  topicGroups: [
    {
      id: "wav-basics",
      title: "Wave Equation & Wave Speed",
      intro:
        "A travelling wave carries phase at speed v = fλ. On a string the speed is set by tension and mass density; in a gas, by pressure and γ.",
      formulas: [
        {
          id: "wav-wave-equation",
          expression: "y = A sin(ωt − kx);   v = fλ = ω/k",
          expressionLatex: "y = A\\sin(\\omega t - kx),\\quad v = \\dfrac{\\omega}{k}",
          label: "Travelling wave equation",
          variables: [
            { symbol: "k", name: "angular wave number (2π/λ)", unit: "rad/m", dimension: "[L⁻¹]" },
            { symbol: "ω", name: "angular frequency (2πf)", unit: "rad/s", dimension: "[T⁻¹]" },
            { symbol: "λ", name: "wavelength", unit: "m", dimension: "[L]" },
          ],
          conditions: [
            "(ωt − kx) travels toward +x; (ωt + kx) toward −x",
            "Particle velocity = −v × (slope of the wave curve) — particle and wave velocities are different things",
          ],
          commonMistakes: [
            "Maximum PARTICLE speed is ωA, unrelated to the WAVE speed v — a favourite trap",
          ],
          usedIn: ["oscillations", "electromagnetic-waves"],
          conceptLink: {
            chapterSlug: "waves",
            sectionHeading: "1. Travelling Waves",
            concept: "travelling wave equation",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 11, jeeAdvanced: 5, neet: 14, mhtCet: 10 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["wave equation", "omega t minus kx", "v f lambda"],
        },
        {
          id: "wav-string-speed",
          expression: "v = √(T/μ)",
          expressionLatex: "v = \\sqrt{\\dfrac{T}{\\mu}}",
          label: "Speed of a wave on a string",
          variables: [
            { symbol: "T", name: "tension in the string", unit: "N", dimension: "[MLT⁻²]" },
            { symbol: "μ", name: "mass per unit length", unit: "kg/m", dimension: "[ML⁻¹]" },
          ],
          conditions: ["Speed depends on the MEDIUM only — changing frequency changes λ, not v"],
          commonMistakes: [
            "A wave passing from a thin to a thick string keeps its FREQUENCY; speed and wavelength both drop",
          ],
          usedIn: ["mechanical-properties-of-solids"],
          conceptLink: {
            chapterSlug: "waves",
            sectionHeading: "2. Speed of Waves",
            concept: "wave speed on a string",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 4, neet: 12, mhtCet: 9 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["root T by mu", "string wave speed"],
        },
        {
          id: "wav-sound-speed",
          expression: "v = √(γP/ρ) = √(γRT/M)  (Laplace)",
          expressionLatex: "v = \\sqrt{\\dfrac{\\gamma P}{\\rho}} = \\sqrt{\\dfrac{\\gamma RT}{M}}",
          label: "Speed of sound in a gas",
          derivedFrom: "Newton's isothermal formula √(P/ρ) corrected by Laplace: sound compressions are adiabatic",
          variables: [
            { symbol: "γ", name: "adiabatic exponent of the gas", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
            { symbol: "M", name: "molar mass", unit: "kg/mol", dimension: "[MN⁻¹]" },
          ],
          conditions: [
            "v ∝ √T — sound is faster on hot days; INDEPENDENT of pressure at fixed temperature (P/ρ fixed)",
            "≈ 332 m/s in air at 0 °C, rising ≈ 0.61 m/s per °C",
          ],
          commonMistakes: [
            "Humidity RAISES the speed of sound — moist air is lighter than dry air",
          ],
          usedIn: ["thermodynamics", "kinetic-theory-of-gases"],
          conceptLink: {
            chapterSlug: "waves",
            sectionHeading: "2. Speed of Waves",
            concept: "speed of sound",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 13, mhtCet: 9 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["speed of sound", "laplace correction", "root gamma RT by M"],
        },
      ],
      importantObservations: [
        "Sound in solids > liquids > gases (steel ≈ 15× air) — stiffness wins over density",
      ],
    },
    {
      id: "wav-superposition",
      title: "Superposition, Standing Waves & Beats",
      intro:
        "Waves add. In phase they reinforce, out of phase they cancel, and two counter-propagating waves lock into a standing pattern of nodes and antinodes.",
      formulas: [
        {
          id: "wav-interference-intensity",
          expression: "I = I₁ + I₂ + 2√(I₁I₂) cosφ;   I(max)/I(min) = (√I₁ + √I₂)²/(√I₁ − √I₂)²",
          expressionLatex: "I = I_1 + I_2 + 2\\sqrt{I_1I_2}\\cos\\varphi",
          label: "Interference of two waves",
          variables: [
            { symbol: "φ", name: "phase difference between the waves", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
            { symbol: "I₁, I₂", name: "individual intensities", unit: "W/m²", dimension: "[MT⁻³]" },
          ],
          conditions: [
            "Constructive: φ = 2nπ (path difference nλ); destructive: φ = (2n+1)π (path difference (2n+1)λ/2)",
            "Intensity ∝ (amplitude)²",
          ],
          usedIn: ["wave-optics"],
          conceptLink: {
            chapterSlug: "waves",
            sectionHeading: "3. Superposition of Waves",
            concept: "interference",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet"],
          frequency: "high",
          examStats: { jeeMain: 7, jeeAdvanced: 4, neet: 8 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["interference", "Imax Imin", "2 root I1 I2 cos phi"],
        },
        {
          id: "wav-string-harmonics",
          expression: "f(n) = n v/(2L) = (n/2L)√(T/μ),  n = 1, 2, 3...",
          expressionLatex: "f_n = \\dfrac{n}{2L}\\sqrt{\\dfrac{T}{\\mu}}",
          label: "Harmonics of a stretched string (fixed both ends)",
          derivedFrom: "Standing wave condition: L = nλ/2",
          derivation: {
            startsFrom: "Both ends are nodes, so the length holds a whole number of half-wavelengths",
            steps: [
              { statement: "Fit condition", expression: "L = nλ/2 ⟹ λ = 2L/n" },
              { statement: "Use v = fλ", expression: "f(n) = nv/2L" },
            ],
          },
          variables: [
            { symbol: "L", name: "length of the vibrating string", unit: "m", dimension: "[L]" },
            { symbol: "n", name: "harmonic number", unit: "dimensionless", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["ALL harmonics present; nth harmonic has n loops, (n+1) nodes counting both ends"],
          commonMistakes: [
            "Sonometer/tuning: f ∝ √T — to raise a string's pitch by 2× the tension must go up 4×",
          ],
          conceptLink: {
            chapterSlug: "waves",
            sectionHeading: "4. Standing Waves",
            concept: "vibrations of a stretched string",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 10, jeeAdvanced: 5, neet: 13, mhtCet: 10 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["string harmonics", "nv by 2L", "sonometer"],
        },
        {
          id: "wav-organ-pipes",
          expression: "Open pipe: f(n) = nv/2L (all n);   Closed pipe: f(n) = nv/4L (odd n only)",
          expressionLatex: "f_{open} = \\dfrac{nv}{2L},\\quad f_{closed} = \\dfrac{nv}{4L}\\ (n\\ \\text{odd})",
          label: "Organ pipe harmonics",
          derivedFrom: "Open end = antinode, closed end = node",
          variables: [
            { symbol: "L", name: "length of the air column", unit: "m", dimension: "[L]" },
          ],
          conditions: [
            "Closed pipe supports ONLY odd harmonics — its fundamental is half the open pipe's",
            "End correction: effective length = L + 0.6r (closed), L + 1.2r (open, both ends)",
          ],
          commonMistakes: [
            "Resonance tube (two-position method): λ = 2(L₂ − L₁) — end correction cancels automatically",
          ],
          conceptLink: {
            chapterSlug: "waves",
            sectionHeading: "4. Standing Waves",
            concept: "organ pipes and air columns",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 4, neet: 12, mhtCet: 9 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["organ pipe", "closed pipe odd harmonics", "resonance tube", "end correction"],
        },
        {
          id: "wav-pressure-displacement",
          expression: "p₀ = B k s₀;   pressure wave leads displacement by π/2",
          expressionLatex: "p_0 = Bks_0",
          label: "Pressure wave vs displacement wave",
          derivedFrom: "p = −B (∂s/∂x): differentiating the displacement wave shifts its phase by 90°",
          variables: [
            { symbol: "p₀", name: "pressure amplitude", unit: "N/m²", dimension: "[ML⁻¹T⁻²]" },
            { symbol: "s₀", name: "displacement amplitude", unit: "m", dimension: "[L]" },
            { symbol: "B", name: "bulk modulus of the medium", unit: "N/m²", dimension: "[ML⁻¹T⁻²]" },
            { symbol: "k", name: "angular wave number", unit: "rad/m", dimension: "[L⁻¹]" },
          ],
          conditions: ["A displacement NODE is a pressure ANTINODE and vice versa — the closed end of a pipe is where pressure swings hardest"],
          commonMistakes: [
            "The ear detects PRESSURE variation — that is why a closed end (displacement node) is where sound feels loudest inside a pipe",
          ],
          usedIn: ["mechanical-properties-of-solids"],
          conceptLink: {
            chapterSlug: "waves",
            sectionHeading: "4. Standing Waves",
            concept: "pressure and displacement waves",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "medium",
          examStats: { jeeMain: 4, jeeAdvanced: 3, neet: 5 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["pressure wave", "displacement node pressure antinode", "Bks0"],
        },
        {
          id: "wav-beats",
          expression: "f(beat) = |f₁ − f₂|",
          expressionLatex: "f_{beat} = |f_1 - f_2|",
          label: "Beat frequency",
          variables: [
            { symbol: "f₁, f₂", name: "the two close frequencies", unit: "Hz", dimension: "[T⁻¹]" },
          ],
          conditions: ["Audible only when the difference is small (≲ 10 Hz)"],
          commonMistakes: [
            "Tuning-fork logic: loading with wax LOWERS its frequency; filing RAISES it — use the beat change to decide which fork is higher",
          ],
          conceptLink: {
            chapterSlug: "waves",
            sectionHeading: "5. Beats",
            concept: "beats",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 12, mhtCet: 9 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["beats", "f1 minus f2", "tuning fork wax"],
        },
      ],
      importantObservations: [
        "Node spacing in any standing wave is λ/2; node-to-adjacent-antinode is λ/4",
        "Between two adjacent nodes all particles move in phase; across a node the phase flips by π",
      ],
      examNotes:
        "NEET rotates pipe-harmonic and beats questions annually; JEE Advanced merges beats with Doppler or with slowly changing tension.",
    },
    {
      id: "wav-doppler-group",
      title: "Doppler Effect",
      intro:
        "Relative motion between source and observer reshapes the received frequency. One master formula with a strict sign convention covers every case.",
      formulas: [
        {
          id: "wav-doppler",
          expression: "f' = f (v ± v(o)) / (v ∓ v(s))",
          expressionLatex: "f' = f\\dfrac{v \\pm v_o}{v \\mp v_s}",
          label: "Doppler effect (sound)",
          derivedFrom: "Moving source compresses wavefronts ahead of it; a moving observer sweeps up wavefronts faster",
          variables: [
            { symbol: "f'", name: "observed frequency", unit: "Hz", dimension: "[T⁻¹]" },
            { symbol: "v", name: "speed of sound in the medium", unit: "m/s", dimension: "[LT⁻¹]" },
            { symbol: "v(o)", name: "observer's speed", unit: "m/s", dimension: "[LT⁻¹]" },
            { symbol: "v(s)", name: "source's speed", unit: "m/s", dimension: "[LT⁻¹]" },
          ],
          conditions: [
            "Signs: pick the upper signs when the motion is TOWARD the other party (approach raises f')",
            "Speeds along the line joining source and observer only",
          ],
          commonMistakes: [
            "Source moving vs observer moving are NOT symmetric — a source at speed v/2 toward you gives f' = 2f, but an observer at v/2 toward a still source gives only 1.5f",
            "No frequency change when motion is perpendicular to the line of sight (at the instant of crossing)",
          ],
          usedIn: ["electromagnetic-waves"],
          conceptLink: {
            chapterSlug: "waves",
            sectionHeading: "6. Doppler Effect",
            concept: "Doppler effect",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 10, jeeAdvanced: 5, neet: 14, mhtCet: 10 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["doppler", "apparent frequency", "approaching source"],
        },
        {
          id: "wav-doppler-wall-echo",
          expression: "Beats heard by the source from its wall echo: Δf = f' − f, with f' via a double Doppler shift",
          label: "Doppler with reflection (echo problems)",
          variables: [
            { symbol: "Δf", name: "beat frequency between direct and reflected sound", unit: "Hz", dimension: "[T⁻¹]" },
          ],
          conditions: [
            "Treat the wall as an observer first (receives f₁), then as a stationary source re-emitting f₁",
          ],
          commonMistakes: [
            "Forgetting the second shift — reflection problems ALWAYS involve two Doppler steps",
          ],
          conceptLink: {
            chapterSlug: "waves",
            sectionHeading: "6. Doppler Effect",
            concept: "Doppler effect with reflection",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "medium",
          examStats: { jeeMain: 5, jeeAdvanced: 4, neet: 6 },
          difficulty: "hard",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["doppler echo", "wall reflection", "double doppler"],
        },
      ],
      importantObservations: [
        "Doppler changes FREQUENCY, never the wave speed — v belongs to the medium",
      ],
    },
  ],
};
