import type { ChapterFormulaSheet } from "./types";

export const waveOpticsFormulaSheet: ChapterFormulaSheet = {
  chapterSlug: "wave-optics",
  chapterName: "Wave Optics",
  className: "12",
  version: "1.0.0",
  lastUpdated: "2026-07-09",
  examCoverage: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
  quickRevisionIds: [
    "wo-fringe-width",
    "wo-condition-constructive",
    "wo-condition-destructive",
    "wo-resultant-intensity",
    "wo-single-slit-minima",
    "wo-malus-law",
    "wo-brewsters-law",
  ],
  topicGroups: [
    {
      id: "wo-interference-ydse",
      title: "Interference & Young's Double Slit Experiment",
      intro:
        "Two coherent light sources create a stable pattern of bright and dark fringes — the position of each fringe depends only on path difference, measured in a fixed geometric setup.",
      formulas: [
        {
          id: "wo-path-difference-ydse",
          expression: "Δx = d sinθ ≈ dy/D",
          expressionLatex: "\\Delta x = \\dfrac{dy}{D}",
          label: "Path difference in Young's double slit experiment",
          derivedFrom: "Geometry of two slits separated by d, screen at distance D, small-angle approximation for the fringe position y",
          variables: [
            { symbol: "d", name: "separation between the two slits", unit: "m", dimension: "[L]" },
            { symbol: "D", name: "distance from slits to screen", unit: "m", dimension: "[L]" },
            { symbol: "y", name: "distance of the point from the central maximum on the screen", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Requires D ≫ d (small-angle approximation) — standard for all YDSE setups"],
          conceptLink: {
            chapterSlug: "wave-optics",
            sectionHeading: "7. Young's Double Slit Experiment (YDSE)",
            concept: "path difference in YDSE",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 4, neet: 12, mhtCet: 8 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["path difference YDSE", "dy by D"],
        },
        {
          id: "wo-condition-constructive",
          expression: "Δx = nλ   (n = 0, ±1, ±2, ...) → bright fringe",
          expressionLatex: "\\Delta x = n\\lambda",
          label: "Condition for constructive interference (bright fringe)",
          variables: [
            { symbol: "n", name: "order of the fringe", unit: "dimensionless (integer)", dimension: "[M⁰L⁰T⁰]" },
          ],
          conceptLink: {
            chapterSlug: "wave-optics",
            sectionHeading: "6. Constructive and Destructive Interference — Conditions",
            concept: "condition for constructive interference",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 10, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["constructive interference condition", "path difference n lambda"],
        },
        {
          id: "wo-condition-destructive",
          expression: "Δx = (2n − 1)λ/2   (n = 1, 2, 3, ...) → dark fringe",
          expressionLatex: "\\Delta x = \\dfrac{(2n-1)\\lambda}{2}",
          label: "Condition for destructive interference (dark fringe)",
          variables: [],
          commonMistakes: [
            "Dark fringes occur at HALF-integer multiples of λ, not λ/2 exactly at n=1,2,3... written as (2n−1)λ/2 — easy to mis-index by one term",
          ],
          conceptLink: {
            chapterSlug: "wave-optics",
            sectionHeading: "6. Constructive and Destructive Interference — Conditions",
            concept: "condition for destructive interference",
          },
          examTags: ["jee-main", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, neet: 10, mhtCet: 7 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["destructive interference condition", "path difference odd half lambda"],
        },
        {
          id: "wo-fringe-width",
          expression: "β = λD/d",
          expressionLatex: "\\beta = \\dfrac{\\lambda D}{d}",
          label: "Fringe width in YDSE",
          derivedFrom: "Distance between two consecutive bright (or dark) fringes, from the constructive-interference condition applied at consecutive n",
          variables: [
            { symbol: "β", name: "fringe width — spacing between consecutive bright or dark fringes", unit: "m", dimension: "[L]" },
          ],
          conditions: ["All bright fringes (and all dark fringes) are EQUALLY spaced — β is the same throughout the pattern, not just near the centre"],
          conceptLink: {
            chapterSlug: "wave-optics",
            sectionHeading: "7. Young's Double Slit Experiment (YDSE)",
            concept: "fringe width",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 4, neet: 12, mhtCet: 8 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["fringe width formula", "beta lambda D by d"],
        },
        {
          id: "wo-resultant-intensity",
          expression: "I = I₁ + I₂ + 2√(I₁I₂) cosφ",
          expressionLatex: "I = I_1+I_2+2\\sqrt{I_1I_2}\\cos\\varphi",
          label: "Resultant intensity from two coherent sources",
          derivedFrom: "Superposition of two waves with amplitudes A₁, A₂ and phase difference φ; I ∝ (resultant amplitude)²",
          variables: [
            { symbol: "I₁, I₂", name: "intensities of the two individual sources", unit: "W/m²", dimension: "[MT⁻³]" },
            { symbol: "φ", name: "phase difference between the two waves at the point", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["Requires COHERENT sources (constant phase relationship) — for incoherent sources, intensities simply add with no interference term"],
          conceptLink: {
            chapterSlug: "wave-optics",
            sectionHeading: "5. Analysis of Interference — Resultant Amplitude and Intensity",
            concept: "resultant intensity from two coherent sources",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 10, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["resultant intensity interference", "I1 I2 2 root I1I2 cos phi"],
        },
        {
          id: "wo-max-min-intensity",
          expression: "I(max) = (√I₁ + √I₂)² ,  I(min) = (√I₁ − √I₂)²",
          expressionLatex: "I_{max} = (\\sqrt{I_1}+\\sqrt{I_2})^2,\\quad I_{min} = (\\sqrt{I_1}-\\sqrt{I_2})^2",
          label: "Maximum and minimum intensity in an interference pattern",
          derivedFrom: "Setting cosφ = +1 and −1 respectively in the resultant intensity formula",
          variables: [],
          conditions: ["I(min) = 0 only when I₁ = I₂ exactly — otherwise dark fringes are dim but not perfectly dark"],
          conceptLink: {
            chapterSlug: "wave-optics",
            sectionHeading: "5. Analysis of Interference — Resultant Amplitude and Intensity",
            concept: "maximum and minimum intensity",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 4, neet: 7, mhtCet: 5 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["max min intensity interference", "root I1 plus root I2 squared"],
        },
        {
          id: "wo-thin-film-slab-shift",
          expression: "Fringe shift = (n − 1)tD/d  (equivalently (n−1)t/λ fringes)",
          expressionLatex: "\\Delta y = \\dfrac{(n-1)tD}{d}",
          label: "Fringe shift when a thin slab is placed in one path of YDSE",
          derivedFrom: "The slab introduces an extra path length (n−1)t in that arm, shifting the entire fringe pattern without changing the fringe width",
          variables: [
            { symbol: "t", name: "thickness of the inserted slab", unit: "m", dimension: "[L]" },
          ],
          conditions: ["The pattern SHIFTS toward the slab side — fringe width β itself stays unchanged"],
          commonMistakes: [
            "Inserting a slab shifts the pattern; it does NOT change the fringe width β = λD/d, which depends only on λ, D, d",
          ],
          conceptLink: {
            chapterSlug: "wave-optics",
            sectionHeading: "9. Effect of a Thin Film Slab Placed in YDSE",
            concept: "fringe shift due to a thin film slab",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "medium",
          examStats: { jeeMain: 5, jeeAdvanced: 4, neet: 5 },
          difficulty: "hard",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["fringe shift thin film YDSE", "n minus 1 t D by d"],
        },
      ],
    },
    {
      id: "wo-diffraction",
      title: "Diffraction",
      intro:
        "Diffraction is what happens when the slit itself isn't infinitesimally narrow — different parts of the SAME slit interfere with each other, producing a central bright band flanked by much weaker secondary maxima.",
      formulas: [
        {
          id: "wo-single-slit-minima",
          expression: "a sinθ = nλ   (n = ±1, ±2, ...) → minima",
          expressionLatex: "a\\sin\\theta = n\\lambda",
          label: "Condition for minima in single-slit diffraction",
          variables: [
            { symbol: "a", name: "width of the single slit", unit: "m", dimension: "[L]" },
          ],
          conditions: ["Note the reversed role compared to YDSE: this condition gives MINIMA here, while the analogous nλ condition gave MAXIMA in double-slit interference"],
          commonMistakes: [
            "Do not confuse this with the double-slit bright-fringe condition — in single-slit diffraction, nλ gives dark bands, not bright ones",
          ],
          conceptLink: {
            chapterSlug: "wave-optics",
            sectionHeading: "12. Fraunhofer Diffraction at a Single Slit",
            concept: "single-slit diffraction minima",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 10, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["single slit diffraction minima", "a sin theta n lambda"],
        },
        {
          id: "wo-single-slit-central-max-width",
          expression: "Width of central maximum = 2λD/a",
          expressionLatex: "w = \\dfrac{2\\lambda D}{a}",
          label: "Width of the central maximum in single-slit diffraction",
          derivedFrom: "Twice the distance to the first minimum on either side of the centre",
          variables: [],
          conditions: ["The central maximum is TWICE as wide as every other (secondary) maximum — a key qualitative fact about diffraction patterns"],
          conceptLink: {
            chapterSlug: "wave-optics",
            sectionHeading: "12. Fraunhofer Diffraction at a Single Slit",
            concept: "width of the central maximum",
          },
          examTags: ["jee-main", "jee-advanced", "neet"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 4, neet: 6 },
          difficulty: "medium",
          isKeyFormula: false,
          pdfInclude: true,
          searchKeywords: ["central maximum width diffraction", "2 lambda D by a"],
        },
        {
          id: "wo-resolving-power-rayleigh",
          expression: "θ(min) = 1.22 λ/D   (Rayleigh's criterion, circular aperture)",
          expressionLatex: "\\theta_{min} = \\dfrac{1.22\\lambda}{D}",
          label: "Rayleigh's criterion for resolving power (telescope/eye)",
          derivedFrom: "Two point sources are just resolvable when the central maximum of one falls on the first minimum of the other's diffraction pattern",
          variables: [
            { symbol: "θ(min)", name: "minimum angular separation for two objects to be resolved", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
            { symbol: "D", name: "diameter of the aperture (lens/mirror/pupil)", unit: "m", dimension: "[L]" },
          ],
          conditions: ["A LARGER aperture gives BETTER resolving power (smaller θ(min)) — the reason large telescopes resolve finer detail"],
          conceptLink: {
            chapterSlug: "wave-optics",
            sectionHeading: "14. Resolving Power — Rayleigh's Criterion",
            concept: "Rayleigh's criterion",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet"],
          frequency: "high",
          examStats: { jeeMain: 6, jeeAdvanced: 4, neet: 7, mhtCet: 5 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["rayleigh criterion resolving power", "1.22 lambda by D"],
        },
      ],
      importantObservations: [
        "Interference gives EQUALLY bright fringes (energy just redistributed); diffraction gives a bright central band with progressively weaker secondary maxima — a key qualitative distinction between the two phenomena",
      ],
    },
    {
      id: "wo-polarisation",
      title: "Polarisation",
      intro:
        "Polarisation only makes sense for transverse waves — it's direct experimental proof that light is transverse, not longitudinal, since sound waves can never be polarised.",
      formulas: [
        {
          id: "wo-malus-law",
          expression: "I = I₀ cos²θ",
          expressionLatex: "I = I_0\\cos^2\\theta",
          label: "Law of Malus",
          variables: [
            { symbol: "I₀", name: "intensity of light after passing through the first (polariser)", unit: "W/m²", dimension: "[MT⁻³]" },
            { symbol: "θ", name: "angle between the polariser's and analyser's transmission axes", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["I is maximum (=I₀) when axes are parallel (θ=0°), zero when perpendicular (θ=90°, 'crossed polarisers')"],
          commonMistakes: [
            "The cos² relates INTENSITY, not amplitude — a common slip is to apply cosθ (not squared) directly to intensity",
          ],
          conceptLink: {
            chapterSlug: "wave-optics",
            sectionHeading: "17. Law of Malus",
            concept: "law of Malus",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 9, jeeAdvanced: 4, neet: 12, mhtCet: 8 },
          difficulty: "easy",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["law of malus", "I0 cos squared theta"],
        },
        {
          id: "wo-brewsters-law",
          expression: "tanθ(B) = n₂/n₁ ,  θ(B) + θ(r) = 90°",
          expressionLatex: "\\tan\\theta_B = \\dfrac{n_2}{n_1}",
          label: "Brewster's law",
          derivedFrom: "At the polarising (Brewster) angle, the reflected and refracted rays are exactly perpendicular to each other",
          variables: [
            { symbol: "θ(B)", name: "Brewster's (polarising) angle of incidence", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
            { symbol: "θ(r)", name: "angle of refraction at the Brewster angle", unit: "rad", dimension: "[M⁰L⁰T⁰]" },
          ],
          conditions: ["At exactly this angle, the REFLECTED light is completely (linearly) polarised, perpendicular to the plane of incidence"],
          usedIn: ["ray-optics-and-optical-instruments"],
          conceptLink: {
            chapterSlug: "wave-optics",
            sectionHeading: "18. Brewster's Law — Deeper Analysis and Critical Angle Relation",
            concept: "Brewster's law",
          },
          examTags: ["jee-main", "jee-advanced", "neet", "mht-cet", "boards"],
          frequency: "very-high",
          examStats: { jeeMain: 8, jeeAdvanced: 4, neet: 11, mhtCet: 7 },
          difficulty: "medium",
          isKeyFormula: true,
          pdfInclude: true,
          searchKeywords: ["brewsters law", "tan theta B n2 by n1", "polarising angle"],
        },
      ],
    },
  ],
};
