// ─────────────────────────────────────────────────────────────────
// PYQ — Exam-Type Availability Map (lightweight)
//
// This module lists, per chapter slug, whether at least one question
// exists for each exam target (NEET = an untagged question; JEE Main /
// JEE Advanced = a question with the matching `examType`). It contains
// NO question content, so client components that merely need to know
// "does this chapter have PYQ for exam X?" can import this instead of
// the full registry — keeping heavy question/option/solution text out
// of the client bundle.
//
// KEEP IN SYNC with index.ts. A build-time guard (see index.ts bottom)
// asserts the slug set matches, so a forgotten chapter fails the build,
// not prod. The per-exam-type booleans themselves are derived once from
// the real registry and must be regenerated by hand if a chapter's PYQ
// exam-type mix changes.
// ─────────────────────────────────────────────────────────────────

export type PyqExamAvailability = {
  neet: boolean;
  jeeMain: boolean;
  jeeAdvanced: boolean;
};

export const pyqAvailability: Readonly<Record<string, PyqExamAvailability>> = {
  "alternating-current": { neet: true, jeeMain: false, jeeAdvanced: false },
  atoms: { neet: true, jeeMain: false, jeeAdvanced: false },
  "basic-mathematics-and-vectors": { neet: true, jeeMain: true, jeeAdvanced: true },
  "centre-of-mass-and-collisions": { neet: true, jeeMain: true, jeeAdvanced: true },
  "circular-motion": { neet: false, jeeMain: true, jeeAdvanced: true },
  "current-electricity": { neet: true, jeeMain: false, jeeAdvanced: false },
  "dual-nature-of-radiation-and-matter": { neet: true, jeeMain: false, jeeAdvanced: false },
  "electric-charges-and-fields": { neet: true, jeeMain: false, jeeAdvanced: false },
  "electromagnetic-induction": { neet: true, jeeMain: false, jeeAdvanced: false },
  "electromagnetic-waves": { neet: true, jeeMain: false, jeeAdvanced: false },
  "electrostatic-potential-and-capacitance": { neet: true, jeeMain: false, jeeAdvanced: false },
  gravitation: { neet: true, jeeMain: true, jeeAdvanced: true },
  kinematics: { neet: true, jeeMain: true, jeeAdvanced: true },
  "kinetic-theory-of-gases": { neet: true, jeeMain: false, jeeAdvanced: false },
  "laws-of-motion": { neet: true, jeeMain: true, jeeAdvanced: true },
  "magnetism-and-matter": { neet: true, jeeMain: false, jeeAdvanced: false },
  "mechanical-properties-of-fluids": { neet: true, jeeMain: true, jeeAdvanced: true },
  "mechanical-properties-of-solids": { neet: true, jeeMain: true, jeeAdvanced: true },
  "moving-charges-and-magnetism": { neet: true, jeeMain: false, jeeAdvanced: false },
  nuclei: { neet: true, jeeMain: false, jeeAdvanced: false },
  oscillations: { neet: true, jeeMain: false, jeeAdvanced: false },
  "physical-world-and-measurement": { neet: false, jeeMain: true, jeeAdvanced: true },
  "ray-optics-and-optical-instruments": { neet: true, jeeMain: false, jeeAdvanced: false },
  "semiconductor-electronics": { neet: true, jeeMain: false, jeeAdvanced: false },
  "system-of-particles-and-rotational-motion": { neet: true, jeeMain: true, jeeAdvanced: true },
  "thermal-properties-of-matter": { neet: true, jeeMain: false, jeeAdvanced: false },
  thermodynamics: { neet: true, jeeMain: false, jeeAdvanced: false },
  "wave-optics": { neet: true, jeeMain: false, jeeAdvanced: false },
  waves: { neet: true, jeeMain: false, jeeAdvanced: false },
  "work-energy-and-power": { neet: true, jeeMain: true, jeeAdvanced: true },
};

/** True if this chapter has at least one PYQ for the given exam target. No question content loaded. */
export function hasPyqFor(
  slug: string,
  exam: "neet" | "jee-main" | "jee-advanced"
): boolean {
  const entry = pyqAvailability[slug];
  if (!entry) return false;
  if (exam === "neet") return entry.neet;
  if (exam === "jee-main") return entry.jeeMain;
  return entry.jeeAdvanced;
}
